force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_TECH_toNotify__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_toNotify__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_TECH_toNotify</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_PDL_PCE__c.field-meta.xml
<CustomField>
    <fullName>Numero_PDL_PCE__c</fullName>
    <label>Numéro de PDL/PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Secteur_activite__c.field-meta.xml
<CustomField>
    <fullName>Secteur_activite__c</fullName>
    <label>Secteur d&apos;activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elec</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Situation_de_vente__c.field-meta.xml
<CustomField>
    <fullName>Situation_de_vente__c</fullName>
    <description>Pemet de déterminer la situation de vente du parcours depuis lequel le conseiller effectue une creation d&apos;OPS</description>
    <label>Situation de vente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Emménagement</fullName>
            </value>
            <value>
                <fullName>Changement de fournisseur</fullName>
            </value>
            <value>
                <fullName>Changement d&apos;offre</fullName>
            </value>
            <value>
                <fullName>Resiliation</fullName>
            </value>
            <value>
                <fullName>HP_Reduction_de_puissance</fullName>
                <label>Réduction de puissance</label>
            </value>
            <value>
                <fullName>HP_Coupure</fullName>
                <label>Coupure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut_dernier_jalon__c.field-meta.xml
<CustomField>
    <fullName>Statut_dernier_jalon__c</fullName>
    <description>@description: ce champ prend le Statut dernier jalon
@projet: smile</description>
    <label>Statut dernier jalon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/recordTypes/HP_PrestationDistributeur.recordType-meta.xml
<RecordType>
    <fullName>HP_PrestationDistributeur</fullName>
    <active>true</active>
    <label>HP_PrestationDistributeur</label>
</RecordType>

force-app/main/default/classes/HP_PrestationController_TEST.cls
/**
 * @File Name          : HP_PrestationController_TEST.cls
 * @Description        : 
 * @Author             : Mouhamadoune Coulibaly
 * @Group              : 
 * @Last Modified By   : Mouhamadoune Coulibaly
 * @Last Modified On   : 24/04/2020 à 17:18:34
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    24/04/2020   Mouhamadoune Coulibaly     Initial Version
**/
@isTEST
public with sharing class HP_PrestationController_TEST {


    @TestSetUp 
	private static void insertTestData(){
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){
            Prestation_distributeur__c testpresta = (Prestation_distributeur__c)HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c', 'HP_PrestationDistributeur', new Map<String, Object>{
                'Numero_PDL_PCE__c' => '230492038433',
                'Statut__c' => 'Terminé',
                'Secteur_activite__c' => 'Elec',
                'Situation_de_vente__c'=>'Changement de fournisseur',
                'Numero_affaire_distributeur__c' => 'QL30DPC4',
                'Statut_dernier_jalon__c'=>'CPE',
                'HP_TECH_toNotify__c' => false
            }, null, null, null);
            insert testpresta;
    
            Prestation_distributeur__c testpresta1 = (Prestation_distributeur__c)HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c', 'HP_PrestationDistributeur', new Map<String, Object>{
                'Numero_PDL_PCE__c' => '3993028736467',
                'Statut__c' => 'Terminé',
                'Secteur_activite__c' => 'Gaz',
                'Situation_de_vente__c'=>'Emménagement',
                'Numero_affaire_distributeur__c' => 'QL30DPC5',
                'Statut_dernier_jalon__c'=>'022',
                'HP_TECH_toNotify__c' => false
            }, null, null, null);
            insert testpresta1;
        }
    }

    @istest
    static void handleUpdatedOPS() {
		System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            List <Prestation_distributeur__c> hpUpdatedOps = [Select Id,Situation_de_vente__c,Secteur_activite__c ,Statut__c ,Statut_dernier_jalon__c From Prestation_distributeur__c limit 2];
            Test.startTest();
            HP_PrestationController.handleUpdatedOPS(hpUpdatedOps);
            Test.stopTest();
        }
    }
}