force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Civilite_interlocuteur_intervention__c.field-meta.xml
<CustomField>
    <fullName>Civilite_interlocuteur_intervention__c</fullName>
    <description>@description : champ civilité interlocuteur intervention
@projet: smile</description>
    <label>Civilité interlocuteur intervention</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MR</fullName>
            </value>
            <value>
                <fullName>MLLE</fullName>
            </value>
            <value>
                <fullName>MME</fullName>
            </value>
            <value>
                <fullName>MLLES</fullName>
            </value>
            <value>
                <fullName>MME et MLLE</fullName>
            </value>
            <value>
                <fullName>MMES</fullName>
            </value>
            <value>
                <fullName>AUTRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Creneau__c.field-meta.xml
<CustomField>
    <fullName>Creneau__c</fullName>
    <label>Créneau</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Journée</fullName>
            </value>
            <value>
                <fullName>Début de matinée</fullName>
            </value>
            <value>
                <fullName>Fin de matinée</fullName>
            </value>
            <value>
                <fullName>Midi</fullName>
            </value>
            <value>
                <fullName>Début d&apos;après midi</fullName>
            </value>
            <value>
                <fullName>Fin d&apos;après midi</fullName>
            </value>
            <value>
                <fullName>Matin</fullName>
            </value>
            <value>
                <fullName>Fin d’après midi</fullName>
            </value>
            <value>
                <fullName>Fin de journée</fullName>
            </value>
            <value>
                <fullName>Début de soirée</fullName>
            </value>
            <value>
                <fullName>Milieu de soirée</fullName>
            </value>
            <value>
                <fullName>Soir</fullName>
            </value>
            <value>
                <fullName>Fin de soirée</fullName>
            </value>
            <value>
                <fullName>Après midi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Date_de_prestation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_prestation__c</fullName>
    <label>Date de prestation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Date_statut_prestation__c.field-meta.xml
<CustomField>
    <fullName>Date_statut_prestation__c</fullName>
    <description>@description: ce champ prend le Date statut prestation
@projet: smile</description>
    <label>Date statut prestation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Identifiant_ENGIE__c.field-meta.xml
<CustomField>
    <fullName>Identifiant_ENGIE__c</fullName>
    <description>Identifiant fournisseur alimenté au retour du WS de creation d&apos;OPS.</description>
    <externalId>true</externalId>
    <label>Identifiant ENGIE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Nom_contact_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Nom_contact_d_intervention__c</fullName>
    <description>Nom du contact d&apos;intervention à alimenter au retour du WS ou lors des flux X12 et SDEM</description>
    <label>Nom contact d&apos;intervention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_dernier_jalon__c.field-meta.xml
<CustomField>
    <fullName>Numero_dernier_jalon__c</fullName>
    <description>@description: ce champ comporte le Numéro dernier jalon
@projet: smile</description>
    <label>Numéro dernier jalon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Prenom_contact_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Prenom_contact_d_intervention__c</fullName>
    <description>Prenom du contact intervention alimenté au retour des flux distributeur ou des flux X12 et SDEM</description>
    <label>Prenom contact d&apos;intervention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Secteur_activite__c.field-meta.xml
<CustomField>
    <fullName>Secteur_activite__c</fullName>
    <label>Secteur d&apos;activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elec</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut_dernier_jalon__c.field-meta.xml
<CustomField>
    <fullName>Statut_dernier_jalon__c</fullName>
    <description>@description: ce champ prend le Statut dernier jalon
@projet: smile</description>
    <label>Statut dernier jalon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Telephone_intervention__c.field-meta.xml
<CustomField>
    <fullName>Telephone_intervention__c</fullName>
    <description>Téléphone du contact d&apos;intervention mis à jour au retour des flux distributeur ou X12 ou SDEM</description>
    <label>Telephone intervention</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SM_AP51_X12_SDEM_DataHandler_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-05-2022
 * @last modified by  : Ahmed LAAMIRI
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   11-10-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
   global class SM_AP51_X12_SDEM_DataHandler_Test {
       
       @isTest static void updateOPS() {

     Case newCaseElec = new Case(status = 'En attente',Sous_statut__c='Retour client');
     insert newCaseElec;

     Case newCaseGaz = new Case(status = 'En attente',Sous_statut__c='Retour client');
     insert newCaseGaz;


      Prestation_distributeur__c opsElec = new Prestation_distributeur__c(Name = 'Elec',
      Case__c = newCaseElec.Id,
      Secteur_activite__c = 'Elec',
      Numero_affaire_distributeur__c = '1234567',
      Telephone_intervention__c = '06666666666',
      Statut_dernier_jalon__c = 'En attente',
      Nom_contact_d_intervention__c = 'test test',
      Date_statut_prestation__c = Date.valueOf('2018-01-01'),
      Creneau__c = 'Journée',
      Prenom_contact_d_intervention__c = 'test',
      Civilite_interlocuteur_intervention__c = 'MR',
      Numero_dernier_jalon__c = 1,
      Statut__c = 'En cours',
      Date_de_prestation__c = Date.valueOf('2018-01-01'),
      Identifiant_ENGIE__c = '123456');
     insert opsElec;



      Prestation_distributeur__c opsGaz = new Prestation_distributeur__c(Name = 'Gaz',
      Case__c = newCaseGaz.Id,
      Secteur_activite__c = 'Gaz',
      Numero_affaire_distributeur__c = '1234568',
      Telephone_intervention__c = '06666666666',
      Statut_dernier_jalon__c = 'En attente',
      Nom_contact_d_intervention__c = 'test test',
      Date_statut_prestation__c = Date.valueOf('2018-01-01'),
      Creneau__c = 'Journée',
      Prenom_contact_d_intervention__c = 'test',
      Civilite_interlocuteur_intervention__c = 'MR',
      Numero_dernier_jalon__c = 1,
      Statut__c = 'En cours',
      Date_de_prestation__c = Date.valueOf('2018-01-01'),
      Identifiant_ENGIE__c = '123457');

     insert opsGaz;
     
      Prestation_distributeur__c opsGazNullDate = new Prestation_distributeur__c(Name = 'Gaz',
      Case__c = newCaseGaz.Id,
      Secteur_activite__c = 'Gaz',
      Numero_affaire_distributeur__c = '01234589',
      Telephone_intervention__c = '06666666666',
      Statut_dernier_jalon__c = 'En attente',
      Nom_contact_d_intervention__c = 'test test',
      Date_statut_prestation__c = Date.valueOf('2018-01-01'),
      Creneau__c = 'Journée',
      Prenom_contact_d_intervention__c = 'test',
      Civilite_interlocuteur_intervention__c = 'MR',
      Numero_dernier_jalon__c = 1,
      Statut__c = 'En cours',
      Date_de_prestation__c = Date.valueOf('2018-01-01'),
      Identifiant_ENGIE__c = '01234589');

     insert opsGazNullDate;

           

     CMN_OPSinfo opsElecFromClient = new CMN_OPSinfo();
     opsElecFromClient.idAffaire = '1234567';
     opsElecFromClient.referenceDemandeur = '1234567';
     opsElecFromClient.statutDernierJalon = 'OK';
     opsElecFromClient.numDernierJalon = 2;
     opsElecFromClient.statutPrestation = 'Terminé';
     opsElecFromClient.datePrestation = '2018-12-20T16:14:04+01:00';
     opsElecFromClient.creneau = 'jou';
     opsElecFromClient.civiliteIntervenant = 'MR';
     opsElecFromClient.nomIntervenant = 'test';
     opsElecFromClient.prenomIntervenant = 'test';
     opsElecFromClient.telephoneIntervenant = '7777777777';
     opsElecFromClient.typeEnergie = 'Elec';


     CMN_OPSinfo opsGazFromClient = new CMN_OPSinfo();
     opsGazFromClient.idAffaire = '1234568';
     opsGazFromClient.referenceDemandeur = '1234568';
     opsGazFromClient.statutDernierJalon = 'OK';
     opsGazFromClient.numDernierJalon = 2;
     opsGazFromClient.statutPrestation = 'Clôturée';
     opsGazFromClient.datePrestation = '2018-12-20T16:14:04+01:00';
     opsGazFromClient.creneau = 'jou6';
     opsGazFromClient.civiliteIntervenant = 'MR';
     opsGazFromClient.nomIntervenant = 'test';
     opsGazFromClient.prenomIntervenant = 'test';
     opsGazFromClient.telephoneIntervenant = '7777777777';
     opsGazFromClient.typeEnergie = 'Gaz';
        
  
           
     CMN_OPSinfo opsGazFromClientDateNull = new CMN_OPSinfo();
     opsGazFromClientDateNull.idAffaire = '01234589';
     opsGazFromClientDateNull.referenceDemandeur = '01234589';
     opsGazFromClientDateNull.statutDernierJalon = 'OK';
     opsGazFromClientDateNull.numDernierJalon = 2;
     opsGazFromClientDateNull.statutPrestation = 'Clôturée';
     opsGazFromClientDateNull.datePrestation = '';
     opsGazFromClientDateNull.creneau = 'jou6';
     opsGazFromClientDateNull.civiliteIntervenant = 'MR';
     opsGazFromClientDateNull.nomIntervenant = 'testnull';
     opsGazFromClientDateNull.prenomIntervenant = 'testnull';
     opsGazFromClientDateNull.telephoneIntervenant = '7700000000';
     opsGazFromClientDateNull.typeEnergie = 'Gaz';   


     RestRequest req = new RestRequest(); 	 
		req.requestURI = '/updateOPS';
		req.httpMethod = 'POST';
		req.requestBody = Blob.valueof(JSON.serializePretty(new Map<String, Object>{'OPSinfos' => new List <CMN_OPSinfo> {opsGazFromClientDateNull,opsElecFromClient,opsGazFromClient}}));
        RestContext.request = req;
		RestResponse res = new RestResponse();
        RestContext.response = res;
     	CMN_OPSUpdate.handleOpsInfos();
 
    }

}