force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Prestation_distributeur_Trigger_Test.cls
@isTest
public class Prestation_distributeur_Trigger_Test {
	@isTest
    static void preclotureTest() {
        Case myCase = new Case();
        myCase.subject = 'test';
        myCase.RecordTypeId	= Schema.SObjectType.Case.getRecordTypeInfosByName().get('Service').getRecordTypeId();
        insert myCase;


        Prestation_distributeur__c ops = new Prestation_distributeur__c(Case__c = myCase.Id, Numero_affaire_distributeur__c = '12345678');

        insert ops;
        
        //Test.startTest();
        ops.Statut__c = 'Terminé';
        update ops;
        myCase = [select status, Sous_statut__c from Case where Id=:myCase.Id];
        //Test.stopTest();

        System.assertEquals('Pré-clôturé', myCase.Status);
        System.assertEquals('Conforme', myCase.Sous_statut__c);
    }
}