force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_PDL_PCE__c.field-meta.xml
<CustomField>
    <fullName>Numero_PDL_PCE__c</fullName>
    <label>Numéro de PDL/PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_SM007_PrestationDistManager_TEST.cls
/** 
* @author Slimen Belhaj Ali 
* @date 14/01/2020  
* @description Classe de test pour HP_SM007_PrestationDistributeurManager_TEST
*/
@IsTest
public with sharing class HP_SM007_PrestationDistManager_TEST {
    /** 
    * @author Slimene Belhaj Ali
    * @date 14/01/2020 
    * @description Methode permet de créer les jeux de données
    */
	@TestSetUp 
	private static void insertTestData() {
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){
            Prestation_distributeur__c pres = (Prestation_distributeur__c) HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c', 
            new Map<String, Object>{
                'Statut__c' => 'En cours',
                'Numero_affaire_distributeur__c' => 'A1234567',
                'Numero_PDL_PCE__c' => '12'}, null);
            insert pres;
        }
    }

    /** 
    * @author Slimene Belhaj Ali
    * @date 14/01/2020 
    * @description Methode permet tester la methode loadPrestationDistrubuteurToCardService
    */
    @IsTest
	static void loadPrestationDistrubuteurToCardService_TEST(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_SM007_PrestationDistributeurManager.loadPrestationDistrubuteurToCardService('12');
        }
    }
}