force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Civilite_interlocuteur_intervention__c.field-meta.xml
<CustomField>
    <fullName>Civilite_interlocuteur_intervention__c</fullName>
    <description>@description : champ civilité interlocuteur intervention
@projet: smile</description>
    <label>Civilité interlocuteur intervention</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MR</fullName>
            </value>
            <value>
                <fullName>MLLE</fullName>
            </value>
            <value>
                <fullName>MME</fullName>
            </value>
            <value>
                <fullName>MLLES</fullName>
            </value>
            <value>
                <fullName>MME et MLLE</fullName>
            </value>
            <value>
                <fullName>MMES</fullName>
            </value>
            <value>
                <fullName>AUTRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Creneau__c.field-meta.xml
<CustomField>
    <fullName>Creneau__c</fullName>
    <label>Créneau</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Journée</fullName>
            </value>
            <value>
                <fullName>Début de matinée</fullName>
            </value>
            <value>
                <fullName>Fin de matinée</fullName>
            </value>
            <value>
                <fullName>Midi</fullName>
            </value>
            <value>
                <fullName>Début d&apos;après midi</fullName>
            </value>
            <value>
                <fullName>Fin d&apos;après midi</fullName>
            </value>
            <value>
                <fullName>Matin</fullName>
            </value>
            <value>
                <fullName>Fin d’après midi</fullName>
            </value>
            <value>
                <fullName>Fin de journée</fullName>
            </value>
            <value>
                <fullName>Début de soirée</fullName>
            </value>
            <value>
                <fullName>Milieu de soirée</fullName>
            </value>
            <value>
                <fullName>Soir</fullName>
            </value>
            <value>
                <fullName>Fin de soirée</fullName>
            </value>
            <value>
                <fullName>Après midi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Date_de_prestation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_prestation__c</fullName>
    <label>Date de prestation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Date_statut_prestation__c.field-meta.xml
<CustomField>
    <fullName>Date_statut_prestation__c</fullName>
    <description>@description: ce champ prend le Date statut prestation
@projet: smile</description>
    <label>Date statut prestation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Identifiant_ENGIE__c.field-meta.xml
<CustomField>
    <fullName>Identifiant_ENGIE__c</fullName>
    <description>Identifiant fournisseur alimenté au retour du WS de creation d&apos;OPS.</description>
    <externalId>true</externalId>
    <label>Identifiant ENGIE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Nom_contact_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Nom_contact_d_intervention__c</fullName>
    <description>Nom du contact d&apos;intervention à alimenter au retour du WS ou lors des flux X12 et SDEM</description>
    <label>Nom contact d&apos;intervention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_dernier_jalon__c.field-meta.xml
<CustomField>
    <fullName>Numero_dernier_jalon__c</fullName>
    <description>@description: ce champ comporte le Numéro dernier jalon
@projet: smile</description>
    <label>Numéro dernier jalon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_PDL_PCE__c.field-meta.xml
<CustomField>
    <fullName>Numero_PDL_PCE__c</fullName>
    <label>Numéro de PDL/PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Prenom_contact_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Prenom_contact_d_intervention__c</fullName>
    <description>Prenom du contact intervention alimenté au retour des flux distributeur ou des flux X12 et SDEM</description>
    <label>Prenom contact d&apos;intervention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Secteur_activite__c.field-meta.xml
<CustomField>
    <fullName>Secteur_activite__c</fullName>
    <label>Secteur d&apos;activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elec</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut_dernier_jalon__c.field-meta.xml
<CustomField>
    <fullName>Statut_dernier_jalon__c</fullName>
    <description>@description: ce champ prend le Statut dernier jalon
@projet: smile</description>
    <label>Statut dernier jalon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Telephone_intervention__c.field-meta.xml
<CustomField>
    <fullName>Telephone_intervention__c</fullName>
    <description>Téléphone du contact d&apos;intervention mis à jour au retour des flux distributeur ou X12 ou SDEM</description>
    <label>Telephone intervention</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/recordTypes/HP_PrestationDistributeur.recordType-meta.xml
<RecordType>
    <fullName>HP_PrestationDistributeur</fullName>
    <active>true</active>
    <label>HP_PrestationDistributeur</label>
</RecordType>

force-app/main/default/classes/HP_EM007_PrestationDistributeur_TEST.cls
/**
 * @description  : 
 * @author       : Antoine Latour
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   03-02-2021   Antoine Latour   Initial Version
**/
@isTest
   global class  HP_EM007_PrestationDistributeur_TEST {

	@testSetup static void dataSetup(){

		Id hpRecordTypeId = Schema.SObjectType.Prestation_distributeur__c.getRecordTypeInfosByDeveloperName().get('HP_PrestationDistributeur').getRecordTypeId();

		List<Case> caseList = new List<Case>();
		Case newCaseElec = new Case(status = 'HP_Pending');
		caseList.add(newCaseElec);
		Case newCaseGaz = new Case(status = 'HP_Pending');
		caseList.add(newCaseGaz);
		insert caseList;
  
		List<Prestation_distributeur__c> prestaList = new List<Prestation_distributeur__c>();
		Prestation_distributeur__c opsElec = new Prestation_distributeur__c(Name = 'Elec',
		Case__c = newCaseElec.Id,
		Secteur_activite__c = 'Elec',
		Numero_PDL_PCE__c = '011111111111111',
		Numero_affaire_distributeur__c = '12345678',
		Telephone_intervention__c = '06666666666',
		Statut_dernier_jalon__c = 'En attente',
		Nom_contact_d_intervention__c = 'test test',
		Date_statut_prestation__c = Date.valueOf('2018-01-01'),
		Creneau__c = 'Journée',
		Prenom_contact_d_intervention__c = 'test',
		Civilite_interlocuteur_intervention__c = 'MR',
		Numero_dernier_jalon__c = 1,
		Statut__c = 'En cours',
		Date_de_prestation__c = Date.valueOf('2018-01-01'),
		Identifiant_ENGIE__c = '123456', 
		RecordTypeId = hpRecordTypeId);
		prestaList.add(opsElec);
  
		Prestation_distributeur__c opsGaz = new Prestation_distributeur__c(Name = 'Gaz',
		Case__c = newCaseGaz.Id,
		Secteur_activite__c = 'Gaz',
		Numero_affaire_distributeur__c = '12345679',
		Numero_PDL_PCE__c = '011111111111112',
		Telephone_intervention__c = '06666666666',
		Statut_dernier_jalon__c = 'En cours',
		Nom_contact_d_intervention__c = 'test test',
		Date_statut_prestation__c = Date.valueOf('2018-01-01'),
		Creneau__c = 'Journée',
		Prenom_contact_d_intervention__c = 'test',
		Civilite_interlocuteur_intervention__c = 'MR',
		Numero_dernier_jalon__c = 1,
		Statut__c = 'Terminé',
		Date_de_prestation__c = Date.valueOf('2018-01-01'),
		Identifiant_ENGIE__c = '123457',
		RecordTypeId = hpRecordTypeId);
		prestaList.add(opsGaz);
		insert prestaList;
	 }

   @isTest static void updatePrestationsDistributeur() {
		List<Prestation_distributeur__c> listPresta = HP_EM007_PrestationDistributeurManager.loadPrestationsDistributeurFromListIdAffaire(new Set<String>{'12345678', '12345679'});

		Test.startTest();
		Database.SaveResult[] srList = HP_EM007_PrestationDistributeurManager.updatePrestationsDistributeur(listPresta);
		Test.stopTest();

		System.assert(srList[0].success);
		System.assert(srList[1].success);
    }

	@isTest static void loadPrestationsDistributeurFromListIdAffaire() {
		Test.startTest();
		List<Prestation_distributeur__c> listPresta = HP_EM007_PrestationDistributeurManager.loadPrestationsDistributeurFromListIdAffaire(new Set<String>{'12345678', '12345679'});
		Test.stopTest();
		System.assert(listPresta.size() == 2);
	}

	
	@isTest static void isExistBussinessNum() {
		Test.startTest();
		boolean elecExist = HP_EM007_PrestationDistributeurManager.isExistBussinessNum('12345678', '');
		boolean gazExist = HP_EM007_PrestationDistributeurManager.isExistBussinessNum('12345679', '');
		Test.stopTest();

		System.assert(!elecExist);
		System.assert(gazExist);
	}
	
	
	@isTest static void loadPrestationDistrubuteurToCardService() {
		Test.startTest();
		Prestation_Distributeur__c prestaElec = HP_EM007_PrestationDistributeurManager.loadPrestationDistrubuteurToCardService('011111111111111');
		Prestation_Distributeur__c prestaGaz = HP_EM007_PrestationDistributeurManager.loadPrestationDistrubuteurToCardService('011111111111112');
		Test.stopTest();

		System.assert(prestaElec != null);
		System.assert(prestaGaz != null);
    }

	@isTest static void loadPrestationDistributeur() {
		Test.startTest();
		Prestation_Distributeur__c prestation = HP_EM007_PrestationDistributeurManager.loadPrestationDistributeur('12345678');
		Test.stopTest();
		System.assert(prestation != null);
    }


}