force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_isHappe__c.field-meta.xml
<CustomField>
    <fullName>HP_isHappe__c</fullName>
    <formula>RecordType.DeveloperName == &quot;HP_PrestationDistributeur&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prestation Happe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_TECH_toNotify__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_toNotify__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_TECH_toNotify</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_PDL_PCE__c.field-meta.xml
<CustomField>
    <fullName>Numero_PDL_PCE__c</fullName>
    <label>Numéro de PDL/PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Secteur_activite__c.field-meta.xml
<CustomField>
    <fullName>Secteur_activite__c</fullName>
    <label>Secteur d&apos;activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elec</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Situation_de_vente__c.field-meta.xml
<CustomField>
    <fullName>Situation_de_vente__c</fullName>
    <description>Pemet de déterminer la situation de vente du parcours depuis lequel le conseiller effectue une creation d&apos;OPS</description>
    <label>Situation de vente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Emménagement</fullName>
            </value>
            <value>
                <fullName>Changement de fournisseur</fullName>
            </value>
            <value>
                <fullName>Changement d&apos;offre</fullName>
            </value>
            <value>
                <fullName>Resiliation</fullName>
            </value>
            <value>
                <fullName>HP_Reduction_de_puissance</fullName>
                <label>Réduction de puissance</label>
            </value>
            <value>
                <fullName>HP_Coupure</fullName>
                <label>Coupure</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/recordTypes/HP_PrestationDistributeur.recordType-meta.xml
<RecordType>
    <fullName>HP_PrestationDistributeur</fullName>
    <active>true</active>
    <label>HP_PrestationDistributeur</label>
</RecordType>

force-app/main/default/classes/HP_UTIL_Vue360LoadPrestationDist_TEST.cls
/**
 * @File Name          : HP_UTIL_Vue360LoadPrestationDist_TEST.cls
 * @Description        : 
 * @Author             : Vincent Albiser
 * @Group              : 
 * @Last Modified By   : Hemdene Ben Hammouda
 * @Last Modified On   : 11-09-2021
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    17/06/2020   Vincent Albiser     Initial Version
**/
@isTest
public with sharing class HP_UTIL_Vue360LoadPrestationDist_TEST {

    private enum StaticResource {
        HP_APIHourAccessTokenResponse_MOCK
    }

    @TestSetUp 
	private static void insertTestData(){
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){
            Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact','HP_Contact', new Map<String, Object>{'HP_IsHappe__c' => true,  'Id_Tiers__c' => 100166,'lastName' => 'testnicot'}, null,null, null);
            insert contact;

            Prestation_distributeur__c prestastionEnCours = (Prestation_distributeur__c)HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c', 'HP_PrestationDistributeur', new Map<String, Object>{
                'Numero_PDL_PCE__c' => '21101817254193',
                'Statut__c' => 'En cours',
                'Secteur_activite__c' => 'Gaz',
                'Numero_affaire_distributeur__c' => 'QL30DPC5',
                'Situation_de_vente__c'=>'Resiliation',
                'HP_TECH_toNotify__c' => false,
                'Contact__c' => contact.Id
            }, null, null, null);
            insert prestastionEnCours;
    
            Prestation_distributeur__c prestastionTermine = (Prestation_distributeur__c)HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c', 'HP_PrestationDistributeur', new Map<String, Object>{
                'Numero_PDL_PCE__c' => '21331238214925',
                'Statut__c' => 'Terminé',
                'Secteur_activite__c' => 'Elec',
                'Numero_affaire_distributeur__c' => 'QL30DPC4',
                'Situation_de_vente__c'=>'Resiliation',
                'HP_TECH_toNotify__c' => false,
                'Contact__c' => contact.Id
            }, null, null, null);
            insert prestastionTermine;

            
        }
    }

    
    @isTest static void execute(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
                'token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(
                    200,
                    StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                    new Map<String, String> {'Content-Type' => 'application/json'}
                )
            
            };
    
            String param = '{ "data": {"_data": [{"idPortefeuilleContrat": 254163,"locaux": [{ "idLocal": 241043, "codePostal": "75003", "libelleVoie": "rue des lilas", "numeroVoie": "68",'+
            ' "codeINSEE": "75103","ville": "Paris", "complementAdresse": "","pointsDeLivraison": [{"idPointDeLivraison": 254236,"numeroPointDeLivraison": "21101817254193","typeCompteur": "",'+
            '"etatPCE": "0", "secteurActivite": "gaz" },{ "idPointDeLivraison": 306363,"numeroPointDeLivraison": "21331238214925","systemeInfoContractuel": "DISCO","codeNiveau": "0","secteurActivite": "elec"}]}]}]}}';
            Contact cont = [SELECT Id FROM Contact limit 1];
            String contactId = String.valueOf(cont.Id);
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
            Object result = HP_UTIL_Vue360LoadPrestationDist.processing( (Object)System.JSON.deserializeUntyped(param),contactId);
            Test.stopTest(); 
            system.assert(result instanceof Map<String, Object>, 'Ok');
        }     
    }


}