force-app/main/default/objects/HP_CaseViewHistory__c/HP_CaseViewHistory__c.object-meta.xml
<CustomObject>
    <label>Case View History</label>
    <nameField>
        <displayFormat>CVH-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case View Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_CaseViewHistory__c/fields/HP_Case__c.field-meta.xml
<CustomField>
    <fullName>HP_Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case View Histories</relationshipLabel>
    <relationshipName>Case_View_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HP_EM044_CaseViewHistory.cls
public with sharing class HP_EM044_CaseViewHistory {
    public static Boolean caseHistoryInLastHour(String caseId) {
        DateTime dt = System.now().addHours(-1);
        String userId = UserInfo.getUserId();
        List<HP_CaseViewHistory__c> caseList = [select id from HP_CaseViewHistory__c 
        where HP_Case__c = :caseId and CreatedById = :userId and createdDate > :dt];

        return caseList.size() < 1;
    }

    public static void insertCaseViewHistory(String caseId) {
        HP_CaseViewHistory__c ch = new HP_CaseViewHistory__c(HP_Case__c = caseId);
        
        insert ch;
    }
}