force-app/main/default/objects/SyncEventLog__c/SyncEventLog__c.object-meta.xml
<CustomObject>
    <description>@description: information sur des donnees transmises a Smile depuis un autre systeme pour la synchronisation de donnees, alimente par la classe SM_AP45_XdataImportUtils @projet: smile</description>
    <label>SyncEventLog</label>
    <nameField>
        <label>SyncEventLogs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SyncEventLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SyncEventLog__c/fields/flux__c.field-meta.xml
<CustomField>
    <fullName>flux__c</fullName>
    <description>@description: description du flux, cad appli emettrice et objet mis a jour @projet: smile</description>
    <label>flux</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyncEventLog__c/fields/inputdat__c.field-meta.xml
<CustomField>
    <fullName>inputdat__c</fullName>
    <description>@description: donnees dont l integration a echoue @projet: smile</description>
    <label>inputdat</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SM_AP45_XdataImportUtils.cls
global with sharing class SM_AP45_XdataImportUtils {

	// pour la tracabilite
	final String flux;
	final String objName;
	List<SyncEventLog__c> evlogs = new List<SyncEventLog__c>();

	public SM_AP45_XdataImportUtils(String streamname, String objn){
		flux = streamname;
        objName = objn;
	}
    
    global static ID getRecTypeId(Schema.sObjectType sobjt,String recType){
        ID rtid;
		Schema.RecordTypeInfo rtinf = sobjt.getDescribe().getRecordTypeInfosByDeveloperName().get(recType);
		if (rtinf != null) { rtid = rtinf.getRecordTypeId();}
        else {rtid = null;}
        return rtid;
    }

	// fonction de log d'un bulk upsert
	global void logBulkUpsert(List<Database.UpsertResult> dbrlts, List<sobject> sobjs){
		integer sizeres = dbrlts.size();
		Database.UpsertResult result;
		for(integer respos=0;respos<sizeres;respos+=1){
			result = dbrlts[respos];
            if (result.isSuccess()) { 
				//logImportOk(sobjs[respos].id);
			}
            else {
				logImportError(null,result.getErrors(), JSON.serialize(sobjs[respos]));
			}
		}
	}
		
	// fonction de log d'un bulk insert
	global void logBulkInsertUpdate(List<Database.SaveResult> dbrlts, List<sobject> sobjs){
		integer sizeres = dbrlts.size();
		Database.SaveResult result;
		for(integer respos=0;respos<sizeres;respos+=1){
			result = dbrlts[respos];
            if (result.isSuccess()) {
				//logImportOk(sobjs[respos].id);
			}
            else {
				logImportError(null,result.getErrors(), JSON.serialize(sobjs[respos]));
			}
		}
	}
   
	// fonction de log de l'import reussi
	global void logImportOk(String objid) {
		// TODO: seulement logguer si on est en debug
		/*
		SyncEventLog__c sel = new SyncEventLog__c (flux__c = flux + objName, name=objid);
		evlogs.add(sel);
		System.debug( Date.today() + ' flux ok: ' + flux + ' import de l object: ' + objName + ' id: ' + objid );
		*/
	}
	
	// Fonction de log d'une erreur pour l'import de donnees
	global void logImportError(String errMsg, List<Database.Error> errs,String inputData) {
		String strcause='';
        if(errs != null) { for (Database.Error err: errs) {strcause = strcause + err.getMessage() +' --- ';}}
		else { strcause = errMsg;}
		SyncEventLog__c sel = new SyncEventLog__c (flux__c = flux + objName, name=strcause, inputdat__c = inputData);
		evlogs.add(sel);
		System.debug( Date.today() + ' flux ko: ' + flux + ' import de l object: ' + objName + ' message: ' + strcause + ' donnees: ' + inputData);
	}

	global void saveLogs(){
		if(evlogs.isEmpty())
			return;
		Database.DMLOptions dmo = new Database.DMLOptions();
		dmo.allowFieldTruncation = true;
		dmo.optAllOrNone = true;
		Database.insert(evlogs,dmo);
	}
}