force-app/main/default/objects/HP_Okta_Token_Parameter__c/HP_Okta_Token_Parameter__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>HP Okta Token Parameter</label>
</CustomObject>

force-app/main/default/objects/HP_Okta_Token_Parameter__c/fields/Encryption_Code__c.field-meta.xml
<CustomField>
    <fullName>Encryption_Code__c</fullName>
    <label>Encryption Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HP_WS015_OktaTokenManager_TEST.cls
/**
 * @description       : 
 * @author            : Hemdene Ben Hammouda
 * @group             : 
 * @last modified on  : 03-01-2022
 * @last modified by  : Hemdene Ben Hammouda
**/
@isTest
public with sharing class HP_WS015_OktaTokenManager_TEST {
    
    @TestSetup
    static void setupData(){
        HP_Okta_Token_Parameter__c settings = HP_Okta_Token_Parameter__c.getOrgDefaults();
        settings.Encryption_Key__c = '8cPkWGCoHv9a3D7K';
        settings.Encryption_Code__c = 'AES128';
        upsert settings HP_Okta_Token_Parameter__c.Id;
    }

    @isTest
    static void updateOktaTokenTestOK(){

        RestRequest reqHttp = new RestRequest();
        RestResponse resHttp = new RestResponse();
        String requestBody = '{"token" : "3VyszXPreriqhotjnXY08"}';
        reqHttp.requestBody = Blob.valueof(requestBody);
        RestContext.request = reqHttp;
        RestContext.response = resHttp;


        Test.startTest();
        HP_WS015_OktaTokenManager.updateOktaToken();
        Test.stopTest();

        System.assert (HP_HttpStatus.OK == resHttp.statusCode, 'Token mis à jour correctement');
    }

    @isTest
    static void updateOktaTokenTestKO(){

        RestRequest reqHttp = new RestRequest();
        RestResponse resHttp = new RestResponse();
        String requestBody = '{"token" : ""}';
        reqHttp.requestBody = Blob.valueof(requestBody);
        RestContext.request = reqHttp;
        RestContext.response = resHttp;


        Test.startTest();
        HP_WS015_OktaTokenManager.updateOktaToken();
        Test.stopTest();

        System.assert (HP_HttpStatus.BAD_REQUEST == resHttp.statusCode, 'Token ne peut pas être vide');
    }
}