force-app/main/default/objects/VI_Site_Prestataire__c/VI_Site_Prestataire__c.object-meta.xml
<CustomObject>
    <description>Permet d&apos;identifier à quel site ou prestataire appartient un vendeur Ex: Marketshot possède Active Contact ou Webhelp comme prestataire HelloWatt possède des sites à Paris et Lille</description>
    <label>Site / Prestataire</label>
    <nameField>
        <label>Nom du site / prestataire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites / Prestataires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Site_Prestataire__c/fields/VI_Nom_du_partenaire__c.field-meta.xml
<CustomField>
    <fullName>VI_Nom_du_partenaire__c</fullName>
    <label>Nom du partenaire</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Merci de sélectionner un compte Partenaire.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Partenaire</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sites / Prestataires</relationshipLabel>
    <relationshipName>Sites_Prestataires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VI_Site_Prestataire__c/fields/VI_Type__c.field-meta.xml
<CustomField>
    <fullName>VI_Type__c</fullName>
    <description>Champs permettant de définir s&apos;il s&apos;agit d&apos;un site interne du partenaire ou si le partenaire fait appel à un prestataire externe</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interne</fullName>
            </value>
            <value>
                <fullName>Externe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI_SM045_CreerUtilisateurPartenaire_Test.cls
@isTest
public class VI_SM045_CreerUtilisateurPartenaire_Test {
    @testSetup
    static void testSetup(){
        Id partnerRecordTypeid=VI_ObjectUtils.getRecordTypeId('Contact','PartenaireContactRT');
        Id partnerAccountRecordTypeid=VI_ObjectUtils.getRecordTypeId('Account','PartenaireAccountRT');
        Account acc = VI_TestUtility.createAccount('Marketshot2');
        acc.RecordTypeId=partnerAccountRecordTypeid;
        insert acc;
        VI_Site_Prestataire__c sitePresta=new VI_Site_Prestataire__c(VI_Type__c='Externe',name='testPresta2',VI_Nom_du_partenaire__c=acc.id);       
        insert sitePresta;
        Contact c=new Contact(RecordTypeId=partnerRecordTypeid,Salutation='Monsieur',FirstName='test2',LastName='test2',Email='tes2@test2.com',AccountId=acc.id,
                              VI_Site_Prestataire__c=sitePresta.id);
        insert c;
    }
    @isTest static void testInsert(){
        Id partnerRecordTypeid=VI_ObjectUtils.getRecordTypeId('Contact','PartenaireContactRT');
        Id partnerAccountRecordTypeid=VI_ObjectUtils.getRecordTypeId('Account','PartenaireAccountRT');
        Account acc = VI_TestUtility.createAccount('Marketshot');
        acc.RecordTypeId=partnerAccountRecordTypeid;
        insert acc;
        VI_Site_Prestataire__c sitePresta=new VI_Site_Prestataire__c(VI_Type__c='Externe',name='testPresta',VI_Nom_du_partenaire__c=acc.id);       
        insert sitePresta;
        Contact c=new Contact(RecordTypeId=partnerRecordTypeid,Salutation='Monsieur',FirstName='test1',LastName='test1',Email='test@test.com',AccountId=acc.id,
                              VI_Site_Prestataire__c=sitePresta.id);
        Test.startTest();
        insert c;
        Test.stopTest();
    }
    @isTest static void testUpdate(){
        Contact c=[SELECT id from contact where firstname='test2' limit 1];
        c.FirstName='test3';
        Test.startTest();
        update c;
        Test.stopTest();
    }
}