force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_Origine__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_Origine__c</fullName>
    <label>Date Origine</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_EnvoyerNotificationClient__c.field-meta.xml
<CustomField>
    <fullName>HP_EnvoyerNotificationClient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Envoyer notification au client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumberPCE__c.field-meta.xml
<CustomField>
    <fullName>HP_NumberPCE__c</fullName>
    <label>N° PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Plan_de_Prix_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Plan_de_Prix_electrique__c</fullName>
    <label>Type de comptage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASE</fullName>
                <label>Simple</label>
            </value>
            <value>
                <fullName>VARIABLE</fullName>
                <label>HP/HC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Statut__c.field-meta.xml
<CustomField>
    <fullName>HP_Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVE_1</fullName>
                <label>Devis envoyé</label>
            </value>
            <value>
                <fullName>SAVE_2</fullName>
                <label>Demande envoyée</label>
            </value>
            <value>
                <fullName>SAVE_2_CONFIRMED</fullName>
                <label>CPV envoyées</label>
            </value>
            <value>
                <fullName>CANCEL</fullName>
                <label>CPV annulées</label>
            </value>
            <value>
                <fullName>RETRACT</fullName>
                <label>CPV rétractées</label>
            </value>
            <value>
                <fullName>PERIMEE</fullName>
                <label>CPV périmées</label>
            </value>
            <value>
                <fullName>SAVE_3</fullName>
                <label>CPV signées</label>
            </value>
            <value>
                <fullName>CPV Périmées</fullName>
                <isActive>false</isActive>
                <label>CPV Périmées</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_TECH_FormulaEnergyPDLPCEConcatField__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_FormulaEnergyPDLPCEConcatField__c</fullName>
    <description>concatener HP_NumPDL__c,HP_NumberPCE__c, HP_Type_Energie__c et le contact de la souscription.</description>
    <formula>HP_NumPDL__c &amp; &quot;_&quot; &amp; HP_NumberPCE__c &amp; &quot;_&quot; &amp; TEXT( HP_Type_Energie__c ) &amp; &quot;_&quot; &amp;  HP_Contact__c</formula>
    <label>HP_TECH_FormulaEnergyPDLPCEConcatField</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Tech_Is_Apex_Processing__c.field-meta.xml
<CustomField>
    <fullName>HP_Tech_Is_Apex_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_Tech_Is_Apex_Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Type_Energie__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_Energie__c</fullName>
    <label>Type Energie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRICITY</fullName>
                <label>Electricité</label>
            </value>
            <value>
                <fullName>GAS</fullName>
                <label>Gaz</label>
            </value>
            <value>
                <fullName>COMBINED_GAS_AND_ELECTRICITY</fullName>
                <label>Dual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_type_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_type_Souscription__c</fullName>
    <label>Type de Souscription</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOVING_IN</fullName>
                <label>Emménagement</label>
            </value>
            <value>
                <fullName>SWITCH_SUPLIER</fullName>
                <label>Changement de fournisseur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_SM048_DedupOrderUpGrade_TEST.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 

 * @last modified on  : 07-09-2021

 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   06-08-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/


@IsTest
public with sharing class HP_SM048_DedupOrderUpGrade_TEST {
   
    @isTest 

    public static void  insertSave1() {

        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
           
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;


        HP_Souscription__c enrolment1 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-01',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_Statut__c' =>'SAVE_1',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true

        }, null);
        insert enrolment1;

        HP_Souscription__c enrolment2 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-02',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_Statut__c' =>'SAVE_1',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true


        }, null);
        insert enrolment2;


            final String jobName = 'HP_BAT015_SouscriptionDedupOrderUpgrade';
            final String cronExp = '0 0 23 ? * * *';
            Test.startTest();
            HP_BAT015_SouscriptionDedupOrderUpgrade.launchNewScheduler(cronExp,jobName);
            Test.stopTest();   
       
    }

    @isTest static void launchSave1(){
        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
           
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;


        HP_Souscription__c enrolment1 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-01',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_Statut__c' =>'SAVE_1',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true


        }, null);
        insert enrolment1;

        HP_Souscription__c enrolment2 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-02',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_Statut__c' =>'SAVE_1',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true

        }, null);
        insert enrolment2;

    

        Test.startTest();
        HP_BAT015_SouscriptionDedupOrderUpgrade.execute(Date.Today());
        Test.stopTest();   
    }

    @isTest static void launch_TEST_SAVE2(){

        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
           
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;


        HP_Souscription__c enrolment1 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-01',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',

            'HP_Statut__c' =>'SAVE_2',

            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true


        }, null);
        insert enrolment1;

        HP_Souscription__c enrolment2 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-02',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',

            'HP_Statut__c' =>'SAVE_2',

            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true

        }, null);
        insert enrolment2;

    

        Test.startTest();
        HP_BAT015_SouscriptionDedupOrderUpgrade.execute(Date.Today());
        Test.stopTest();   
    }


    @isTest static void launch_TEST_SAVE_3(){

        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
           
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;


        HP_Souscription__c enrolment1 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-01',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',

            'HP_Statut__c' =>'SAVE_3',

            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true


        }, null);
        insert enrolment1;

        HP_Souscription__c enrolment2 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-02',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',

            'HP_Statut__c' =>'SAVE_3',

            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true

        }, null);
        insert enrolment2;

    

        Test.startTest();
        HP_BAT015_SouscriptionDedupOrderUpgrade.execute(Date.Today());
        Test.stopTest();   
    }




    @isTest static void populateMapContainsKey(){

        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
           
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;


        HP_Souscription__c enrolment1 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-01',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_Statut__c' =>'SAVE_3',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true


        }, null);
        insert enrolment1;

        HP_Souscription__c enrolment2 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {

            'HP_Souscription_Digital_Id__c' =>'testGaz-02_map',

            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_Statut__c' =>'SAVE_3',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true

        }, null);
        insert enrolment2;


        Map<String,List<HP_souscription__c>> canceledSouscriptionMap =  new Map<String,List<HP_souscription__c>>();
        List<HP_souscription__c> listSouscription = new     List<HP_souscription__c>();
        listSouscription = [select id,HP_TECH_FormulaEnergyPDLPCEConcatField__c, HP_Contact__c from HP_Souscription__c where HP_Souscription_Digital_Id__c =:'testGaz-02_map'];
        HP_souscription__c sousc =  [select id,HP_TECH_FormulaEnergyPDLPCEConcatField__c, HP_Contact__c from HP_Souscription__c where HP_Souscription_Digital_Id__c =:'testGaz-02_map' limit 1];
       canceledSouscriptionMap.put(sousc.HP_TECH_FormulaEnergyPDLPCEConcatField__c,listSouscription);
        Test.startTest();
        HP_SM048_SouscriptionDedupOrderUpGrade.populateMap(sousc,canceledSouscriptionMap);
        Test.stopTest();   
    }
    @isTest static void populateMapNoKey(){
        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
           
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;

        HP_Souscription__c enrolment2 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testGaz-00_map',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_Statut__c' =>'SAVE_3',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Type_Energie__c' =>'GAS',
            'HP_Contact__c'=> contact.Id,
            'HP_Date_Origine__c'  =>System.today(),
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_EnvoyerNotificationClient__c' => true

        }, null);
        insert enrolment2;
       
        Map<String,List<HP_souscription__c>> canceledSouscriptionMap =  new Map<String,List<HP_souscription__c>>();
        HP_souscription__c sousc =  [select id,HP_TECH_FormulaEnergyPDLPCEConcatField__c, HP_Contact__c from HP_Souscription__c where HP_Souscription_Digital_Id__c =:'testGaz-00_map' limit 1];
   
        Test.startTest();
        HP_SM048_SouscriptionDedupOrderUpGrade.populateMap(sousc,canceledSouscriptionMap);

        Test.stopTest();   
    }

    


}