force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Statut__c.field-meta.xml
<CustomField>
    <fullName>HP_Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVE_1</fullName>
                <label>Devis envoyé</label>
            </value>
            <value>
                <fullName>SAVE_2</fullName>
                <label>Demande envoyée</label>
            </value>
            <value>
                <fullName>SAVE_2_CONFIRMED</fullName>
                <label>CPV envoyées</label>
            </value>
            <value>
                <fullName>CANCEL</fullName>
                <label>CPV annulées</label>
            </value>
            <value>
                <fullName>RETRACT</fullName>
                <label>CPV rétractées</label>
            </value>
            <value>
                <fullName>PERIMEE</fullName>
                <label>CPV périmées</label>
            </value>
            <value>
                <fullName>SAVE_3</fullName>
                <label>CPV signées</label>
            </value>
            <value>
                <fullName>CPV Périmées</fullName>
                <isActive>false</isActive>
                <label>CPV Périmées</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_TECH_DedupOrder__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_DedupOrder__c</fullName>
    <label>HP_TECH_DedupOrder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_TECH_FormulaConcatField__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_FormulaConcatField__c</fullName>
    <description>concatener HP_NumPDL__c,HP_NumberPCE__c et HP_Date_Origine__c  de la souscription.</description>
    <formula>HP_NumPDL__c &amp; &quot;_&quot; &amp; HP_NumberPCE__c</formula>
    <label>HP_TECH_FormulaConcatField</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HP_SM048_SouscriptionDedupOrder.cls
/**
 * @description  : 
 * @author       : Ali AJELLAL
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   02-12-2020   Ali AJELLAL   Initial Version
**/
public without sharing class HP_SM048_SouscriptionDedupOrder{

    
    /**
    * @La méthode permet de MAJ le champ HP_TECH_DedupOrder__c  sur la souscription en double ayant le statut le plus élevé.
    * @author Ali AJELLAL | 12-03-2020 
    * @param souscriptions 
    **/
    public static void updateSouscriptionWithHighestStatus(List<HP_souscription__c> souscriptions, Date souscriptionDate){
        if(souscriptions == null) return;

        Set<String> concatenationSet = new Set<String>();
        Map<String,List<HP_souscription__c>> mapPdlPceToSouscription = new Map<String,List<HP_souscription__c>>();
        List<HP_souscription__c> souscriptionsToUpdate = new List<HP_souscription__c>();
        Set<Id> ids = new Set<Id>();

        for (HP_souscription__c souscription : souscriptions) {
            concatenationSet.add(souscription.HP_TECH_FormulaConcatField__c);
        }
        System.debug('****************souscriptionList before size************** : ' + souscriptions.size());

        List<HP_Souscription__c> souscriptionList =  HP_EM005_Souscription.getSouscriptionsConcat(concatenationSet, souscriptionDate);
        System.debug('****************souscriptionList************** : ' + souscriptionList);
        System.debug('****************souscriptionList after size************** : ' + souscriptionList.size());


        // construire la Map des concaténations et la liste des souscriptions associée.
        for (HP_Souscription__c souscription : souscriptionList) {
            if(mapPdlPceToSouscription.containsKey(souscription.HP_TECH_FormulaConcatField__c)){
                List<HP_souscription__c> listSouscription = mapPdlPceToSouscription.get(souscription.HP_TECH_FormulaConcatField__c);
                listSouscription.add(souscription);
                mapPdlPceToSouscription.put(souscription.HP_TECH_FormulaConcatField__c, listSouscription);
            }else {
                mapPdlPceToSouscription.put(souscription.HP_TECH_FormulaConcatField__c, new List<HP_souscription__c> { souscription });
               
            }
        }
        System.debug('****************mapPdlPceToSouscription************** : ' + mapPdlPceToSouscription);

        // recuperer les ids des souscriptions avec le statut le plus elevé
        for (String  folmulaConcatField  :  mapPdlPceToSouscription.keySet()) {
            Id idSouscription;
            Integer maxValue = 0;
            for (HP_souscription__c souscription  : mapPdlPceToSouscription.get(folmulaConcatField)){
                souscription.HP_TECH_DedupOrder__c = null;
                Integer statusValue = getStatusValue(souscription.HP_Statut__c);
                if(statusValue > maxValue) {
                    maxValue = statusValue;
                    idSouscription = souscription.Id;
                }
            }
            for (HP_souscription__c souscription  : mapPdlPceToSouscription.get(folmulaConcatField)) {
                if(idSouscription == souscription.Id){
                    souscription.HP_TECH_DedupOrder__c = 1;
                }

                souscriptionsToUpdate.add(souscription);
            }

        }

        if(souscriptionsToUpdate.size() > 0) Database.update(souscriptionsToUpdate);
    }

    /**
    * @
    * @author Ali AJELLAL | 12-04-2020 
    * @param status 
    * @return Integer 
    **/
    public static Integer getStatusValue(String status){

        switch on status {
            when 'RETRACT' {
                return 1;
            }
            when 'PERIMEE' {
                return 2;
            }
            when 'CANCEL' {
                return 3;
            }
            when 'SAVE_1' {
                return 4;
            }
            when 'SAVE_2' {
                return 5;
            }
            when 'SAVE_2_CONFIRMED' {
                return 6;
            }
            when 'SAVE_3' {
                return 7;
            }
        }
        return 1;
    }
}