force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_Origine__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_Origine__c</fullName>
    <label>Date Origine</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumberPCE__c.field-meta.xml
<CustomField>
    <fullName>HP_NumberPCE__c</fullName>
    <label>N° PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumPDL__c.field-meta.xml
<CustomField>
    <fullName>HP_NumPDL__c</fullName>
    <label>N° PDL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Statut__c.field-meta.xml
<CustomField>
    <fullName>HP_Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVE_1</fullName>
                <label>Devis envoyé</label>
            </value>
            <value>
                <fullName>SAVE_2</fullName>
                <label>Demande envoyée</label>
            </value>
            <value>
                <fullName>SAVE_2_CONFIRMED</fullName>
                <label>CPV envoyées</label>
            </value>
            <value>
                <fullName>CANCEL</fullName>
                <label>CPV annulées</label>
            </value>
            <value>
                <fullName>RETRACT</fullName>
                <label>CPV rétractées</label>
            </value>
            <value>
                <fullName>PERIMEE</fullName>
                <label>CPV périmées</label>
            </value>
            <value>
                <fullName>SAVE_3</fullName>
                <label>CPV signées</label>
            </value>
            <value>
                <fullName>CPV Périmées</fullName>
                <isActive>false</isActive>
                <label>CPV Périmées</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_TECH_FormulaConcatField__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_FormulaConcatField__c</fullName>
    <description>concatener HP_NumPDL__c,HP_NumberPCE__c et HP_Date_Origine__c  de la souscription.</description>
    <formula>HP_NumPDL__c &amp; &quot;_&quot; &amp; HP_NumberPCE__c</formula>
    <label>HP_TECH_FormulaConcatField</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HP_BAT015_SouscriptionDedupOrder.cls
/**
 * @description       : 
 * @author            : Ali AJELLAL
 * @last modified on  : 03-23-2021
 * Modifications Log 
 * 1.0   12-02-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/

global with sharing class HP_BAT015_SouscriptionDedupOrder implements  Database.Batchable<SObject>, Schedulable, Database.RaisesPlatformEvents, HP_UTIL_BatchInterface {
   
    public static final Integer BATCH_CHUNK_SIZE = 100;
    public static Date dateQuery = System.now().date().addDays(-30);
    private Date  souscriptionDate;

    global String query = 'select id , HP_NumPDL__c, HP_NumberPCE__c, HP_TECH_FormulaConcatField__c, HP_Statut__c from hp_souscription__c';  


    public HP_BAT015_SouscriptionDedupOrder() {
    
        query = query + '  where  DAY_ONLY(HP_Date_Origine__c ) >= :dateQuery';
        souscriptionDate = dateQuery;

    }

    public HP_BAT015_SouscriptionDedupOrder(Date selectedDate) {
        Datetime toFormatDate = selectedDate;
        souscriptionDate = selectedDate;
        String dateFormat = toFormatDate.formatGmt('yyyy-MM-dd');
        query = query + ' where  DAY_ONLY(HP_Date_Origine__c ) >= ' + dateFormat;
        System.debug('Query : ' + query);
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug(query);
        return Database.getQueryLocator(query);
    }

    global static void launchNewScheduler(String schedule, String jobName){
		System.schedule(jobName, schedule, new HP_BAT015_SouscriptionDedupOrder());
    }

    global static void execute(SchedulableContext sc){
        execute();
    }

    global static void execute(){
        HP_BAT015_SouscriptionDedupOrder batchQsouscriptionDedupOrder = new HP_BAT015_SouscriptionDedupOrder();
        Database.executeBatch(batchQsouscriptionDedupOrder, BATCH_CHUNK_SIZE);
    }

    global static void execute(Date selectedDate) {
        HP_BAT015_SouscriptionDedupOrder batchQsouscriptionDedupOrder = new HP_BAT015_SouscriptionDedupOrder(selectedDate);
        Database.executeBatch(batchQsouscriptionDedupOrder, BATCH_CHUNK_SIZE);
    }

    global void execute(Database.BatchableContext bc, List<hp_souscription__c> souscriptions) { 
        System.debug('*******list usesouscriptionsrs:***'+souscriptions);
       HP_SM048_SouscriptionDedupOrder.updateSouscriptionWithHighestStatus(souscriptions, souscriptionDate);
    }


    global void finish(Database.BatchableContext bc){
        
    }

}