force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Canal_de_vente__c.field-meta.xml
<CustomField>
    <fullName>HP_Canal_de_vente__c</fullName>
    <label>Canal de vente</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Classe_de_la_consommation_Gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Classe_de_la_consommation_Gaz__c</fullName>
    <label>Classe de la consommation Gaz</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASE</fullName>
            </value>
            <value>
                <fullName>B0</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_Electrique_Produit__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_Electrique_Produit__c</fullName>
    <label>Code offre électricité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_Gaz_Produit__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_Gaz_Produit__c</fullName>
    <label>Code offre gaz</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_postal__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_postal__c</fullName>
    <label>Code postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_code_Postal_Insee__c.field-meta.xml
<CustomField>
    <fullName>HP_code_Postal_Insee__c</fullName>
    <label>Code INSEE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_de_Contractualisation__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_de_Contractualisation__c</fullName>
    <label>Date de début de contrat souhaitée</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_Origine__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_Origine__c</fullName>
    <label>Date Origine</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Energie_Verte__c.field-meta.xml
<CustomField>
    <fullName>HP_Energie_Verte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Energie Verte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Estimation_Consommation_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Estimation_Consommation_electrique__c</fullName>
    <label>Estimation Consommation électricité</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Estimation_Consommation_gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Estimation_Consommation_gaz__c</fullName>
    <label>Estimation Consommation gaz</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Jour_de_facturation__c.field-meta.xml
<CustomField>
    <fullName>HP_Jour_de_facturation__c</fullName>
    <label>Date de réglement personnalisée</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Lien_enregistrement__c.field-meta.xml
<CustomField>
    <fullName>HP_Lien_enregistrement__c</fullName>
    <label>Lien d&apos;enregistrement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Methode_de_paiement__c.field-meta.xml
<CustomField>
    <fullName>HP_Methode_de_paiement__c</fullName>
    <label>Mode de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRANSFER</fullName>
                <label>Prélèvement</label>
            </value>
            <value>
                <fullName>BANK_CARD</fullName>
                <label>Carte bancaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Montant_de_la_facturation_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Montant_de_la_facturation_electrique__c</fullName>
    <label>Montant de la mensualité - électricité</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Montant_de_la_facturation_gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Montant_de_la_facturation_gaz__c</fullName>
    <label>Montant de la mensualité - gaz</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Nom_de_rue__c.field-meta.xml
<CustomField>
    <fullName>HP_Nom_de_rue__c</fullName>
    <label>Nom de rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Nom_de_ville__c.field-meta.xml
<CustomField>
    <fullName>HP_Nom_de_ville__c</fullName>
    <label>Nom de ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumberPCE__c.field-meta.xml
<CustomField>
    <fullName>HP_NumberPCE__c</fullName>
    <label>N° PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Numero_de_voie__c.field-meta.xml
<CustomField>
    <fullName>HP_Numero_de_voie__c</fullName>
    <label>Numéro de voie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumPDL__c.field-meta.xml
<CustomField>
    <fullName>HP_NumPDL__c</fullName>
    <label>N° PDL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Periode_de_facturation__c.field-meta.xml
<CustomField>
    <fullName>HP_Periode_de_facturation__c</fullName>
    <label>Fréquence de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY</fullName>
                <label>Annuel</label>
            </value>
            <value>
                <fullName>BIMONTHLY</fullName>
                <label>Bimestriel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Plan_de_Prix_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Plan_de_Prix_electrique__c</fullName>
    <label>Type de comptage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASE</fullName>
                <label>Simple</label>
            </value>
            <value>
                <fullName>VARIABLE</fullName>
                <label>HP/HC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Predecesseur__c.field-meta.xml
<CustomField>
    <fullName>HP_Predecesseur__c</fullName>
    <label>Nom du prédécesseur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Puissance_Compteur_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Puissance_Compteur_electrique__c</fullName>
    <label>Puissance Compteur électricité</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Statut__c.field-meta.xml
<CustomField>
    <fullName>HP_Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVE_1</fullName>
                <label>Devis envoyé</label>
            </value>
            <value>
                <fullName>SAVE_2</fullName>
                <label>Demande envoyée</label>
            </value>
            <value>
                <fullName>SAVE_2_CONFIRMED</fullName>
                <label>CPV envoyées</label>
            </value>
            <value>
                <fullName>CANCEL</fullName>
                <label>CPV annulées</label>
            </value>
            <value>
                <fullName>RETRACT</fullName>
                <label>CPV rétractées</label>
            </value>
            <value>
                <fullName>PERIMEE</fullName>
                <label>CPV périmées</label>
            </value>
            <value>
                <fullName>SAVE_3</fullName>
                <label>CPV signées</label>
            </value>
            <value>
                <fullName>CPV Périmées</fullName>
                <isActive>false</isActive>
                <label>CPV Périmées</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Type_Energie__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_Energie__c</fullName>
    <label>Type Energie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRICITY</fullName>
                <label>Electricité</label>
            </value>
            <value>
                <fullName>GAS</fullName>
                <label>Gaz</label>
            </value>
            <value>
                <fullName>COMBINED_GAS_AND_ELECTRICITY</fullName>
                <label>Dual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_type_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_type_Souscription__c</fullName>
    <label>Type de Souscription</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOVING_IN</fullName>
                <label>Emménagement</label>
            </value>
            <value>
                <fullName>SWITCH_SUPLIER</fullName>
                <label>Changement de fournisseur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_SM045_NoteSatisfaction_TEST.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-16-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   11-04-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@IsTest
public with sharing class HP_SM045_NoteSatisfaction_TEST {
    @testSetup static void dataSetup(){
        Account acc = (Account)HP_UTIL_SmartFactory.createSObject('Account','HP_Account' ,new Map<String, Object>{
            'HP_XDataExternalId__c' => 100166,
            'Name' => 'UnitTest',
            'OwnerId' => UserInfo.getUserId()
        },null,null, null);
        insert acc;
        
        Contact acontact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
            'AccountId' => acc.Id,
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY',
            'OwnerId' => UserInfo.getUserId(),
            'HP_IsHappe__c' => true
        }, null, null, null);
        insert acontact;

    }
    @IsTest
    public static void loadSatTest() {
        HP_SM045_NoteSatisfaction.loadContactWithNoteSatisfaction([select id from contact].Id);
    }

    @IsTest
    public static void noteSatisfactionFromAvisTest() {
        Contact acontact  = [ select Id from Contact limit 1 ];
        HP_Souscription__c enrolment = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Canal_de_vente__c'  => 'Vente Online',
            'HP_Contact__c'=> acontact.Id,
            'HP_Classe_de_la_consommation_Gaz__c'  => 'B0',
            'HP_Code_Gaz_Produit__c'  => 'GITR2_H',
            'HP_Code_Electrique_Produit__c'  => 'EITR2_H',
            'HP_Code_postal__c'  => '92160',
            'HP_code_Postal_Insee__c'  => '92002',
            'HP_Date_de_Contractualisation__c'  => System.today().addDays(1),
            'HP_Date_Origine__c'  =>DateTime.newInstance(2019, 10, 9, 13, 0, 0),
            'HP_Energie_Verte__c'  => false,
            'HP_Estimation_Consommation_electrique__c'  => 6000,
            'HP_Estimation_Consommation_gaz__c'  => 13000,
            'HP_Jour_de_facturation__c' => 16,
            'HP_Lien_enregistrement__c' =>'test.fr',
            'HP_Methode_de_paiement__c' =>'BANK_CARD',
            'HP_Montant_de_la_facturation_electrique__c' =>58,
            'HP_Montant_de_la_facturation_gaz__c' =>120,
            'HP_Predecesseur__c' =>'Dupont',
            'HP_Nom_de_rue__c' =>'rue des bois',
            'HP_Nom_de_ville__c' =>'ANTONY',
            'HP_Numero_de_voie__c' =>'15 ter',
            'HP_Periode_de_facturation__c' =>'BIMONTHLY',
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_Puissance_Compteur_electrique__c' =>6,
            'HP_Souscription_Digital_Id__c' =>'testGazElec-01',
            'HP_Type_Energie__c' =>'COMBINED_GAS_AND_ELECTRICITY',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_NumPDL__c' =>'31431211214170',
            'HP_Statut__c' =>'SAVE_1',
            'OwnerId' => UserInfo.getUserId()
        }, null);
        insert enrolment;
        
        HP_EM041_NoteSatisfaction.noteSatisfactionFromAvis('5','9','870dd7ad','1612540251614_vq8L0Uqvoh',enrolment.Id,acontact.Id, '2021-02-08 09:24:08',DateTime.newInstance(2019, 10, 9, 13, 0, 0),'review','test','test','test');
    }
}