force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumberPCE__c.field-meta.xml
<CustomField>
    <fullName>HP_NumberPCE__c</fullName>
    <label>N° PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumPDL__c.field-meta.xml
<CustomField>
    <fullName>HP_NumPDL__c</fullName>
    <label>N° PDL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Type_Energie__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_Energie__c</fullName>
    <label>Type Energie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRICITY</fullName>
                <label>Electricité</label>
            </value>
            <value>
                <fullName>GAS</fullName>
                <label>Gaz</label>
            </value>
            <value>
                <fullName>COMBINED_GAS_AND_ELECTRICITY</fullName>
                <label>Dual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_type_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_type_Souscription__c</fullName>
    <label>Type de Souscription</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOVING_IN</fullName>
                <label>Emménagement</label>
            </value>
            <value>
                <fullName>SWITCH_SUPLIER</fullName>
                <label>Changement de fournisseur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_WRP039_Devis.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 


 * @last modified on  : 03-03-2021


 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   02-19-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/


global with sharing class HP_WRP039_Devis {

	global class Request {
		public final String digitalId;

		global Request(String digitalId){
			this.digitalId = digitalId;
		}
    }
    
    global class Response {

		public final List<souscriptionInfos> souscriptionInfos;

		global Response(List<HP_Souscription__c> souscriptionList){
			this.souscriptionInfos = new List<souscriptionInfos>();

			for(HP_Souscription__c souscription : souscriptionList) {
				this.souscriptionInfos.add(new souscriptionInfos(souscription));
			}
			
		}

		global boolean isListEmpty(){
			return this.souscriptionInfos.size() == 0;
		}






    }
    
    global class souscriptionInfos {

        public final String digitalSouscriptionId;




		public final String name;
        public final String typeSouscription;
        public final String typeEnergy;
        public final String pdl;
		public final String pce;
		

		global souscriptionInfos(HP_Souscription__c souscription){
			this.digitalSouscriptionId  = souscription.HP_Souscription_Digital_Id__c;




            this.typeSouscription = souscription.HP_type_Souscription__c;
            this.typeEnergy = souscription.HP_Type_Energie__c;
            this.pdl = souscription.HP_NumPDL__c;
			this.pce = souscription.HP_NumberPCE__c;
			this.name = souscription.Name;



		}
	}

	global class APIException extends Exception {}

}