force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/HP_EC_Sharegroop_Setting__mdt.object-meta.xml
<CustomObject>
    <label>HP EC Sharegroop Setting</label>
    <pluralLabel>HP EC Sharegroop Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/fields/currency__c.field-meta.xml
<CustomField>
    <fullName>currency__c</fullName>
    <label>currency</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/fields/locale__c.field-meta.xml
<CustomField>
    <fullName>locale__c</fullName>
    <label>locale</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/fields/notifyUrl__c.field-meta.xml
<CustomField>
    <fullName>notifyUrl__c</fullName>
    <label>notifyUrl</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/fields/quantity__c.field-meta.xml
<CustomField>
    <fullName>quantity__c</fullName>
    <label>quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/fields/secure3D__c.field-meta.xml
<CustomField>
    <fullName>secure3D__c</fullName>
    <defaultValue>true</defaultValue>
    <label>secure3D</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_EC_Sharegroop_Setting__mdt/fields/ux__c.field-meta.xml
<CustomField>
    <fullName>ux__c</fullName>
    <label>ux</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HP_SM076_ShareGroopController.cls
/**
 * @description       : 
 * @author            : Badr Eddine Belkarchi
 * @group             : 
 * @last modified on  : 06-10-2022
 * @last modified by  : Badr Eddine Belkarchi
**/
public with sharing class HP_SM076_ShareGroopController {

    public static final String SHAREGROOP = 'EC_Sharegroop';

    public static String createOrderPaiementAPlusieurs(String echeance_reference, String montant_restant_du, String email, String prenom, String nom) {
        System.debug('HP_SM076_ShareGroopController.createOrderPaiementAPlusieurs() | Methode Start');

        HP_EC_Sharegroop_Setting__mdt sahregroopSetting = [ SELECT DeveloperName, ux__c, locale__c, currency__c, secure3D__c, notifyUrl__c, name__c, quantity__c
                                                            FROM HP_EC_Sharegroop_Setting__mdt WHERE DeveloperName = :SHAREGROOP LIMIT 1];

        String body = buildBody(sahregroopSetting,echeance_reference,montant_restant_du,email,prenom,nom);

        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://api.sandbox.sharegroop.com/v1/orders');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        req.setHeader('Authorization', 'sk_test_dd84dad5-d73c-48aa-bbee-eb1dab5a8499');
        req.setBody(body);
        HttpResponse response = http.send(req);

        System.debug('HP_SM076_ShareGroopController.createOrderPaiementAPlusieurs() status code : ' + response.getStatusCode());
        System.debug('@@Response : '+response);
        System.debug('@@Response Body : '+response.getBody());

        System.debug('HP_SM076_ShareGroopController.createOrderPaiementAPlusieurs() | Methode Exit');
        return response.getBody();
    }

    public static String buildBody(HP_EC_Sharegroop_Setting__mdt sahregroopSetting, String echeance_reference, String montant_restant_du, String email, String prenom, String nom) {
        
        Integer montant     = (Decimal.valueOf(montant_restant_du) * 100).intValue();
        String UX           = sahregroopSetting.ux__c;
        String LOCALE       = sahregroopSetting.locale__c;
        String CURRENCYY    = sahregroopSetting.currency__c;
        String SECURE3D     = String.valueOf(sahregroopSetting.secure3D__c);
        String NOTIFY_URL   = sahregroopSetting.notifyUrl__c + echeance_reference;
        String NAME         = sahregroopSetting.name__c;
        String QUANTITY     = String.valueOf(sahregroopSetting.quantity__c);

        String result =
                '{'+
                    '"amount": "'+montant+'",'+
                    '"ux": "'+UX+'",'+
                    '"locale": "'+LOCALE+'",'+
                    '"currency": "'+CURRENCYY+'",'+
                    '"secure3D": '+SECURE3D+','+
                    '"email": "'+email+'",'+
                    '"firstName": "'+prenom+'",'+
                    '"lastName": "'+nom+'",'+
                    '"trackId": "'+echeance_reference+'",'+
                    '"notifyUrl": "'+NOTIFY_URL+'",'+
                    '"items": ['+
                    '        {'+
                    '        "trackId": "'+echeance_reference+'",'+
                    '        "name": "'+NAME+'",'+
                    '        "description": "Echeance REF: '+echeance_reference+'",'+
                    '        "amount": "'+montant+'",'+
                    '        "quantity": '+QUANTITY+''+
                    '        }'+
                    '    ]'+
                    '}';

        System.debug('@@buildBody result : '+result);
        return result;
    }
    
}