force-app/main/default/objects/HP_MajConsentements__c/HP_MajConsentements__c.object-meta.xml
<CustomObject>
    <description>Consements des clients Happe en provenance de Xdata</description>
    <label>Consentement Happe</label>
    <nameField>
        <displayFormat>HPCO-{000000}</displayFormat>
        <label>Nom des Consentements Happe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consentements Happe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_MajConsentements__c/fields/HP_Canal__c.field-meta.xml
<CustomField>
    <fullName>HP_Canal__c</fullName>
    <label>Canal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_MajConsentements__c/fields/HP_Consentement__c.field-meta.xml
<CustomField>
    <fullName>HP_Consentement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consentement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_MajConsentements__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.HP_IsHappe__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Consentements Happe</relationshipLabel>
    <relationshipName>Consentements_Happe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HP_MajConsentements__c/fields/HP_IdQuestionConsentement__c.field-meta.xml
<CustomField>
    <fullName>HP_IdQuestionConsentement__c</fullName>
    <label>ID Question consentement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_MajConsentements__c/fields/HP_IdQuestionnaireConsentement__c.field-meta.xml
<CustomField>
    <fullName>HP_IdQuestionnaireConsentement__c</fullName>
    <label>ID Questionnaire consentement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_MajConsentements__c/fields/HP_IdXDATA__c.field-meta.xml
<CustomField>
    <fullName>HP_IdXDATA__c</fullName>
    <label>Id XDATA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_MajConsentements__c/fields/HP_Source__c.field-meta.xml
<CustomField>
    <fullName>HP_Source__c</fullName>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HP_SM071_Consentement.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-15-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class HP_SM071_Consentement {
    
    public static HP_MajConsentements__c createConsentement(Contact c, Boolean consentement, Decimal xDataId, Integer questionId, Integer questionnaireID, String source, String canal) {
        HP_MajConsentements__c cons = new HP_MajConsentements__c();
        cons.HP_Contact__c = c.Id;
        cons.HP_Consentement__c = consentement;
        cons.HP_IdXDATA__c = xDataId;
        cons.HP_IdQuestionConsentement__c = questionId;
        cons.HP_IdQuestionnaireConsentement__c = questionnaireID;
        cons.HP_Source__c = source;
        cons.HP_Canal__c = canal;
        return cons;
    }
}