force-app/main/default/objects/SM_interactionDetail__mdt/SM_interactionDetail__mdt.object-meta.xml
<CustomObject>
    <label>SM_interactionDetail</label>
    <pluralLabel>SM_interactionDetail</pluralLabel>
</CustomObject>

force-app/main/default/objects/SM_interactionDetail__mdt/fields/detailInteraction__c.field-meta.xml
<CustomField>
    <fullName>detailInteraction__c</fullName>
    <label>detailInteraction</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SM_interactionDetail__mdt/fields/parcours__c.field-meta.xml
<CustomField>
    <fullName>parcours__c</fullName>
    <label>parcours</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SM_AP86_FillInteractionDetails.cls
global with sharing class SM_AP86_FillInteractionDetails implements vlocity_cmt.VlocityOpenInterface{
    
    global Boolean invokeMethod(String methodName, Map < String, Object > inputMap, Map < String, Object > outMap, Map < String, Object > options) {

        if (methodName.equals('FillInteractionDetails')) {
            try {
                FillInteractionDetails(inputMap, outMap, options);
                } catch (Exception e) {
                system.debug(e.getStackTraceString());
                return false;
            }
        }

        return true;
    }
    
    public void FillInteractionDetails( Map < String, Object > inputMap, Map < String, Object > outMap, Map < String, Object > options) {
		
        String interactionDetail;
        String interactionDetailsTransform;
        String parcours = String.valueOf(inputMap.get('parcours'));
        Map<String,Object> parameters = (Map<String,Object>) inputMap.get('interactionDetailsParam');

        system.debug('parameters' + parameters);
        
        if(!Test.isRunningTest()){
         interactionDetail = [SELECT Id, parcours__c, detailInteraction__c, DeveloperName FROM SM_interactionDetail__mdt where parcours__c = :parcours limit 1].detailInteraction__c;
        }
        else{
            interactionDetail = 'Informations clients\n'
                +'\tMaj infos perso : OK / KO\n'+
                +'\tConsentement Engie et Partenaires : OK / KO\n';
        }
        
        for(String Key : parameters.keySet()){
            system.debug('key:' + key + ' value:' + parameters.get(key));
            interactionDetail = interactionDetail.replace('%'+key+'%',String.valueOf(parameters.get(key)));           
        }
		
        outMap.put('InteractionDetails',interactionDetail);

    }
   
}