force-app/main/default/objects/SM_ProcessSettings__mdt/SM_ProcessSettings__mdt.object-meta.xml
<CustomObject>
    <description>Define in JSON all attributes that can be used for a process (batch, trigger, api ...)</description>
    <label>SM_ProcessSettings</label>
    <pluralLabel>SM_ProcessSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SM_ProcessSettings__mdt/fields/JsonAttr__c.field-meta.xml
<CustomField>
    <fullName>JsonAttr__c</fullName>
    <description>Contains All attr to parse in JSON</description>
    <label>JsonAttr</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SM_EM105_ProcessSettings.cls
/**
 * @author Sutharsan Pushparajah
 * @date 24/6/2022
 * @description SM_EM105_ProcessSettings - Entity to manage SM_ProcessSettings__mdt custommetadatatype
 */
public inherited sharing class SM_EM105_ProcessSettings {
    
    /**
     * @author Sutharsan Pushparajah
     * @date 24/06/2022
     * @description get configuration from the SM_ProcessSettings__mdt for the corresponding apiName
     * @param apiName the API Name of the setting
     * @return Map<String, Object> The map contains attribute key and value
     */
    public static Map<String, Object> getProcessSettings(String apiName){
        SM_ProcessSettings__mdt processSettings = SM_ProcessSettings__mdt.getInstance(apiName);
        Map<String, Object> attributes = (Map<String, Object>) JSON.deserializeUntyped(processSettings.JsonAttr__c);
        
        return attributes;
    }
}