force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/TECH_2_Nom_Partenaire__c.field-meta.xml
<CustomField>
    <fullName>TECH_2_Nom_Partenaire__c</fullName>
    <formula>SUBSTITUTE(Owner:User.Contact.Account.Name, &quot; &quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH 2 Nom Partenaire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/Tech_Nom_Partenaire__c.field-meta.xml
<CustomField>
    <fullName>Tech_Nom_Partenaire__c</fullName>
    <formula>Owner:User.Contact.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech Nom Partenaire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Case__c.field-meta.xml
<CustomField>
    <fullName>VI_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Parcours</relationshipLabel>
    <relationshipName>Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_NomClient__c.field-meta.xml
<CustomField>
    <fullName>VI_NomClient__c</fullName>
    <description>Champ de création client</description>
    <label>Nom</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutCasePartnerCommunity__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutCasePartnerCommunity__c</fullName>
    <formula>IF(AND(ISPICKVAL(VI_Case__r.Status, &quot;Pré-clôturé&quot;),
       ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Abandon&quot;)),&quot;Abandon&quot;,
			
IF(ISPICKVAL(VI_Case__r.Status, &quot;Annulé&quot;),&quot;Annulé&quot;,
			
IF(OR(AND(ISPICKVAL(VI_Case__r.Status, &quot;Pré-clôturé&quot;),
          ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Rétractation&quot;)
																																															),
						ISPICKVAL(VI_Case__r.Status, &quot;Rétracté&quot;)),&quot;Rétracté&quot;,


			
			
IF(OR(AND(ISPICKVAL(VI_Case__r.Status, &quot;En attente&quot;),
                                                    ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Retour distributeur&quot;)				
						), 
						AND(ISPICKVAL(VI_Case__r.Status, &quot;A traiter&quot;),
										ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Absence retour distributeur&quot;)
						),
						AND(ISPICKVAL(VI_Case__r.Status, &quot;En traitement&quot;),
										ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Absence retour distributeur&quot;)
						),
						AND(ISPICKVAL(VI_Case__r.Status, &quot;Pré-clôturé&quot;),
										OR(ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Conforme&quot;),
													ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;&quot;)
										)
      ),
						AND(ISPICKVAL(VI_Case__r.Status, &quot;Clôturé&quot;),
										OR(ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Conforme&quot;),
													ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;&quot;)))),&quot;Vente transformée&quot;,



IF(AND (OR(AND(ISPICKVAL(VI_Case__r.Status, &quot;En Traitement&quot;),
															ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;&quot;)
											),
											AND(ISPICKVAL(VI_Case__r.Status, &quot;En attente&quot;),
														 ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Retour client&quot;)
											),
											AND(ISPICKVAL(VI_Case__r.Status, &quot;A traiter&quot;),
               ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Retour client&quot;)
											),
										ISPICKVAL(VI_Case__r.Status, &quot;Différé&quot;))),&quot;En traitement BO&quot;,
			

IF(AND(ISPICKVAL(VI_Case__r.Status, &quot;En attente&quot;),
       ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Retour Partenaire&quot;)),&quot;Vente à completer&quot;, 


IF(AND(OR(ISPICKVAL(VI_Case__r.Status, &quot;A traiter&quot;),
									 ISPICKVAL(VI_Case__r.Status, &quot;Affecté&quot;)
							),
							OR(ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;&quot;),
										ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Retour Partenaire&quot;)
								/*ISPICKVAL(VI_Case__r.Sous_statut__c, &quot;Absence retour Partenaire&quot;)*/ 	)),&quot;A traiter BO&quot;,
			

IF(AND( /*CPV envoyées*/
       CONTAINS(TEXT(VI_StatutParcours__c),&quot;CPV Envoyées&quot;),
							NOT(ISPICKVAL(VI_Case__r.VI_StatutEnveloppe__c ,&quot;Delivered&quot;)),
	      NOT(ISPICKVAL(VI_Case__r.VI_StatutEnveloppe__c ,&quot;Signed&quot;))
			), &quot;CPV envoyées&quot;,
			
			
IF(AND(ISPICKVAL(VI_ChoixParcours__c, &quot;CHF&quot;),
							ISPICKVAL(VI_Case__r.VI_StatutEnveloppe__c,&quot;Signed&quot;)),&quot;CPV signées&quot;,	
			
			
IF(AND(ISPICKVAL(VI_ChoixParcours__c, &quot;CHF&quot;),
							ISPICKVAL(VI_Case__r.VI_StatutEnveloppe__c, &quot;Delivered&quot;)), &quot;CPV délivrées&quot;,		
			
&quot;&quot;))))))))))</formula>
    <label>Statut du case</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutduCase__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutduCase__c</fullName>
    <description>Données techniques, statut du case</description>
    <label>OLDStatut du case</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPV Délivrées</fullName>
                <default>true</default>
                <label>CPV Délivrées</label>
            </value>
            <value>
                <fullName>CPV Signées</fullName>
            </value>
            <value>
                <fullName>A traiter BO</fullName>
            </value>
            <value>
                <fullName>En traitement BO</fullName>
            </value>
            <value>
                <fullName>Vente à compléter</fullName>
            </value>
            <value>
                <fullName>Vente transformée</fullName>
            </value>
            <value>
                <fullName>Vente perdue</fullName>
            </value>
            <value>
                <fullName>Abandon</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Rétracté</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutParcours__c</fullName>
    <label>Statut du parcours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vente en cours</fullName>
                <default>true</default>
                <label>Vente en cours</label>
            </value>
            <value>
                <fullName>Vente à compléter</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE connu</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE non connu</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>A traiter BO</fullName>
                <isActive>false</isActive>
                <label>A traiter BO</label>
            </value>
            <value>
                <fullName>CPV Délivrées</fullName>
                <isActive>false</isActive>
                <label>CPV Délivrées</label>
            </value>
            <value>
                <fullName>CPV Signées</fullName>
                <isActive>false</isActive>
                <label>CPV Signées</label>
            </value>
            <value>
                <fullName>En traitement BO</fullName>
                <isActive>false</isActive>
                <label>En traitement BO</label>
            </value>
            <value>
                <fullName>Rétracté</fullName>
                <isActive>false</isActive>
                <label>Rétracté</label>
            </value>
            <value>
                <fullName>Vente en suspens</fullName>
                <isActive>false</isActive>
                <label>Vente en suspens</label>
            </value>
            <value>
                <fullName>Vente transformée</fullName>
                <isActive>false</isActive>
                <label>Vente transformée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_NomDuClient__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_NomDuClient__c</fullName>
    <formula>VI_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Nom du client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_SitePrestatairePartenaire__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_SitePrestatairePartenaire__c</fullName>
    <formula>Owner:User.Contact.VI_Site_Prestataire__r.Name + &quot; &quot; +  Owner:User.Contact.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Site / Prestataire - Partenaire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_TelephonePrincipal__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_TelephonePrincipal__c</fullName>
    <formula>IF(
				NOT(VI_Contact__r.TechMobilePrincipale__c == null),
				VI_Contact__r.TechMobilePrincipale__c,
				VI_Contact__r.TechFixePrincipale__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Telephone principal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_TypeDuSitePrestataire__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_TypeDuSitePrestataire__c</fullName>
    <formula>TEXT(Owner:User.Contact.VI_Site_Prestataire__r.VI_Type__c)</formula>
    <label>TECH Type du site / prestataire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Site_Prestataire__c/VI_Site_Prestataire__c.object-meta.xml
<CustomObject>
    <description>Permet d&apos;identifier à quel site ou prestataire appartient un vendeur Ex: Marketshot possède Active Contact ou Webhelp comme prestataire HelloWatt possède des sites à Paris et Lille</description>
    <label>Site / Prestataire</label>
    <nameField>
        <label>Nom du site / prestataire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites / Prestataires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VI_SM041_NotifyPartner.cls
/*@Author: Amal Chreiteh
*@Description: Classe test de VI_SM041_NotifyPartner_Test
*@CreatedDate: 04/05/2021
*@LastModified: 04/05/2021
*/

public class VI_SM041_NotifyPartner {
    
    /**
* @author Amal Chreiteh
* @date 04/05/2021
* @description Créer une tâche côté Partenaire suite au changement du statut = En traitement et sous-statut = Retours Tiers => Recu
* @param creerPersonneInput, context, port (wrappers Définit par WSDL), NamedCredentialName (callout:VI_AuthOctopus, callout:AuthOctopus), partitionName (local.VIToken,local.smileToken)
* @return creerPersonneResponse_element wrapper defined in the wsdl
*/
    public static void NotifyPartner(Case[] newList,Map<Id, Case> oldMap){
        system.debug('NotifyPartner');
        List<Case> listcase=new List<Case>();
        List<Task> tasksToInsert=new List<Task>();
        set<Id> casesId = new Set<Id>();
        String BORecordTypeId=VI_ObjectUtils.getRecordTypeId('Task','VI_DemandeBO');
        Id CaseRTId = Case.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Acquisition_Harmonica').getRecordTypeId();
        system.debug('newList'+ newList);
        
        for(case cas:newList){
            system.debug('cas.Origin'+ cas.Origin);
            system.debug('cas.Status'+ cas.Status);
            system.debug('cas.Sous_statut__c'+ cas.Sous_statut__c);
            system.debug(cas.RecordTypeId == CaseRTId);
            
            system.debug(cas.Status != oldMap.get(cas.Id).Status);
            system.debug(oldMap.containsKey(cas.Id));
            if(!(cas.Sous_statut__c == null || cas.Origin == null) && cas.RecordTypeId == CaseRTId){
                system.debug('here');
                system.debug(cas.Origin.equals('Partner Community') );
                system.debug(cas.Status.equals('En attente'));
                system.debug(cas.Sous_statut__c.equals('Retour partenaire'));
                system.debug(cas.Status != oldMap.get(cas.Id).Status);
                system.debug(oldMap.containsKey(cas.Id));
                if(cas.Origin.equals('Partner Community')
                   && cas.Status.equals('En attente') && cas.Sous_statut__c.equalsIgnoreCase('Retour partenaire')
                   && oldMap.containsKey(cas.Id)  
                   && cas.Status != oldMap.get(cas.Id).Status){
                       listcase.add(cas);
                       system.debug('cas'+ cas);
                   }   
            }
        }
        system.debug('listcase'+ listcase);
        if(listcase != null && listcase.size()>0){
            //Remonter les parcours relié aux cases 
            Map<Id,VI_Parcours__c> mapParcoursCase=new Map<Id,VI_Parcours__c>();
            List<VI_Parcours__c> listParcours=[SELECT id,Name,CreatedDate,VI_Case__c,VI_Case__r.Status,VI_Case__r.Sous_statut__c,VI_Case__r.Origin,Tech_Nom_Partenaire__c,
                                               VI_TECH_TypeDuSitePrestataire__c,VI_TECH_NomDuClient__c,VI_TECH_TelephonePrincipal__c,VI_StatutCasePartnerCommunity__c,
                                               VI_StatutParcours__c, VI_TECH_SitePrestatairePartenaire__c,Tech_2_Nom_Partenaire__c
                                               From VI_Parcours__c
                                               Where VI_Case__c in:listcase];
            
            for(VI_Parcours__c parcours:listParcours){
                mapParcoursCase.put(parcours.VI_Case__c,parcours);
            }
            
            
            //Remonter les queues disponibles
            List<Group> ownerQueue = [Select Id,DeveloperName from Group where Type = 'Queue' AND DeveloperName LIKE '%BO_Partenaire'];
            Map<String,Id> mapQueueIds=new Map<String,Id>();
            for(Group queue:ownerQueue){
                mapQueueIds.put(queue.DeveloperName,queue.id);
            }
            //Remonter les tâches reliées aux cases
            List<Task> taskCases = [SELECT Id, Description, Subject, WhatId, createddate
                                    FROM Task
                                    WHERE WhatId in:listcase order by WhatId, createddate desc];
            system.debug('taskCases'+ taskCases);
            for(Task t: taskCases){
                if(!casesId.contains(t.whatId)){
                    VI_Parcours__c parcoursToCheck=mapParcoursCase.get(t.WhatId);
                    casesId.add(t.whatId);
                    Task newTask=new Task();
                    newTask.recordTypeId=BORecordTypeId;
                    newTask.WhatId=parcoursToCheck.Id;
                    newTask.Description=t.Description;
                    newTask.IsVisibleInSelfService=true;
                    newTask.Subject=t.Subject;
                    newTask.VI_TypeDuSitePrestataire__c = parcoursToCheck.VI_TECH_TypeDuSitePrestataire__c;
                    newTask.VI_NomClient__c = parcoursToCheck.VI_TECH_NomDuClient__c;
                    newTask.VI_TelephonePrincipal__c = parcoursToCheck.VI_TECH_TelephonePrincipal__c;
                    newTask.VI_DateDeCreationDuParcours__c = parcoursToCheck.CreatedDate;
                    newTask.VI_StatutDuCase__c = parcoursToCheck.VI_StatutCasePartnerCommunity__c;
                    newTask.VI_StatutDuParcours__c = parcoursToCheck.VI_StatutParcours__c;
                    newTask.VI_Site_prestataire__c = parcoursToCheck.VI_TECH_SitePrestatairePartenaire__c;
                    newTask.VI_WhatName__c=parcoursToCheck.name;
                    if(t.Description!=null){
                        if (t.Description.length() > 254) {
                            newTask.VI_ApercuDuCommentaire__c = t.Description.substring(0, 254);
                        }
                        else {
                            newTask.VI_ApercuDuCommentaire__c = t.Description;
                        }
                    }
                    
                    if(!test.isRunningTest()){
                        newTask.OwnerId=mapQueueIds.get('VI_'+parcoursToCheck.Tech_2_Nom_Partenaire__c+'BO_Partenaire');
                    }
                    else{
                        Profile p = [SELECT Id FROM Profile WHERE name='System Administrator']; 
                        User u = new User(Alias = 'standaat', Email='standardueeeser@testorg.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testinddddg', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, 
                                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduseeeer@testorg.com');
                        insert u;
                        newTask.OwnerId=u.id;
                        
                    }
                    tasksToInsert.add(newTask);
                }
                
            }
            system.debug('tasksToInsert'+ tasksToInsert);
            if(tasksToInsert!= null & tasksToInsert.size()>0){
                insert tasksToInsert;
            }
        }
    }
}