force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ChoixMoyenPaiement__c.field-meta.xml
<CustomField>
    <fullName>VI_ChoixMoyenPaiement__c</fullName>
    <description>Champ étape saisie moyens de paiement pour le choix du moyen de paiement</description>
    <label>Choix moyen de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prélèvement automatique</fullName>
                <default>true</default>
                <label>Prélèvement automatique</label>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ChoixParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_ChoixParcours__c</fullName>
    <description>Le prospect au téléphone effectue soit un changement de fournisseur (même adresse cible) soit un emménagement (nouvelle adresse)</description>
    <label>Choix de la situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
                <label>Emménager dans un nouveau logement</label>
            </value>
            <value>
                <fullName>CHF</fullName>
                <label>Changer de fournisseur pour Engie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ConsentProspectionEngieNonAnalogue__c.field-meta.xml
<CustomField>
    <fullName>VI_ConsentProspectionEngieNonAnalogue__c</fullName>
    <label>Consent prospection engie non analogue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IndexBaseRechercheLocal__c.field-meta.xml
<CustomField>
    <fullName>VI_IndexBaseRechercheLocal__c</fullName>
    <description>Section champs complémentaires
Correspond au numéro de relevé de compteur Base</description>
    <label>Index Base</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IndexHCRechercheLocal__c.field-meta.xml
<CustomField>
    <fullName>VI_IndexHCRechercheLocal__c</fullName>
    <description>Section champs complémentaires
Correspond au numéro de relevé de compteur Heure creuse</description>
    <label>Index HC</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IndexHPRechercheLocal__c.field-meta.xml
<CustomField>
    <fullName>VI_IndexHPRechercheLocal__c</fullName>
    <description>Section champs complémentaires
Correspond au numéro de relevé de compteur - Heure pleine</description>
    <label>Index HP</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutParcours__c</fullName>
    <label>Statut du parcours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vente en cours</fullName>
                <default>true</default>
                <label>Vente en cours</label>
            </value>
            <value>
                <fullName>Vente à compléter</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE connu</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE non connu</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>A traiter BO</fullName>
                <isActive>false</isActive>
                <label>A traiter BO</label>
            </value>
            <value>
                <fullName>CPV Délivrées</fullName>
                <isActive>false</isActive>
                <label>CPV Délivrées</label>
            </value>
            <value>
                <fullName>CPV Signées</fullName>
                <isActive>false</isActive>
                <label>CPV Signées</label>
            </value>
            <value>
                <fullName>En traitement BO</fullName>
                <isActive>false</isActive>
                <label>En traitement BO</label>
            </value>
            <value>
                <fullName>Rétracté</fullName>
                <isActive>false</isActive>
                <label>Rétracté</label>
            </value>
            <value>
                <fullName>Vente en suspens</fullName>
                <isActive>false</isActive>
                <label>Vente en suspens</label>
            </value>
            <value>
                <fullName>Vente transformée</fullName>
                <isActive>false</isActive>
                <label>Vente transformée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI_ParcoursTriggerHandler_Test.cls
/*
*@Author: Georges Mardini
*@Description: Classe test de CaseHandler.
*@CreatedDate: 15/11/2020
*@LastModified: 15/11/2020
*/
@isTest 
public class VI_ParcoursTriggerHandler_Test {
    @testSetup
    static void testSetup(){
        List<Group> ownerQueue = [Select Id,DeveloperName from Group where Type = 'Queue'];
        
        system.debug('query queue '+ownerQueue);
        Id profileId = [Select Id From Profile Where Name ='VI_PurePlayer'].Id;
        Account acc = VI_TestUtility.createAccount('Marketshot');
        insert acc;
        Contact con = VI_TestUtility.createContact('test','Contact','test@gmail.com',acc.Id);
        insert con;
        User u = VI_TestUtility.createCommunityUser(con.Id,profileId,'Test','Test');
        insert u;
    }
    
    @isTest
    public static void TriggerHandlerTest() {
        // create Account
        Account Acc = SM_TestDataFactory.createAccount('Harmonica_Account');
        Insert acc;
        
        // Create Case
        Case caseTest = SM_TestDataFactory.createCase('TEST', Acc.Id);
        caseTest.Sous_type__c = 'Changement de fournisseur';
        caseTest.Origin = 'Partner Community';
        insert caseTest;   
        
        // Create Parcours
        User u =[Select id from user where firstname='Test' and lastname='Test' and isActive=true limit 1];
        System.runAs(u){
            Test.startTest();
            //VI_Parcours__c parcrousTest = VI_TestDataFactory.createParcours('CHF', caseTest.id, 'PURE PLAYERS');
            VI_Parcours__c parcrousTest = VI_TestDataFactory.createParcours('CHF', null, 'PURE PLAYERS');
            parcrousTest.VI_ConsentProspectionEngieNonAnalogue__c = 'Non';
            
            insert parcrousTest;   
            VI_Parcours__c parcours1=[Select id,VI_ConsentProspectionEngieNonAnalogue__c from VI_Parcours__c where id=:parcrousTest.id limit 1];
            system.assertEquals(parcours1.VI_ConsentProspectionEngieNonAnalogue__c, 'Non');
            parcrousTest.VI_ConsentProspectionEngieNonAnalogue__c = 'Oui';
            parcrousTest.VI_StatutParcours__c = 'CPV Envoyées: PDL/PCE connu';
            parcrousTest.VI_ChoixParcours__c ='CHF';
            parcrousTest.VI_IndexBaseRechercheLocal__c = '1';
            parcrousTest.VI_IndexHCRechercheLocal__c = '1';
            parcrousTest.VI_IndexHPRechercheLocal__c = '1';
            parcrousTest.VI_ChoixMoyenPaiement__c = 'Prélèvement automatique';
            update parcrousTest; 
            VI_Parcours__c parcours2=[Select id,VI_ChoixMoyenPaiement__c from VI_Parcours__c where id=:parcrousTest.id limit 1];
            system.assertEquals(parcours2.VI_ChoixMoyenPaiement__c,  'Prélèvement automatique');
            Test.stopTest();
        }
        VI_ParcoursTriggerHandler parcoursTriggerHandler = new VI_ParcoursTriggerHandler();
            parcoursTriggerHandler.isDisabled();
    }
}