force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Date_envoi_email__c.field-meta.xml
<CustomField>
    <fullName>VI_Date_envoi_email__c</fullName>
    <label>Date d&apos;envoi d&apos;email</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutEnveloppe__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutEnveloppe__c</fullName>
    <formula>TEXT(VI_Case__r.VI_StatutEnveloppe__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut de l&apos;enveloppe</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VI_SCH005_ExpirationParcours_Test.cls
/*
*@Auhtor: Clément	 Bouquin
*@Description: Classe de test de VI_SCH005_ExpirationParcours
*@CreatedDate: 06/07/2021
*/

@isTest
public class VI_SCH005_ExpirationParcours_Test {
    
    public static String CRON_EXP = '0 0 1 * * ? *';
    @testSetup
    static void testSetup1(){
        Case casex=new Case(VI_StatutEnveloppe__c='Sent' );
        insert casex;
        VI_Parcours__c parcours= VI_TestDataFactory.createParcours('CHF', casex.id, 'PURE PLAYERS');
        parcours.VI_Date_envoi_email__c=system.today().adddays(-11);
        insert parcours;
    }
    static testmethod void testScheduledJob() {
        Test.startTest();
        // Schedule the test job
        VI_SCH005_ExpirationParcours schExpirationBatch = new VI_SCH005_ExpirationParcours();
        String jobID = System.schedule('Mise à jour du statut du Parcours à \'Expiré\' ainsi que le status du Case à \'Pré-clôturé\' et son sous-statut à \'Abandon\' Si le status de l enveloppe n est pas \'Signed\' 10 jours après son envoie', CRON_EXP, schExpirationBatch);
        Test.stopTest();
    }
}