force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Case__c.field-meta.xml
<CustomField>
    <fullName>VI_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Parcours</relationshipLabel>
    <relationshipName>Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ChoixParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_ChoixParcours__c</fullName>
    <description>Le prospect au téléphone effectue soit un changement de fournisseur (même adresse cible) soit un emménagement (nouvelle adresse)</description>
    <label>Choix de la situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
                <label>Emménager dans un nouveau logement</label>
            </value>
            <value>
                <fullName>CHF</fullName>
                <label>Changer de fournisseur pour Engie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateEnvoiEnveloppe__c.field-meta.xml
<CustomField>
    <fullName>VI_DateEnvoiEnveloppe__c</fullName>
    <formula>VI_Case__r.VI_DateEnvoiEnveloppe__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date d&apos;envoi enveloppe</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutEnveloppe__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutEnveloppe__c</fullName>
    <formula>TEXT(VI_Case__r.VI_StatutEnveloppe__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut de l&apos;enveloppe</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutParcours__c</fullName>
    <label>Statut du parcours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vente en cours</fullName>
                <default>true</default>
                <label>Vente en cours</label>
            </value>
            <value>
                <fullName>Vente à compléter</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE connu</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE non connu</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>A traiter BO</fullName>
                <isActive>false</isActive>
                <label>A traiter BO</label>
            </value>
            <value>
                <fullName>CPV Délivrées</fullName>
                <isActive>false</isActive>
                <label>CPV Délivrées</label>
            </value>
            <value>
                <fullName>CPV Signées</fullName>
                <isActive>false</isActive>
                <label>CPV Signées</label>
            </value>
            <value>
                <fullName>En traitement BO</fullName>
                <isActive>false</isActive>
                <label>En traitement BO</label>
            </value>
            <value>
                <fullName>Rétracté</fullName>
                <isActive>false</isActive>
                <label>Rétracté</label>
            </value>
            <value>
                <fullName>Vente en suspens</fullName>
                <isActive>false</isActive>
                <label>Vente en suspens</label>
            </value>
            <value>
                <fullName>Vente transformée</fullName>
                <isActive>false</isActive>
                <label>Vente transformée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI_BAT005_ExpirationParcours.cls
/*
*@Author: Clément Bouquin
*@Description: Batch qui met à jours le status du Case à 'Pré-clôturé' et son sous-statut à 'Abandon'
Si le status de l'enveloppe n'est pas 'Signed' 30 jours après son envoie.
*@CreatedDate: 06/07/2021
*@LastModified: 13/09/2021
*/

global class VI_BAT005_ExpirationParcours implements Database.Batchable<sObject>{

    // Query select every Parcours and their linked Cases ids with an enveloppe not Signed after 30 days
    global final String query = 'SELECT Id, VI_StatutParcours__c, VI_Case__c FROM VI_Parcours__c WHERE VI_ChoixParcours__c=\'CHF\' AND VI_Case__r.VI_DateEnvoiEnveloppe__c < LAST_N_DAYS:30 AND VI_Case__r.VI_StatutEnveloppe__c!=\'Signed\'';
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('VI_BAT005_ExpirationParcours starting...');
        return Database.getQueryLocator(query);
    }
    
    public static void execute(){
        VI_BAT005_ExpirationParcours expirationBatch = new VI_BAT005_ExpirationParcours();
        Database.executeBatch(expirationBatch,200);
    }
    
	global void execute(Database.BatchableContext bc, List<VI_Parcours__c> scope){
        // Update VI_StatutParcours__c, Case's Status and Sous_statut__c of every VI_StatutEnveloppe__c != 'Signed' if VI_DateEnvoiEnveloppe__c higher than 30 days

        Set<Id> setCaseIds=new Set<Id>();
        for(VI_Parcours__c parcours:scope) {
            // Add the id case of the current parcours, from the scope, in setCaseIds
            setCaseIds.add(parcours.VI_Case__c);
        }
        // Query select every Case's in the parcours previously selected
        List<Case> listcase=new List<Case>();
        listcase=[SELECT Id, VI_DateEnvoiEnveloppe__c, VI_StatutEnveloppe__c, Status, Sous_statut__c FROM Case WHERE Id IN :setCaseIds];

        for(Case currentCase :listcase){
            // Update Status from Case
            currentCase.Status= 'Pré-clôturé';
            // Update Sous_statut__c from Case
            currentCase.Sous_statut__c = 'Abandon';  
        }
        update listcase;

    }
        
    global void finish(Database.BatchableContext bc){
        System.debug('VI_BAT005_ExpirationParcours ending...');
    }
    
}