force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_NomClient__c.field-meta.xml
<CustomField>
    <fullName>VI_NomClient__c</fullName>
    <description>Champ de création client</description>
    <label>Nom</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutduCase__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutduCase__c</fullName>
    <description>Données techniques, statut du case</description>
    <label>OLDStatut du case</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPV Délivrées</fullName>
                <default>true</default>
                <label>CPV Délivrées</label>
            </value>
            <value>
                <fullName>CPV Signées</fullName>
            </value>
            <value>
                <fullName>A traiter BO</fullName>
            </value>
            <value>
                <fullName>En traitement BO</fullName>
            </value>
            <value>
                <fullName>Vente à compléter</fullName>
            </value>
            <value>
                <fullName>Vente transformée</fullName>
            </value>
            <value>
                <fullName>Vente perdue</fullName>
            </value>
            <value>
                <fullName>Abandon</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Rétracté</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Site_Prestataire__c/VI_Site_Prestataire__c.object-meta.xml
<CustomObject>
    <description>Permet d&apos;identifier à quel site ou prestataire appartient un vendeur Ex: Marketshot possède Active Contact ou Webhelp comme prestataire HelloWatt possède des sites à Paris et Lille</description>
    <label>Site / Prestataire</label>
    <nameField>
        <label>Nom du site / prestataire</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites / Prestataires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/VI_SM041_NotifyPartner_Test.cls
/*@Author: Amal Chreiteh
*@Description: Classe test de VI_SM041_NotifyPartner
*@CreatedDate: 5/5/2021
*@LastModified: 5/5/2021
*/
@isTest
public class VI_SM041_NotifyPartner_Test {
 @isTest
    static void testMethod1(){
        VI_TaskTriggerHandler handler=new VI_TaskTriggerHandler();
        handler.isDisabled();
        Id caseRTId = Case.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Acquisition_Harmonica').getRecordTypeId();
        String boRecordTypeId=Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('VI_DemandeBO').getRecordTypeId();
        User ownerUser=[SELECT id,contact.account.name from user limit 1];
        
        Case c=new case();
        c.status='En traitment';
        c.Origin='Partner Community';
        c.RecordTypeId = caseRTId;
        insert c;
        
        VI_Parcours__c parcours=VI_testDataFactory.createParcours('CHF', c.id, 'PURE PLAYERS');
        parcours.OwnerId=ownerUser.id;
        insert parcours;
        
        Task insertedTask=new Task();
        insertedTask.recordTypeId=Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('SMILE').getRecordTypeId();
        insertedTask.whatid=c.id;
        insertedTask.Description='test';
        insert insertedTask;
        
        c.status='En attente';
        c.Sous_statut__c='Retour partenaire';
        update c;
        
        List<Task> listTask=[Select id, VI_NomClient__c, VI_TelephonePrincipal__c, VI_DateDeCreationDuParcours__c,VI_StatutDuCase__c, VI_StatutDuParcours__c, VI_Site_prestataire__c
                             from task 
                             where recordTypeid=:boRecordTypeId];
        //system.assert(listTask.size()>0);
    }
}