force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Case__c.field-meta.xml
<CustomField>
    <fullName>VI_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Parcours</relationshipLabel>
    <relationshipName>Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Id_coordonnees_bancaires__c.field-meta.xml
<CustomField>
    <fullName>VI_Id_coordonnees_bancaires__c</fullName>
    <label>ID coordonnées bancaires</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ID_Mandat__c.field-meta.xml
<CustomField>
    <fullName>VI_ID_Mandat__c</fullName>
    <description>Lorsque ce champ est rempli, cela veut dire qu&apos;il y a un mandat Sepa, cela déclenche alors le statut &quot;A signer&quot; du champ statut mandat de données de vente</description>
    <label>ID Mandat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IDReferenceClient__c.field-meta.xml
<CustomField>
    <fullName>VI_IDReferenceClient__c</fullName>
    <description>Donnée technique - Id du contact dans Symphonie</description>
    <label>ID Référence client</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutMandat__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutMandat__c</fullName>
    <formula>TEXT(VI_Case__r.VI_StatutMandat__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut mandat</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VI_SM039_SignatureMandatListCase.cls
public class VI_SM039_SignatureMandatListCase {
    
    public static void signedCase(Case[] newList,Map<Id, Case> oldMap){
        System.debug('### START sendCase ');
        System.debug('### newList : ' + newList);
        System.debug('### oldMap : ' + oldMap);
        List<Case> listcase=new List<Case>();
        Set<id> setCaseIds=new Set<Id>();
        List<VI_Parcours__c> listParcours;
        List<case> listCaseToUpdate=new List<Case>();
        Id CaseRTId = Case.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Acquisition_Harmonica').getRecordTypeId();
        for(case cas:newList){
            if(cas.Origin != null){
                if(cas.Origin.equals('Partner Community')
                   && cas.VI_StatutMandat__c == 'Signed'
                   && oldMap.containsKey(cas.Id)  
                   && cas.VI_StatutMandat__c != oldMap.get(cas.Id).VI_StatutMandat__c
                   && cas.RecordTypeId == CaseRTId){
                       listcase.add(cas);
                   }   
            }
        }
        System.debug('listcase '+listcase);
        
        //Filling caseIds in set to query parcours for required fields
        if(listcase!= null & listcase.size()>0){
            for(case cas:listcase){
                setCaseIds.add(cas.id);
            }
        }
        listParcours=[Select id,VI_IDReferenceClient__c, VI_Id_coordonnees_bancaires__c, VI_ID_Mandat__c,VI_Case__c  from VI_Parcours__c where VI_Case__c in :setCaseIds];
        
        if(listParcours!= null & listParcours.size()>0){
            for(VI_Parcours__c parcoursWithMandatToUpdate:listParcours){
                VI_SM038_MAJMandat.majMandat(parcoursWithMandatToUpdate.VI_Case__c,parcoursWithMandatToUpdate.VI_ID_Mandat__c,
                                             '1',
                                             parcoursWithMandatToUpdate.VI_IDReferenceClient__c,
                                             parcoursWithMandatToUpdate.VI_Id_coordonnees_bancaires__c,
                                             'VI',
                                             '1.0',
                                             'callout:VI_AuthOctopus');
                
            }
        }
    }
}