force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CiviliteClient__c.field-meta.xml
<CustomField>
    <fullName>VI_CiviliteClient__c</fullName>
    <description>Champ de recherche et de création client</description>
    <label>Civilité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madame</fullName>
            </value>
            <value>
                <fullName>Monsieur</fullName>
            </value>
            <value>
                <fullName>Co-titulaire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Email_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Email_CPV__c</fullName>
    <description>Champ email supplémentaire en cas de volonté du client de donner une adresse email différente pour l&apos;envoi des CPV</description>
    <label>Email CPV</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Id_coordonnees_bancaires__c.field-meta.xml
<CustomField>
    <fullName>VI_Id_coordonnees_bancaires__c</fullName>
    <label>ID coordonnées bancaires</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ID_Mandat__c.field-meta.xml
<CustomField>
    <fullName>VI_ID_Mandat__c</fullName>
    <description>Lorsque ce champ est rempli, cela veut dire qu&apos;il y a un mandat Sepa, cela déclenche alors le statut &quot;A signer&quot; du champ statut mandat de données de vente</description>
    <label>ID Mandat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IDReferenceClient__c.field-meta.xml
<CustomField>
    <fullName>VI_IDReferenceClient__c</fullName>
    <description>Donnée technique - Id du contact dans Symphonie</description>
    <label>ID Référence client</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_NomClient__c.field-meta.xml
<CustomField>
    <fullName>VI_NomClient__c</fullName>
    <description>Champ de création client</description>
    <label>Nom</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_PrenomClient__c.field-meta.xml
<CustomField>
    <fullName>VI_PrenomClient__c</fullName>
    <description>Champ de recherche et création  client</description>
    <label>Prénom</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VI_SM037_ComposerMandat_Test.cls
@isTest
public class VI_SM037_ComposerMandat_Test {
    @isTest
    static void testComposerMandat(){
        Id contactRTId = Contact.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Contact_Smile').getRecordTypeId();
        Contact parcoursContact =new Contact();
        parcoursContact.firstname='tests';
        parcoursContact.salutation='Mr';
        parcoursContact.lastName='test';
        parcoursContact.Complement_adresse__c='test';
        parcoursContact.MailingPostalCode='test';
        parcoursContact.Mailingcity='test';
        parcoursContact.Mailingcountry='test';
        parcoursContact.recordTypeId=contactRTId;
        
        
        insert parcoursContact;
        VI_Parcours__c parcours =new VI_Parcours__c();
        
        parcours.VI_ID_Mandat__c='2134';
        parcours.VI_IDReferenceClient__c='1234';
        parcours.VI_CiviliteClient__c='Monsieur';
        parcours.VI_NomClient__c='test';
        parcours.VI_PrenomClient__c='test';
        parcours.VI_IDReferenceClient__c='test';
        parcours.VI_Email_CPV__c='test@est.com';
        parcours.VI_Id_coordonnees_bancaires__c='0202000001-01';
        insert parcours;
        Test.startTest();
        VI_SM037_ComposerMandat.retourMandat response=
            VI_SM037_ComposerMandat.composerMandat('MANDAT_POUR_SIGNATURE_ELECTRONIQUE',parcours ,parcoursContact,true,'PP','1.0','callout:VI_AuthOctopus');
        system.assertEquals(response.idDocument,'00MPA2112619234606130000');
        Test.stopTest();
    }
}