force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_EmailEnvoye__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailEnvoye__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Champ coché lorsque l&apos;email envoyé au client est envoyé</description>
    <label>Email envoyé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ID_Mandat__c.field-meta.xml
<CustomField>
    <fullName>VI_ID_Mandat__c</fullName>
    <description>Lorsque ce champ est rempli, cela veut dire qu&apos;il y a un mandat Sepa, cela déclenche alors le statut &quot;A signer&quot; du champ statut mandat de données de vente</description>
    <label>ID Mandat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_idCompteClient__c.field-meta.xml
<CustomField>
    <fullName>VI_idCompteClient__c</fullName>
    <label>ID Compte Client</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IDReferenceClient__c.field-meta.xml
<CustomField>
    <fullName>VI_IDReferenceClient__c</fullName>
    <description>Donnée technique - Id du contact dans Symphonie</description>
    <label>ID Référence client</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Tech_relance__c.field-meta.xml
<CustomField>
    <fullName>VI_Tech_relance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech relance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_URL_Mandat__c.field-meta.xml
<CustomField>
    <fullName>VI_URL_Mandat__c</fullName>
    <description>Champ pour stocker l&apos;URL vers l&apos;enveloppe du mandat Sepa envoyé par DocuSign</description>
    <label>URL Mandat</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/VI_BAT001_RelanceMandat_Test.cls
/*
*@Auhtor: Paul Ghoussoub
*@Description: Classe de test de VI_BAT001_RelanceMandat
*@CreatedDate: 16/03/2021
*/
@isTest
public class VI_BAT001_RelanceMandat_Test {
    @testSetup
    static void testSetup1(){
        VI_Parcours__c parcours=new VI_Parcours__c(VI_URL_Mandat__c='www.urlmandat.com',VI_IDReferenceClient__c='1',VI_ID_Mandat__c='1',VI_EmailEnvoye__c=true,VI_idCompteClient__c='1',VI_Tech_relance__c=false);
        insert parcours;
    }
    @isTest
    static void testBatch(){
		Test.startTest();
        VI_BAT001_RelanceMandat.execute();
        Test.stopTest();        
        List<VI_Parcours__c> listParcours =[SELECT id,VI_Tech_relance__c from VI_Parcours__c];
        system.debug('listParcours '+listParcours);
        for(VI_Parcours__c parcours:listParcours){
            System.assert(parcours.VI_Tech_relance__c);
        }
    }

}