force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentaireGeneral_Constitutionpanier__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentaireGeneral_Constitutionpanier__c</fullName>
    <description>Zone de commentaire général pour l&apos;étape Constitution du panier</description>
    <label>Commentaire général Constitution panier</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentaireGeneral_EstimationConso__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentaireGeneral_EstimationConso__c</fullName>
    <description>Zone de commentaire général pour l&apos;étape estimation de la consommation</description>
    <label>Commentaire général Estimation conso</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentaireGeneral_idbesoin__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentaireGeneral_idbesoin__c</fullName>
    <description>Zone de commentaire général pour l&apos;étape identification besoin</description>
    <label>Commentaire général Identificationbesoin</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentaireGeneral_idclient__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentaireGeneral_idclient__c</fullName>
    <description>Zone de commentaire général pour l&apos;étape identification client</description>
    <label>Commentaire général Identificationclient</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentaireGeneral_idlocal__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentaireGeneral_idlocal__c</fullName>
    <description>Zone de commentaire général pour l&apos;étape identification local</description>
    <label>Commentaire général Identification local</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentaireGeneral_InfosCompl__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentaireGeneral_InfosCompl__c</fullName>
    <description>Zone de commentaire général pour l&apos;étape informations complémentaires</description>
    <label>Commentaire général infoscomplémentaire</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentaireGeneral_MoyensPaiement__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentaireGeneral_MoyensPaiement__c</fullName>
    <description>Zone de commentaire général pour l&apos;étape Saisie moyens de paiement</description>
    <label>Commentaire général Moyens de paiement</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentairesParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentairesParcours__c</fullName>
    <label>Commentaires</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentairesReprendreParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentairesReprendreParcours__c</fullName>
    <description>Zone de commentaires en complément du bouton reprendre le parcours plus tard</description>
    <label>Commentaires Reprendre le parcours</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CommentairesTransfertAppel__c.field-meta.xml
<CustomField>
    <fullName>VI_CommentairesTransfertAppel__c</fullName>
    <description>Zone de commentaires en complément du bouton transfert d&apos;appel</description>
    <label>Commentaires Transfert d&apos;appel</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Contact__c.field-meta.xml
<CustomField>
    <fullName>VI_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contient le contact utilisé dans ce parcours</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parcours</relationshipLabel>
    <relationshipName>Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateEcheanceTache__c.field-meta.xml
<CustomField>
    <fullName>VI_DateEcheanceTache__c</fullName>
    <label>Date échéance de la tâche</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DescriptionTache__c.field-meta.xml
<CustomField>
    <fullName>VI_DescriptionTache__c</fullName>
    <label>Description tâche</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_HeureEcheanceTache__c.field-meta.xml
<CustomField>
    <fullName>VI_HeureEcheanceTache__c</fullName>
    <label>Heure échéance de la tâche</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_NomClient__c.field-meta.xml
<CustomField>
    <fullName>VI_NomClient__c</fullName>
    <description>Champ de création client</description>
    <label>Nom</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_PlanifierTache__c.field-meta.xml
<CustomField>
    <fullName>VI_PlanifierTache__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Planification d&apos;un tâche possible en cas de reprise du parcours plus tard.</description>
    <label>Planifier une tâche</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutduCase__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutduCase__c</fullName>
    <description>Données techniques, statut du case</description>
    <label>OLDStatut du case</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPV Délivrées</fullName>
                <default>true</default>
                <label>CPV Délivrées</label>
            </value>
            <value>
                <fullName>CPV Signées</fullName>
            </value>
            <value>
                <fullName>A traiter BO</fullName>
            </value>
            <value>
                <fullName>En traitement BO</fullName>
            </value>
            <value>
                <fullName>Vente à compléter</fullName>
            </value>
            <value>
                <fullName>Vente transformée</fullName>
            </value>
            <value>
                <fullName>Vente perdue</fullName>
            </value>
            <value>
                <fullName>Abandon</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Rétracté</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutParcours__c</fullName>
    <label>Statut du parcours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vente en cours</fullName>
                <default>true</default>
                <label>Vente en cours</label>
            </value>
            <value>
                <fullName>Vente à compléter</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE connu</fullName>
            </value>
            <value>
                <fullName>CPV Envoyées: PDL/PCE non connu</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>A traiter BO</fullName>
                <isActive>false</isActive>
                <label>A traiter BO</label>
            </value>
            <value>
                <fullName>CPV Délivrées</fullName>
                <isActive>false</isActive>
                <label>CPV Délivrées</label>
            </value>
            <value>
                <fullName>CPV Signées</fullName>
                <isActive>false</isActive>
                <label>CPV Signées</label>
            </value>
            <value>
                <fullName>En traitement BO</fullName>
                <isActive>false</isActive>
                <label>En traitement BO</label>
            </value>
            <value>
                <fullName>Rétracté</fullName>
                <isActive>false</isActive>
                <label>Rétracté</label>
            </value>
            <value>
                <fullName>Vente en suspens</fullName>
                <isActive>false</isActive>
                <label>Vente en suspens</label>
            </value>
            <value>
                <fullName>Vente transformée</fullName>
                <isActive>false</isActive>
                <label>Vente transformée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_NomDuClient__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_NomDuClient__c</fullName>
    <formula>VI_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Nom du client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_SitePrestatairePartenaire__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_SitePrestatairePartenaire__c</fullName>
    <formula>Owner:User.Contact.VI_Site_Prestataire__r.Name + &quot; &quot; +  Owner:User.Contact.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Site / Prestataire - Partenaire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_TelephonePrincipal__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_TelephonePrincipal__c</fullName>
    <formula>IF(
				NOT(VI_Contact__r.TechMobilePrincipale__c == null),
				VI_Contact__r.TechMobilePrincipale__c,
				VI_Contact__r.TechFixePrincipale__c 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH Telephone principal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TECH_TypeDuSitePrestataire__c.field-meta.xml
<CustomField>
    <fullName>VI_TECH_TypeDuSitePrestataire__c</fullName>
    <formula>TEXT(Owner:User.Contact.VI_Site_Prestataire__r.VI_Type__c)</formula>
    <label>TECH Type du site / prestataire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TypeParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_TypeParcours__c</fullName>
    <description>Attribue au compte le type d’enseigne dans la CPV créée et qui fera le lien avec Symphonie/Amadeus pour les reporting de vente notamment</description>
    <label>Type parcours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PURE PLAYERS</fullName>
            </value>
            <value>
                <fullName>VENTE DIRECTE</fullName>
            </value>
            <value>
                <fullName>STORE</fullName>
            </value>
            <value>
                <fullName>DISTRIBUTION</fullName>
            </value>
            <value>
                <fullName>CORNER</fullName>
                <isActive>false</isActive>
                <label>CORNER</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI_ParcoursPpRoundButton_Controller.cls
/*@Author: Eloi Dereeper
*@Description: Controlleur Apex du LWC ParcoursPpRoundButton
*@CreatedDate: 15/12/2020
*@LastModified: 22/12/2020
*/
public without sharing class VI_ParcoursPpRoundButton_Controller { 
    /*@Author: Eloi Dereeper
*@Description: ajouter un commentaire sur le parours--> n'est plus utilisé
*@CreatedDate: 15/12/2020
*@LastModified: 22/12/2020
*/
    @AuraEnabled
    public static void transfererParcours(VI_Parcours__c  parcours, String comments){
        parcours.VI_CommentairesTransfertAppel__c = comments;
        update parcours;
    }
        /*@Author: Eloi Dereeper
*@Description: ajouter un commentaire sur le parours dans une etape
*@CreatedDate: 15/12/2020
*@LastModified: 22/12/2020
*/
    
    @AuraEnabled
    public static void writeComment(VI_Parcours__c  parcours, String comments,String step){
        System.debug('EDE Debug; parcours : ' + parcours);
        if(!(parcours.VI_StatutParcours__c.equals('CPV Envoyées: PDL/PCE connu') || parcours.VI_StatutParcours__c.equals('CPV Envoyées: PDL/PCE non connu'))){
            if(step.equals('situation')    || step.equals('energy')){
                parcours.VI_CommentaireGeneral_idbesoin__c=comments;
            }
            else if(step.equals('client_energy')){
                parcours.VI_CommentaireGeneral_idclient__c=comments;
            }
            else if(step.equals('identification_local')){
                parcours.VI_CommentaireGeneral_idlocal__c=comments;
            }
            else if(step.equals('EstimationConsommation')){
                parcours.VI_CommentaireGeneral_EstimationConso__c=comments;
            }
            else if(step.equals('ConstitutionPanier')){
                parcours.VI_CommentaireGeneral_Constitutionpanier__c=comments;
            }
            if(step.equals('DateEffetContrat')    || step.equals('RelevesCompteur')){
                parcours.VI_CommentaireGeneral_InfosCompl__c=comments;
            }
            else if(step.equals('Saisie_moyen_de_paiement')){
                parcours.VI_CommentaireGeneral_MoyensPaiement__c=comments;
            }
            else if(step.equals('Recapitulatif')){
                parcours.VI_CommentairesParcours__c=comments;
            }
            update parcours;
        }
    }
    /*@Author: Eloi Dereeper
*@Description: reprendre le parours plus tard sans tache --> Ajout d'un commentaire sur le parcours 
*@CreatedDate: 15/12/2020
*@LastModified: 22/12/2020
*/
    @AuraEnabled
    public static void reprendrePlutardSansTache(VI_Parcours__c  parcours,String comments){
        parcours.VI_CommentairesReprendreParcours__c = comments;
        try{
            update parcours;
        }
        catch(Exception e){
            System.debug('L\'update du parcours a échoué');
            throw e;
        }
    }
    /*@Author: Eloi Dereeper
*@Description: reprendre le parours plus tard avec tache --> Ajout d'un commentaire sur le parcours + une tâche est crée
*@CreatedDate: 15/12/2020
*@LastModified: 22/12/2020
*/    
    @AuraEnabled
    public static void createTask(VI_Parcours__c  parcours, Date dateEcheance, String heureEcheance, String description, String comments, Boolean planTask){
        
        System.debug('EDE Debug; create Task for parcours : ' + parcours);
        System.debug('heureEcheance ' + heureEcheance);
        String currentUserId=Userinfo.getUserId();
        String currentParcoursContactLastName;
        String currentParcoursContactPhone;
        User currentUser=[SELECT Id, AccountId,account.name, Account.VI_TypeParcours__c, Account.VI_Groupe_Fonctionnel__c
                          FROM User  
                          WHERE Id =:currentUserId
                          LIMIT 1];
        String queueName='VI_'+currentUser.account.name;
        parcours.VI_CommentairesReprendreParcours__c = comments;
        system.debug('queueName '+queueName);
        if(planTask){
            
            // Task creation
            Datetime datetimeEcheance= Datetime.newInstance(dateEcheance.year(), dateEcheance.month(), dateEcheance.day(),
                                                            Integer.valueOf(heureEcheance.substringBefore(':')), Integer.valueOf(heureEcheance.substringAfter(':')), 0);
            
            system.debug('description '+description);
            system.debug('comments '+comments);
            parcours.VI_DescriptionTache__c = description;
            parcours.VI_DateEcheanceTache__c = dateEcheance;
            parcours.VI_HeureEcheanceTache__c = Time.newInstance( Integer.valueOf(heureEcheance.substringBefore(':')), Integer.valueOf(heureEcheance.substringAfter(':')), 0, 0);
            parcours.VI_PlanifierTache__c = true;
            parcours.VI_StatutParcours__c = 'Vente à compléter';

            Task tache = new Task();
            tache.WhatId = parcours.Id;
            tache.OwnerId =Userinfo.getUserId();
            tache.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('PurePlayerTask').getRecordTypeId();
            tache.ActivityDate = dateEcheance;
            tache.IsReminderSet=true;
            tache.ReminderDateTime=datetimeEcheance.addMinutes(-30);
            tache.Description=description;
            tache.Type='Appel';
            //tache.VI_DateEtHeureEcheance__c=datetimeEcheance;
            tache.Subject = 'Rappel parcours '+parcours.name;
            tache.VI_Site_prestataire__c = parcours.VI_TECH_SitePrestatairePartenaire__c;
            tache.VI_TypeDuSitePrestataire__c = parcours.VI_TECH_TypeDuSitePrestataire__c;
            system.debug('¤ VI_TECH_NomDuClient__c : ' + parcours.VI_TECH_NomDuClient__c);
            system.debug('¤ VI_TelephonePrincipal__c : ' + parcours.VI_TECH_TelephonePrincipal__c);
            if(parcours.VI_Contact__c!=null && (parcours.VI_TECH_NomDuClient__c==null || parcours.VI_TECH_TelephonePrincipal__c==null)){
                System.debug('dans if contact');
                System.debug('1');
                List<Contact> listCurrentParcoursContact = [SELECT Id, LastName,TechMobilePrincipale__c ,TechFixePrincipale__c
                          FROM Contact 
                          WHERE Id =:parcours.VI_Contact__c];
                          System.debug('2');
                          System.debug('Select');
                          System.debug(listCurrentParcoursContact);
                if(listCurrentParcoursContact!=null && listCurrentParcoursContact.size()>0){
                    if(listCurrentParcoursContact[0].LastName!=null){
                        currentParcoursContactLastName=listCurrentParcoursContact[0].LastName;
                    }
                    if(listCurrentParcoursContact[0].TechMobilePrincipale__c!=null){
                        currentParcoursContactPhone=listCurrentParcoursContact[0].TechMobilePrincipale__c;
                    }
                    else if (listCurrentParcoursContact[0].TechFixePrincipale__c!=null)
                    {
                        currentParcoursContactPhone=listCurrentParcoursContact[0].TechFixePrincipale__c;
                    }
                }
            }
            System.debug('3');
            System.debug('VI_TECH_NomDuClient__c : ' + parcours.VI_TECH_NomDuClient__c);
            System.debug('currentParcoursContactLastName : ' + currentParcoursContactLastName);
            if(parcours.VI_TECH_NomDuClient__c!=null){
                tache.VI_NomClient__c=parcours.VI_TECH_NomDuClient__c;
            }
            else{
                tache.VI_NomClient__c=currentParcoursContactLastName;
            }
            System.debug('5');
            if(parcours.VI_TECH_TelephonePrincipal__c!=null){
                tache.VI_TelephonePrincipal__c=parcours.VI_TECH_TelephonePrincipal__c;
            }
            else{
                tache.VI_TelephonePrincipal__c=currentParcoursContactPhone;
            }
            System.debug('après le if contact');
            tache.VI_DateDeCreationDuParcours__c = parcours.CreatedDate;
            tache.VI_StatutDuCase__c = parcours.VI_StatutCasePartnerCommunity__c;
            tache.VI_StatutDuParcours__c = parcours.VI_StatutParcours__c;
            tache.VI_WhatName__c=parcours.name;
            if (comments.length() > 254) {
                tache.VI_ApercuDuCommentaire__c = comments.substring(0, 254);
            }
            else {
                tache.VI_ApercuDuCommentaire__c = comments;
            }
            // try{
            insert tache;
            //   }
            //   catch(Exception e){
            //       System.debug('La création de la tâche a échoué');
            //       throw e;
            //   }
        }
        try{
            update parcours;
            system.debug('¤ parcours updaté');
        }
        catch(Exception e){
            System.debug('L\'update du parcours a échoué');
            throw e;
        }
    }
    
    /*@Author: Eloi Dereeper
*@Description: Annulé le parcours --> saisir un motif, commentaire et changement de statut
*@CreatedDate: 15/12/2020
*@LastModified: 22/12/2020
*/     
    
    @AuraEnabled
    public static void annulerParcours(VI_Parcours__c  parcours, String motif, Boolean regie, Boolean tempo, String commentaire){
        
        parcours.VI_MotifAnnulationParcours__c = motif;
        parcours.VI_StatutParcours__c = 'Annulé';
        parcours.VI_CommentairesAnnulerParcours__c = commentaire;
        system.debug('parcours.VI_Case__c'+ parcours.VI_Case__c);
        /* TODO : 
* Implémenter le traitement de Régie/tempo
* Voir le délai de 1h 2 h avant annulation défintive
*/
        
        try{
            update parcours;
            case caseToUpdate = new Case(Id = parcours.VI_Case__c, Status = 'Annulé');
            update caseToUpdate;
        }
        catch (Exception e){
            System.debug('L\'annulation du parcours a échoué');
            throw e;
        }
    }
}