force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutMandat__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutMandat__c</fullName>
    <formula>TEXT(VI_Case__r.VI_StatutMandat__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut mandat</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VI_SM039_SignatureMandatListCase_Test.cls
@isTest
public class VI_SM039_SignatureMandatListCase_Test {

   	@isTest
    static void signedCaseTest() {
        // create Account
        Account Acc = SM_TestDataFactory.createAccount('Harmonica_Account');
        Insert acc;
        
        // Create Case
        Id CaseRTId = Case.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Acquisition_Harmonica').getRecordTypeId();
        Case caseTest = SM_TestDataFactory.createCase('TEST', Acc.Id);
        caseTest.recordTypeId=CaseRTId;
        caseTest.Origin = 'Partner Community';
        caseTest.VI_StatutMandat__c = 'Delivered';
        insert caseTest;   
        
         VI_Parcours__c parcours=VI_TestDataFactory.createParcours('CHF', caseTest.id, 'PURE PLAYERS');
        insert parcours;
        
        caseTest.VI_StatutMandat__c = 'Signed';
        update caseTest;   
    }
    
}