force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Contact__c.field-meta.xml
<CustomField>
    <fullName>VI_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contient le contact utilisé dans ce parcours</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parcours</relationshipLabel>
    <relationshipName>Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Email_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Email_CPV__c</fullName>
    <description>Champ email supplémentaire en cas de volonté du client de donner une adresse email différente pour l&apos;envoi des CPV</description>
    <label>Email CPV</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutEnveloppe__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutEnveloppe__c</fullName>
    <formula>TEXT(VI_Case__r.VI_StatutEnveloppe__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut de l&apos;enveloppe</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_StatutMandat__c.field-meta.xml
<CustomField>
    <fullName>VI_StatutMandat__c</fullName>
    <formula>TEXT(VI_Case__r.VI_StatutMandat__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut mandat</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VI_SM044_EmailDeConfirmation_Test.cls
/*
*@Author: Clement Bouquin
*@Description: classe de test de VI_SM044_EmailDeConfirmation
*@CreatedDate: 13/09/2021
*@LastModified: 13/09/2021
*/

@isTest
public class VI_SM044_EmailDeConfirmation_Test {

    @isTest
    static void EmailDeConfirmationTest() {
        // create Account
        Account Acc = SM_TestDataFactory.createAccount('Harmonica_Account');
        Insert acc;
        
        // create Contact
        Contact c = new Contact(LastName='Bouquin', FirstName='Clement', Salutation='Mr', Id_Tiers__c=100166,
                                No_Voie__c='127', MailingStreet='Avenue Simon Bolivar', MailingPostalCode='75019', MailingCity='Paris', Complement_adresse__c='');
        Insert c;
        
        // Create Case
        Id CaseRTId = Case.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Acquisition_Harmonica').getRecordTypeId();
        Case caseTest = SM_TestDataFactory.createCase('TEST', Acc.Id);
        caseTest.recordTypeId=CaseRTId;
        caseTest.VI_StatutMandat__c = 'Sent';
        caseTest.VI_StatutEnveloppe__c = 'Sent';
        insert caseTest;   
        
        VI_Parcours__c parcours=VI_testDataFactory.createParcours('CHF', caseTest.id, 'PURE PLAYERS');
        parcours.VI_Contact__c = c.id;
        parcours.VI_Email_CPV__c = 'clement.bouquin@ei-technologies.com';
        insert parcours;
        
        caseTest.VI_StatutMandat__c = 'Signed';
        caseTest.VI_StatutEnveloppe__c = 'Signed';
        update caseTest; 
    }
    
}