force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/HP_Porte_Feuille_Contrat__c.object-meta.xml
<CustomObject>
    <label>Portefeuille Contrat Happe</label>
    <nameField>
        <label>Nom du Portefeuille Contrat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portefeuilles Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portefeuilles Contrats Happe</relationshipLabel>
    <relationshipName>HP_Porte_Feuilles_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/Xdata_Id__c.field-meta.xml
<CustomField>
    <fullName>Xdata_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HP_EM024_PorteFeuilleContrat.cls
/**
 * @File Name          : HP_EM024_PorteFeuilleContrat.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : Badr Eddine Belkarchi
 * @Last Modified On   : 02-14-2022
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    10/02/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class HP_EM024_PorteFeuilleContrat {
    public static String createPorteFeuilleContratXdata(HP_ContractPortfolio contractPortfolio) {
        HttpResponse response = HP_UTIL_HTTPUtils.calloutPost(HP_Constantes.XDATA_PORTEFEUILLES_CONTRATS, System.JSON.serialize(new HP_APIHourContractPortfolio(contractPortfolio)));
        String location;
        if(response.getHeaderKeys().contains(HP_HttpUtils.HTTP_LOCATION)){
            location = response.getHeader(HP_HttpUtils.HTTP_LOCATION); 
        }else if(response.getHeaderKeys().contains(HP_HttpUtils.HTTP_LOCATION_APIGEE)){
            location = response.getHeader(HP_HttpUtils.HTTP_LOCATION_APIGEE);
        }
        final String portfolioContractId = location.substringAfterLast(HP_HttpUtils.URI_SEP);
		return portfolioContractId;
    }

    public static void updatePorteFeuilleContratXdata(String contractPortfolioXdataId, HP_ContractPortfolio contractPortfolio) {
        Set<String> filterString = new Set<String>{'idPersonne'};
		String fstring = HP_ParseUtils.serializeStringSet(contractPortfolio,filterString);
        HttpResponse response = HP_UTIL_HTTPUtils.calloutPut(HP_Constantes.XDATA_PORTEFEUILLES_CONTRATS, fstring,'/' + contractPortfolioXdataId);

    }

    public static HP_Porte_Feuille_Contrat__c loadPorteFeuilleContrat(String selfcareId) {
        return [select Id, HP_Contact__c, HP_Souscription_Digital_Id__c, Xdata_Id__c from HP_Porte_Feuille_Contrat__c where HP_Souscription_Digital_Id__c = :selfcareId];
    }

    public static HP_Porte_Feuille_Contrat__c getPortefeuilleContratByXdataId(String porteFeuilleContratXdataId) {
        return [select Id, HP_Contact__c, HP_Souscription_Digital_Id__c, Xdata_Id__c from HP_Porte_Feuille_Contrat__c where Xdata_Id__c = :porteFeuilleContratXdataId];
    }
}