force-app/main/default/objects/HP_NoteDeSatisfaction__c/HP_NoteDeSatisfaction__c.object-meta.xml
<CustomObject>
    <label>HP Note de satisfaction</label>
    <nameField>
        <displayFormat>NDS-{00000000}</displayFormat>
        <label>HP Note de satisfaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HP Notes de satisfaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_Case__c.field-meta.xml
<CustomField>
    <fullName>HP_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>HP Notes de satisfaction</relationshipLabel>
    <relationshipName>HP_Notes_de_satisfaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>HP Notes de satisfaction</relationshipLabel>
    <relationshipName>HP_Notes_de_satisfaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_Date_creation__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_creation__c</fullName>
    <label>Date de création</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_ID_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_ID_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipLabel>HP Notes de satisfaction</relationshipLabel>
    <relationshipName>HP_Notes_de_satisfaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_ID_Souscription_Digital__c.field-meta.xml
<CustomField>
    <fullName>HP_ID_Souscription_Digital__c</fullName>
    <externalId>true</externalId>
    <label>ID Souscription Digital</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_IdAvisVerifie__c.field-meta.xml
<CustomField>
    <fullName>HP_IdAvisVerifie__c</fullName>
    <label>Id Avis Vérifié</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_Nom__c.field-meta.xml
<CustomField>
    <fullName>HP_Nom__c</fullName>
    <label>Nom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_NPS__c.field-meta.xml
<CustomField>
    <fullName>HP_NPS__c</fullName>
    <label>NPS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_Prenom__c.field-meta.xml
<CustomField>
    <fullName>HP_Prenom__c</fullName>
    <label>Prénom</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_ReponseApportee__c.field-meta.xml
<CustomField>
    <fullName>HP_ReponseApportee__c</fullName>
    <label>Réponse apportée</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_satisfaction_canal__c.field-meta.xml
<CustomField>
    <fullName>HP_satisfaction_canal__c</fullName>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Téléphone</fullName>
            </value>
            <value>
                <fullName>Souscription</fullName>
            </value>
            <value>
                <fullName>MKTC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_satisfaction_date__c.field-meta.xml
<CustomField>
    <fullName>HP_satisfaction_date__c</fullName>
    <label>Date d’envoi de l&apos;enquête</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_satisfaction_OeD__c.field-meta.xml
<CustomField>
    <fullName>HP_satisfaction_OeD__c</fullName>
    <label>Once &amp; done</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_satisfaction_score__c.field-meta.xml
<CustomField>
    <fullName>HP_satisfaction_score__c</fullName>
    <label>Note de satisfaction /5</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_NoteDeSatisfaction__c/fields/HP_satisfaction_verbatim__c.field-meta.xml
<CustomField>
    <fullName>HP_satisfaction_verbatim__c</fullName>
    <label>Verbatim client / Commentaire</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HP_EM041_NoteSatisfaction.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 



 * @last modified on  : 10-18-2021



 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   10-28-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class HP_EM041_NoteSatisfaction {
    public static Contact loadContactWithNoteSatisfaction(String idContact) {
        return [select Id,HP_Chat_Score__c,HP_Dernier_score__c,HP_Email_Score__c,
        HP_global_moyenne_score__c,HP_Telephone_Score__c,
        HP_Souscription_CSAT_Score__c,HP_Souscription_NPS_Score__c,
        HP_Resil_CSAT_Note__c, HP_Resil_NPS_Note__c, HP_VDS_CSAT_Note__c, HP_VDS_NPS_Note__c,
        (select id, HP_Case__c,HP_Case__r.CaseNumber,CreatedDate,HP_satisfaction_verbatim__c,
        HP_satisfaction_score__c,HP_satisfaction_canal__c,HP_satisfaction_OeD__c, Name
         from HP_Notes_de_satisfaction__r order by createdDate desc) 
        from Contact where Id = :idContact];
    } 

    public static HP_NoteDeSatisfaction__c noteSatisfactionFromAvis(String rate,String nps, String idReview,String orderRef,Id souscriptionId,Id contactId,String reviewDdate, Datetime dt, String review, String lastname, String firstname, String moderation ){
       
        HP_NoteDeSatisfaction__c noteSatisfaction = new HP_NoteDeSatisfaction__c();


        noteSatisfaction.HP_satisfaction_score__c = (rate != null ? Decimal.valueOf(rate)  : null);
        noteSatisfaction.HP_NPS__c =  (nps != null ? Decimal.valueOf(nps) : null);
        noteSatisfaction.HP_IdAvisVerifie__c =  idReview;
        noteSatisfaction.HP_ID_Souscription_Digital__c =  orderRef	;
        noteSatisfaction.HP_ID_Souscription__c = souscriptionId;
        noteSatisfaction.HP_Contact__c = contactId;
        noteSatisfaction.HP_Date_creation__c = Datetime.valueOf(reviewDdate);
        noteSatisfaction.HP_satisfaction_date__c = dt.date();
        noteSatisfaction.HP_satisfaction_verbatim__c = review;
        noteSatisfaction.HP_Nom__c =  lastname;
        noteSatisfaction.HP_Prenom__c = firstname;
        noteSatisfaction.HP_ReponseApportee__c = moderation;
        noteSatisfaction.HP_satisfaction_canal__c = 'Souscription';

        return noteSatisfaction;
    }





    public static  List<HP_NoteDeSatisfaction__c>  getNoteSatisfaction(set<String> ids, set<String> idsDigital){
        return [ select id, HP_IdAvisVerifie__c, HP_ID_Souscription_Digital__c, HP_ID_Souscription__c from  HP_NoteDeSatisfaction__c where HP_IdAvisVerifie__c  in : ids OR HP_ID_Souscription_Digital__c  in :idsDigital];

    }





}