force-app/main/default/objects/Parcours_Mapping__c/Parcours_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Utilisé par vente indirecte pour faire le mapping avec les valeurs octopus pour l&apos;estimation de la consommation</description>
    <label>Parcours Mapping</label>
</CustomObject>

force-app/main/default/objects/Parcours_Mapping__c/fields/API_Value__c.field-meta.xml
<CustomField>
    <fullName>API_Value__c</fullName>
    <label>API Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parcours_Mapping__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parcours_Mapping__c/fields/Local_Value__c.field-meta.xml
<CustomField>
    <fullName>Local_Value__c</fullName>
    <label>Local Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_AnneeConstructionLogementSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_AnneeConstructionLogementSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; l&apos;année de construction du logement</description>
    <label>Année de construction du logement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Avant 1975</fullName>
            </value>
            <value>
                <fullName>Entre 1975 et 1988</fullName>
            </value>
            <value>
                <fullName>Entre 1989 et 1999</fullName>
            </value>
            <value>
                <fullName>Entre 2000 et 2005</fullName>
            </value>
            <value>
                <fullName>Après 2005</fullName>
            </value>
            <value>
                <fullName>Je ne sais pas</fullName>
                <default>true</default>
                <label>Je ne sais pas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_CodePostalRechercheLocal__c.field-meta.xml
<CustomField>
    <fullName>VI_CodePostalRechercheLocal__c</fullName>
    <description>Champ de recherche local par adresse</description>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DispositifChauffageSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_DispositifChauffageSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; le dispositif de chauffage utilisé (Individuel, Collectif)</description>
    <label>Dispositif chauffage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individuel</fullName>
            </value>
            <value>
                <fullName>Collectif</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DispositifEauChaudeSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_DispositifEauChaudeSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; le dispositif de l&apos;eau chaude (Individuel, Collectif)</description>
    <label>Dispositif Eau chaude</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collectif</fullName>
            </value>
            <value>
                <fullName>Individuel</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Je ne sais pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_EnergieChauffageSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_EnergieChauffageSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; l&apos;énergie utilisée pour le chauffage</description>
    <label>Energie chauffage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gaz naturel</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
            <value>
                <fullName>Fioul</fullName>
            </value>
            <value>
                <fullName>Réseau de chaleur</fullName>
            </value>
            <value>
                <fullName>Propane GPL</fullName>
            </value>
            <value>
                <fullName>Butane</fullName>
            </value>
            <value>
                <fullName>Bois</fullName>
            </value>
            <value>
                <fullName>Charbon</fullName>
            </value>
            <value>
                <fullName>Solaire</fullName>
            </value>
            <value>
                <fullName>Autre énergie renouv</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Je ne sais pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_EnergieCuissonSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_EnergieCuissonSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; l&apos;énergie utilisée pour la cuisson</description>
    <label>Energie Cuisson</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gaz naturel</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
            <value>
                <fullName>Fioul</fullName>
            </value>
            <value>
                <fullName>Butane</fullName>
            </value>
            <value>
                <fullName>Bois</fullName>
            </value>
            <value>
                <fullName>Charbon</fullName>
            </value>
            <value>
                <fullName>Mixte</fullName>
            </value>
            <value>
                <fullName>Je ne sais pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_EnergieEauChaudeSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_EnergieEauChaudeSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; l&apos;énergie utilisée pour l&apos;eau chaude</description>
    <label>Energie Eau chaude</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gaz naturel</fullName>
            </value>
            <value>
                <fullName>Electricité</fullName>
            </value>
            <value>
                <fullName>Fioul</fullName>
            </value>
            <value>
                <fullName>Réseau de chaleur</fullName>
            </value>
            <value>
                <fullName>Propane GPL</fullName>
            </value>
            <value>
                <fullName>Butane</fullName>
            </value>
            <value>
                <fullName>Bois</fullName>
            </value>
            <value>
                <fullName>Charbon</fullName>
            </value>
            <value>
                <fullName>Solaire</fullName>
            </value>
            <value>
                <fullName>Autre énergie renouv</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Je ne sais pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Estimation_conso_elec_HC__c.field-meta.xml
<CustomField>
    <fullName>VI_Estimation_conso_elec_HC__c</fullName>
    <description>Estimation Elec HC remontée par le flux Octopus</description>
    <label>Estimation consommation elec HC</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Estimation_conso_elec_HP__c.field-meta.xml
<CustomField>
    <fullName>VI_Estimation_conso_elec_HP__c</fullName>
    <description>Estimation Elec HP ou ST remontée par le flux Octopus</description>
    <label>Estimation consommation elec HP</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Estimation_conso_gaz__c.field-meta.xml
<CustomField>
    <fullName>VI_Estimation_conso_gaz__c</fullName>
    <description>Estimation gaz remontée par le flux Octopus</description>
    <label>Estimation consommation gaz</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_NombreOccupantLogementSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_NombreOccupantLogementSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; le nombre d&apos;habitant(s) au sein du logement entre 1 et 20</description>
    <label>Nombre d’occupant dans le logement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_SaisieConsommationElec_HP_HC__c.field-meta.xml
<CustomField>
    <fullName>VI_SaisieConsommationElec_HP_HC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Choix saisie de la consommation annuelle Elec</description>
    <label>HP/HC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_SurfaceLogementSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_SurfaceLogementSaisieConso__c</fullName>
    <description>Champ de saisie de la surface du logement en m2</description>
    <label>Surface du logement (m2)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TypeLogementSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_TypeLogementSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; s&apos;il s&apos;agit d&apos;un logement Collection ou individuel</description>
    <label>Type de logement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individuel</fullName>
            </value>
            <value>
                <fullName>Collectif</fullName>
            </value>
            <value>
                <fullName>Je ne sais pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TypeResidenceSaisieConso__c.field-meta.xml
<CustomField>
    <fullName>VI_TypeResidenceSaisieConso__c</fullName>
    <description>Le PP choisi, en fonction du prospect au téléphone ; s&apos;il s&apos;agit d&apos;une résidence principale ou secondaire</description>
    <label>Type de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Secondaire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI_parcoursConso_Test.cls
/*
* @Author: Paul Ghoussoub
*@Description: Classe de test de VI_parcoursConso_Controller
*@CreatedDate: 28/1/2021
*/
@isTest
public class VI_parcoursConso_Test {
    @testSetup
    static void testSetup(){
        List<Group> ownerQueue = [Select Id,DeveloperName from Group where Type = 'Queue'];
        
        system.debug('query queue '+ownerQueue);
        Id profileId = [Select Id From Profile Where Name ='VI_PurePlayer'].Id;
        Account acc = VI_TestUtility.createAccount('Marketshot');
        insert acc;
        Contact con = VI_TestUtility.createContact('test','Contact','test@gmail.com',acc.Id);
        insert con;
        User u = VI_TestUtility.createCommunityUser(con.Id,profileId,'Test','Test');
        u.isActive=true;
        insert u;
    }
    @isTest
    static void getEstimationGazTest(){
        User u =[Select id from user where firstname='Test' and lastname='Test' and isActive=true limit 1];
        System.runAs(u){
            Test.startTest();
            System.assertEquals(VI_parcoursConso_Controller.getEstimationGaz('1989_1999','75015','010','010',3,11,'030','030','010','010','010'),1000);
            Test.stopTest();
        }
    }
    
    @isTest
    static void getEstimationElecTest(){
        User u =[Select id from user where firstname='Test' and lastname='Test' and isActive=true limit 1];
        System.runAs(u){
            Test.startTest();
            System.assertEquals(VI_parcoursConso_Controller.getEstimationElec('1989_1999','75015','010','030',3,11,'010','030','010','010','010', true, true, true, true),4415);
            Test.stopTest();
        }
    }
    
    @isTest
    static void getEstimationElecHPHCTest(){
        User u =[Select id from user where firstname='Test' and lastname='Test' and isActive=true limit 1];
        System.runAs(u){
            Test.startTest();
            VI_SM017_PreconiserRepartitionHPHCConso.EstimationHPHC responsTest = VI_parcoursConso_Controller.getEstimationElecHPHC('010','030','010','030');
            System.assertNotEquals(responsTest.cleRepartitionHC,null);
            System.assertNotEquals(responsTest.cleRepartitionHP,null);
            Test.stopTest();
        }
    }
    
    @isTest
    static void getEstimationElecHPHCWETest(){
        User u =[Select id from user where firstname='Test' and lastname='Test' and isActive=true limit 1];
        System.runAs(u){
            Test.startTest();
            VI_SM018_Preconiser3cadransConso.Estimation3Cadrans responsTest = VI_parcoursConso_Controller.getEstimationElecHPHCWE('010','030','010','030');
            
            System.assertNotEquals(responsTest.cleHC,null);
            System.assertNotEquals(responsTest.cleHP,null);
            System.assertNotEquals(responsTest.cleWE,null);
            Test.stopTest();
        }
    }
    
    @isTest
    static void getCustomSettingsTest(){
        Parcours_Mapping__c mapTest = new Parcours_Mapping__c();
        mapTest.Name = 'TESTNAME';
        mapTest.Field_Name__c = 'testName';
        mapTest.Local_Value__c = '10';
        mapTest.API_Value__c = '50';
        
        insert mapTest;
        
        Map<String, String> keyValue = new Map<String, String>();
        keyValue.put('50', '10');
        Map<String, Map<String, String>> parcoursMappings = new Map<String, Map<String, String>>();
        parcoursMappings.put('testName', keyValue);
        User u =[Select id from user where firstname='Test' and lastname='Test' and isActive=true limit 1];
        System.runAs(u){
            Test.startTest();
            System.assertEquals(VI_parcoursConso_Controller.getCustomSettings(), parcoursMappings);
            Test.stopTest();
        }
    }
    
    @isTest
    static void getEstimationLWCTest(){
        List<Parcours_Mapping__c>  listMapInsert = new list<Parcours_Mapping__c>();
        //INSERT ALL MAPPING
        Parcours_Mapping__c mapTest = new Parcours_Mapping__c(Name = 'TESTNAME',
                                                              Field_Name__c = 'VI_AnneeConstructionLogementSaisieConso__c',
                                                              Local_Value__c = '1989_1999',
                                                              API_Value__c = 'Entre 1975 et 1988');
        
        listMapInsert.add(mapTest);
        
        Parcours_Mapping__c mapTest2 = new Parcours_Mapping__c(Name = 'TESTNAME2',
                                                               Field_Name__c = 'VI_EnergieChauffageSaisieConso__c',
                                                               Local_Value__c = '030',
                                                               API_Value__c = 'Electricité');
        
        listMapInsert.add(mapTest2);
        Parcours_Mapping__c mapTest3 = new Parcours_Mapping__c(Name = 'TESTNAME3',
                                                               Field_Name__c = 'VI_DispositifEauChaudeSaisieConso__c',
                                                               Local_Value__c = '010',
                                                               API_Value__c = 'Collectif');
        
        listMapInsert.add(mapTest3);
        Parcours_Mapping__c mapTest4 = new Parcours_Mapping__c(Name = 'TESTNAME4',
                                                               Field_Name__c = 'VI_DispositifChauffageSaisieConso__c',
                                                               Local_Value__c = '030',
                                                               API_Value__c = 'Individuel');
        
        listMapInsert.add(mapTest4);
        Parcours_Mapping__c mapTest5 = new Parcours_Mapping__c(Name = 'TESTNAME5',
                                                               Field_Name__c = 'VI_TypeLogementSaisieConso__c',
                                                               Local_Value__c = '010',
                                                               API_Value__c = 'Individuel');
        
        listMapInsert.add(mapTest5);
        Parcours_Mapping__c mapTest6 = new Parcours_Mapping__c(Name = 'TESTNAME6',
                                                               Field_Name__c = 'VI_TypeResidenceSaisieConso__c',
                                                               Local_Value__c = '010',
                                                               API_Value__c = 'Principale');
        
        listMapInsert.add(mapTest6);
        Parcours_Mapping__c mapTest7 = new Parcours_Mapping__c(Name = 'TESTNAME7',
                                                               Field_Name__c = 'VI_EnergieCuissonSaisieConso__c',
                                                               Local_Value__c = '010',
                                                               API_Value__c = 'Fioul');
        
        listMapInsert.add(mapTest7);
        Parcours_Mapping__c mapTest8 = new Parcours_Mapping__c(Name = 'TESTNAME8',
                                                               Field_Name__c = 'VI_NombreOccupantLogementSaisieConso__c',
                                                               Local_Value__c = '3',
                                                               API_Value__c = '3');
        
        listMapInsert.add(mapTest8);
        Parcours_Mapping__c mapTest9 = new Parcours_Mapping__c(Name = 'TESTNAME9',
                                                               Field_Name__c = 'VI_SurfaceLogementSaisieConso__c',
                                                               Local_Value__c = '20',
                                                               API_Value__c = '20');
        
        listMapInsert.add(mapTest9);
        
        Parcours_Mapping__c mapTest10 = new Parcours_Mapping__c(Name = 'TESTNAME10',
                                                               Field_Name__c = 'VI_EnergieEauChaudeSaisieConso__c',
                                                               Local_Value__c = '020',
                                                               API_Value__c = 'Electricité');
        
        listMapInsert.add(mapTest10);
        insert listMapInsert;
        
        VI_Parcours__c parcrousTest2 = VI_TestDataFactory.createParcours('CHF', null, 'PURE PLAYERS');
        parcrousTest2.VI_AnneeConstructionLogementSaisieConso__c = 'Entre 1975 et 1988';
        parcrousTest2.VI_EnergieChauffageSaisieConso__c = 'Electricité';
        parcrousTest2.VI_EnergieEauChaudeSaisieConso__c = 'Electricité';
        parcrousTest2.VI_DispositifEauChaudeSaisieConso__c = 'Collectif';
        parcrousTest2.VI_DispositifChauffageSaisieConso__c = 'Individuel';
        parcrousTest2.VI_TypeLogementSaisieConso__c = 'Individuel';
        parcrousTest2.VI_TypeResidenceSaisieConso__c = 'Principale';
        parcrousTest2.VI_EnergieCuissonSaisieConso__c = 'Fioul';
        parcrousTest2.VI_NombreOccupantLogementSaisieConso__c = '3';
        parcrousTest2.VI_SurfaceLogementSaisieConso__c = 20;
        parcrousTest2.VI_SaisieConsommationElec_HP_HC__c = true;
        parcrousTest2.VI_CodePostalRechercheLocal__c = '75015';
        
        insert parcrousTest2;   
        User u =[Select id from user where firstname='Test' and lastname='Test' and isActive=true limit 1];
        System.runAs(u){
            TEST.startTest();
            
            VI_parcoursConso_Controller.ConsoResponse responsTest = VI_parcoursConso_Controller.getEstimationLWC(parcrousTest2);
            
            System.assertNotEquals(responsTest.parcours.VI_Estimation_conso_gaz__c,null);
            System.assertNotEquals(responsTest.parcours.VI_Estimation_conso_elec_HP__c,null);
            System.assertNotEquals(responsTest.parcours.VI_Estimation_conso_elec_HC__c,null);
            
            TEST.StopTest();
        }
    }   
}