force-app/main/default/objects/InfoCouleur__c/InfoCouleur__c.object-meta.xml
<CustomObject>
    <label>Info Couleur</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Info Couleur</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InfoCouleur__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(Date_de_validit__c &gt;=  TODAY()    , true, false)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/Archive__c.field-meta.xml
<CustomField>
    <fullName>Archive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Archive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/Couleur__c.field-meta.xml
<CustomField>
    <fullName>Couleur__c</fullName>
    <description>représente le type d&apos;Info Couleur</description>
    <label>Couleur</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bleue</fullName>
            </value>
            <value>
                <fullName>Rouge</fullName>
            </value>
            <value>
                <fullName>Violette</fullName>
            </value>
            <value>
                <fullName>Verte</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Bleu</fullName>
                <isActive>false</isActive>
                <label>Bleu</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/Date_de_validit__c.field-meta.xml
<CustomField>
    <fullName>Date_de_validit__c</fullName>
    <description>Permet de prédéfinir une période d&apos;affichage pour les Info Couleur</description>
    <label>Date de validité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>est le contenu de l&apos;Info Couleur</description>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/imgColorSource__c.field-meta.xml
<CustomField>
    <fullName>imgColorSource__c</fullName>
    <formula>IF( ISPICKVAL(Couleur__c, &apos;Rouge&apos;) , $Label.SM_URL &amp; &apos;resource/SM_ImageR&apos;, 
IF( ISPICKVAL(Couleur__c, &apos;Verte&apos;)  , $Label.SM_URL &amp; &apos;resource/SM_ImageVert&apos;, 
IF( ISPICKVAL(Couleur__c, &apos;Violette&apos;)  , $Label.SM_URL &amp; &apos;resource/SM_ImageV&apos;, 
IF( ISPICKVAL(Couleur__c, &apos;Bleue&apos;) , $Label.SM_URL &amp; &apos;resource/SM_ImageB&apos;, 
IF( ISPICKVAL(Couleur__c, &apos;Orange&apos;) , $Label.SM_URL &amp; &apos;resource/SM_ImageO&apos;, 

$Label.SM_URL

)
)
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>imgColorSource</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/Info_Url__c.field-meta.xml
<CustomField>
    <fullName>Info_Url__c</fullName>
    <formula>$Label.SM_URL &amp; Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Info Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/Nombre_de_vue__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_vue__c</fullName>
    <description>Permet de comptabiliser le nombre de vues</description>
    <label>Nombre de vues</label>
    <summaryForeignKey>Nombre_de_vue__c.Info_Couleur__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Nombre_de_vue__c/Nombre_de_vue__c.object-meta.xml
<CustomObject>
    <label>Nombre de vues</label>
    <nameField>
        <displayFormat>VUE-{0000}</displayFormat>
        <label>Nombre de vue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nombre de vues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Nombre_de_vue__c/fields/Date_de_vue__c.field-meta.xml
<CustomField>
    <fullName>Date_de_vue__c</fullName>
    <label>Date de vue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Nombre_de_vue__c/fields/Info_Couleur__c.field-meta.xml
<CustomField>
    <fullName>Info_Couleur__c</fullName>
    <label>Info Couleur</label>
    <referenceTo>InfoCouleur__c</referenceTo>
    <relationshipName>TEST_nombre_de_vue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Nombre_de_vue__c/fields/Nombre_de_vue__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_vue__c</fullName>
    <label>Nombre de vues</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Nombre_de_vue__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TEST_nombre_de_vue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InfoCouleurController.cls
/**
 * @File Name          : InfoCouleurController.cls
 * @Description        : Controller de deux LWC (sM_LWC_POC_InfoCouleurVue ET sM_LWC_NbreInfoCouleur)
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Ticket             : FT2-277, FT2-289, FT2-291/ Sprint 10
 * Ver       Date            Author      		    Modification
 * 1.0    05/03/2020   Jihad AZAMI HASSANI     Initial Version
**/
public class InfoCouleurController {

    /**
    * @description: Renvoi un liste des InfoCouleur Actif
    * @return List<InfoCouleur__c> 
    **/
    @AuraEnabled (cacheable=true)
    public static List<InfoCouleur__c> getInfoCouleur(){
        return [Select Id,Name ,Description__c, Couleur__c, Info_Url__c, imgColorSource__c  from InfoCouleur__c where Active__c=true AND Archive__c=false];
    }

    /**
    * @description: Renvoi un liste des InfoCouleur Non Lues
    * @return List<InfoCouleur__c> 
    **/
    @AuraEnabled (cacheable=true)
    public static List<InfoCouleur__c> getNbreInfoCouleurNonLues(){
      	Integer nbreInfocouleur= 0;
        String userId = UserInfo.getUserId();
       List<InfoCouleur__c> infoCouleurNonVue = [select Id,Name ,Description__c, Couleur__c, Info_Url__c, imgColorSource__c, Active__c, Date_de_validit__c, CreatedDate, Nombre_de_vue__c  from InfoCouleur__c  where  Archive__c=false AND Id not in (SELECT Info_Couleur__c FROM Nombre_de_vue__c where User__c =: userId)];
       system.debug('***getNbreInfoCouleurNonLues:'+infoCouleurNonVue);
       
        return infoCouleurNonVue;

    }

    /**
    * @description: Test si la liste des infocrouleur est vide, pour ne pas afficher le carousel
    * @return boolean
    **/
    @AuraEnabled (cacheable=true)
    public static Boolean getCarousel(){
        Boolean ifCarousel=false;
        List<InfoCouleur__c> infoCouleurActives =  [Select Id,Name ,Description__c, Couleur__c, Info_Url__c, imgColorSource__c  from InfoCouleur__c where Active__c=true AND Archive__c=false];
        system.debug('infoCouleurActives :'+infoCouleurActives);
        if(infoCouleurActives!=null && !infoCouleurActives.isEmpty()) {
            ifCarousel = true;
            }else{
                ifCarousel= false;
            }
            system.debug('ifCarousel :'+ifCarousel);
        return ifCarousel;
    }

    /**
    * @description: 3 Methodes qui renvoient le nombre d'infoCouleur non vu par un utilisateur 
    *              suivant la couleur de l'info (Rouge/bleu/violet) 
    * @return Integer 
    **/
    @AuraEnabled (cacheable=true)
    public static Integer getNbreInfoCouleurBleu(){
      	Integer nbreInfocouleur= 0;
        String userId = UserInfo.getUserId();
       List<InfoCouleur__c> infoCouleurNonVue = [select Id, Name  from InfoCouleur__c where Couleur__c = 'Bleue' AND Archive__c=false AND Id not in (SELECT Info_Couleur__c FROM Nombre_de_vue__c where User__c =: userId)];
       system.debug('infoCouleurNonVue:'+infoCouleurNonVue);
       if (infoCouleurNonVue == null || infoCouleurNonVue.isEmpty())
            nbreInfocouleur = 0;
        else
            nbreInfocouleur = infoCouleurNonVue.size();
            system.debug('nbreInfocouleur:'+nbreInfocouleur);
        return nbreInfocouleur;

    }

    @AuraEnabled (cacheable=true)
    public static Integer getNbreInfoCouleurRouge(){
      	Integer nbreInfocouleur= 0;
        String userId = UserInfo.getUserId();
       List<InfoCouleur__c> infoCouleurNonVue = [select Id, Name  from InfoCouleur__c where Couleur__c = 'Rouge' AND Archive__c=false AND Id not in (SELECT Info_Couleur__c FROM Nombre_de_vue__c where User__c =: userId)];
       system.debug('infoCouleurNonVue:'+infoCouleurNonVue);
       if (infoCouleurNonVue == null)
            nbreInfocouleur = 0;
        else
            nbreInfocouleur = infoCouleurNonVue.size();
            system.debug('nbreInfocouleur:'+nbreInfocouleur);
        return nbreInfocouleur;

    }

    @AuraEnabled (cacheable=true)
    public static Integer getNbreInfoCouleurViolette(){
      	Integer nbreInfocouleur= 0;
        String userId = UserInfo.getUserId();
       List<InfoCouleur__c> infoCouleurNonVue = [select Id, Name  from InfoCouleur__c where Couleur__c = 'Violette' AND Archive__c=false AND Id not in (SELECT Info_Couleur__c FROM Nombre_de_vue__c where User__c =: userId)];
       system.debug('infoCouleurNonVue:'+infoCouleurNonVue);
       if (infoCouleurNonVue == null)
            nbreInfocouleur = 0;
        else
            nbreInfocouleur = infoCouleurNonVue.size();
            system.debug('nbreInfocouleur:'+nbreInfocouleur);
        return nbreInfocouleur;

    }

    /**
    * @description:  Au clic sur la carrousel la méthode "createViewBy" de la classe "InfoCouleurController" récupère l'id de l’objet InfoCouleur
                    -> Ajoute un enregistrement de l’objet "Nombre de vues" dans l'onglet associé
                    -> Sinon Implémenter le nombre de vue déjà existant 
    **/
    @AuraEnabled
    public static Nombre_de_vue__c createViewBy(String idInfoCouleur){    
       	String userId = UserInfo.getUserId();
        system.debug('userId:'+userId);
        system.debug('ParameterJs:'+idInfoCouleur);
        String InfoCouleurId=idInfoCouleur;
        system.debug('InfoCouleurId:'+InfoCouleurId);
        List<Nombre_de_vue__c> ExistingView = [Select Id,Name,Nombre_de_vue__c from Nombre_de_vue__c where User__c =: userId AND Info_Couleur__c =: InfoCouleurId ]; 
        system.debug('ExistingView:'+ExistingView);
        if (ExistingView != null && ExistingView.size()>0 )
        {    
        	ExistingView[0].Nombre_de_vue__c = ExistingView[0].Nombre_de_vue__c+1;
            ExistingView[0].Date_de_vue__c = system.today() ;
            update ExistingView[0];
            return ExistingView[0];
        }
        else
        {
            Nombre_de_vue__c ViewBy = new Nombre_de_vue__c(Nombre_de_vue__c =1, User__c=userId,Info_Couleur__c=InfoCouleurId, Date_de_vue__c = system.today()  );
            upsert ViewBy;
            return ViewBy;    
        }
   }       

}