force-app/main/default/objects/InfoCouleur__c/InfoCouleur__c.object-meta.xml
<CustomObject>
    <label>Info Couleur</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Info Couleur</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InfoCouleur__c/fields/Couleur__c.field-meta.xml
<CustomField>
    <fullName>Couleur__c</fullName>
    <description>représente le type d&apos;Info Couleur</description>
    <label>Couleur</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bleue</fullName>
            </value>
            <value>
                <fullName>Rouge</fullName>
            </value>
            <value>
                <fullName>Violette</fullName>
            </value>
            <value>
                <fullName>Verte</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Bleu</fullName>
                <isActive>false</isActive>
                <label>Bleu</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InfoCouleur__c/fields/Nombre_de_vue__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_vue__c</fullName>
    <description>Permet de comptabiliser le nombre de vues</description>
    <label>Nombre de vues</label>
    <summaryForeignKey>Nombre_de_vue__c.Info_Couleur__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Nombre_de_vue__c/Nombre_de_vue__c.object-meta.xml
<CustomObject>
    <label>Nombre de vues</label>
    <nameField>
        <displayFormat>VUE-{0000}</displayFormat>
        <label>Nombre de vue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nombre de vues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Nombre_de_vue__c/fields/Info_Couleur__c.field-meta.xml
<CustomField>
    <fullName>Info_Couleur__c</fullName>
    <label>Info Couleur</label>
    <referenceTo>InfoCouleur__c</referenceTo>
    <relationshipName>TEST_nombre_de_vue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Nombre_de_vue__c/fields/Nombre_de_vue__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_vue__c</fullName>
    <label>Nombre de vues</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Nombre_de_vue__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User ID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TEST_nombre_de_vue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/POC_InfoCouleurVueTest.cls
/**
 * @File Name          : POC_InfoCouleurVueTest.cls
 * @Description        : Classe de test de la classe "POC_InfoCouleurVue"
 * @Author             : Jihad AZAMI HASSANI
 * @Ticket             : FT2-277, FT2-289, FT2-291/ Sprint 10
 * Ver       Date            Author      		    Modification
 * 1.0    05/03/2020   Jihad AZAMI HASSANI     Initial Version
**/
@isTest
public class POC_InfoCouleurVueTest {
        //Test Variable get;set -- Controller -- Action vf
    @isTest private static void testAutoRun() {
        test.startTest();
        PageReference pageRef = Page.DejaLuVFP;
        InfoCouleur__c c = new InfoCouleur__c(name='test', Couleur__c='Rouge');
        insert c;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',c.id);
        ApexPages.StandardController sc = new ApexPages.standardController(c);
        POC_InfoCouleurVue  controller = new POC_InfoCouleurVue(sc);
        controller.InfoCouleurVue();
        test.stopTest();
    }
        //Test methode viewBy
    @isTest static void testcreateViewBy() {
          InfoCouleur__c ic = new InfoCouleur__c(name='test', Couleur__c='Rouge');
          insert ic;     
          String ViewBy = POC_InfoCouleurVue.createViewBy(ic.id);
        }
    @isTest static void testcreateViewBy1() {
          String userId = UserInfo.getUserId();
          InfoCouleur__c ic2 = new InfoCouleur__c(name='test', Couleur__c='Rouge');
          insert ic2;
          Nombre_de_vue__c nbrv = new Nombre_de_vue__c(User__c=userId, Info_Couleur__c=ic2.id,Nombre_de_vue__c=1);
          insert nbrv;      
          String ViewBy = POC_InfoCouleurVue.createViewBy(ic2.id);
        }
}