force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Compteur_Base_Plan_Index__c.field-meta.xml
<CustomField>
    <fullName>HP_Compteur_Base_Plan_Index__c</fullName>
    <label>Index Elec</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Compteur_Plan_Bottom_Price_Index__c.field-meta.xml
<CustomField>
    <fullName>HP_Compteur_Plan_Bottom_Price_Index__c</fullName>
    <label>Index Elec HC</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Compteur_Variable_Plan_prix_Index__c.field-meta.xml
<CustomField>
    <fullName>HP_Compteur_Variable_Plan_prix_Index__c</fullName>
    <label>Index Elec HP</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Contrat_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Id_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Id_Compteur__c</fullName>
    <label>Id Compteur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Numero_reference_du_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Numero_reference_du_Compteur__c</fullName>
    <label>Numéro référence du Compteur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Proposition_Commerciale_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Proposition_Commerciale_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Proposition Commerciale XdataId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Souscription Digital Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Canal_de_vente__c.field-meta.xml
<CustomField>
    <fullName>HP_Canal_de_vente__c</fullName>
    <label>Canal de vente</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Classe_de_la_consommation_Gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Classe_de_la_consommation_Gaz__c</fullName>
    <label>Classe de la consommation Gaz</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASE</fullName>
            </value>
            <value>
                <fullName>B0</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_Electrique_Produit__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_Electrique_Produit__c</fullName>
    <label>Code offre électricité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_Gaz_Produit__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_Gaz_Produit__c</fullName>
    <label>Code offre gaz</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_postal__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_postal__c</fullName>
    <label>Code postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_code_Postal_Insee__c.field-meta.xml
<CustomField>
    <fullName>HP_code_Postal_Insee__c</fullName>
    <label>Code INSEE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_de_Contractualisation__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_de_Contractualisation__c</fullName>
    <label>Date de début de contrat souhaitée</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_Origine__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_Origine__c</fullName>
    <label>Date Origine</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Energie_Verte__c.field-meta.xml
<CustomField>
    <fullName>HP_Energie_Verte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Energie Verte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Estimation_Consommation_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Estimation_Consommation_electrique__c</fullName>
    <label>Estimation Consommation électricité</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Estimation_Consommation_gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Estimation_Consommation_gaz__c</fullName>
    <label>Estimation Consommation gaz</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Jour_de_facturation__c.field-meta.xml
<CustomField>
    <fullName>HP_Jour_de_facturation__c</fullName>
    <label>Date de réglement personnalisée</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Lien_enregistrement__c.field-meta.xml
<CustomField>
    <fullName>HP_Lien_enregistrement__c</fullName>
    <label>Lien d&apos;enregistrement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Methode_de_paiement__c.field-meta.xml
<CustomField>
    <fullName>HP_Methode_de_paiement__c</fullName>
    <label>Mode de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRANSFER</fullName>
                <label>Prélèvement</label>
            </value>
            <value>
                <fullName>BANK_CARD</fullName>
                <label>Carte bancaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Montant_de_la_facturation_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Montant_de_la_facturation_electrique__c</fullName>
    <label>Montant de la mensualité - électricité</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Montant_de_la_facturation_gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Montant_de_la_facturation_gaz__c</fullName>
    <label>Montant de la mensualité - gaz</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Nom_de_rue__c.field-meta.xml
<CustomField>
    <fullName>HP_Nom_de_rue__c</fullName>
    <label>Nom de rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Nom_de_ville__c.field-meta.xml
<CustomField>
    <fullName>HP_Nom_de_ville__c</fullName>
    <label>Nom de ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumberPCE__c.field-meta.xml
<CustomField>
    <fullName>HP_NumberPCE__c</fullName>
    <label>N° PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Numero_de_voie__c.field-meta.xml
<CustomField>
    <fullName>HP_Numero_de_voie__c</fullName>
    <label>Numéro de voie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumPDL__c.field-meta.xml
<CustomField>
    <fullName>HP_NumPDL__c</fullName>
    <label>N° PDL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Periode_de_facturation__c.field-meta.xml
<CustomField>
    <fullName>HP_Periode_de_facturation__c</fullName>
    <label>Fréquence de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY</fullName>
                <label>Annuel</label>
            </value>
            <value>
                <fullName>BIMONTHLY</fullName>
                <label>Bimestriel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Plan_de_Prix_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Plan_de_Prix_electrique__c</fullName>
    <label>Type de comptage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASE</fullName>
                <label>Simple</label>
            </value>
            <value>
                <fullName>VARIABLE</fullName>
                <label>HP/HC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Predecesseur__c.field-meta.xml
<CustomField>
    <fullName>HP_Predecesseur__c</fullName>
    <label>Nom du prédécesseur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Puissance_Compteur_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Puissance_Compteur_electrique__c</fullName>
    <label>Puissance Compteur électricité</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Statut__c.field-meta.xml
<CustomField>
    <fullName>HP_Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVE_1</fullName>
                <label>Devis envoyé</label>
            </value>
            <value>
                <fullName>SAVE_2</fullName>
                <label>Demande envoyée</label>
            </value>
            <value>
                <fullName>SAVE_2_CONFIRMED</fullName>
                <label>CPV envoyées</label>
            </value>
            <value>
                <fullName>CANCEL</fullName>
                <label>CPV annulées</label>
            </value>
            <value>
                <fullName>RETRACT</fullName>
                <label>CPV rétractées</label>
            </value>
            <value>
                <fullName>PERIMEE</fullName>
                <label>CPV périmées</label>
            </value>
            <value>
                <fullName>SAVE_3</fullName>
                <label>CPV signées</label>
            </value>
            <value>
                <fullName>CPV Périmées</fullName>
                <isActive>false</isActive>
                <label>CPV Périmées</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Type_Energie__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_Energie__c</fullName>
    <label>Type Energie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRICITY</fullName>
                <label>Electricité</label>
            </value>
            <value>
                <fullName>GAS</fullName>
                <label>Gaz</label>
            </value>
            <value>
                <fullName>COMBINED_GAS_AND_ELECTRICITY</fullName>
                <label>Dual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_type_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_type_Souscription__c</fullName>
    <label>Type de Souscription</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOVING_IN</fullName>
                <label>Emménagement</label>
            </value>
            <value>
                <fullName>SWITCH_SUPLIER</fullName>
                <label>Changement de fournisseur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_SendMailContratualizationService_TEST.cls
/**
 * @description  : 
 * @author       : Vincent Albiser
 * Modifications Log 
 * Ver   Date         Author            Modification
 * 1.0   09-12-2020   Vincent Albiser   Initial Version
**/
@isTest
public with sharing class HP_SendMailContratualizationService_TEST {

    private enum StaticResource {		
        HP_APIHourAccessTokenResponse_MOCK,
        HP_SendEmail_Mock
    }

 
    //only test invocable method 

    @testSetup 
    static void dataSetup(){

        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{
            'Id_Tiers__c' => 100166,
            'HP_IsHappe__c' => true,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;

        HP_Souscription__c enrolment = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Canal_de_vente__c'  => 'Vente Online',
            'HP_Contact__c'=>contact.Id,
            'HP_Classe_de_la_consommation_Gaz__c'  => 'B0',
            'HP_Code_Gaz_Produit__c'  => 'GITR2_H',
            'HP_Code_Electrique_Produit__c'  => 'EITR2_H',
            'HP_Code_postal__c'  => '92160',
            'HP_code_Postal_Insee__c'  => '92002',
            'HP_Date_de_Contractualisation__c'  => Date.newInstance(2019, 12, 22),
            'HP_Date_Origine__c'  =>DateTime.newInstance(2019, 10, 9, 13, 0, 0),
            'HP_Energie_Verte__c'  => false,
            'HP_Estimation_Consommation_electrique__c'  => 6000,
            'HP_Estimation_Consommation_gaz__c'  => 13000,
			'HP_Jour_de_facturation__c' => 16,
            'HP_Lien_enregistrement__c' =>'test.fr',
            'HP_Methode_de_paiement__c' =>'BANK_CARD',
            'HP_Montant_de_la_facturation_electrique__c' =>58,
            'HP_Montant_de_la_facturation_gaz__c' =>120,
            'HP_Predecesseur__c' =>'Dupont',
            'HP_Nom_de_rue__c' =>'rue des bois',
            'HP_Nom_de_ville__c' =>'ANTONY',
            'HP_Numero_de_voie__c' =>'15 ter',
            'HP_Periode_de_facturation__c' =>'BIMONTHLY',
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_Puissance_Compteur_electrique__c' =>6,
            'HP_Souscription_Digital_Id__c' =>'testGazElec-01',
            'HP_Type_Energie__c' =>'COMBINED_GAS_AND_ELECTRICITY',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_NumPDL__c' =>'31431211214170',
            'HP_Statut__c' =>'SAVE_1'
		}, null);
        insert enrolment;

        HP_Contrat__c contrat =(HP_Contrat__c) HP_UTIL_SmartFactory.createSObject('HP_Contrat__c', 
        new Map<String, Object>{ 
            'HP_Numero_reference_du_Compteur__c' => '423',
            'HP_Id_Compteur__c' => '31431211214170',
            'HP_Compteur_Base_Plan_Index__c' => 56726,
            'HP_Compteur_Variable_Plan_prix_Index__c' => 34251,
            'HP_Compteur_Plan_Bottom_Price_Index__c' => 78098,
            'HP_Contrat_XdataId__c' => 100148,
            'HP_Souscription_Digital_Id__c' => enrolment.HP_Souscription_Digital_Id__c+'ELEC',
            'HP_Proposition_Commerciale_XdataId__c'=>'775949',
            'HP_Souscription__c'=> enrolment.id,
            'HP_Type_de_Compteur__c' => 'ELEC'
        }, null);
        insert contrat;

        HP_Souscription__c enrolment2 = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Souscription_Digital_Id__c' =>'testElec-01',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumPDL__c' =>'31431211214170',
            'HP_Statut__c' =>'SAVE_3',
            'HP_Tech_Is_Apex_Processing__c'=> false,
            'HP_Type_Energie__c' =>'ELECTRICITY',
            'HP_Contact__c'=> contact.Id,
            'HP_Plan_de_Prix_electrique__c' =>'BASE'
		}, null);
        insert enrolment2;

        HP_Contrat__c celec =(HP_Contrat__c) HP_UTIL_SmartFactory.createSObject('HP_Contrat__c', 
        new Map<String, Object>{ 
            'HP_Numero_reference_du_Compteur__c' => '423',
            'HP_Id_Compteur__c' => '31431211214170',
            'HP_Compteur_Base_Plan_Index__c' => 56726,
            'HP_Compteur_Variable_Plan_prix_Index__c' => 34251,
            'HP_Compteur_Plan_Bottom_Price_Index__c' => 78098,
            'HP_Souscription_Digital_Id__c' => enrolment2.HP_Souscription_Digital_Id__c+'ELEC',
            'HP_Proposition_Commerciale_XdataId__c'=>'775949',
            'HP_Type_de_Compteur__c' => 'ELEC',
            'HP_Contrat_XdataId__c' => 100149,
            'HP_Souscription__c'=> enrolment2.id
        }, null);
        insert celec;
    }

    @IsTest static void sendMailViaCabestan_TEST(){

        Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
            'token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(
                200,
                StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                new Map<String, String> {'Content-Type' => 'application/json'}
            ),
            'ES-Correspondance_v2' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(
                200,
                StaticResource.HP_SendEmail_Mock.name(),
                new Map<String, String> {'Content-Type' => 'application/json'}
            )
        };

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
            List<HP_SendMailContratualizationService.ObjectToSend> senderlist = new List<HP_SendMailContratualizationService.ObjectToSend>();
            HP_SendMailContratualizationService.ObjectToSend sender = new HP_SendMailContratualizationService.ObjectToSend(
                null,
                'user@example.com',
                100166,
                'testnicot',
                'MR',
                'lenfant',
                'Emménagement',
                '12',
                'Gaz',
                null,
                'rue',
                'rue',
                '75000',
                'Paris'
            );
            senderlist.add(sender);
            HP_SendMailContratualizationService.sendMailViaCabestan(senderlist);
        Test.stopTest();
        System.assert([SELECT count() FROM EmailMessage] > 0 , 'EmailMessage created in SF');
    }


    @IsTest static void sendMailViaCabestanSyncDUAL_TEST(){

        Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
            'token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(
                200,
                StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                new Map<String, String> {'Content-Type' => 'application/json'}
            ),
            'ES-Correspondance_v2' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(
                200,
                StaticResource.HP_SendEmail_Mock.name(),
                new Map<String, String> {'Content-Type' => 'application/json'}
            )
        };

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));

            HP_Contrat__c celec = [SELECT id,HP_Souscription__r.HP_Contact__r.Email, HP_Souscription__r.HP_Contact__r.Id_Tiers__c, HP_Souscription__r.HP_Contact__r.Lastname, HP_Souscription__r.HP_Contact__r.Salutation, HP_Souscription__r.HP_Contact__r.Firstname,HP_Souscription__r.HP_Type_Energie__c FROM HP_Contrat__c WHERE HP_Contrat_XdataId__c = 100148  LIMIT 1];
            HP_WRP022_SFResponse response = new HP_WRP022_SFResponse(200);
            HP_SendMailContratualizationService.sendMailViaCabestanSync('SF12', celec, response);
        Test.stopTest();
        System.assert([SELECT count() FROM EmailMessage] == 0 , 'EmailMessage created in SF');

    }


    
    @IsTest static void sendMailViaCabestanSyncElec_TEST(){

        Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
            'token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(
                200,
                StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                new Map<String, String> {'Content-Type' => 'application/json'}
            ),
            'ES-Correspondance_v2' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(
                200,
                StaticResource.HP_SendEmail_Mock.name(),
                new Map<String, String> {'Content-Type' => 'application/json'}
            )
        };

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));

            HP_Contrat__c celec = [SELECT id,HP_Type_de_Compteur__c,HP_Souscription__r.HP_Plan_de_Prix_electrique__c,  HP_Souscription__r.HP_Contact__r.Email, HP_Souscription__r.HP_Contact__r.Id_Tiers__c, HP_Souscription__r.HP_Contact__r.Lastname, HP_Souscription__r.HP_Contact__r.Salutation, HP_Souscription__r.HP_Contact__r.Firstname,HP_Souscription__r.HP_Type_Energie__c FROM HP_Contrat__c  WHERE HP_Contrat_XdataId__c = 100149 LIMIT 1];
            HP_WRP022_SFResponse response = new HP_WRP022_SFResponse(200);
            HP_SendMailContratualizationService.sendMailViaCabestanSync('SF12', celec, response);
        Test.stopTest();
        System.assert([SELECT count() FROM EmailMessage] == 0 , 'EmailMessage created in SF');

    }
}