force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Contrat_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Id_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Id_Compteur__c</fullName>
    <label>Id Compteur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Numero_reference_du_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Numero_reference_du_Compteur__c</fullName>
    <label>Numéro référence du Compteur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Souscription Digital Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Type_de_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_de_Compteur__c</fullName>
    <label>Type de Compteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GAS</fullName>
            </value>
            <value>
                <fullName>ELEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/HP_Porte_Feuille_Contrat__c.object-meta.xml
<CustomObject>
    <label>Portefeuille Contrat Happe</label>
    <nameField>
        <label>Nom du Portefeuille Contrat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portefeuilles Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portefeuilles Contrats Happe</relationshipLabel>
    <relationshipName>HP_Porte_Feuilles_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/Xdata_Id__c.field-meta.xml
<CustomField>
    <fullName>Xdata_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_de_Contractualisation__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_de_Contractualisation__c</fullName>
    <label>Date de début de contrat souhaitée</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Statut__c.field-meta.xml
<CustomField>
    <fullName>HP_Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVE_1</fullName>
                <label>Devis envoyé</label>
            </value>
            <value>
                <fullName>SAVE_2</fullName>
                <label>Demande envoyée</label>
            </value>
            <value>
                <fullName>SAVE_2_CONFIRMED</fullName>
                <label>CPV envoyées</label>
            </value>
            <value>
                <fullName>CANCEL</fullName>
                <label>CPV annulées</label>
            </value>
            <value>
                <fullName>RETRACT</fullName>
                <label>CPV rétractées</label>
            </value>
            <value>
                <fullName>PERIMEE</fullName>
                <label>CPV périmées</label>
            </value>
            <value>
                <fullName>SAVE_3</fullName>
                <label>CPV signées</label>
            </value>
            <value>
                <fullName>CPV Périmées</fullName>
                <isActive>false</isActive>
                <label>CPV Périmées</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>HP_Contrat__c</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>HP_Effective_Date__c</fullName>
    <description>Nouvelle date d’effet souhaitée par le client</description>
    <inlineHelpText>Nouvelle date d’effet souhaitée par le client</inlineHelpText>
    <label>Date d&apos;effet souhaitée</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_PDL_PCE__c.field-meta.xml
<CustomField>
    <fullName>Numero_PDL_PCE__c</fullName>
    <label>Numéro de PDL/PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/recordTypes/HP_PrestationDistributeur.recordType-meta.xml
<RecordType>
    <fullName>HP_PrestationDistributeur</fullName>
    <active>true</active>
    <label>HP_PrestationDistributeur</label>
</RecordType>

force-app/main/default/classes/HP_WS010_Case_TEST.cls
/**
 * @File Name          : HP_WS010_Case_TEST.cls
 * @Description        : Test class for WS caseCreation
 * @Author             : Sara El-Hannaoui
 * @Group              : 
 * @Last Modified By   : Badr Eddine Belkarchi
 * @Last Modified On   : 03-07-2022
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    15/04/2020   Sara El-Hannaoui     Initial Version
**/
@isTest
public with sharing class HP_WS010_Case_TEST {


    @testSetup static void dataSetup(){
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){
            Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', null, new Map<String, Object>{
                'LastName' => 'Test Lastname',
                'Email' => 'test@gmail.com',
                'Id_Tiers__c' => 195464
            }, null, null, null);
            insert contact;

            HP_Porte_Feuille_Contrat__c porteFeuille = (HP_Porte_Feuille_Contrat__c)HP_UTIL_SmartFactory.createSObject('HP_Porte_Feuille_Contrat__c', null, new Map<String, Object>{
                'HP_Contact__c' => contact.id,
                'Xdata_Id__c' => '1222',
                'HP_Souscription_Digital_Id__c'=>'testGazElec-01'
            }, null, null, null);
            insert porteFeuille;

            HP_Contrat__c celec =(HP_Contrat__c) HP_UTIL_SmartFactory.createSObject('HP_Contrat__c', 
            new Map<String, Object>{ 
                'HP_Numero_reference_du_Compteur__c' => '423',
                'HP_Id_Compteur__c' => '12',
                'HP_Contrat_XdataId__c' => 282713,
                'HP_Souscription_Digital_Id__c' => 'testGazElec-01ELEC',
                'HP_Type_de_Compteur__c' => 'ELEC'
            }, null);
            insert celec;

            HP_Contrat__c cgaz =(HP_Contrat__c) HP_UTIL_SmartFactory.createSObject('HP_Contrat__c', 
            new Map<String, Object>{ 
                'HP_Numero_reference_du_Compteur__c' => '324',
                'HP_Id_Compteur__c' => '13',
                'HP_Contrat_XdataId__c' => 282714,
                'HP_Souscription_Digital_Id__c' => 'testGazElec-01GAS',
                'HP_Type_de_Compteur__c' => 'GAS'
            }, null);
            insert cgaz;

            HP_Souscription__c enrolment = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
                'HP_Souscription_Digital_Id__c'  => '123456',
                'HP_Date_de_Contractualisation__c' => System.today().addDays(1),
                'HP_Statut__c' =>'SAVE_3',
                'HP_Contact__c'=> contact.Id
            }, null);
            insert enrolment;

            Case caseElec = (Case) HP_UTIL_SmartFactory.createSObject('Case', new Map<String, Object> {
                'Status' => HP_SLCT_Case.Status.HP_PENDING.name(),
                'HP_Contrat__c' => celec.id,
                'RecordTypeId' => HP_UTIL_RecordType.getRecordTypeId('Case','HP_Facturation'),
                'HP_Type__c' => 'HP_Coupure_ReductionPuissance',
                'Status' => 'NEW_CASE',
                'OwnerId' => HP_UTIL_QueueManager.getQueueIdByName('HP_Niveau_1'),
                'ContactId' => contact.Id,
                'Portefeuille_Contrat_Happe__c' => porteFeuille.Id,
                'Origin' => 'HP_BILLING',
                'HP_Energy__c' => 'Electricity'
            }, null);
            insert caseElec;

            Case caseGas = (Case) HP_UTIL_SmartFactory.createSObject('Case', new Map<String, Object> {
                'Status' => HP_SLCT_Case.Status.HP_PENDING.name(),
                'HP_Contrat__c' => cgaz.id,
                'RecordTypeId' => HP_UTIL_RecordType.getRecordTypeId('Case','HP_Facturation'),
                'HP_Type__c' => 'HP_Coupure_ReductionPuissance',
                'Status' => 'NEW_CASE',
                'OwnerId' => HP_UTIL_QueueManager.getQueueIdByName('HP_Niveau_1'),
                'ContactId' => contact.Id,
                'Portefeuille_Contrat_Happe__c' => porteFeuille.Id,
                'Origin' => 'HP_BILLING',
                'HP_Energy__c' => 'Gas'
            }, null);
            insert caseGas;

            Prestation_distributeur__c prestationForElec = (Prestation_distributeur__c) HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c','HP_PrestationDistributeur', 
            new Map<String, Object>{
                'Statut__c' => 'En cours',
                'Numero_affaire_distributeur__c' => 'A1234567',
                'Numero_PDL_PCE__c' => '12',
                'Contact__c' => contact.Id,
                'HP_Contrat__c' => celec.Id,
                'Case__c' => caseElec.Id,
                'HP_Effective_Date__c' => Date.newInstance(2021, 09, 22)}, null, null, null);
            insert prestationForElec;

            Prestation_distributeur__c prestationForGas = (Prestation_distributeur__c) HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c','HP_PrestationDistributeur', 
            new Map<String, Object>{
                'Statut__c' => 'En cours',
                'Numero_affaire_distributeur__c' => 'A1234568',
                'Numero_PDL_PCE__c' => '13',
                'Contact__c' => contact.Id,
                'HP_Contrat__c' => celec.Id,
                'Case__c' => caseGas.Id,
                'HP_Effective_Date__c' => Date.newInstance(2021, 09, 22)}, null, null, null);
            insert prestationForGas;
        }
    }

    @isTest static void caseCreationOK_CaseOffline(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.contactInfo = new HP_WRP034_Case.ContactInfo ();
            req.contactInfo.email = 'test@gmail.com';
            req.contactInfo.firstname = 'test firstname';
            req.contactInfo.lastname = 'test lastname';
            req.context = 'Case offline';
            req.description = 'test description' ;
    
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
    
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();

            Id recordTypeId = HP_UTIL_RecordType.getRecordTypeId('Case','HP_CaseRecontact');
            System.assertEquals(1,[SELECT count() FROM Case WHERE recordTypeId=:recordTypeId], 'SUCCESS case inserted');
        }
    }

    @isTest static void anomalieCreationOK_CaseOffline(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.contactInfo = new HP_WRP034_Case.ContactInfo ();
            req.contactInfo.email = 'test@gmail.com';
            req.contactInfo.firstname = 'test firstname';
            req.contactInfo.lastname = 'test lastname';
            req.contactInfo.xdataId = 195464;
            req.context = 'Anomalie creation xdata Save2';
            req.description = 'test description' ;
            req.selfcareId = '123456';    
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
    
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
        }
    }

    @isTest static void caseCreationOK_Consentement(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.contactInfo = new HP_WRP034_Case.ContactInfo ();
            req.context = 'Consentement';
            req.description = 'test description' ;
            req.contactInfo.xdataId = 195464;
            
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
    
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
            Id recordTypeId = HP_UTIL_RecordType.getRecordTypeId('Case','HP_ContractErrorSave3');
            System.assertEquals(1,[SELECT count() FROM Case WHERE recordTypeId=:recordTypeId], 'SUCCESS case inserted');
        }
    }
     
    @isTest static void caseCreationPreconditionFailed(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.context = 'Case offline';
            req.contactInfo = new HP_WRP034_Case.ContactInfo ();
    
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
    
            reqHttp.requestBody =  Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
    
            System.assertEquals(400, resHttp.statusCode, 'Precondition Failed');
        }
    }

    @isTest static void caseCreationOK_CoupureReductionPuissance(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.context = 'Coupure_ReductionPuissance';
            req.porteFeuilleContratXdataId = 1222;
            req.contratXdataId = 282713;
            req.energie = 'Electricity';
            req.pdl = '12';
            req.contactInfo = new HP_WRP034_Case.ContactInfo();
            req.contactInfo.xdataId = 195464;
            req.contactInfo.clientAide = false;
            
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
            Id recordTypeId = HP_UTIL_RecordType.getRecordTypeId('Case','HP_Facturation');
            System.assertEquals(3,[SELECT count() FROM Case WHERE recordTypeId=:recordTypeId], 'SUCCESS case inserted');
        }
    }

    @isTest static void caseElectricityTraitementMAJCoupure_ETAT1_OK(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.context = 'MAJCoupure_ReductionPuissance';
            req.porteFeuilleContratXdataId = 1222;
            req.contratXdataId = 282713;
            req.energie = 'Electricity';
            req.pdl = '12';
            req.etat = 1;
            
            req.numeroAffaire = 'A1234567';
            req.objectCode = 'SAI';
            req.motifNonRealisationCode = 'motifNonRealisationCode';
            req.motifCode = 'motifCode';
            req.attestationPaiement = true;
            req.remiseChq = true;

            req.contactInfo = new HP_WRP034_Case.ContactInfo();
            req.contactInfo.xdataId = 195464;
            req.contactInfo.clientAide = false;
            
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
        }
    }

    @isTest static void caseGasTraitementMAJCoupure_ETAT1_OK(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.context = 'MAJCoupure_ReductionPuissance';
            req.porteFeuilleContratXdataId = 1222;
            req.contratXdataId = 282713;
            req.energie = 'Gas';
            req.pdl = '13';
            req.etat = 1;
            
            req.numeroAffaire = 'A1234568';
            req.motifNonRealisationCode = 'motifNonRealisationCode';
            req.motifCode = 'motifCode';
            req.attestationPaiement = false;
            req.remiseChq = false;

            req.contactInfo = new HP_WRP034_Case.ContactInfo();
            req.contactInfo.xdataId = 195464;
            req.contactInfo.clientAide = false;
            
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
        }
    }

    @isTest static void caseElectricityTraitementMAJCoupure_ETAT2_OK(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.context = 'MAJCoupure_ReductionPuissance';
            req.porteFeuilleContratXdataId = 1222;
            req.contratXdataId = 282713;
            req.energie = 'Electricity';
            req.pdl = '12';
            req.etat = 2;
            
            req.numeroAffaire = 'A1234567';
            req.objectCode = 'SAI';
            req.motifNonRealisationCode = 'motifNonRealisationCode';
            req.motifCode = 'motifCode';
            req.attestationPaiement = true;
            req.remiseChq = true;

            req.contactInfo = new HP_WRP034_Case.ContactInfo();
            req.contactInfo.xdataId = 195464;
            req.contactInfo.clientAide = false;
            
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
        }
    }

    @isTest static void caseElectricityTraitementMAJCoupure_ETAT3_OK(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.context = 'MAJCoupure_ReductionPuissance';
            req.porteFeuilleContratXdataId = 1222;
            req.contratXdataId = 282713;
            req.energie = 'Electricity';
            req.pdl = '12';
            req.etat = 3;
            
            req.numeroAffaire = 'A1234567';
            req.objectCode = 'SAI';
            req.motifNonRealisationCode = 'motifNonRealisationCode';
            req.motifCode = 'motifCode';
            req.attestationPaiement = true;
            req.remiseChq = true;

            req.contactInfo = new HP_WRP034_Case.ContactInfo();
            req.contactInfo.xdataId = 195464;
            req.contactInfo.clientAide = false;
            
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
        }
    }

    @isTest static void caseElectricityTraitementMAJCoupure_ETAT4_OK(){
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_WRP034_Case.Request req = new HP_WRP034_Case.Request();
            req.context = 'MAJCoupure_ReductionPuissance';
            req.porteFeuilleContratXdataId = 1222;
            req.contratXdataId = 282713;
            req.energie = 'Electricity';
            req.pdl = '12';
            req.etat = 4;
            
            req.numeroAffaire = 'A1234567';
            req.objectCode = 'SAI';
            req.motifNonRealisationCode = 'motifNonRealisationCode';
            req.motifCode = 'motifCode';
            req.attestationPaiement = true;
            req.remiseChq = true;

            req.contactInfo = new HP_WRP034_Case.ContactInfo();
            req.contactInfo.xdataId = 195464;
            req.contactInfo.clientAide = false;
            
            RestRequest reqHttp = new RestRequest();
            RestResponse resHttp = new RestResponse();
            reqHttp.requestBody = Blob.valueof(JSON.serialize(req, false));
            RestContext.request = reqHttp;
            RestContext.response = resHttp;
    
            Test.startTest();
            HP_WS010_Case.caseCreation();
            Test.stopTest();
        }
    }

}