force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Proposition_Commerciale_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Proposition_Commerciale_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Proposition Commerciale XdataId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Type_de_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_de_Compteur__c</fullName>
    <label>Type de Compteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GAS</fullName>
            </value>
            <value>
                <fullName>ELEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HP_EM032_RetractLoadPCInfo.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-04-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-28-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
global class HP_EM032_RetractLoadPCInfo {
    @InvocableMethod(label='Get PC Info')
    global static List<PCInfoWrapper> getInfoPC(List<String> souscriptionId) {
         List<HP_Contrat__c> contratList = [select HP_Proposition_Commerciale_XdataId__c, HP_Type_de_Compteur__c from HP_Contrat__c where HP_Souscription__c in :souscriptionId];
         PCInfoWrapper result = new PCInfoWrapper();
         for(HP_Contrat__c cont : contratList) {
             if(cont.HP_Proposition_Commerciale_XdataId__c == null) {
                 continue;
             }
             String body = HP_EM034_Retractation.loadPropositionCommecrialeXdata(String.valueOf(cont.HP_Proposition_Commerciale_XdataId__c));
             Map<String, Object> contMap = (Map<String, Object>) JSON.deserializeUntyped(body);
 
             System.debug('## body : ' + body);
             if(cont.HP_Type_de_Compteur__c == 'ELEC') {
                 result.statusElec = String.valueOf(contMap.get('codeStatutPropositionCommercialeHeader'));
             } else {
                 result.statusGaz = String.valueOf(contMap.get('codeStatutPropositionCommercialeHeader'));
             }
         }

         return new List<PCInfoWrapper>{result};
    }
    
    global class PCInfoWrapper {
         @InvocableVariable
         global String statusElec;
         @InvocableVariable
         global String statusGaz;
         
    }
}