force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Contrat_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Type_de_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_de_Compteur__c</fullName>
    <label>Type de Compteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GAS</fullName>
            </value>
            <value>
                <fullName>ELEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/HP_Porte_Feuille_Contrat__c.object-meta.xml
<CustomObject>
    <label>Portefeuille Contrat Happe</label>
    <nameField>
        <label>Nom du Portefeuille Contrat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portefeuilles Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portefeuilles Contrats Happe</relationshipLabel>
    <relationshipName>HP_Porte_Feuilles_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/Xdata_Id__c.field-meta.xml
<CustomField>
    <fullName>Xdata_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HP_EM036_SyncXdataSF.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-26-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   09-09-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class HP_EM036_SyncXdataSF {
    
    public static Map<String, Object> loadContractFromXdata(String xdataId) {
        Map<String, Object> listJson = (Map<String, Object>) JSON.deserializeUntyped(HP_UTIL_HTTPUtils.calloutGet(HP_Constantes.XDATA_CONTRATS, '/' + xdataId).getBody());
        HP_Contrat__c cont = new HP_Contrat__c(
            HP_Contrat_XdataId__c = Integer.valueOf(xdataId),
            HP_Type_de_Compteur__c = (listJson.get('energie') == 'Electricité' ? 'ELEC' : 'GAS'),
            HP_Porte_Feuille_Contrat__r = new HP_Porte_Feuille_Contrat__c(Xdata_Id__c = String.valueOf(listJson.get('idPortefeuilleContrat')))
        );

        Map<String, Object> result = new Map<String, Object>();
        result.put('cont' , cont);
        result.put('xdataPersonne' , listJson.get('idPersonne'));
        result.put('xdataPDL', listJson.get('idPointDeLivraison'));

        return result;
    }

    public static HP_Porte_Feuille_Contrat__c createPFC(String xdataIdPFC, String xdataContact) {
        HP_Porte_Feuille_Contrat__c pfc = new HP_Porte_Feuille_Contrat__c(
            HP_Contact__r = new Contact(Id_Tiers__c = Integer.valueOf(xdataContact)),
            Xdata_Id__c = xdataIdPFC
        );

        return pfc;
    }
}