force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Contrat_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>HP_Contrat__c</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_TECH_toNotify__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_toNotify__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_TECH_toNotify</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_PDL_PCE__c.field-meta.xml
<CustomField>
    <fullName>Numero_PDL_PCE__c</fullName>
    <label>Numéro de PDL/PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Secteur_activite__c.field-meta.xml
<CustomField>
    <fullName>Secteur_activite__c</fullName>
    <label>Secteur d&apos;activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elec</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/recordTypes/HP_PrestationDistributeur.recordType-meta.xml
<RecordType>
    <fullName>HP_PrestationDistributeur</fullName>
    <active>true</active>
    <label>HP_PrestationDistributeur</label>
</RecordType>

force-app/main/default/classes/HP_SCH004_CaseResiliationNotif_TEST.cls
/**
 * @File Name          : HP_SCH004_CaseResiliationNotification_TEST.cls
 * @Description        : 
 * @Author             : Sara El-Hannaoui
 * @Group              : 
 * @Last Modified By   : Sara El-Hannaoui
 * @Last Modified On   : 25/06/2020 à 14:03:22
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    25/06/2020   Sara El-Hannaoui     Initial Version
**/
@IsTest
global with sharing class HP_SCH004_CaseResiliationNotif_TEST {

    
    @testSetup static void dataSetup(){
        HP_Contrat__c contrat = (HP_Contrat__c)HP_UTIL_SmartFactory.createSObject('HP_Contrat__c', null, new Map<String, Object>{
            'HP_Contrat_XdataId__c' => 282535
            }, null, null, null);
        insert contrat;

        Prestation_distributeur__c testpresta = (Prestation_distributeur__c)HP_UTIL_SmartFactory.createSObject('Prestation_distributeur__c', 'HP_PrestationDistributeur', new Map<String, Object>{
            'Numero_PDL_PCE__c' => '230492038433',
            'Statut__c' => 'En cours',
            'Secteur_activite__c' => 'Gaz',
            'Numero_affaire_distributeur__c' => 'QL30DPC4',
            'HP_Contrat__c' => contrat.Id,
            'HP_TECH_toNotify__c' => true
        }, null, null, null);
        insert testpresta;
    
    }

    @isTest static void launchNewScheduler_TEST(){
            Test.startTest();
            HP_SCH004_CaseResiliationNotification.launchNewScheduler();
            Test.stopTest();
            System.assertEquals(2, [Select count() from AsyncApexJob],'job executed');

    }
    
   
}