force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Contrat_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Souscription Digital Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Type_de_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_de_Compteur__c</fullName>
    <label>Type de Compteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GAS</fullName>
            </value>
            <value>
                <fullName>ELEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/HP_Porte_Feuille_Contrat__c.object-meta.xml
<CustomObject>
    <label>Portefeuille Contrat Happe</label>
    <nameField>
        <label>Nom du Portefeuille Contrat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portefeuilles Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portefeuilles Contrats Happe</relationshipLabel>
    <relationshipName>HP_Porte_Feuilles_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Type_Energie__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_Energie__c</fullName>
    <label>Type Energie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRICITY</fullName>
                <label>Electricité</label>
            </value>
            <value>
                <fullName>GAS</fullName>
                <label>Gaz</label>
            </value>
            <value>
                <fullName>COMBINED_GAS_AND_ELECTRICITY</fullName>
                <label>Dual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/OK_Electricite__c.field-meta.xml
<CustomField>
    <fullName>OK_Electricite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OK Electricité</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/OK_Gaz__c.field-meta.xml
<CustomField>
    <fullName>OK_Gaz__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OK Gaz</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HP_SM031_RelanceSouscriptionSave3.cls
/**
 * @File Name          : HP_SM031_RelanceSouscriptionSave3.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : Hemdene Ben Hammouda
 * @Last Modified On   : 04-25-2022
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    22/05/2020   Sara El-Hannaoui     Initial Version
**/
public with sharing class HP_SM031_RelanceSouscriptionSave3 {
    
    
	/**
	* @description Permet de relancer le processus de contractualisation depuis une requête dont le record type est “HP_ContractErrorSave3” afin de créer le contrat dans Agilab et la prestation GRD.
	* @author Sara El-Hannaoui | 25/05/2020 
	* @param finalList<Id> myCaseIds 
	* @return List<String> 
	**/
        @InvocableMethod(label='Rerun contractualisation Agilab save 3')
	public static List<String> rerunContractualisationAgilab(final List<Id> myCaseIds){  
                List<String> listResult = new  List<String> ();         
                System.debug('MyCase' +myCaseIds);
                List<Case>  myCaseList = HP_EM010_Case.loadCase(myCaseIds[0]);
                listResult.add(execute(myCaseList[0]));
                return listResult;	
	}

	public static String execute(Case myCase){
                String selfcareId = myCase.HP_Souscription__r.HP_Souscription_Digital_Id__c;
                String energy = myCase.HP_Energy__c == 'Gas' ? 'GAS' : 'ELEC';
                HP_WRP022_SFResponse response = new HP_WRP022_SFResponse(HP_HttpStatus.OK);
                Map<String,List<SObject> > resultApi = null;
        
                String relanceContractResult;

                HP_Porte_Feuille_Contrat__c ptf = HP_EM024_PorteFeuilleContrat.loadPorteFeuilleContrat(selfcareId);
                Contact cont = HP_EM020_Contact.loadContact(ptf.HP_Contact__c);
                List<HP_Contrat__c> contractList = HP_EM023_Contrat.loadContratByEnergy(selfcareId, energy);
                HP_Souscription__c souscription = HP_EM005_Souscription.loadSouscription(selfcareId);
                
                resultApi = HP_SM024_Case.callAPIProcessing(souscription, cont, contractList, ptf, true, response);
                List<Case> caseList = (List<Case>)resultApi.get('case');
                boolean isContractualisationEnErreurAgilab = false;
                for (Integer i = (caseList.size()-1) ; i>= 0 ; i--){
                        if(caseList[i].RecordTypeId != Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('HP_ContractErrorSave3').getRecordTypeId()){
                                continue;
                        }
                        if (caseList[i].HP_Type__c == 'HP_Contractualization') {
                                isContractualisationEnErreurAgilab = true;
                        }
                        myCase.Description = caseList[i].Description;
                        relanceContractResult = 'Le contrat Agilab n’a pas pu être créé. Visualisez la description de la requête pour plus de détail.';
                        resultApi.get('case').remove(i);
                }
                if (relanceContractResult == null){
                        myCase.Status = 'CLOSED';
                        relanceContractResult = 'Le contrat est créé dans Agilab';
                }

                String electricityContractXdataId = '';
                String gasContractXdataId = '';
                if (!isContractualisationEnErreurAgilab) {
                        for(HP_Contrat__c acontrat : contractList) {
                                String typeCompteur = acontrat.HP_Type_de_Compteur__c;
                                if (typeCompteur == 'ELEC') {
                                        souscription.OK_Electricite__c = true;
                                        electricityContractXdataId = String.valueOf(acontrat.HP_Contrat_XdataId__c);
                                        System.debug('souscription.OK_Electricite__c = true;');
                                }
                                if (typeCompteur == 'GAS') {
                                        souscription.OK_Gaz__c = true;
                                        gasContractXdataId = String.valueOf(acontrat.HP_Contrat_XdataId__c);
                                        System.debug('souscription.OK_Gaz__c = true;');
                                } 
                        }
                        myCase.Etat_du_Case__c = 'Contrat validé';

                        if(myCase.Etat_du_Case__c == 'Contrat validé' && souscription.HP_Type_Energie__c != 'COMBINED_GAS_AND_ELECTRICITY'){
                                HP_SM063_WelcomeEmailSender.sendWelcomeEmail(souscription.Id,electricityContractXdataId, gasContractXdataId, souscription.OK_Electricite__c, souscription.OK_Gaz__c);
                        }
                        if(myCase.Etat_du_Case__c == 'KO définitif' && souscription.HP_Type_Energie__c == 'COMBINED_GAS_AND_ELECTRICITY'){
                                HP_SM063_WelcomeEmailSender.sendWelcomeEmail(souscription.Id,electricityContractXdataId, gasContractXdataId, souscription.OK_Electricite__c, souscription.OK_Gaz__c);
                        }
                }
                if(!isContractualisationEnErreurAgilab){
                        ID jobID = System.enqueueJob(new HP_EC_CommunityUserManagerAsync(cont.Id_Tiers__c));
		}
                resultApi.get('case').add(myCase);
                HP_SM022_SouscriptionSave3.updateDataProcessing(null, resultApi, souscription, cont, contractList, false, true, response);
                return relanceContractResult; 
	}

}