force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Contrat_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Type_de_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_de_Compteur__c</fullName>
    <label>Type de Compteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GAS</fullName>
            </value>
            <value>
                <fullName>ELEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_de_Contractualisation__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_de_Contractualisation__c</fullName>
    <label>Date de début de contrat souhaitée</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_Origine__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_Origine__c</fullName>
    <label>Date Origine</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalDateSave3__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalDateSave3__c</fullName>
    <label>Date de signature (Digital - save 3)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/HP_EM031_RetractLoadContractInfo.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 


 * @last modified on  : 08-12-2020


 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   07-28-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
global class HP_EM031_RetractLoadContractInfo {
    @InvocableMethod(label='Get contract Info')
    global static List<ContractStatusWrapper> getInfoContract(List<String> souscriptionId) {
        System.debug('@@ souscriptionId1 ' + souscriptionId);
         List<HP_Contrat__c> contratList = [select HP_Contrat_XdataId__c, HP_Type_de_Compteur__c from HP_Contrat__c where HP_Souscription__c in :souscriptionId];
         ContractStatusWrapper result = new ContractStatusWrapper();
         for(HP_Contrat__c cont : contratList) {
             if(cont.HP_Contrat_XdataId__c == null || String.valueOf(cont.HP_Contrat_XdataId__c) == null) {
                 continue;
             }
             String body = HP_EM034_Retractation.loadContractFromXdata(String.valueOf(cont.HP_Contrat_XdataId__c));
             Map<String, Object> contMap = (Map<String, Object>) JSON.deserializeUntyped(body);
 
             System.debug('## body : ' + body);
             if(cont.HP_Type_de_Compteur__c == 'ELEC') {
                 result.statusElec = String.valueOf(contMap.get('codeStatutCrm'));


                 result.labelStatusElec = String.valueOf(contMap.get('libelleStatutCrm'));
             } else {
                 result.statusGaz = String.valueOf(contMap.get('codeStatutCrm'));
                 result.labelStatusGaz = String.valueOf(contMap.get('libelleStatutCrm'));


             }
         }
         result.dayNumberSave3 = null;
         System.debug('@@ souscriptionId ' + souscriptionId);
         HP_Souscription__c souscription = [select HP_DigitalDateSave3__c, HP_Date_de_Contractualisation__c, HP_Date_Origine__c 
                            from HP_Souscription__c where id in :souscriptionId];
         result.dateContractulisation = souscription.HP_Date_de_Contractualisation__c;
         result.dateOrigine = Date.newinstance(souscription.HP_Date_Origine__c.year(), souscription.HP_Date_Origine__c.month(), souscription.HP_Date_Origine__c.day());
        
         result.dateToday =System.today();
         if(souscription.HP_DigitalDateSave3__c != null) {
            result.dateSave3 = Date.newinstance(souscription.HP_DigitalDateSave3__c.year(), souscription.HP_DigitalDateSave3__c.month(), souscription.HP_DigitalDateSave3__c.day());
             result.dayNumberSave3 = numberDateFromToday(result.dateSave3, System.today());
         }
         result.dayNumberContractualisation = numberDateFromToday(result.dateOrigine, souscription.HP_Date_de_Contractualisation__c);
         return new List<ContractStatusWrapper>{result};
    }
    
    private static Integer numberDateFromToday(Date d1, Date d2) {
        if( d1 == null || d2 == null) {
            return null;
        }
        return d1.daysBetween(d2);
    }
    global class ContractStatusWrapper {
         @InvocableVariable
         global String statusElec;
         @InvocableVariable
         global String statusGaz;
         @InvocableVariable


         global String labelStatusElec;
         @InvocableVariable
         global String labelStatusGaz;
         @InvocableVariable


         global Integer dayNumberSave3;
         @InvocableVariable
         global Integer dayNumberContractualisation;
         @InvocableVariable
         global Date dateToday;
         @InvocableVariable
         global Date dateOrigine;
         @InvocableVariable
         global Date dateContractulisation;
         @InvocableVariable
         global Date dateSave3;

    }
}