force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Contrat_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/HP_Porte_Feuille_Contrat__c.object-meta.xml
<CustomObject>
    <label>Portefeuille Contrat Happe</label>
    <nameField>
        <label>Nom du Portefeuille Contrat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portefeuilles Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/Xdata_Id__c.field-meta.xml
<CustomField>
    <fullName>Xdata_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>HP_Contrat__c</referenceTo>
    <relationshipLabel>Prestations distributeurs</relationshipLabel>
    <relationshipName>Prestations_distributeurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/HP_TECH_toNotify__c.field-meta.xml
<CustomField>
    <fullName>HP_TECH_toNotify__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_TECH_toNotify</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/recordTypes/HP_PrestationDistributeur.recordType-meta.xml
<RecordType>
    <fullName>HP_PrestationDistributeur</fullName>
    <active>true</active>
    <label>HP_PrestationDistributeur</label>
</RecordType>

force-app/main/default/classes/HP_BAT005_SynchroXdataAgilab.cls
/**
 * @File Name          : HP_BAT005_SynchroXdataAgilab.cls
 * @Description        : 
 * @Author             : Mouhamadoune Coulibaly
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 11-16-2020
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    18/03/2020   Mouhamadoune Coulibaly     Initial Version
**/
global class HP_BAT005_SynchroXdataAgilab implements Database.Batchable<sObject>,Database.AllowsCallouts, Schedulable, Database.RaisesPlatformEvents, HP_UTIL_BatchInterface {
    
    final Id hpRecordTypeId = HP_UTIL_RecordType.getRecordTypeId('Prestation_distributeur__c','HP_PrestationDistributeur');
   
    public static final Integer BATCH_CHUNK_SIZE = 1;
    global final  String query = 'Select Id,case__c, case__r.HP_Contrat__c,HP_Contrat__r.HP_Contrat_XdataId__c, case__r.Contact.Id_Tiers__c, case__r.HP_TECH_ExternalId__c, case__r.HP_Contrat__r.HP_Contrat_XdataId__c, HP_Contrat__c, HP_TECH_toNotify__c,RecordTypeId from Prestation_distributeur__c where RecordTypeId=\'' + hpRecordTypeId+ '\''+'AND HP_TECH_toNotify__c= true';   
    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('@@Query '+this.query);
    return Database.getQueryLocator(query);
    }
    



    global static void launchNewScheduler(String schedule, String jobName){
		System.schedule(jobName, schedule, new HP_BAT005_SynchroXdataAgilab());
    }
    
    global static void execute(SchedulableContext sc){
		execute();
	}
    



    global static void execute(){
		HP_BAT005_SynchroXdataAgilab batchSynchro = new HP_BAT005_SynchroXdataAgilab();
		Database.executeBatch(batchSynchro, BATCH_CHUNK_SIZE); 
	}
    
    global void execute(Database.BatchableContext bc, List<Prestation_distributeur__c> currentPres) { 
        List<HP_Contrat__c> contList = new List<HP_Contrat__c>();
        List<HP_Porte_Feuille_Contrat__c> pfcList = new List<HP_Porte_Feuille_Contrat__c>();
        List<Case> caseList = new List<Case>();
        for(Prestation_distributeur__c apresta : currentPres){
            Decimal xdataId = null;
            if(apresta.HP_Contrat__c != null &&  apresta.HP_Contrat__r.HP_Contrat_XdataId__c != null) {
                xdataId = apresta.HP_Contrat__r.HP_Contrat_XdataId__c ;
            } else if(apresta.case__r != null &&
            apresta.case__r.HP_Contrat__r != null &&
            apresta.case__r.HP_Contrat__r.HP_Contrat_XdataId__c != null) {
                xdataId = apresta.case__r.HP_Contrat__r.HP_Contrat_XdataId__c;
                apresta.HP_Contrat__c = apresta.case__r.HP_Contrat__c;
            } else if(apresta.case__r != null && apresta.case__r.HP_TECH_ExternalId__c != null
            && apresta.case__r.ContactId != null && apresta.case__r.Contact.Id_Tiers__c != null) {
                try {
                    xdataId = Integer.valueOf(apresta.case__r.HP_TECH_ExternalId__c.replace('CONTRACT_CANCELATION/', ''));
                    Map<String, Object> datas = HP_EM036_SyncXdataSF.loadContractFromXdata(String.valueOf(xdataId));
                    HP_Contrat__c cont = (HP_Contrat__c)datas.get('cont');
                    contList.add(cont);
                    pfcList.add(HP_EM036_SyncXdataSF.createPFC(cont.HP_Porte_Feuille_Contrat__r.Xdata_Id__c, String.valueOf(datas.get('xdataPersonne'))));
                    apresta.HP_Contrat__r = new HP_Contrat__c(HP_Contrat_XdataId__c = Integer.valueOf(xdataId));
                    caseList.add(new case(Id = apresta.case__c, HP_Contrat__r = new HP_Contrat__c(HP_Contrat_XdataId__c = Integer.valueOf(xdataId))));
                } catch(Exception e) {
                    Continue;
                }

            } else {
                continue;
            }
          
               HP_AgilabCommercialPropositionService.updateContractSync((Integer)xdataId, '9', null,new HP_WRP022_SFResponse(200));
            
               HP_APIHourContractService.updateContractSync(String.valueOf((Integer)xdataId),
               HP_APIHourContractService.APIHOUR_STATUS_BY_STATUS.get(HP_Contract.Status.CANCELLATION_NOT_DONE),'ACTIF', null);
               apresta.HP_TECH_toNotify__c = false;
           

        }
        if(pfcList.size() > 0) {
            upsert pfcList Xdata_Id__c;
           }
        if(contList.size() > 0) {
            upsert contList HP_Contrat_XdataId__c;
        }
        upsert currentPres;   
        
        

        if(caseList.size() > 0) {
            upsert caseList;
        }
    }
    global void finish(Database.BatchableContext bc){

    }
}