force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Proposition_Commerciale_XdataId__c.field-meta.xml
<CustomField>
    <fullName>HP_Proposition_Commerciale_XdataId__c</fullName>
    <externalId>true</externalId>
    <label>Proposition Commerciale XdataId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Souscription Digital Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Type_de_Compteur__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_de_Compteur__c</fullName>
    <label>Type de Compteur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GAS</fullName>
            </value>
            <value>
                <fullName>ELEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_PortailPrestataire__c/HP_PortailPrestataire__c.object-meta.xml
<CustomObject>
    <label>Prestataire</label>
    <nameField>
        <label>Prestataire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestataires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailUtilisateur__c/HP_PortailUtilisateur__c.object-meta.xml
<CustomObject>
    <label>Utilisateur Portail</label>
    <nameField>
        <displayFormat>UP-{00000}</displayFormat>
        <label>Utilisateur Portail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilisateurs Portail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Format email</inlineHelpText>
    <label>Login</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Prestataire__c.field-meta.xml
<CustomField>
    <fullName>Prestataire__c</fullName>
    <label>Prestataire associé</label>
    <referenceTo>HP_PortailPrestataire__c</referenceTo>
    <relationshipLabel>Utilisateurs Portail</relationshipLabel>
    <relationshipName>Utilisateurs_Portail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/HP_Porte_Feuille_Contrat__c.object-meta.xml
<CustomObject>
    <label>Portefeuille Contrat Happe</label>
    <nameField>
        <label>Nom du Portefeuille Contrat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portefeuilles Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portefeuilles Contrats Happe</relationshipLabel>
    <relationshipName>HP_Porte_Feuilles_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/Xdata_Id__c.field-meta.xml
<CustomField>
    <fullName>Xdata_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Xdata</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_code_promotion__c.field-meta.xml
<CustomField>
    <fullName>HP_code_promotion__c</fullName>
    <label>Code promo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_creation_CPV_elec__c.field-meta.xml
<CustomField>
    <fullName>HP_creation_CPV_elec__c</fullName>
    <label>Création document - CPV élec</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_creation_CPV_gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_creation_CPV_gaz__c</fullName>
    <label>Création document - CPV gaz</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_creation_mandat__c.field-meta.xml
<CustomField>
    <fullName>HP_creation_mandat__c</fullName>
    <label>Création document - Mandat SEPA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalDateSave2__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalDateSave2__c</fullName>
    <label>Date de lead (Digital - save 2)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalDocumentMandateId__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalDocumentMandateId__c</fullName>
    <label>Id Document - Mandat SEPA</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalElecDocumentId__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalElecDocumentId__c</fullName>
    <label>Id Document - CPV Elec</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalExemplaires__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalExemplaires__c</fullName>
    <label>Type de vente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalGazDocumentId__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalGazDocumentId__c</fullName>
    <label>Id Document - CPV gaz</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalLogin__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalLogin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ID vendeur</label>
    <referenceTo>HP_PortailUtilisateur__c</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>Happ_e_Informations_de_souscriptionV2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_DigitalUpdatePropositionStatus__c.field-meta.xml
<CustomField>
    <fullName>HP_DigitalUpdatePropositionStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Digital - Mise à jour statut proposition</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumberPCE__c.field-meta.xml
<CustomField>
    <fullName>HP_NumberPCE__c</fullName>
    <label>N° PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumPDL__c.field-meta.xml
<CustomField>
    <fullName>HP_NumPDL__c</fullName>
    <label>N° PDL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Porte_Feuille_Contrat__c.field-meta.xml
<CustomField>
    <fullName>HP_Porte_Feuille_Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portefeuille Contrat</label>
    <referenceTo>HP_Porte_Feuille_Contrat__c</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Revision_Document__c.field-meta.xml
<CustomField>
    <fullName>HP_Revision_Document__c</fullName>
    <label>Révision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Statut__c.field-meta.xml
<CustomField>
    <fullName>HP_Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVE_1</fullName>
                <label>Devis envoyé</label>
            </value>
            <value>
                <fullName>SAVE_2</fullName>
                <label>Demande envoyée</label>
            </value>
            <value>
                <fullName>SAVE_2_CONFIRMED</fullName>
                <label>CPV envoyées</label>
            </value>
            <value>
                <fullName>CANCEL</fullName>
                <label>CPV annulées</label>
            </value>
            <value>
                <fullName>RETRACT</fullName>
                <label>CPV rétractées</label>
            </value>
            <value>
                <fullName>PERIMEE</fullName>
                <label>CPV périmées</label>
            </value>
            <value>
                <fullName>SAVE_3</fullName>
                <label>CPV signées</label>
            </value>
            <value>
                <fullName>CPV Périmées</fullName>
                <isActive>false</isActive>
                <label>CPV Périmées</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Type_Energie__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_Energie__c</fullName>
    <label>Type Energie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRICITY</fullName>
                <label>Electricité</label>
            </value>
            <value>
                <fullName>GAS</fullName>
                <label>Gaz</label>
            </value>
            <value>
                <fullName>COMBINED_GAS_AND_ELECTRICITY</fullName>
                <label>Dual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_type_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_type_Souscription__c</fullName>
    <label>Type de Souscription</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOVING_IN</fullName>
                <label>Emménagement</label>
            </value>
            <value>
                <fullName>SWITCH_SUPLIER</fullName>
                <label>Changement de fournisseur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_WRP006_PortailRecords.cls
/**
 * @File Name          : HP_WRP006_PortailRecords.cls
 * @Description        :
 * @Author             : Vincent Albiser
 * @Group              :
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 10-15-2021
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    01/01/2020   Vincent Albiser     Initial Version
 **/

global with sharing class HP_WRP006_PortailRecords {

	global class Request {
		public final String login;
		public final Datetime startDate;
		public final Datetime endDate;
	}

	global class Response {

		public final List<Record> records;

		global Response(List<HP_Souscription__c> souscriptionList){

			this.records = new List<Record>();
			for(HP_Souscription__c souscription : souscriptionList) {
				this.records.add(new Record(souscription));
			}
		}
	}

	global class Record {

		public final String lastName;
		public final String firstName;
		public final String email;
		public final String gasMeterId;
		public final String electricityMeterId;
		public final String energyType;
		public final String nbExemplaires;
		public final String promotionalCode;
		public final String status;
		public final String selfcareId;
		public final Datetime createdDate;
		public final String login;
		public final String prestataire;
		public final Integer contractPortfolioXdataId;
		public final String electricityDocumentId;
		public final String gasDocumentId;
		public final String revisionDocument;
		public final Boolean updatePropositionStatus;
		public final String typeSouscription;

		public final Boolean creationCPVElec;
		public final Boolean creationCPVGaz;
		public final Boolean creationMandat;
		public final String idDocumentMandate;

		public final String pcElecId;
		public final String pcGazId;
        
        public final String hps;

		public final HP_EnrolmentRestResourceModel.Consentements consentements;

		global Record(HP_Souscription__c souscription){
			this.lastName           = souscription.HP_Contact__r.LastName;
			this.firstName          = souscription.HP_Contact__r.FirstName;
			this.email              = souscription.HP_Contact__r.Email;
			this.gasMeterId         = souscription.HP_NumberPCE__c;
			this.electricityMeterId = souscription.HP_NumPDL__c;
			this.energyType         = souscription.HP_Type_Energie__c;
			this.nbExemplaires      = souscription.HP_DigitalExemplaires__c;
			this.promotionalCode    = souscription.HP_code_promotion__c;
			this.status             = souscription.HP_Statut__c;
			this.selfcareId         = souscription.HP_Souscription_Digital_Id__c;
			this.createdDate        = souscription.HP_DigitalDateSave2__c;
			this.login              = souscription.HP_DigitalLogin__r.Login__c;
			this.prestataire        = souscription.HP_DigitalLogin__r.Prestataire__r.Name;
			this.electricityDocumentId = souscription.HP_DigitalElecDocumentId__c;
			this.gasDocumentId         = souscription.HP_DigitalGazDocumentId__c;
			this.revisionDocument         = souscription.HP_Revision_Document__c;
			this.contractPortfolioXdataId = souscription.HP_Porte_Feuille_Contrat__r.Xdata_Id__c != null ? Integer.valueOf(souscription.HP_Porte_Feuille_Contrat__r.Xdata_Id__c) : null;
			this.updatePropositionStatus = souscription.HP_DigitalUpdatePropositionStatus__c;
			this.idDocumentMandate = souscription.HP_DigitalDocumentMandateId__c;
			this.typeSouscription = souscription.HP_type_Souscription__c;
            this.hps = souscription.Name;


			if(souscription.HP_creation_CPV_elec__c != null && souscription.HP_creation_CPV_elec__c != '') {
				this.creationCPVElec  = (souscription.HP_creation_CPV_elec__c == 'Oui' ? true : false);
			}

			if(souscription.HP_creation_CPV_gaz__c != null && souscription.HP_creation_CPV_gaz__c != '') {
				this.creationCPVGaz = (souscription.HP_creation_CPV_gaz__c == 'Oui' ? true : false);
			}

			if(souscription.HP_creation_mandat__c != null && souscription.HP_creation_mandat__c != '') {
				this.creationMandat = (souscription.HP_creation_mandat__c == 'Oui' ? true : false);
			}

			for(HP_Contrat__c acontrat : souscription.HP_Contrats__r) {
				if(acontrat.HP_Type_de_Compteur__c == 'ELEC') {
					this.pcElecId = acontrat.HP_Proposition_Commerciale_XdataId__c;
				} else if(acontrat.HP_Type_de_Compteur__c == 'GAS') {
					this.pcGazId = acontrat.HP_Proposition_Commerciale_XdataId__c;
				}
			}
		}
	}

}