force-app/main/default/objects/HP_Contrat__c/HP_Contrat__c.object-meta.xml
<CustomObject>
    <label>Contrat Happe</label>
    <nameField>
        <displayFormat>HPC-{0000}</displayFormat>
        <label>Nom du Contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Souscription</label>
    <referenceTo>HP_Souscription__c</referenceTo>
    <relationshipName>HP_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Souscription Digital Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Offre__c/HP_Offre__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HP Offres</label>
</CustomObject>

force-app/main/default/objects/HP_Offre__c/fields/marqueCode__c.field-meta.xml
<CustomField>
    <fullName>marqueCode__c</fullName>
    <label>Code marque</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Offre__c/fields/offreCode__c.field-meta.xml
<CustomField>
    <fullName>offreCode__c</fullName>
    <externalId>true</externalId>
    <label>Code Offre</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Offre__c/fields/offreId__c.field-meta.xml
<CustomField>
    <fullName>offreId__c</fullName>
    <label>Id Offre</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Offre__c/fields/offreLibelle__c.field-meta.xml
<CustomField>
    <fullName>offreLibelle__c</fullName>
    <label>Libellé Offre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Offre__c/fields/packId__c.field-meta.xml
<CustomField>
    <fullName>packId__c</fullName>
    <label>Id Pack</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/HP_Porte_Feuille_Contrat__c.object-meta.xml
<CustomObject>
    <label>Portefeuille Contrat Happe</label>
    <nameField>
        <label>Nom du Portefeuille Contrat</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portefeuilles Contrats Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portefeuilles Contrats Happe</relationshipLabel>
    <relationshipName>HP_Porte_Feuilles_Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Porte_Feuille_Contrat__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/HP_Souscription__c.object-meta.xml
<CustomObject>
    <label>Souscription Happe</label>
    <nameField>
        <displayFormat>HPS-{00000000}</displayFormat>
        <label>Nom de Souscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Souscriptions Happe</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Canal_de_vente__c.field-meta.xml
<CustomField>
    <fullName>HP_Canal_de_vente__c</fullName>
    <label>Canal de vente</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Classe_de_la_consommation_Gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Classe_de_la_consommation_Gaz__c</fullName>
    <label>Classe de la consommation Gaz</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASE</fullName>
            </value>
            <value>
                <fullName>B0</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2I</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_Electrique_Produit__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_Electrique_Produit__c</fullName>
    <label>Code offre électricité</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_Gaz_Produit__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_Gaz_Produit__c</fullName>
    <label>Code offre gaz</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Code_postal__c.field-meta.xml
<CustomField>
    <fullName>HP_Code_postal__c</fullName>
    <label>Code postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_code_Postal_Insee__c.field-meta.xml
<CustomField>
    <fullName>HP_code_Postal_Insee__c</fullName>
    <label>Code INSEE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Contact__c.field-meta.xml
<CustomField>
    <fullName>HP_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Souscriptions Happe</relationshipLabel>
    <relationshipName>HP_Souscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_de_Contractualisation__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_de_Contractualisation__c</fullName>
    <label>Date de début de contrat souhaitée</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Date_Origine__c.field-meta.xml
<CustomField>
    <fullName>HP_Date_Origine__c</fullName>
    <label>Date Origine</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Energie_Verte__c.field-meta.xml
<CustomField>
    <fullName>HP_Energie_Verte__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Energie Verte</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Estimation_Consommation_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Estimation_Consommation_electrique__c</fullName>
    <label>Estimation Consommation électricité</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Estimation_Consommation_gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Estimation_Consommation_gaz__c</fullName>
    <label>Estimation Consommation gaz</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Jour_de_facturation__c.field-meta.xml
<CustomField>
    <fullName>HP_Jour_de_facturation__c</fullName>
    <label>Date de réglement personnalisée</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Lien_enregistrement__c.field-meta.xml
<CustomField>
    <fullName>HP_Lien_enregistrement__c</fullName>
    <label>Lien d&apos;enregistrement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Methode_de_paiement__c.field-meta.xml
<CustomField>
    <fullName>HP_Methode_de_paiement__c</fullName>
    <label>Mode de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRANSFER</fullName>
                <label>Prélèvement</label>
            </value>
            <value>
                <fullName>BANK_CARD</fullName>
                <label>Carte bancaire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Montant_de_la_facturation_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Montant_de_la_facturation_electrique__c</fullName>
    <label>Montant de la mensualité - électricité</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Montant_de_la_facturation_gaz__c.field-meta.xml
<CustomField>
    <fullName>HP_Montant_de_la_facturation_gaz__c</fullName>
    <label>Montant de la mensualité - gaz</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Nom_de_rue__c.field-meta.xml
<CustomField>
    <fullName>HP_Nom_de_rue__c</fullName>
    <label>Nom de rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Nom_de_ville__c.field-meta.xml
<CustomField>
    <fullName>HP_Nom_de_ville__c</fullName>
    <label>Nom de ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumberPCE__c.field-meta.xml
<CustomField>
    <fullName>HP_NumberPCE__c</fullName>
    <label>N° PCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Numero_de_voie__c.field-meta.xml
<CustomField>
    <fullName>HP_Numero_de_voie__c</fullName>
    <label>Numéro de voie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_NumPDL__c.field-meta.xml
<CustomField>
    <fullName>HP_NumPDL__c</fullName>
    <label>N° PDL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Periode_de_facturation__c.field-meta.xml
<CustomField>
    <fullName>HP_Periode_de_facturation__c</fullName>
    <label>Fréquence de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY</fullName>
                <label>Annuel</label>
            </value>
            <value>
                <fullName>BIMONTHLY</fullName>
                <label>Bimestriel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Plan_de_Prix_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Plan_de_Prix_electrique__c</fullName>
    <label>Type de comptage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASE</fullName>
                <label>Simple</label>
            </value>
            <value>
                <fullName>VARIABLE</fullName>
                <label>HP/HC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Predecesseur__c.field-meta.xml
<CustomField>
    <fullName>HP_Predecesseur__c</fullName>
    <label>Nom du prédécesseur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Puissance_Compteur_electrique__c.field-meta.xml
<CustomField>
    <fullName>HP_Puissance_Compteur_electrique__c</fullName>
    <label>Puissance Compteur électricité</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Souscription_Digital_Id__c.field-meta.xml
<CustomField>
    <fullName>HP_Souscription_Digital_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id Digital Souscription</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_Type_Energie__c.field-meta.xml
<CustomField>
    <fullName>HP_Type_Energie__c</fullName>
    <label>Type Energie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ELECTRICITY</fullName>
                <label>Electricité</label>
            </value>
            <value>
                <fullName>GAS</fullName>
                <label>Gaz</label>
            </value>
            <value>
                <fullName>COMBINED_GAS_AND_ELECTRICITY</fullName>
                <label>Dual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_Souscription__c/fields/HP_type_Souscription__c.field-meta.xml
<CustomField>
    <fullName>HP_type_Souscription__c</fullName>
    <label>Type de Souscription</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOVING_IN</fullName>
                <label>Emménagement</label>
            </value>
            <value>
                <fullName>SWITCH_SUPLIER</fullName>
                <label>Changement de fournisseur</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_SM063_WelcomeEmailSender_TEST.cls
/**
 * @description       : 
 * @author            : Hemdene Ben Hammouda
 * @group             : 
 * @last modified on  : 02-24-2022
 * @last modified by  : Badr Eddine Belkarchi
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   07-13-2021   Hemdene Ben Hammouda   Initial Version
**/
@isTest
public with sharing class HP_SM063_WelcomeEmailSender_TEST {
    @TestSetUp 
	private static void insertTestData() {
        

        Contact contact = (Contact)HP_UTIL_SmartFactory.createSObject('Contact', 'HP_Contact', new Map<String, Object>{ 
            'Id_Tiers__c' => 100166,
            'Salutation'=>'MR',
            'lastName' => 'testnicot',
            'firstName' => 'lenfant',
            'email' => 'user@example.com',
            'mobilePhone' => '0756543434',
            'Phone' => '0145454545',
            'No_Voie__c' => '22',
            'MailingStreet' => 'rue des bois',
            'MailingPostalCode' => '92160',
            'Complement_adresse__c' => 'REZID',
            'MailingCity' =>'ANTONY'
        }, null, null, null);
        insert contact;


        HP_Offre__c offre = (HP_Offre__c)HP_UTIL_SmartFactory.createSObject('HP_Offre__c', null, new Map<String, Object>{
           
            // offreCode__c,offreId__c,marqueCode__c,packId__c,offreLibelle__c
            'offreCode__c' => 'EITR2_H',
            'offreId__c'=> 436
            
        }, null, null, null);
        insert offre;

        HP_Offre__c offreGaz = (HP_Offre__c)HP_UTIL_SmartFactory.createSObject('HP_Offre__c', null, new Map<String, Object>{
            'offreCode__c' => 'GITR2_H',
            'offreId__c'=> 435
            
        }, null, null, null);
        insert offreGaz;

        HP_Souscription__c enrolment = (HP_Souscription__c) HP_UTIL_SmartFactory.createSObject('HP_Souscription__c', new Map<String, Object> {
            'HP_Canal_de_vente__c'  => 'Vente Online',
            'HP_Contact__c'=>contact.Id,
            'HP_Classe_de_la_consommation_Gaz__c'  => 'B0',
            'HP_Code_Gaz_Produit__c'  => 'GITR2_H',
            'HP_Code_Electrique_Produit__c'  => 'EITR2_H',
            'HP_Code_postal__c'  => '92160',
            'HP_code_Postal_Insee__c'  => '92002',
            'HP_Date_de_Contractualisation__c'  => Date.newInstance(2019, 12, 22),
            'HP_Date_Origine__c'  =>DateTime.newInstance(2019, 10, 9, 13, 0, 0),
            'HP_Energie_Verte__c'  => false,
            'HP_Estimation_Consommation_electrique__c'  => 6000,
            'HP_Estimation_Consommation_gaz__c'  => 13000,
			'HP_Jour_de_facturation__c' => 16,
            'HP_Lien_enregistrement__c' =>'test.fr',
            'HP_Methode_de_paiement__c' =>'BANK_CARD',
            'HP_Montant_de_la_facturation_electrique__c' =>58,
            'HP_Montant_de_la_facturation_gaz__c' =>120,
            'HP_Predecesseur__c' =>'Dupont',
            'HP_Nom_de_rue__c' =>'rue des bois',
            'HP_Nom_de_ville__c' =>'ANTONY',
            'HP_Numero_de_voie__c' =>'15 ter',
            'HP_Periode_de_facturation__c' =>'BIMONTHLY',
            'HP_Plan_de_Prix_electrique__c' =>'BASE',
            'HP_Puissance_Compteur_electrique__c' =>6,
            'HP_Souscription_Digital_Id__c' =>'testGazElec-01',
            'HP_Type_Energie__c' =>'COMBINED_GAS_AND_ELECTRICITY',
            'HP_type_Souscription__c' =>'MOVING_IN',
            'HP_NumberPCE__c' =>'31431211214068',
            'HP_NumPDL__c' =>'31431211214170',
            'HP_Statut__c' =>'SAVE_3'
		}, null);
        insert enrolment;

       
        HP_Porte_Feuille_Contrat__c porteFeuille = (HP_Porte_Feuille_Contrat__c)HP_UTIL_SmartFactory.createSObject('HP_Porte_Feuille_Contrat__c', null, new Map<String, Object>{
            'HP_Contact__c' => contact.id,
            //'Xdata_Id__c' => '1222',
            'HP_Souscription_Digital_Id__c'=>'testGazElec-01'
        }, null, null, null);
        insert porteFeuille;
		


        HP_Contrat__c cgaz =(HP_Contrat__c) HP_UTIL_SmartFactory.createSObject('HP_Contrat__c', 
        new Map<String, Object>{ 
            'HP_Numero_reference_du_Compteur__c' => '423',
            'HP_Id_Compteur__c' => '31431211214068',
            'HP_Contrat_XdataId__c' => 100148,
            'HP_Souscription_Digital_Id__c' => enrolment.HP_Souscription_Digital_Id__c+'GAS',
            'HP_Proposition_Commerciale_XdataId__c'=>'775949',
            'HP_Souscription__c'=> enrolment.id,
            'HP_Type_de_Compteur__c' => 'GAS',
            'HP_Index_de_Compteur__c'=>2323434
        }, null);
        insert cgaz;

        HP_Contrat__c celec =(HP_Contrat__c) HP_UTIL_SmartFactory.createSObject('HP_Contrat__c', 
        new Map<String, Object>{ 
            'HP_Numero_reference_du_Compteur__c' => '423',
            'HP_Id_Compteur__c' => '31431211214170',
            'HP_Compteur_Base_Plan_Index__c' => 56726,
            'HP_Compteur_Variable_Plan_prix_Index__c' => 34251,
            'HP_Compteur_Plan_Bottom_Price_Index__c' => 78098,
            'HP_Contrat_XdataId__c' => 100149,
            'HP_Souscription_Digital_Id__c' => enrolment.HP_Souscription_Digital_Id__c+'ELEC',
            'HP_Proposition_Commerciale_XdataId__c'=>'775949',
            'HP_Souscription__c'=> enrolment.id,
            'HP_Type_de_Compteur__c' => 'ELEC'
        }, null);
        insert celec;

	}

    @isTest
    static void sendSouscriptionEnAttenteDeValidationEmail_TEST(){
        Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
            'auth.marketingcloudapis.com/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                   'HP_MarketingCloudAccessTokenResponse_MOCK',
                                                   new Map<String, String> {'Content-Type' => 'application/json'}),

            '/messaging/v1/email/messages/' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(202,
                                                  'HP_MarketingCloudResponseOk',
                                                  new Map<String, String> { 'Content-Type' => 'application/json'}
                                                  )
        };
        
        HP_Souscription__c souscription = [SELECT Id from HP_Souscription__c limit 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
        HP_SM063_WelcomeEmailSender.sendSouscriptionEnAttenteDeValidationEmail(souscription.Id, '1278760', '1278758', true, false);
        Test.stopTest();     
    }

    @isTest
    static void sendWelcomeEmailOk_TEST(){
        Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
            'auth.marketingcloudapis.com/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                   'HP_MarketingCloudAccessTokenResponse_MOCK',
                                                   new Map<String, String> {'Content-Type' => 'application/json'}),

            '/messaging/v1/email/messages/' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(202,
                                                  'HP_MarketingCloudResponseOk',
                                                  new Map<String, String> { 'Content-Type' => 'application/json'}
                                                  )
        };
        HP_Souscription__c souscription = [SELECT Id from HP_Souscription__c limit 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
        HP_SM063_WelcomeEmailSender.sendWelcomeEmail(souscription.Id, '1278760', '1278758', true, false);
        Test.stopTest();     
    }

    @isTest
    static void sendWelcomeEmailOkk_Test(){
        Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
            'auth.marketingcloudapis.com/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                   'HP_MarketingCloudAccessTokenResponse_MOCK',
                                                   new Map<String, String> {'Content-Type' => 'application/json'}),

            '/messaging/v1/email/messages/' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(202,
                                                  'HP_MarketingCloudResponseOk',
                                                  new Map<String, String> { 'Content-Type' => 'application/json'}
                                                  )
        };
        HP_Souscription__c souscription = [SELECT Id from HP_Souscription__c limit 1];
        Contact con = [SELECT Id,Email from Contact limit 1];
        con.Email = 'test_engie@example.com';
        update con;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
        HP_SM063_WelcomeEmailSender.sendWelcomeEmail(souscription.Id, '1278760', '1278758', true, false);
        Test.stopTest();     
    }

    @isTest
    static void sendWelcomeEmailKo_TEST(){
        Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
            'auth.marketingcloudapis.com/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                   'HP_MarketingCloudAccessTokenResponse_MOCK',
                                                   new Map<String, String> {'Content-Type' => 'application/json'}),

            '/messaging/v1/email/messages/' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(400,
                                                  'HP_MarketingCloudResponseKo',
                                                  new Map<String, String> { 'Content-Type' => 'application/json'}
                                                  )
        };
        HP_Souscription__c souscription = [SELECT Id from HP_Souscription__c limit 1];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
        HP_SM063_WelcomeEmailSender.sendWelcomeEmail(souscription.Id, '1278760', '1278758', true, false);
        Test.stopTest();     
    }
}