force-app/main/default/objects/HP_CaseOwner__c/HP_CaseOwner__c.object-meta.xml
<CustomObject>
    <label>HP_CaseOwner</label>
    <nameField>
        <label>HP_CaseOwner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP_CaseOwners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_CaseOwner__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>HP_CaseOwners</relationshipLabel>
    <relationshipName>HP_CaseOwners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HP_CaseOwner__c/fields/HP_ActualOwner__c.field-meta.xml
<CustomField>
    <fullName>HP_ActualOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP Actual Owner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_CaseOwner__c/fields/HP_ElapsedTime__c.field-meta.xml
<CustomField>
    <fullName>HP_ElapsedTime__c</fullName>
    <label>HP ElapsedTime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_CaseOwner__c/fields/HP_LastAssignment__c.field-meta.xml
<CustomField>
    <fullName>HP_LastAssignment__c</fullName>
    <label>HP Last Assignment</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_CaseOwner__c/fields/ProfileName__c.field-meta.xml
<CustomField>
    <fullName>ProfileName__c</fullName>
    <label>Niveau/rôle</label>
    <length>225</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HP_EM050_HPCaseOwner.cls
/**
 * @description  : 
 * @author       : Antoine Latour
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   06-05-2021   Antoine Latour   Initial Version
**/

public inherited sharing class HP_EM050_HPCaseOwner {
    
    
    /**
    * @description 
    * @author Antoine Latour | 06-05-2021 
    * @param Set<Id> casesId 
    * @return Map<Id, List<HP_CaseOwner__c>> 
    **/
    public static Map<Id, List<HP_CaseOwner__c>> getCaseOwnerMap(Set<Id> casesId) {
        Map<Id, List<HP_CaseOwner__c>> result = new Map<Id, List<HP_CaseOwner__c>>();
        List<HP_CaseOwner__c> caseOwnerList = [SELECT ProfileName__c, Case__c, HP_ElapsedTime__c, HP_LastAssignment__c, HP_ActualOwner__c FROM HP_CaseOwner__c WHERE Case__c in : casesId];
        for(HP_CaseOwner__c co : caseOwnerList) {
            List<HP_CaseOwner__c> tempList;
            if(result.containsKey(co.Case__c)) {
                tempList = result.get(co.Case__c);
            }
            else {
                tempList = new List<HP_CaseOwner__c>();
            }
            tempList.add(co);
            result.put(co.Case__c, tempList);
        }

        return result;
    }
}