force-app/main/default/objects/HP_Community_User__c/HP_Community_User__c.object-meta.xml
<CustomObject>
    <description>Objet qui contiens les credentials des users de la community pour Happe</description>
    <label>HP Community User</label>
    <nameField>
        <label>HP Community User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP Community Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Community_User__c/fields/Activation_Count__c.field-meta.xml
<CustomField>
    <fullName>Activation_Count__c</fullName>
    <formula>TODAY() -  Activation_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activation Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Community_User__c/fields/Activation_Key__c.field-meta.xml
<CustomField>
    <fullName>Activation_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Activation Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HP_BAT034_ArchiveActivationKey.cls
/**
 * @description       : 
 * @author            : Hemdene Ben Hammouda
 * @group             : 
 * @last modified on  : 05-06-2022
 * @last modified by  : Hemdene Ben Hammouda
**/
global class HP_BAT034_ArchiveActivationKey implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable{
    public static final Integer BATCH_CHUNK_SIZE = 50;
    public static final String ACTIVATION_LIMIT = 'HP_Activation_Limit';

    @TestVisible
    public static Integer activationLimit {
        get{
            if(activationLimit == null){
                activationLimit = Integer.valueOf(HP_UTIL_MetadataManager.getConfigByKey(ACTIVATION_LIMIT));
            }
            return activationLimit;
        }
        private set;
    }

	global Database.QueryLocator start(Database.BatchableContext batchableContext){
        return Database.getQueryLocator(
            [   
                SELECT  Id, Activation_Key__c
                FROM    HP_Community_User__c
                WHERE   Activation_Key__c != NULL
                AND Activation_Count__c > :activationLimit 
            ]
        );
        
	}

	global static void launchNewScheduler(String schedule, String jobName){
		System.schedule(jobName, schedule, new HP_BAT034_ArchiveActivationKey());
	}

	global static void execute(SchedulableContext sc){
		execute();
	}

	global static void execute(){
		HP_BAT034_ArchiveActivationKey activationKeyBatch = new HP_BAT034_ArchiveActivationKey();
		Database.executeBatch(activationKeyBatch, BATCH_CHUNK_SIZE);
	}

    global void execute(Database.BatchableContext batchableContext, List<HP_Community_User__c> communityUserLoginList){
        System.debug('HP_BAT034_ArchiveActivationKey.execute | Method Start');
        if(communityUserLoginList.isEmpty()){
            return;
        }
        for(HP_Community_User__c communityUserLogin : communityUserLoginList){
            communityUserLogin.Activation_Key__c = null;
        }
        update communityUserLoginList;
        System.debug('HP_BAT034_ArchiveActivationKey.execute | Method Exit');
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('HP_BAT034_ArchiveActivationKey.finish');
	}

}