force-app/main/default/objects/HP_Community_User__c/HP_Community_User__c.object-meta.xml
<CustomObject>
    <description>Objet qui contiens les credentials des users de la community pour Happe</description>
    <label>HP Community User</label>
    <nameField>
        <label>HP Community User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP Community Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Community_User__c/fields/Reset_Password_Count__c.field-meta.xml
<CustomField>
    <fullName>Reset_Password_Count__c</fullName>
    <formula>FLOOR( MOD( ( NOW() - ( Reset_Password_Time__c + (1/48) ) ) * 24, 24 ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reset Password Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_Community_User__c/fields/Reset_Password_Key__c.field-meta.xml
<CustomField>
    <fullName>Reset_Password_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Reset Password Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HP_BAT035_ArchiveResetPasswordKey.cls
/**
 * @description       : 
 * @author            : Hemdene Ben Hammouda
 * @group             : 
 * @last modified on  : 05-06-2022
 * @last modified by  : Hemdene Ben Hammouda
**/
global class HP_BAT035_ArchiveResetPasswordKey implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable{
    public static final Integer BATCH_CHUNK_SIZE = 50;
    public static final String PASSWORD_LIMIT = 'HP_Password_Limit';

    @TestVisible
    public static Integer passwordLimit {
        get{
            if(passwordLimit == null){
                passwordLimit = Integer.valueOf(HP_UTIL_MetadataManager.getConfigByKey(PASSWORD_LIMIT));
            }
            return passwordLimit;
        }
        private set;
    }

	global Database.QueryLocator start(Database.BatchableContext batchableContext){
        return Database.getQueryLocator(
            [   
                SELECT  Id, Reset_Password_Key__c
                FROM    HP_Community_User__c
                WHERE   Reset_Password_Key__c != NULL
                AND Reset_Password_Count__c > :passwordLimit 
            ]
        );
        
	}

	global static void launchNewScheduler(String schedule, String jobName){
		System.schedule(jobName, schedule, new HP_BAT035_ArchiveResetPasswordKey());
	}

	global static void execute(SchedulableContext sc){
		execute();
	}

	global static void execute(){
		HP_BAT035_ArchiveResetPasswordKey passwordKeyBatch = new HP_BAT035_ArchiveResetPasswordKey();
		Database.executeBatch(passwordKeyBatch, BATCH_CHUNK_SIZE);
	}

    global void execute(Database.BatchableContext batchableContext, List<HP_Community_User__c> communityUserLoginList){
        System.debug('HP_BAT035_ArchiveResetPasswordKey.execute | Method Start');
        if(communityUserLoginList.isEmpty()){
            return;
        }
        for(HP_Community_User__c communityUserLogin : communityUserLoginList){
            communityUserLogin.Reset_Password_Key__c = null;
        }
        update communityUserLoginList;
        System.debug('HP_BAT035_ArchiveResetPasswordKey.execute | Method Exit');
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('HP_BAT035_ArchiveResetPasswordKey.finish');
	}
}