force-app/main/default/objects/HP_Community_User__c/HP_Community_User__c.object-meta.xml
<CustomObject>
    <description>Objet qui contiens les credentials des users de la community pour Happe</description>
    <label>HP Community User</label>
    <nameField>
        <label>HP Community User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP Community Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_Community_User__c/fields/Reset_Password_Key__c.field-meta.xml
<CustomField>
    <fullName>Reset_Password_Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Reset Password Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Community_User__c/fields/Reset_Password_Time__c.field-meta.xml
<CustomField>
    <fullName>Reset_Password_Time__c</fullName>
    <label>Reset Password Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_Community_User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HP_BAT035_ArchiveResetPasswordKey_TEST.cls
/**
 * @description       : 
 * @author            : Hemdene Ben Hammouda
 * @group             : 
 * @last modified on  : 05-09-2022
 * @last modified by  : Hemdene Ben Hammouda
**/
@isTest 
public with sharing class HP_BAT035_ArchiveResetPasswordKey_TEST {
    @TestSetup
    static void makeData(){
        HP_Community_User__c myCommunityUser = new HP_Community_User__c(Reset_Password_Key__c = 'jkaehfkjaepfkjaemf',
                                                                        Reset_Password_Time__c = System.now().addHours(-6),
                                                                        Username__c = 'myEmail@email.com');
        insert myCommunityUser;
    }

    @isTest
    public static void executeTest(){
        Test.startTest();
        HP_BAT035_ArchiveResetPasswordKey.passwordLimit = 4;
        HP_BAT035_ArchiveResetPasswordKey.execute();
        Test.stopTest();
        HP_Community_User__c commUser = [SELECT Id, Reset_Password_Key__c FROM HP_Community_User__c LIMIT 1];
        System.assert(commUser.Reset_Password_Key__c == null, 'Reset Password effacée');
    }

    @isTest 
    public static void testSchedule(){
        Test.startTest();
        final String jobName = 'HP_BAT035_ArchiveResetPasswordKey'+System.Math.random()*1000;
        final String cronExp = '0 30 9 ? * * *';
        HP_BAT035_ArchiveResetPasswordKey.launchNewScheduler(cronExp,jobName);
        Test.stopTest();
    }
}