force-app/main/default/objects/SM_HarmonicaCompetence__c/SM_HarmonicaCompetence__c.object-meta.xml
<CustomObject>
    <description>Cet objet a été crée  pour filtrer les compétences par site pour le cadre du routage par compétendes.</description>
    <label>Compétence par site</label>
    <nameField>
        <label>Compétence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compétences par site</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_HarmonicaCompetence__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Le champs Site est un champs lockup vers l&apos;ojet compétence , ce champs est utilisé pour lier les compétences a chaque Site utilisé dans le cadre du routage par compétences .</description>
    <label>Site</label>
    <referenceTo>SM_HarmonicaSite__c</referenceTo>
    <relationshipLabel>Compétences par site</relationshipLabel>
    <relationshipName>competences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SM_HarmonicaSite__c/SM_HarmonicaSite__c.object-meta.xml
<CustomObject>
    <description>Cet objet a été crée  pour filtrer les compétences par site , afin d’assurer le bon routage des cases.</description>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SM_AP93_ServiceRessourceSklHandler.cls
public class SM_AP93_ServiceRessourceSklHandler {

    public static void checkSkillValidForUserSite(List<ServiceResourceSkill> newList){
        // getUser and his Site
            Id userId = UserInfo.getUserId();
            User usr = [ select id , site__c from User where Id =: userId ];
            System.debug('user Site: '+ usr.Site__c);
            String siteName =  usr.Site__c ; 
        if(Test.isRunningTest()){
            siteName = 'Equipe 1 Fes DSPC DGP';
        }
        System.debug('siteName : ' + siteName);
            //get site and skills related to it
             List<Id> skillIds = new List<Id>();
            List<SM_HarmonicaSite__c> harmonicaSite = [select id,Name,(select Name from Competences__r) from SM_HarmonicaSite__c where Name =: siteName limit 1];
        	
            System.debug('list empty:' + harmonicaSite.isEmpty());
            //List<ServiceResourceSkill> ServiceResourceSkills =   [Select id  from ServiceResourceSkill where id in :Trigger.new];
            for(ServiceResourceSkill serviceResourceSkill : newList) {
                skillIds.add(serviceResourceSkill.SkillId);
            }
            List<Skill> skills = [Select id,MasterLabel from Skill where id in :skillIds ];
            for(ServiceResourceSkill srs : newList){ 
                // TODO: get skill name from id (we got list of skills)  
                String SkillName = '';
                for(Skill skill : skills){
                    if(skill.Id == srs.SkillId){
                         SkillName = skill.MasterLabel;
                    }
                }
                // test if skill is eligible for the site
                SM_HarmonicaSite__c Hsite = null; 
              
                   if(!harmonicaSite.isEmpty() &&  skillName != '' ){
                        
                    Hsite = harmonicaSite[0];
                    Set<String> CompetenceEligibles = new Set<String>();
                    for(SM_HarmonicaCompetence__c Hcomp : Hsite.competences__r){
                        CompetenceEligibles.add(Hcomp.Name);
                    } 
                    //String skillName = skillMatrix.get(srs.SKill.MasterLabel);
                    System.debug(' Skill: '+ skillName );
                    if(!CompetenceEligibles.contains( skillName)){
                        System.debug('skill not elligible !!');
                        srs.addError(System.label.Comp_tence_non_ligible);
                    } else {System.debug('skill elligible :)');}
                } else {
                    System.debug('empty !'); 
                } 
                
                
                
            }  
    }
}