force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/RGPD_PurgeDonneesIdentification__e.object-meta.xml
<CustomObject>
    <label>RGPD_PurgeDonneesIdentification</label>
    <pluralLabel>RGPD_PurgeDonneesIdentifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/eventId__c.field-meta.xml
<CustomField>
    <fullName>eventId__c</fullName>
    <description>c&apos;est l&apos;identifiant de l&apos;événement du Bus Kinesis Stream Purge</description>
    <label>eventId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/eventSubType__c.field-meta.xml
<CustomField>
    <fullName>eventSubType__c</fullName>
    <description>correspond au sous type de l&apos;événement du stream purge (cf. Politique des DCP partie finalités )</description>
    <label>eventSubType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/eventType__c.field-meta.xml
<CustomField>
    <fullName>eventType__c</fullName>
    <description>Correspond au type de l&apos;événement du stream purge pouvant contenir les valeurs suivantes : PurgeDonneesFines, PurgeDonneesIdentification, PurgeConsoMensEtFacturation</description>
    <label>eventType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idContrat__c.field-meta.xml
<CustomField>
    <fullName>idContrat__c</fullName>
    <description>correspond à l&apos;Id Contrat du client auquel s&apos;applique l&apos;événement.</description>
    <label>idContrat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idDemande__c.field-meta.xml
<CustomField>
    <fullName>idDemande__c</fullName>
    <description>correspond à l&apos;Id Demande  qui est l&apos;identifiant pour notifier le stream purge que l&apos;action est réalisée</description>
    <label>idDemande</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idPortefeuilleContrat__c.field-meta.xml
<CustomField>
    <fullName>idPortefeuilleContrat__c</fullName>
    <label>idPortefeuilleContrat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idTiers__c.field-meta.xml
<CustomField>
    <fullName>idTiers__c</fullName>
    <description>correspond à l&apos;Id tiers du client auquel s&apos;applique l&apos;événement.</description>
    <label>idTiers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/noBp__c.field-meta.xml
<CustomField>
    <fullName>noBp__c</fullName>
    <description>correspond numéro de BP du client auquel s&apos;applique l&apos;événement.</description>
    <label>noBp</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/noContrat__c.field-meta.xml
<CustomField>
    <fullName>noContrat__c</fullName>
    <description>correspond au numéro de Contrat du client auquel s&apos;applique l&apos;événement.</description>
    <label>noContrat</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/noPortefeuilleContrat__c.field-meta.xml
<CustomField>
    <fullName>noPortefeuilleContrat__c</fullName>
    <label>noPortefeuilleContrat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HP_RGPD_PurgeDonneesInvocable.cls
/**
 * @description       : 
 * @author            : Hemdene Ben Hammouda
 * @group             : 
 * @last modified on  : 03-08-2022
 * @last modified by  : Hemdene Ben Hammouda
**/
public with sharing class HP_RGPD_PurgeDonneesInvocable {
    @InvocableMethod
    public static void sendConfirmationPurge(List<Requests> requestList){
        System.debug('HP_RGPD_PurgeDonneesInvocable.sendConfirmationPurge() | Method Start');
        if(!requestList.isEmpty()){
            RGPD_PurgeDonneesIdentification__e eventObject = requestList[0].eventObject;
            try {
                String messageBody =  convertEventToMessageBody(eventObject);
                sendPurgeConfirmation(messageBody);
            } catch (Exception ex) {
                System.debug('HP_RGPD_PurgeDonneesInvocable.sendConfirmationPurge() | Exception : '+ex.getMessage());
            }   
        }
        System.debug('HP_RGPD_PurgeDonneesInvocable.sendConfirmationPurge() | Method Exit');
    }

    public static String convertEventToMessageBody(RGPD_PurgeDonneesIdentification__e eventObject){
        Map<String, Object> cleObjet = new Map<String, Object>();
        cleObjet.put('idTiers', eventObject.idTiers__c);
        cleObjet.put('noPortefeuilleContrat', eventObject.noPortefeuilleContrat__c);
        cleObjet.put('noContrat', eventObject.noContrat__c);
        cleObjet.put('idPortefeuilleContrat', eventObject.idPortefeuilleContrat__c);
        cleObjet.put('noBp', eventObject.noBp__c);
        cleObjet.put('idContrat', eventObject.idContrat__c);
        Map<String, Object> dataInside = new Map<String, Object>();
        dataInside.put('idDemande', eventObject.idDemande__c);
        dataInside.put('cleObjet', cleObjet);
        Map<String, Object> data = new Map<String, Object>();
        data.put('eventVersion', '1.0');
        data.put('eventSource', 'HAPPE');
        data.put('eventTime', Datetime.now().format('yyyy-MM-dd hh:mm:ss'));
        data.put('eventType', eventObject.eventType__c+'OK');
        data.put('eventSubType', eventObject.eventSubType__c);
        data.put('eventId', eventObject.id);
        data.put('parentEventId', eventObject.eventId__c);
        data.put('data', dataInside);
        Map<String, Object> bodyObj = new Map<String, Object>();
        bodyObj.put('data', data);
        bodyObj.put('partition-key', '1');
        return JSON.serialize(bodyObj);
    } 

    @future(callout = true)
    public static void sendPurgeConfirmation(String messageBody){
        HP_UTIL_HTTPUtils.calloutPut(HP_Constantes.STREAM_PURGE_API_SERVICE, messageBody, null);
        
    } 

    public class Requests {
        @InvocableVariable(label='eventObject' description='La platform event object')
        public RGPD_PurgeDonneesIdentification__e eventObject;
    }
}