force-app/main/default/objects/HP_LOG_CALLOUT__b/HP_LOG_CALLOUT__b.object-meta.xml
<CustomObject>
    <label>HP LOG CALLOUT</label>
    <pluralLabel>HP LOG CALLOUT</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Body_Request__c.field-meta.xml
<CustomField>
    <fullName>Body_Request__c</fullName>
    <label>Body_Request</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Body_Response__c.field-meta.xml
<CustomField>
    <fullName>Body_Response__c</fullName>
    <label>Body_Response</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Call_Time_Execution__c.field-meta.xml
<CustomField>
    <fullName>Call_Time_Execution__c</fullName>
    <label>Call Time Execution</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Key_Row__c.field-meta.xml
<CustomField>
    <fullName>Key_Row__c</fullName>
    <label>Key Row</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User_Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/HP_LOG_WS__c.object-meta.xml
<CustomObject>
    <label>HP LOG WS</label>
    <nameField>
        <displayFormat>LOGWS-{000000}</displayFormat>
        <label>HP LOG WS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HP LOG WS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_LOG_WS__c/fields/Body_Request__c.field-meta.xml
<CustomField>
    <fullName>Body_Request__c</fullName>
    <label>Body_Request</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/fields/Body_Response__c.field-meta.xml
<CustomField>
    <fullName>Body_Response__c</fullName>
    <label>Body_Response</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/fields/Call_Time_Execution__c.field-meta.xml
<CustomField>
    <fullName>Call_Time_Execution__c</fullName>
    <label>Call Time Execution</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HP_UTIL_LogConsoleControllerTest.cls
/**
 * @File Name          : HP_UTIL_LogConsoleControllerTest.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 24/04/2020 à 11:20:47
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    24/04/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
@IsTest
public class HP_UTIL_LogConsoleControllerTest {
    @testSetup 
    static void initData() {
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){    
            HP_LOG_WS__c log = new HP_LOG_WS__c();

            log.Endpoint__c =  'xx';
            log.Body_Request__c = 'xx';
            
            log.Status__c = 200;
            log.Body_Response__c = 'xx';          
            log.User_Id__c = UserInfo.getUserId();            
            log.Date__c = DateTime.Now();
            log.Call_Time_Execution__c = 15;
            log.Transaction_Id__c = 'xxx';
            insert log;      
        }
		
    }
 	@isTest
	static void logSearchTest() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            HP_LOG_CALLOUT__b pb = new HP_LOG_CALLOUT__b();
            pb.Body_Request__c = 'xx';
            pb.Endpoint__c =  'xx';
            pb.User_Id__c = UserInfo.getUserId();
            pb.Method__c = 'xx';
            pb.Date__c = DateTime.Now();
            pb.Call_Time_Execution__c = 15;
            pb.Key_Row__c = 'K022';
            pb.Transaction_Id__c = 'xxx';
            Test.startTest();
            HP_UTIL_LogConsoleController.LogConsoleWrapper logW = new HP_UTIL_LogConsoleController.LogConsoleWrapper(pb);
            logW.compareTo(logW);
            List<HP_UTIL_LogConsoleController.LogConsoleWrapper> logList = HP_UTIL_LogConsoleController.loadLog(DateTime.Now().addHours(-1), DateTime.Now().addHours(1),
                                                null, null, null, null, 'INOUT', 'xxx');
            Test.stopTest();
            System.assertEquals(1, logList.size(), 'List de log doit avoir nu seul element');
        }
       
    }
}