force-app/main/default/objects/HP_LOG_CALLOUT__b/HP_LOG_CALLOUT__b.object-meta.xml
<CustomObject>
    <label>HP LOG CALLOUT</label>
    <pluralLabel>HP LOG CALLOUT</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Key_Row__c.field-meta.xml
<CustomField>
    <fullName>Key_Row__c</fullName>
    <label>Key Row</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User_Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Parameters__c/HP_Parameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>HP_Parameters</label>
</CustomObject>

force-app/main/default/objects/HP_Parameters__c/fields/Cycle_Purge_Log__c.field-meta.xml
<CustomField>
    <fullName>Cycle_Purge_Log__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Cycle Purge Log</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HP_BAT008_NettoyageLogCallOut.cls
/**
 * @File Name          : HP_BAT008_NettoyageLogCallOut.cls
 * @Description        : 
 * @Author             : Mouhamadoune Coulibaly
 * @Group              : 
 * @Last Modified By   : Mouhamadoune Coulibaly
 * @Last Modified On   : 31/03/2020 à 13:29:31
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    31/03/2020   Mouhamadoune Coulibaly     Initial Version
**/
global  class HP_BAT008_NettoyageLogCallOut implements Database.batchable<HP_LOG_CALLOUT__b>, Database.RaisesPlatformEvents {
    DateTime nowDateTime = System.now();
    HP_Parameters__c param = [Select id,Cycle_Purge_Log__c from HP_Parameters__c];
    final Integer cyclepurge = (Integer)param.Cycle_Purge_Log__c;
    final DateTime periode = nowDateTime.addDays(- cyclepurge);
    List<HP_LOG_CALLOUT__b> listToDelete = null;
       
    global HP_BAT008_NettoyageLogCallOut() {
        listToDelete =[select Status__c, Date__c, Key_Row__c,User_Id__c from HP_LOG_CALLOUT__b where Date__c <= :periode LIMIT 40000];
    }
   
    global List<HP_LOG_CALLOUT__b> start(Database.batchableContext info){
        return  listToDelete;
    }    
    global void execute(Database.batchableContext info, List<HP_LOG_CALLOUT__b> scope){
        Database.deleteImmediate(scope);

    }    
    global void finish(Database.batchableContext info){  
        List<HP_LOG_CALLOUT__b> newListToDelete =[select Id from HP_LOG_CALLOUT__b where Date__c <= :periode LIMIT 1];
        if(newListToDelete.size() > 0) {
            Database.executeBatch(new HP_BAT008_NettoyageLogCallOut());
        }
    }
 }