force-app/main/default/objects/HP_LOG_CALLOUT__b/HP_LOG_CALLOUT__b.object-meta.xml
<CustomObject>
    <label>HP LOG CALLOUT</label>
    <pluralLabel>HP LOG CALLOUT</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Body_Request__c.field-meta.xml
<CustomField>
    <fullName>Body_Request__c</fullName>
    <label>Body_Request</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Call_Time_Execution__c.field-meta.xml
<CustomField>
    <fullName>Call_Time_Execution__c</fullName>
    <label>Call Time Execution</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_CALLOUT__b/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User_Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/HP_LOG_WS__c.object-meta.xml
<CustomObject>
    <label>HP LOG WS</label>
    <nameField>
        <displayFormat>LOGWS-{000000}</displayFormat>
        <label>HP LOG WS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HP LOG WS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_LOG_WS__c/fields/Body_Request__c.field-meta.xml
<CustomField>
    <fullName>Body_Request__c</fullName>
    <label>Body_Request</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/fields/Call_Time_Execution__c.field-meta.xml
<CustomField>
    <fullName>Call_Time_Execution__c</fullName>
    <label>Call Time Execution</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HP_LOG_WS__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_TECH_LOG__c/HP_TECH_LOG__c.object-meta.xml
<CustomObject>
    <label>HP Log Tech</label>
    <nameField>
        <displayFormat>HPLOG-{000000}</displayFormat>
        <label>HP TECH LOG Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HP Log Tech</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_TECH_LOG__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_TECH_LOG__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Projet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Happe</fullName>
            </value>
            <value>
                <fullName>Smile</fullName>
            </value>
            <value>
                <fullName>Non identifié</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_TECH_LOG__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nouveau</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Traité</fullName>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_UTIL_ErrorEmailNotificationTEST.cls
@isTest
public class HP_UTIL_ErrorEmailNotificationTEST {
	@testSetup static void dataSetup(){
		
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){
            HP_LOG_WS__c pb = new HP_LOG_WS__c();
                pb.Body_Request__c = 'xx';
                pb.Endpoint__c =  'xx';
                pb.User_Id__c = UserInfo.getUserId();
                pb.Method__c = 'xx';
                pb.Date__c = DateTime.Now();
                pb.Call_Time_Execution__c = 15;
            	pb.Status__c = 401;
                pb.Transaction_Id__c = 'xxx';
            insert pb;
           
            HP_TECH_LOG__c tech = new HP_TECH_LOG__c();
                tech.EmailSubject__c = 'xx';
                tech.Phase__c = 'xx';
                tech.Project__c = 'Happe';
                tech.Status__c = 'Nouveau';
                tech.Type__c = 'xx';
    
            insert tech;
        }
    }

    @isTest static void loadEmailContent_TEST(){
    
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Test.startTest();
            new HP_UTIL_ErrorEmailNotification();
    
            User us = [select Id, Name, Profile.Name from user where id = :UserInfo.getUserId()];
            new HP_UTIL_ErrorEmailNotification.LoginHistoryWrapper (new LoginHistory(), us);
            new HP_UTIL_ErrorEmailNotification.InfoNotifactionWrapper (new HP_LOG_CALLOUT__b(), '');
    
            Test.stopTest();
        }
    }
    
    @isTest static void scheduleEmailContent_TEST(){
    
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Test.startTest();
            system.schedule('HP_SCH008_EmailErrorNotificationTest','0 0 23 * * ?', new HP_SCH008_EmailErrorNotification());
            Test.stopTest();
        }
    }
}