force-app/main/default/objects/VI_DocuSignTokens__c/VI_DocuSignTokens__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains keys to decrypt the Mandat or CPV envelope&apos;s id during the DocuSign redirection</description>
    <label>Token DocuSign</label>
</CustomObject>

force-app/main/default/objects/VI_DocuSignTokens__c/fields/VI_Value__c.field-meta.xml
<CustomField>
    <fullName>VI_Value__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VI_BAT003_SuppressionDocuSignTokens_Test.cls
/*
*@Auhtor: Clément Bouquin
*@Description: Classe de test de VI_BAT003_SuppressionDocuSignTokens
*@CreatedDate: 07/05/2021
*/

@isTest
public class VI_BAT003_SuppressionDocuSignTokens_Test {

    @testSetup
    static void testSetup1(){
        VI_DocuSignTokens__c DocuSignTokens = new VI_DocuSignTokens__c(Name=string.ValueOf(system.now()), VI_Value__c='Test');
        insert DocuSignTokens;
    }
    
	 @isTest
    static void testBatch(){
		Test.startTest();
        VI_BAT003_SuppressionDocuSignTokens.execute('=today');
        Test.stopTest();
	}
}