force-app/main/default/objects/VI_DocuSignTokens__c/VI_DocuSignTokens__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains keys to decrypt the Mandat or CPV envelope&apos;s id during the DocuSign redirection</description>
    <label>Token DocuSign</label>
</CustomObject>

force-app/main/default/objects/VI_DocuSignTokens__c/fields/VI_Value__c.field-meta.xml
<CustomField>
    <fullName>VI_Value__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/VI_BAT003_SuppressionDocuSignTokens.cls
/*
*@Author: Clément Bouquin
*@Description: Batch qui relance chaque jour la suppression des DocuSignTokens agés de plus de 30 jours
*@CreatedDate: 06/05/2021
*@LastModified: 07/05/2021
*/

global class VI_BAT003_SuppressionDocuSignTokens implements Database.Batchable<sObject>{
    
    // Query select all VI_DocuSignTokens__c older than 30 days
    global final String query = 'SELECT ID, Name, VI_Value__c, CreatedDate FROM VI_DocuSignTokens__c WHERE CreatedDate ';
    global String numberOfDay = '< LAST_N_DAYS:30';
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('VI_BAT003_SuppressionDocuSignTokens starting...');
        return Database.getQueryLocator(query + numberOfDay);
    }
    
    public static void execute(String numberOfDay){
        VI_BAT003_SuppressionDocuSignTokens relanceBatch = new VI_BAT003_SuppressionDocuSignTokens();
        relanceBatch.numberOfDay = numberOfDay;
        Database.executeBatch(relanceBatch,200); 
    }
    
	global void execute(Database.BatchableContext bc, List<VI_DocuSignTokens__c> oldDocuSignTokens){
		// Delete all VI_DocuSignTokens__c older than 30 days
        delete oldDocuSignTokens;
    }
        
    global void finish(Database.BatchableContext bc){
        System.debug('VI_BAT003_SuppressionDocuSignTokens ending...');
    }
}