force-app/main/default/objects/HP_OPSEventLog__c/HP_OPSEventLog__c.object-meta.xml
<CustomObject>
    <label>HP OPSEventLog</label>
    <nameField>
        <label>HP OPSEventLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP OPSEventLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_TECH_LOG__c/HP_TECH_LOG__c.object-meta.xml
<CustomObject>
    <label>HP Log Tech</label>
    <nameField>
        <displayFormat>HPLOG-{000000}</displayFormat>
        <label>HP TECH LOG Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HP Log Tech</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/Prestation_distributeur__c.object-meta.xml
<CustomObject>
    <description>Objet qui contient les informations concernant la prestation de service du client</description>
    <label>Prestation distributeur</label>
    <nameField>
        <label>Prestation distributeur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestations distributeurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prestation_distributeur__c/fields/Civilite_interlocuteur_intervention__c.field-meta.xml
<CustomField>
    <fullName>Civilite_interlocuteur_intervention__c</fullName>
    <description>@description : champ civilité interlocuteur intervention
@projet: smile</description>
    <label>Civilité interlocuteur intervention</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MR</fullName>
            </value>
            <value>
                <fullName>MLLE</fullName>
            </value>
            <value>
                <fullName>MME</fullName>
            </value>
            <value>
                <fullName>MLLES</fullName>
            </value>
            <value>
                <fullName>MME et MLLE</fullName>
            </value>
            <value>
                <fullName>MMES</fullName>
            </value>
            <value>
                <fullName>AUTRE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Creneau__c.field-meta.xml
<CustomField>
    <fullName>Creneau__c</fullName>
    <label>Créneau</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Journée</fullName>
            </value>
            <value>
                <fullName>Début de matinée</fullName>
            </value>
            <value>
                <fullName>Fin de matinée</fullName>
            </value>
            <value>
                <fullName>Midi</fullName>
            </value>
            <value>
                <fullName>Début d&apos;après midi</fullName>
            </value>
            <value>
                <fullName>Fin d&apos;après midi</fullName>
            </value>
            <value>
                <fullName>Matin</fullName>
            </value>
            <value>
                <fullName>Fin d’après midi</fullName>
            </value>
            <value>
                <fullName>Fin de journée</fullName>
            </value>
            <value>
                <fullName>Début de soirée</fullName>
            </value>
            <value>
                <fullName>Milieu de soirée</fullName>
            </value>
            <value>
                <fullName>Soir</fullName>
            </value>
            <value>
                <fullName>Fin de soirée</fullName>
            </value>
            <value>
                <fullName>Après midi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Date_de_prestation__c.field-meta.xml
<CustomField>
    <fullName>Date_de_prestation__c</fullName>
    <label>Date de prestation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Date_statut_prestation__c.field-meta.xml
<CustomField>
    <fullName>Date_statut_prestation__c</fullName>
    <description>@description: ce champ prend le Date statut prestation
@projet: smile</description>
    <label>Date statut prestation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Nom_contact_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Nom_contact_d_intervention__c</fullName>
    <description>Nom du contact d&apos;intervention à alimenter au retour du WS ou lors des flux X12 et SDEM</description>
    <label>Nom contact d&apos;intervention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_affaire_distributeur__c.field-meta.xml
<CustomField>
    <fullName>Numero_affaire_distributeur__c</fullName>
    <label>Numéro d&apos;affaire distributeur</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Numero_dernier_jalon__c.field-meta.xml
<CustomField>
    <fullName>Numero_dernier_jalon__c</fullName>
    <description>@description: ce champ comporte le Numéro dernier jalon
@projet: smile</description>
    <label>Numéro dernier jalon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Prenom_contact_d_intervention__c.field-meta.xml
<CustomField>
    <fullName>Prenom_contact_d_intervention__c</fullName>
    <description>Prenom du contact intervention alimenté au retour des flux distributeur ou des flux X12 et SDEM</description>
    <label>Prenom contact d&apos;intervention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Secteur_activite__c.field-meta.xml
<CustomField>
    <fullName>Secteur_activite__c</fullName>
    <label>Secteur d&apos;activité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elec</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A initier</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Statut_dernier_jalon__c.field-meta.xml
<CustomField>
    <fullName>Statut_dernier_jalon__c</fullName>
    <description>@description: ce champ prend le Statut dernier jalon
@projet: smile</description>
    <label>Statut dernier jalon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prestation_distributeur__c/fields/Telephone_intervention__c.field-meta.xml
<CustomField>
    <fullName>Telephone_intervention__c</fullName>
    <description>Téléphone du contact d&apos;intervention mis à jour au retour des flux distributeur ou X12 ou SDEM</description>
    <label>Telephone intervention</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/HP_SM053_UpdateOPS.cls
/**
 * @description  : 
 * @author       : Antoine Latour
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   03-02-2021   Antoine Latour   Initial Version
**/

global class HP_SM053_UpdateOPS  implements CMN_OPSProcessingInterface {
                                       
                            
    public void processing(List<CMN_OPSinfo> OPSinfos){
        List < Prestation_distributeur__c > prestaDistribToUpdate = new List < Prestation_distributeur__c > ();
        List < HP_OpsEventLog__c > opsKO = new List < HP_OpsEventLog__c > ();
        updatePrestaDistribFields(OPSinfos, prestaDistribToUpdate, opsKO);
            
        if (!prestaDistribToUpdate.isEmpty() || !opsKO.isEmpty()) {
            Database.SaveResult[] srList  = HP_EM007_PrestationDistributeurManager.updatePrestationsDistributeur(prestaDistribToUpdate);                                                       
            try {
                traceLog(prestaDistribToUpdate,srList,opsKO);
                HP_SM033_PrestationFluxUpdate.updateOPSAndCase(prestaDistribToUpdate,OPSinfos);
            }
            catch(Exception e) {
                HP_TECH_LOG__c hpLogTech = HP_EM031_HPLogTech.buildHPLogTechFromGenericApexError('Happe', 'Nouveau',
                'HP_SM053_UpdateOPS', 'Mise à jour des Prestation Distributeur', e.getMessage());
                insert hpLogTech;
            }
        }  
    }

    public static void updatePrestaDistribFields(List <CMN_OPSinfo> ops, List < Prestation_distributeur__c > prestaDistribToUpdate,List < HP_OpsEventLog__c > opsKO) {
        Map < String, CMN_OPSinfo > ids_OPS = new Map < String, CMN_OPSinfo> ();
        for (CMN_OPSinfo opstemp: ops) {
            ids_OPS.put(opstemp.idAffaire, opstemp);
        }
  
        List < Prestation_distributeur__c > accs = HP_EM007_PrestationDistributeurManager.loadPrestationsDistributeurFromListIdAffaire(ids_OPS.keySet());
        
        if (accs == null || accs.isEmpty()) {
            return;
        }

        List<String> constantes = new List<String>{'HP_OPS_CIVILITE_GAZ', 'HP_OPS_CRENEAUX', 'HP_OPS_STATUT_ELEC', 'HP_OPS_STATUT_GAZ'};
        Map<String, Map<object,object>> mapConstantes = HP_UTIL_MetadataManager.getCodification(constantes);

        for (Prestation_distributeur__c acc: accs) {
            CMN_OPSinfo opsInfo = ids_OPS.get(acc.Numero_affaire_distributeur__c);
            try{
                updateFields(opsInfo, acc, prestaDistribToUpdate, mapConstantes);
            } catch (Exception e) {
                HP_OpsEventLog__c opsInfoKODetails = HP_EM046_HPOPSEventLog.fillOPSKOLog(acc,opsInfo,e);
                opsKO.add(opsInfoKODetails) ; 
            }
        }
    }

    private  static void traceLog(List<Prestation_distributeur__c> prestaDistribToUpdate ,Database.SaveResult[]  srList,List<HP_OpsEventLog__c> opsKO){
        List<HP_OpsEventLog__c> listOpsTraceLog = new List<HP_OpsEventLog__c>() ;
            
        if(srList != null){ 
            for( integer i = 0 ; i< prestaDistribToUpdate.size(); i++){
                Database.SaveResult sr = srList[i];
                Prestation_distributeur__c presta = prestaDistribToUpdate[i];
                HP_OPSEventLog__c log = HP_EM046_HPOPSEventLog.createHPOpsEventLog(sr, presta);                 
                listOpsTraceLog.add(log) ;
            }
        }

        if(opsKO.size() > 0 ){ 
            listOpsTraceLog.addAll(opsKO);
        }

        HP_EM046_HPOPSEventLog.updateOpsLog(listOpsTraceLog);   
    }

    public static void updateFields(CMN_OPSinfo opsInfo, Prestation_distributeur__c acc, List < Prestation_distributeur__c > prestaDistribToUpdate, Map<String, Map<object,object>> mapConstantes) {     
        
        updateOPSCommonFields(opsInfo, acc, mapConstantes) ;
        
        boolean missingEnergy = String.isBlank(opsInfo.typeEnergie) || String.isBlank(acc.Secteur_activite__c);
        boolean isElec = !missingEnergy && opsInfo.typeEnergie.equals(acc.Secteur_activite__c) && acc.Secteur_activite__c.equals('Elec');
        boolean isGaz = !missingEnergy && opsInfo.typeEnergie.equals(acc.Secteur_activite__c) && acc.Secteur_activite__c.equals('Gaz');
        boolean isNumDernierJalonValid = opsInfo.numDernierJalon != null && ((acc.Numero_dernier_jalon__c !=null && opsInfo.numDernierJalon > acc.Numero_dernier_jalon__c) || acc.Numero_dernier_jalon__c== null);
        
        if (isElec &&  isNumDernierJalonValid) {
            updateOPSElecFields(opsInfo, acc, mapConstantes);
            prestaDistribToUpdate.add(acc);
        }
        else if (isGaz) {
            updateOPSGazFields(opsInfo, acc, mapConstantes) ;
            prestaDistribToUpdate.add(acc);
        }
        else {
            throw new IoException('Cas non traité');  
        }
              
    }

    static void  updateOPSElecFields(CMN_OPSinfo opsInfo , Prestation_distributeur__c acc, Map<String, Map<object,object>> mapConstantes){
        Map<Object, Object> statutElec = mapConstantes.get('HP_OPS_STATUT_ELEC');

        acc.Civilite_interlocuteur_intervention__c = opsInfo.civiliteIntervenant;
        acc.Date_de_prestation__c = String.isBlank(opsInfo.datePrestation) ? null : Date.valueOf(opsInfo.datePrestation.substring(0, 10));
        acc.Numero_dernier_jalon__c = opsInfo.numDernierJalon;
        acc.Statut__c = String.isBlank(opsInfo.statutPrestation) ? null : (String) statutElec.get(opsInfo.statutPrestation);
        acc.Statut_dernier_jalon__c = opsInfo.statutDernierJalon;   
        acc.Date_statut_prestation__c = Date.today();
    }
    
    static void  updateOPSGazFields(CMN_OPSinfo opsInfo , Prestation_distributeur__c acc, Map<String, Map<object,object>> mapConstantes){
        Map<Object, Object> mapCiviliteGaz = mapConstantes.get('HP_OPS_CIVILITE_GAZ');
        Map<Object, Object> statutGaz = mapConstantes.get('HP_OPS_STATUT_GAZ');

        acc.Civilite_interlocuteur_intervention__c =  String.isBlank(opsInfo.civiliteIntervenant) ? null : (String) mapCiviliteGaz.get(String.valueOf(opsInfo.civiliteIntervenant)) == null ? 'AUTRE' : (String) mapCiviliteGaz.get(String.valueOf(opsInfo.civiliteIntervenant));
        acc.Date_de_prestation__c = String.isBlank(opsInfo.datePrestation) ? null : Date.valueOf(opsInfo.datePrestation.substring(0, 10));
        acc.Numero_dernier_jalon__c = opsInfo.numDernierJalon;
        acc.Statut__c =  String.isBlank(opsInfo.statutPrestation) ? null :   (String) statutGaz.get(opsInfo.statutPrestation);
        acc.Statut_dernier_jalon__c = opsInfo.statutDernierJalon;
        acc.Date_statut_prestation__c = Date.today();
    }
    
    static void  updateOPSCommonFields(CMN_OPSinfo opsInfo , Prestation_distributeur__c acc, Map<String, Map<Object, Object>> mapConstantes){
        acc.Creneau__c =  String.isBlank(opsInfo.creneau) ? null :  (String) mapConstantes.get('HP_OPS_CRENEAUX').get(opsInfo.creneau);
        acc.Nom_contact_d_intervention__c = opsInfo.nomIntervenant;
        acc.Prenom_contact_d_intervention__c = opsInfo.prenomIntervenant;
        acc.Telephone_intervention__c = opsInfo.telephoneIntervenant;
    }

    public class IOException extends Exception {	
    }
}