force-app/main/default/objects/MP_Xdata_credentials__c/MP_Xdata_credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MP_Xdata_credentials</label>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ChoixMoyenPaiement__c.field-meta.xml
<CustomField>
    <fullName>VI_ChoixMoyenPaiement__c</fullName>
    <description>Champ étape saisie moyens de paiement pour le choix du moyen de paiement</description>
    <label>Choix moyen de paiement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prélèvement automatique</fullName>
                <default>true</default>
                <label>Prélèvement automatique</label>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ChoixParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_ChoixParcours__c</fullName>
    <description>Le prospect au téléphone effectue soit un changement de fournisseur (même adresse cible) soit un emménagement (nouvelle adresse)</description>
    <label>Choix de la situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
                <label>Emménager dans un nouveau logement</label>
            </value>
            <value>
                <fullName>CHF</fullName>
                <label>Changer de fournisseur pour Engie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Contact__c.field-meta.xml
<CustomField>
    <fullName>VI_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contient le contact utilisé dans ce parcours</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parcours</relationshipLabel>
    <relationshipName>Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Date_envoi_email__c.field-meta.xml
<CustomField>
    <fullName>VI_Date_envoi_email__c</fullName>
    <label>Date d&apos;envoi d&apos;email</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Email_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Email_CPV__c</fullName>
    <description>Champ email supplémentaire en cas de volonté du client de donner une adresse email différente pour l&apos;envoi des CPV</description>
    <label>Email CPV</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_EmailEnvoye__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailEnvoye__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Champ coché lorsque l&apos;email envoyé au client est envoyé</description>
    <label>Email envoyé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IBANEnSelfCare__c.field-meta.xml
<CustomField>
    <fullName>VI_IBANEnSelfCare__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox indiquant si le client souhaite renseigner son IBAN en SelfCare</description>
    <label>IBAN en SelfCare</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Id_coordonnees_bancaires__c.field-meta.xml
<CustomField>
    <fullName>VI_Id_coordonnees_bancaires__c</fullName>
    <label>ID coordonnées bancaires</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ID_Mandat__c.field-meta.xml
<CustomField>
    <fullName>VI_ID_Mandat__c</fullName>
    <description>Lorsque ce champ est rempli, cela veut dire qu&apos;il y a un mandat Sepa, cela déclenche alors le statut &quot;A signer&quot; du champ statut mandat de données de vente</description>
    <label>ID Mandat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_IDReferenceClient__c.field-meta.xml
<CustomField>
    <fullName>VI_IDReferenceClient__c</fullName>
    <description>Donnée technique - Id du contact dans Symphonie</description>
    <label>ID Référence client</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_InfosCompl_DateContratEffectif__c.field-meta.xml
<CustomField>
    <fullName>VI_InfosCompl_DateContratEffectif__c</fullName>
    <description>Champ étape Informations complémentaires
Date effet de contrat</description>
    <label>Date contrat effectif</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_OffreChoisieElecPanierClient__c.field-meta.xml
<CustomField>
    <fullName>VI_OffreChoisieElecPanierClient__c</fullName>
    <description>Champ pour sauvegarder l&apos;offre choisie Elec sur le parcours.</description>
    <label>Offre choisie (Elec)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_OffreChoisieGazPanierClient__c.field-meta.xml
<CustomField>
    <fullName>VI_OffreChoisieGazPanierClient__c</fullName>
    <description>Champ pour sauvegarder l&apos;offre choisie Gaz sur le parcours.</description>
    <label>Offre choisie (Gaz)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TypeParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_TypeParcours__c</fullName>
    <description>Attribue au compte le type d’enseigne dans la CPV créée et qui fera le lien avec Symphonie/Amadeus pour les reporting de vente notamment</description>
    <label>Type parcours</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PURE PLAYERS</fullName>
            </value>
            <value>
                <fullName>VENTE DIRECTE</fullName>
            </value>
            <value>
                <fullName>STORE</fullName>
            </value>
            <value>
                <fullName>DISTRIBUTION</fullName>
            </value>
            <value>
                <fullName>CORNER</fullName>
                <isActive>false</isActive>
                <label>CORNER</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VI_SM024_GetDocusignToken_Test.cls
/*
*@Author: Paul Ghoussoub
*@Description: VI_SM024_GetDocusignToken
*@CreatedDate: 2/12/2020
*@LastModified: 29/12/2021
*/

@isTest 
public class VI_SM024_GetDocusignToken_Test {
    @testSetup 
    static void testSetup(){ 
        MP_Xdata_credentials__c client_id = new MP_Xdata_credentials__c();
        client_id.Value__c = '516a8780-afd6-45d0-903e-e3caaeab4bc5';
        client_id.Name = 'VI_client_id';
        insert client_id;
        
        MP_Xdata_credentials__c client_secret = new MP_Xdata_credentials__c();
        client_secret.Value__c = 'fa1a7c0c-8420-447e-bfd8-b54303b84794';
        client_secret.Name = 'VI_client_secret';
        insert client_secret;
        
        MP_Xdata_credentials__c VI_api_key_digital_INT = new MP_Xdata_credentials__c();
        VI_api_key_digital_INT.Value__c = '516a8780-afd6-45d0-903e-e3caaeab4bc5';
        VI_api_key_digital_INT.Name = 'VI_api_key_digital_INT';
        insert VI_api_key_digital_INT;
        
        MP_Xdata_credentials__c VI_digital_id_client = new MP_Xdata_credentials__c();
        VI_digital_id_client.Value__c = '516a8780-afd6-45d0-903e-e3caaeab4bc5';
        VI_digital_id_client.Name = 'VI_api_key_INT';
        insert VI_digital_id_client;
        
        MP_Xdata_credentials__c VI_digital_secret_client = new MP_Xdata_credentials__c();
        VI_digital_secret_client.Value__c = '516a8780-afd6-45d0-903e-e3caaeab4bc5';
        VI_digital_secret_client.Name = 'VI_digital_secret_client';
        insert VI_digital_secret_client;
        
        MP_Xdata_credentials__c VI_scope = new MP_Xdata_credentials__c();
        VI_scope.Value__c = 'apiset.read';
        VI_scope.Name = 'VI_scope';
        insert VI_scope;
        
        MP_Xdata_credentials__c VI_user_tranquility = new MP_Xdata_credentials__c();
        VI_user_tranquility.Value__c = '4bf81dd4-b8ec-4c4b-9c84-8e009d8a2b35';
        VI_user_tranquility.Name = 'VI_user_tranquility';
        insert VI_user_tranquility;
        
        MP_Xdata_credentials__c VI_password_tranquility = new MP_Xdata_credentials__c();
        VI_password_tranquility.Value__c = '868e3fed-b555-4e42-9430-5bc93755ca51';
        VI_password_tranquility.Name = 'VI_password_tranquility';
        insert VI_password_tranquility;
    }
   
    @isTest
    static void testGetToken(){
        StaticResourceCalloutMock multimock = new StaticResourceCalloutMock();
        multimock.setStaticResource('VI_TestGetDocusignToken');
        multimock.setStatusCode(200);
        multimock.setHeader('Content-Type', 'application/json');
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, multimock);
        String token=VI_SM024_GetDocusignToken.getAccessToken('local.VIToken');
        system.assertEquals('test', token);
        Test.stopTest();
    }
    
   @isTest
    static void testCreateEnvelope(){
        Account acct = new Account(Name='TEST_ACCT', VI_Type_Enseigne__c='INDIRECTE', VI_TypeParcours__c='PURE PLAYERS');
        insert acct;
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;     
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = acct.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        
        Contact c=new Contact(LastName='test',Salutation='MR',FirstName='test',MailingPostalCode='testt',Mailingcity='test',Mailingcountry='test');
        Id contactrecordTypeId = Contact.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Contact_Smile').getRecordTypeId();
        c.recordTypeId=contactrecordTypeId;
        insert c;
        date d=system.today();
       // VI_Parcours__c p=new VI_Parcours__c(VI_Contact__c=c.id,VI_Email_CPV__c='test@test.com',VI_OffreChoisieGazPanierClient__c='GBUKF2',VI_InfosCompl_DateContratEffectif__c=d,
       //                                     VI_OffreChoisieElecPanierClient__c='EBUKF3V100',VI_ChoixParcours__c='EM'); 
         VI_Parcours__c p=new VI_Parcours__c(VI_Contact__c=c.id,VI_Email_CPV__c='test@test.com',VI_ChoixMoyenPaiement__c = 'Autre',VI_OffreChoisieGazPanierClient__c='GBUKF2',VI_InfosCompl_DateContratEffectif__c=d
                                             , VI_TypeParcours__c='PURE PLAYERS',
                                            VI_OffreChoisieElecPanierClient__c='EBUKF3V100',VI_ChoixParcours__c='EM',VI_IDReferenceClient__c='test',VI_ID_Mandat__c='test',VI_Id_coordonnees_bancaires__c='0202000001-01'); 
        
        insert p;
        Test.startTest();
        List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element> listcouple=new List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element>();
        VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element element=new VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element();
        listcouple.add(element);
        VI_SM024_GetDocusignToken.retourEnvoiDocument retourEnvoi=  VI_SM024_GetDocusignToken.envoyerDocumentsfromLWC(p,null,listcouple,'local.VIDocusignToken');
        //system.assert(retourEnvoi.parcours.VI_EmailEnvoye__c);
        //system.assert(retourEnvoi.parcours.VI_Date_envoi_email__c!=null);
        Test.stopTest();
    }
    
    @isTest
    static void testCreateEnvelope3(){
        date d=system.today();
        Account acct = new Account(Name='TEST_ACCT',VI_Type_Enseigne__c='INDIRECTE', VI_TypeParcours__c='PURE PLAYERS');
        insert acct;
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;     
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = acct.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        Contact c=new Contact(LastName='test',Salutation='MR',FirstName='test',MailingPostalCode='testt',Mailingcity='test',Mailingcountry='test');
        Id contactrecordTypeId = Contact.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Contact_Smile').getRecordTypeId();
        c.recordTypeId=contactrecordTypeId;
        insert c;
        VI_Parcours__c p=new VI_Parcours__c(VI_Contact__c=c.id,VI_Email_CPV__c='test@test.com',VI_ChoixMoyenPaiement__c = 'Autre', VI_IBANEnSelfCare__c= true,VI_OffreChoisieGazPanierClient__c='GBUKF2',VI_InfosCompl_DateContratEffectif__c=d
                                            , VI_TypeParcours__c='PURE PLAYERS',
                                            VI_OffreChoisieElecPanierClient__c='EBUKF3V100',VI_IDReferenceClient__c='test',VI_ID_Mandat__c='test',VI_Id_coordonnees_bancaires__c='0202000001-01'); 
        insert p;
        p.VI_ChoixParcours__c='CHF';      
        update p;
        Test.startTest(); 
        List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element> listcouple=new List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element>();
        VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element element=new VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element();
        listcouple.add(element);
        VI_SM024_GetDocusignToken.retourEnvoiDocument retourEnvoi = VI_SM024_GetDocusignToken.envoyerDocumentsfromLWC(p,null,listcouple,'local.VIDocusignToken');
        //system.assert(retourEnvoi.parcours.VI_EmailEnvoye__c);
        //system.assert(retourEnvoi.parcours.VI_Date_envoi_email__c!=null);
        Test.stopTest();
        
    }
    
    @isTest
    static void testCreateEnvelope2(){
        date d=system.today();
        Account acct = new Account(Name='TEST_ACCT',VI_Type_Enseigne__c='INDIRECTE', VI_TypeParcours__c='PURE PLAYERS');
        insert acct;
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;     
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = acct.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        Contact c=new Contact(LastName='test',Salutation='MR',FirstName='test',MailingPostalCode='testt',Mailingcity='test',Mailingcountry='test');
        Id contactrecordTypeId = Contact.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Contact_Smile').getRecordTypeId();
        c.recordTypeId=contactrecordTypeId;
        insert c;
  
        VI_Parcours__c p=new VI_Parcours__c(VI_Contact__c=c.id,VI_Email_CPV__c='test@test.com', VI_OffreChoisieGazPanierClient__c='GBUKF2',VI_InfosCompl_DateContratEffectif__c=d
                                            , VI_TypeParcours__c='PURE PLAYERS',
                                            VI_OffreChoisieElecPanierClient__c='EBUKF3V100',VI_IDReferenceClient__c='test',VI_ID_Mandat__c='test',VI_Id_coordonnees_bancaires__c='0202000001-01'); 
        
        insert p;
        p.VI_ChoixParcours__c='EM';      
        update p;
        Test.startTest(); 
        List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element> listcouple=new List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element>();
        VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element element=new VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element();
        listcouple.add(element);
        VI_SM024_GetDocusignToken.retourEnvoiDocument retourEnvoi = VI_SM024_GetDocusignToken.envoyerDocumentsfromLWC(p,null,listcouple,'local.VIDocusignToken');
        //system.assert(retourEnvoi.parcours.VI_EmailEnvoye__c);
        //system.assert(retourEnvoi.parcours.VI_Date_envoi_email__c!=null);
        Test.stopTest();
        
    }
    @isTest
    static void testCreateEnvelope4(){
        date d=system.today();
        Account acct = new Account(Name='TEST_ACCT',VI_Type_Enseigne__c='INDIRECTE', VI_TypeParcours__c='PURE PLAYERS');
        insert acct;
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;     
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = acct.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        Contact c=new Contact(LastName='test',Salutation='MR',FirstName='test',MailingPostalCode='testt',Mailingcity='test',Mailingcountry='test');
        Id contactrecordTypeId = Contact.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Contact_Smile').getRecordTypeId();
        c.recordTypeId=contactrecordTypeId;
        insert c;
        VI_Parcours__c p=new VI_Parcours__c(VI_Contact__c=c.id,VI_Email_CPV__c='test@test.com',VI_OffreChoisieGazPanierClient__c='GBUKF2',VI_InfosCompl_DateContratEffectif__c=d,
                                        //
                                            VI_TypeParcours__c='PURE PLAYERS', VI_OffreChoisieElecPanierClient__c='EBUKF3V100' ); 
        
        insert p;
        p.VI_ChoixParcours__c='EM';      
        update p;
        Test.startTest(); 
        List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element> listcouple=new List<VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element>();
        VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element element=new VI_gdfsuezComBefCalypsoCpvV2.listeCodeValeurDt_coupleCodeValeur_element();
        listcouple.add(element);
        VI_SM024_GetDocusignToken.retourEnvoiDocument retourEnvoi = VI_SM024_GetDocusignToken.envoyerDocumentsfromLWC(p,null,listcouple,'local.VIDocusignToken');
        system.assertEquals(retourEnvoi.retourMessage,'Erreur lors de la génération du CPV');
        Test.stopTest();
        
    }
}