force-app/main/default/objects/MP_Xdata_credentials__c/MP_Xdata_credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MP_Xdata_credentials</label>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_ServicePayant__c/VI_ServicePayant__c.object-meta.xml
<CustomObject>
    <label>Service payant</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Numéro du service payant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services payants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_ServicePayant__c/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <label>Canal</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pure player</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_ServicePayant__c/fields/VI_NomDuService__c.field-meta.xml
<CustomField>
    <fullName>VI_NomDuService__c</fullName>
    <label>Nom du service</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assurance facture</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_ServicePayant__c/fields/VI_Partenaire__c.field-meta.xml
<CustomField>
    <fullName>VI_Partenaire__c</fullName>
    <label>Partenaire</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Merci de sélectionner un compte Partenaire.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PartenaireAccountRT</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Services payants</relationshipLabel>
    <relationshipName>Services_payants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VI_parcoursOptionsEtServices_Test.cls
/*
*@Author: Paul Ghoussoub
*@Description: Classe test de VI_parcoursOptionsEtServices_Controller.
*@CreatedDate: 23/05/2022
*/
@isTest
public class VI_parcoursOptionsEtServices_Test {
    @testSetup
    static void testSetup(){
        List<Group> ownerQueue = [Select Id,DeveloperName from Group where Type = 'Queue'];
        
        MP_Xdata_credentials__c VI_user_tranquility = new MP_Xdata_credentials__c();
        VI_user_tranquility.Value__c = '4bf81dd4-b8ec-4c4b-9c84-8e009d8a2b35';
        VI_user_tranquility.Name = 'VI_user_tranquility';
        insert VI_user_tranquility;
        
        MP_Xdata_credentials__c VI_password_tranquility = new MP_Xdata_credentials__c();
        VI_password_tranquility.Value__c = '868e3fed-b555-4e42-9430-5bc93755ca51';
        VI_password_tranquility.Name = 'VI_password_tranquility';
        insert VI_password_tranquility;
        
        MP_Xdata_credentials__c scope = new MP_Xdata_credentials__c();
        scope.Value__c = 'PCKEY';
        scope.Name = 'VI_ConsumerKeySymphonie';
        insert scope;
        
        MP_Xdata_credentials__c consumerKey = new MP_Xdata_credentials__c();
        consumerKey.Value__c = 'PCVALUE';
        consumerKey.Name = 'VI_ConsumerSecretSymphonie';
        insert consumerKey;

        
        system.debug('query queue '+ownerQueue);
        Id profileId = [Select Id From Profile Where Name ='VI_PurePlayer'].Id;
        Account acc = VI_TestUtility.createAccount('Marketshot');
        acc.RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PartenaireAccountRT').getRecordTypeId();
        insert acc;
        Contact con = VI_TestUtility.createContact('test','Contact','test@gmail.com',acc.Id);
        insert con;
        
        VI_ServicePayant__c sp1=new VI_ServicePayant__c(VI_NomDuService__c= 'Assurance Facture',VI_Partenaire__c=acc.id,Canal__c='Pure Player');
        insert sp1;
        User u = VI_TestUtility.createCommunityUser(con.Id,profileId,'TestVI','TestVI');
        insert u;
    }
    
    @isTest
    static void getOptionsEtServicesTest(){
        User u =[Select id from user where firstname='TestVI' and lastname='TestVI' and isActive=true limit 1];
        System.runAs(u){
            Test.startTest();
            VI_Parcours__c parcoursTest = VI_TestDataFactory.createParcours('CHF', null, 'PURE PLAYERS');
            VI_parcoursOptionsEtServices_Controller.OptionsEtServices OptionsEtServices=VI_parcoursOptionsEtServices_Controller.getOptionsEtServices(parcoursTest);
            system.assertEquals(5.00,OptionsEtServices.AssuranceFacturePrixTTC);
            Test.stopTest();
        }
    }
    @isTest
    static void wrapperPromotionTest(){
        VI_parcoursOptionsEtServices_Controller.wrapperPromotion wp=new VI_parcoursOptionsEtServices_Controller.wrapperPromotion(
            'NumPromotion',  'CodePromo',  'LibelleSurFacture',  'NomPromotion', 
            'DescriptifPromotion',  'DebutValidity',  'FinValidity',  'CanalDeVente');
    }
}