force-app/main/default/objects/SM_CodeProduitProjet__mdt/SM_CodeProduitProjet__mdt.object-meta.xml
<CustomObject>
    <description>Métadonnées de correspondance de code produit et le type de projet pour le parcours détection de projet.</description>
    <label>SM_CodeProduitProjet</label>
    <pluralLabel>SM_CodeProduitProjet</pluralLabel>
</CustomObject>

force-app/main/default/objects/SM_CodeProduitProjet__mdt/fields/CodeProduit__c.field-meta.xml
<CustomField>
    <fullName>CodeProduit__c</fullName>
    <description>Code de Produit</description>
    <label>CodeProduit</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_CodeProduitProjet__mdt/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <description>Ordre</description>
    <label>OrderId</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_CodeProduitProjet__mdt/fields/Projet__c.field-meta.xml
<CustomField>
    <fullName>Projet__c</fullName>
    <description>Projet</description>
    <label>Projet</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_CodeProduitProjet__mdt/fields/TypedeProjet__c.field-meta.xml
<CustomField>
    <fullName>TypedeProjet__c</fullName>
    <description>Type de projet</description>
    <label>TypedeProjet</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_EM104_CodeProduitProjet.cls
/**
 * @author Sutharsan Pushparajah
 * @date 19/04/2022
 * @description SM_EM104_CodeProduitProjet - Entity to manage SM_CodeProduitProjet__mdt CustomMetadaType
 */
public inherited sharing class SM_EM104_CodeProduitProjet {
    
    /* Instance of the SM_CodeProduitProjet__mdt datamanager to access SOQL & DML operations */
    public static ITF001_DataManager datamanager = new DM001_SObjectInstance(SObjectType.SM_CodeProduitProjet__mdt.Name, 'SM_EM104_CodeProduitProjet');

    /* All Active SM_CodeProduitProjet__mdt records sorted by OrderId__c */
    public static List<SM_CodeProduitProjet__mdt> allActivesSortedByOrderId;

    static {
        allActivesSortedByOrderId = getActivesSortedByOrderId();
    }

    /**
     * @author Sutharsan Pushparajah
     * @date 19/04/2022
     * @description get All Active SM_CodeProduitProjet__mdt records sorted by OrderId__c
     * @return List<SM_CodeProduitProjet__mdt> All Active SM_CodeProduitProjet__mdt records sorted by OrderId__c
     */
    public static List<SM_CodeProduitProjet__mdt> getActivesSortedByOrderId(){
        return (List<SM_CodeProduitProjet__mdt>) datamanager.query('Projet__c, TypedeProjet__c, CodeProduit__c, IsActive__c', 'IsActive__c = true', 'order by OrderId__c', null, null);
    }
}