force-app/main/default/objects/Donnees_Vente__c/Donnees_Vente__c.object-meta.xml
<CustomObject>
    <label>Données Vente</label>
    <nameField>
        <displayFormat>TEL-{0000}</displayFormat>
        <label>Nom de Données Vente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Données Ventes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donnees_Vente__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CaseId</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Données Ventes</relationshipLabel>
    <relationshipName>Donn_es_Ventes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/RGPD_PurgeDonneesIdentification__e.object-meta.xml
<CustomObject>
    <label>RGPD_PurgeDonneesIdentification</label>
    <pluralLabel>RGPD_PurgeDonneesIdentifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/eventId__c.field-meta.xml
<CustomField>
    <fullName>eventId__c</fullName>
    <description>c&apos;est l&apos;identifiant de l&apos;événement du Bus Kinesis Stream Purge</description>
    <label>eventId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/eventSubType__c.field-meta.xml
<CustomField>
    <fullName>eventSubType__c</fullName>
    <description>correspond au sous type de l&apos;événement du stream purge (cf. Politique des DCP partie finalités )</description>
    <label>eventSubType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/eventType__c.field-meta.xml
<CustomField>
    <fullName>eventType__c</fullName>
    <description>Correspond au type de l&apos;événement du stream purge pouvant contenir les valeurs suivantes : PurgeDonneesFines, PurgeDonneesIdentification, PurgeConsoMensEtFacturation</description>
    <label>eventType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idContrat__c.field-meta.xml
<CustomField>
    <fullName>idContrat__c</fullName>
    <description>correspond à l&apos;Id Contrat du client auquel s&apos;applique l&apos;événement.</description>
    <label>idContrat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idDemande__c.field-meta.xml
<CustomField>
    <fullName>idDemande__c</fullName>
    <description>correspond à l&apos;Id Demande  qui est l&apos;identifiant pour notifier le stream purge que l&apos;action est réalisée</description>
    <label>idDemande</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idPortefeuilleContrat__c.field-meta.xml
<CustomField>
    <fullName>idPortefeuilleContrat__c</fullName>
    <label>idPortefeuilleContrat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/idTiers__c.field-meta.xml
<CustomField>
    <fullName>idTiers__c</fullName>
    <description>correspond à l&apos;Id tiers du client auquel s&apos;applique l&apos;événement.</description>
    <label>idTiers</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/noBp__c.field-meta.xml
<CustomField>
    <fullName>noBp__c</fullName>
    <description>correspond numéro de BP du client auquel s&apos;applique l&apos;événement.</description>
    <label>noBp</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/noContrat__c.field-meta.xml
<CustomField>
    <fullName>noContrat__c</fullName>
    <description>correspond au numéro de Contrat du client auquel s&apos;applique l&apos;événement.</description>
    <label>noContrat</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RGPD_PurgeDonneesIdentification__e/fields/noPortefeuilleContrat__c.field-meta.xml
<CustomField>
    <fullName>noPortefeuilleContrat__c</fullName>
    <label>noPortefeuilleContrat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SM_RGPD_PurgeDonneesInvocable.cls
public with sharing class SM_RGPD_PurgeDonneesInvocable {
    @InvocableMethod
    public static void execute (List<Requests> requestList) {
        String operation = requestList[0].operation;
        if(operation.equals('DeleteRelatedRecords')){
            // récupérer les paramètres envoyés par le flow
            String contactId = requestList[0].contactId;
            List<Case> casesList = requestList[0].casesList;
            List<Task> tasksList = requestList[0].tasksList;

            // variables pour stocker les Ids des enregistrements
            Set<Id> casesIds = new Set<Id>();
            Set<Id> tasksIds = new Set<Id>();
            Set<Id> accountIds = new Set<Id>();

            // variables pour stocker les enregistrements à supprimer
            List<Donnees_Vente__c> donneesVenteToDelete= new  List<Donnees_Vente__c>();
            List<EmailMessage> emailMessagesToDelete = new  List<EmailMessage>();
            List<Order> ordersToDelete = new  List<Order>();
            List<Order> ordersToUpdateDraft = new  List<Order>();
            List<Account> accountsToDelete = new List<Account>();
            
            // récupérer les Ids des cases et tasks
            if(casesList != null && casesList.size() > 0){
                for(Case c: casesList)
                    casesIds.add(c.Id);
            }
            if(tasksList != null && tasksList.size() > 0){
                for(Task t: tasksList)
                    tasksIds.add(t.Id);
            }

            // récupérer les enregistrements données vente
            donneesVenteToDelete = [SELECT Id FROM Donnees_Vente__c WHERE CaseId__c IN :casesIds];
            
            // récupérer les enregistrements EmailMessage
            emailMessagesToDelete = [SELECT Id FROM EmailMessage WHERE Case__c IN :casesIds OR ActivityId IN :tasksIds];

            // récupérer les enregistrements Orders
            ordersToDelete = [SELECT Id,Status FROM Order WHERE Case__c IN :casesIds];
            
            // Mettre les orders activés à Draft avant de les supprimer
            for(Order ord:ordersToDelete){
                if(ord.Status.equals('Activated')){
                    ord.status='Draft';
                    ordersToUpdateDraft.add(ord);
                }
            }

            // récupérer les enregistrements Accounts
            List<AccountContactRelation> acrs = [SELECT id, Accountid FROM AccountContactRelation Where contactId= :contactId and isDirect=false];
            for(AccountContactRelation acr: acrs)
                accountIds.add(acr.accountId);
            accountsToDelete= [SELECT id FROM Account WHERE Id IN :accountIds];


            System.debug('donneesVenteToDelete'+donneesVenteToDelete);
            System.debug('emailMessagesToDelete'+emailMessagesToDelete);
            System.debug('ordersToDelete'+ordersToDelete);
            System.debug('accountsToDelete'+accountsToDelete);

            // suppression des enregistrements
            try{
                delete donneesVenteToDelete;
                delete emailMessagesToDelete;
                update ordersToUpdateDraft;
                delete ordersToDelete;
                delete accountsToDelete;
            }catch(DmlException e){
                System.debug('#### GDPR Error'+ e);
            }
        }else if(operation.equals('sendConfirmation')){
            // vérifier le contenu du message à envoyer
            RGPD_PurgeDonneesIdentification__e eventObject = requestList[0].eventObject;
            String messageBody =  transformApiMessageBody(eventObject);
            sendPurgeConfirmation(messageBody);
        }
        
    }
    
public static String transformApiMessageBody(RGPD_PurgeDonneesIdentification__e eventObject){
    Map<String, Object> cleObjet = new Map<String, Object>();
    cleObjet.put('idTiers', eventObject.idTiers__c);
    cleObjet.put('noPortefeuilleContrat', eventObject.noPortefeuilleContrat__c);
    cleObjet.put('noContrat', eventObject.noContrat__c);
    cleObjet.put('idPortefeuilleContrat', eventObject.idPortefeuilleContrat__c);
    cleObjet.put('noBp', eventObject.noBp__c);
    cleObjet.put('idContrat', eventObject.idContrat__c);
    Map<String, Object> dataInside = new Map<String, Object>();
    dataInside.put('idDemande', eventObject.idDemande__c);
    dataInside.put('cleObjet', cleObjet);
	Map<String, Object> data = new Map<String, Object>();
    data.put('eventVersion', '1.0');
    data.put('eventSource', 'SMILE');
    data.put('eventTime', Datetime.now().format('yyyy-MM-dd hh:mm:ss'));
    data.put('eventType', eventObject.eventType__c+'OK');
    data.put('eventSubType', eventObject.eventSubType__c);
    data.put('eventId', eventObject.id);
    data.put('parentEventId', eventObject.eventId__c);
    data.put('data', dataInside);
    Map<String, Object> bodyObj = new Map<String, Object>();
    bodyObj.put('data', data);
    bodyObj.put('partition-key', '1');
    return JSON.serialize(bodyObj);
} 
    
@future(callout = true)
public static void sendPurgeConfirmation(String messageBody){
    SM_StreampurgeApiService.callStreampurgeApi(messageBody);
} 
public class Requests {
  @InvocableVariable(label='opération' description='L\'opération à executer')
  public String operation;
  @InvocableVariable(label='contactId' description='L\'id du contact impacté par RGPD')
  public String contactId;
  @InvocableVariable(label='casesList' description='La list des cases du contact impacté par RGPD')
  public List<Case> casesList;
  @InvocableVariable(label='tasksList' description='La list des tâches du contact impacté par RGPD')
  public List<Task> tasksList;
  @InvocableVariable(label='eventObject' description='La platform event object')
  public RGPD_PurgeDonneesIdentification__e eventObject;
  }
  
}