force-app/main/default/objects/Donnees_Vente__c/Donnees_Vente__c.object-meta.xml
<CustomObject>
    <label>Données Vente</label>
    <nameField>
        <displayFormat>TEL-{0000}</displayFormat>
        <label>Nom de Données Vente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Données Ventes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donnees_Vente__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CaseId</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Données Ventes</relationshipLabel>
    <relationshipName>Donn_es_Ventes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/ID_coordonnees_bancaires__c.field-meta.xml
<CustomField>
    <fullName>ID_coordonnees_bancaires__c</fullName>
    <label>ID coordonnées bancaires</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/recordTypes/Acquisition_Harmonica.recordType-meta.xml
<RecordType>
    <fullName>Acquisition_Harmonica</fullName>
    <active>true</active>
    <description>Type d&apos;enregistrement utilisé pour les enregistrements du parcours acquisition Harmonica</description>
    <label>Acquisition_Harmonica</label>
</RecordType>

force-app/main/default/classes/SM_CaseCHOHarmonica_Controller_test.cls
/**
* @description       : Test class for SM_CaseCHOHarmonica_Controller (FT1-4947)
* @author            : Zouhair BOUKHRISS
* @group             : 
* @last modified on  : 02-07-2021
* @last modified by  : David ATTALI
* Modifications Log 
* Ver   Date         Author               Modification
* 1.0   01-07-2021   Zouhair BOUKHRISS    Initial Version
* 1.1   02-07-2021   David ATTALI         Comments, delete method testGetDataCHO_OnlineTunnel_WithoutBanksDetails and modify method testGetDataCHO_OnlineTunnel_WithBanksDetails
**/
@isTest
public class SM_CaseCHOHarmonica_Controller_test {
    
    @isTest
    static void testGetDataCHO_OnlineTunnel_WithBanksDetails() {
        
        // Create contact
        String contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact_Smile').getRecordTypeId(); 
        Contact contact = new Contact(LastName = 'Test', RecordTypeId = contactRecordTypeId, Identifiant_Buisness_Partener__c = '146559850');
        insert contact;

        // Create case
        String caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();   
        Case onlineTunnelCase = new Case();
        onlineTunnelCase.ContactId = contact.Id;
        onlineTunnelCase.Subject = 'Test';
        onlineTunnelCase.Status = 'Nouveau';
        onlineTunnelCase.RecordTypeId = caseRecordTypeId;
        insert onlineTunnelCase;
        
        // Case : with banks details (without IBAN crypted)
        String dataRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Acquisition_Harmonica').getRecordTypeId();   
        Donnees_Vente__c onlineTunnelData = new Donnees_Vente__c();
        onlineTunnelData.CaseId__c = onlineTunnelCase.id;
        onlineTunnelCase.RecordTypeId = dataRecordTypeId;
        onlineTunnelData.ID_coordonnees_bancaires__c = '0306559850-0001';
        insert onlineTunnelData;
        
        Test.startTest();
        
        SM_CaseCHOHarmonica_Controller.HarmonicaCHOData harmonicaDataCHO = SM_CaseCHOHarmonica_Controller.getDataCHO(onlineTunnelCase.id);
        
        Test.stopTest();
        
        System.assertEquals('0306559850-0001', harmonicaDataCHO.harmonicaBankDetailsId);
        System.assertEquals('146559850', harmonicaDataCHO.clientBPId);
        System.assertEquals(contact.Id, harmonicaDataCHO.contactId);
    }
    
}