force-app/main/default/objects/Donnees_Vente__c/Donnees_Vente__c.object-meta.xml
<CustomObject>
    <label>Données Vente</label>
    <nameField>
        <displayFormat>TEL-{0000}</displayFormat>
        <label>Nom de Données Vente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Données Ventes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donnees_Vente__c/fields/Assurance_facture__c.field-meta.xml
<CustomField>
    <fullName>Assurance_facture__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assurance facture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CaseId</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Données Ventes</relationshipLabel>
    <relationshipName>Donn_es_Ventes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Civilite_client__c.field-meta.xml
<CustomField>
    <fullName>Civilite_client__c</fullName>
    <label>Civilité client</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Code_postale__c.field-meta.xml
<CustomField>
    <fullName>Code_postale__c</fullName>
    <label>Code postale</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Commune__c.field-meta.xml
<CustomField>
    <fullName>Commune__c</fullName>
    <label>Commune</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Degex__c.field-meta.xml
<CustomField>
    <fullName>Degex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Degex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Degexplus__c.field-meta.xml
<CustomField>
    <fullName>Degexplus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DEGEX+</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Depex__c.field-meta.xml
<CustomField>
    <fullName>Depex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Depex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Depexplus__c.field-meta.xml
<CustomField>
    <fullName>Depexplus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DEPEX+</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/E_documents__c.field-meta.xml
<CustomField>
    <fullName>E_documents__c</fullName>
    <defaultValue>false</defaultValue>
    <label>E document</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Email_client__c.field-meta.xml
<CustomField>
    <fullName>Email_client__c</fullName>
    <label>Email client</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/EmailRisque__c.field-meta.xml
<CustomField>
    <fullName>EmailRisque__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ce champ est un flag qui sera renseigné par le TEL. 
Si la checkbox est à true cela signifie que le mail renseigné par le client n&apos;est pas valide</description>
    <label>Email Risque</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Libelle_voie__c.field-meta.xml
<CustomField>
    <fullName>Libelle_voie__c</fullName>
    <label>Libelle voie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Maj_email__c.field-meta.xml
<CustomField>
    <fullName>Maj_email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checked if email préfére checkbox is checked</description>
    <label>Maj email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Nom_client__c.field-meta.xml
<CustomField>
    <fullName>Nom_client__c</fullName>
    <label>Nom client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Numero_de_voie__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_voie__c</fullName>
    <label>Numéro de voie</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Prenom_client__c.field-meta.xml
<CustomField>
    <fullName>Prenom_client__c</fullName>
    <label>Prenom client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Statut_Iban__c.field-meta.xml
<CustomField>
    <fullName>Statut_Iban__c</fullName>
    <description>Champ spécifique à Harmonica CHO alimenté par le tunnel en ligne</description>
    <label>Statut IBAN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Telephone_client__c.field-meta.xml
<CustomField>
    <fullName>Telephone_client__c</fullName>
    <label>Téléphone client</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SM_HarmonicaDisplayContactInfos.cls
public with sharing class SM_HarmonicaDisplayContactInfos {
    public SM_HarmonicaDisplayContactInfos() {}
    @AuraEnabled(cacheable=true)
    public static String getDataClient (String caseId){
        System.debug('### caseId '+caseId);
        Donnees_Vente__c donneVente = [SELECT id,CaseId__r.contact.reference_client_f__c, 
                                              Civilite_client__c,Email_client__c,Nom_client__c,
                                              Prenom_client__c, Telephone_client__c,Libelle_voie__c,
                                              Code_postale__c,Numero_de_voie__c,Commune__c,E_documents__c,Statut_Iban__c,
                                       		  CaseId__r.Origin, CaseId__r.MES_urgente__c,Maj_email__c, CaseId__r.Type , 
                                  			  CaseId__r.Depex__c, CaseId__r.Degex__c,CaseId__r.Depexplus__c,CaseId__r.Degexplus__c,
                                 			  CaseId__r.Garantie_Electromenager__c,CaseId__r.Assurance_Facture__c, EmailRisque__c 
                                        FROM Donnees_Vente__c
                                        WHERE CaseId__c = :caseId];
        System.debug('## donneVente '+donneVente);
        return JSON.serialize(donneVente);
    }
}