force-app/main/default/objects/Donnees_Vente__c/Donnees_Vente__c.object-meta.xml
<CustomObject>
    <label>Données Vente</label>
    <nameField>
        <displayFormat>TEL-{0000}</displayFormat>
        <label>Nom de Données Vente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Données Ventes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donnees_Vente__c/fields/Code_pack__c.field-meta.xml
<CustomField>
    <fullName>Code_pack__c</fullName>
    <description>CODE_PACK</description>
    <label>Code pack</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Commune__c.field-meta.xml
<CustomField>
    <fullName>Commune__c</fullName>
    <label>Commune</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donnees_Vente__c/fields/Date_resiliation__c.field-meta.xml
<CustomField>
    <fullName>Date_resiliation__c</fullName>
    <label>Date de résiliation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SM_HarmonicaEmailTemplates_TEST.cls
/*
* @Author: Ibrahim Merabti
* @Date: 20/04/2020
* @Description: Test Class for HarmonicaMail class 
*/

@isTest
public without sharing class SM_HarmonicaEmailTemplates_TEST {

    @testSetup 
    static void setup() {
        
        // create Account
        Account Acc = SM_TestDataFactory.createAccount('Harmonica_Account');
        Insert acc;
        // Create Case
        Case harmonicaCase = SM_TestDataFactory.createCase('TEST', Acc.Id);
        insert harmonicaCase;
        
        // Create donneé vente
        Donnees_Vente__c dv = SM_TestDataFactory.createDonneeVente(harmonicaCase.Id,'Cergy','ABCD','52','Avenue des loups', '95800');
        dv.Code_pack__c ='DGBUEBUVR2_P';
        dv.Commune__c = 'Cergy';
        dv.Date_resiliation__c =date.valueOf('2021-04-29');
        insert dv;
        
        // Create a product
        Product2 offre = SM_TestDataFactory.createProduct('harmonica_product', 'ABCD', 'ABCD');
        offre.familyLabel__c = 'Offre energie 2 ans';
        offre.Family ='DGBUEBUVR2_P';
        insert offre;
    }
    
    @isTest 
    public static void testDonneesVente(){
        // retrieve the case 
        Case harmonicaCase = [select Id from Case limit 1];
        
        // Prefill SM_HarmonicaEmailTemplates attributes with the CaseId
        SM_HarmonicaEmailTemplates smh = new SM_HarmonicaEmailTemplates();
        smh.CaseId = harmonicaCase.Id;
        smh.dvFieldName = 'Commune__c';
        
        Test.startTest();
        String commune = smh.dvValue;
        Test.stopTest();
        
        // assert equal 
        system.assertEquals('Cergy', commune);
    }
    
       @isTest 
    public static void testProductCode(){
        // retrieve the case 
        Case harmonicaCase = [select Id from Case limit 1];
        
        // Prefill SM_HarmonicaEmailTemplates attributes with the CaseId
        SM_HarmonicaEmailTemplates smh = new SM_HarmonicaEmailTemplates();
        smh.CaseId = harmonicaCase.Id;
        smh.dvFieldName = 'Code_pack__c';
        
        Test.startTest();
        String familyLabel = smh.dvValue;
        Test.stopTest();
        
        // assert equal 
        system.assertEquals('Offre energie 2 ans', familyLabel);
    }
    
}