force-app/main/default/objects/Donnees_Vente__c/Donnees_Vente__c.object-meta.xml
<CustomObject>
    <label>Données Vente</label>
    <nameField>
        <displayFormat>TEL-{0000}</displayFormat>
        <label>Nom de Données Vente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Données Ventes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donnees_Vente__c/fields/Parcours_Client__c.field-meta.xml
<CustomField>
    <fullName>Parcours_Client__c</fullName>
    <label>Parcours Client</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMDM</fullName>
            </value>
            <value>
                <fullName>Emménagement</fullName>
            </value>
            <value>
                <fullName>Changement de fournisseur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Omnichannel_Rule__c/Omnichannel_Rule__c.object-meta.xml
<CustomObject>
    <label>Omnichannel Rule</label>
    <nameField>
        <label>Omnichannel Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Omnichannel Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SM_AP95_SkillBasedRouting_Test.cls
@isTest
public class SM_AP95_SkillBasedRouting_Test {
    
	@testSetup 
    static void dataSetup() {
        // create Omnichannel Rule
		Omnichannel_Rule__c omniRule = SM_TestDataFactory.createOmniChannelRule('Case','Origin','Tunnel en ligne','WEB PARTICULIER',null,null);
        Insert omniRule;
        
        omniRule = SM_TestDataFactory.createOmniChannelRule('Donnees_Vente__c','Parcours_Client__c','RES','RESILIATION',null,null);
        Insert omniRule;
        
        // create Account
        Account acc = SM_TestDataFactory.createAccount('Smile_Account');
        Insert acc;

        // create Contact
        Contact testContact = SM_TestDataFactory.createContact('testContact', acc.Id);
        Insert testContact;
        
        // Create Cases
        Case testCase = SM_TestDataFactory.createCase('TEST', acc.Id);
        Insert testCase;
        
        // Create donnée vente
        Donnees_Vente__c dv = SM_TestDataFactory.createDonneeVente(testCase.Id,'Cergy','ABCD','52','Avenue des loups', '95800');
        insert dv;
    }
    
    @isTest
    static void testRoutingCasesToAgents() {
        List<Case> caseList = [SELECT id FROM Case Limit 1];
        List<String> caseIds = new List<String>();
        caseIds.add(caseList[0].Id);

		Test.startTest();
        SM_AP95_SkillBasedRouting.routingCasesToAgents(caseIds);
        Test.stopTest();
    }
}