force-app/main/default/objects/SM_WS_Suffix__mdt/SM_WS_Suffix__mdt.object-meta.xml
<CustomObject>
    <description>@Project: Smile &amp; MyPower
@Description: Suffix des appels Webservices</description>
    <label>SM_WS_Suffix</label>
    <pluralLabel>SM_WS_Suffixs</pluralLabel>
</CustomObject>

force-app/main/default/objects/SM_WS_Suffix__mdt/fields/suffix__c.field-meta.xml
<CustomField>
    <fullName>suffix__c</fullName>
    <description>@Projet: Smile &amp; MyPower
@Description: Le suffix qui correspond à l&apos;appel</description>
    <label>suffix</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_WS_Suffix__mdt/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>Version - to use in Web service for field &quot;Context Version&quot;</description>
    <label>Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_Utils_Process.cls
global class SM_Utils_Process implements vlocity_cmt.VlocityOpenInterface {
    
    global Boolean invokeMethod(String methodName, Map < String, Object > inputMap, Map < String, Object > outMap, Map < String, Object > options) {
  
    if (methodName.equals('getParams')) {
        getEndPoint(inputMap, outMap, options);
        if((String)inputMap.get('IdDistribCached') ==null ||(String)inputMap.get('IdDistribCached')=='' ){
          getIdDistrib(inputMap, outMap, options);  
        }
        return true;
    }
  return false;
 }
    public void getIdDistrib (Map<String, Object> input, Map<String, Object> output, Map<String, Object> options){
        User sUser = [SELECT distributor_login__c FROM User WHERE id=:userinfo.getuserid()];
        
        output.put('IdDistrib',sUser!=null?sUser.distributor_login__c:null);
    }
    // Add_PERF - AKA
    public void getEndPoint (Map<String, Object> input, Map<String, Object> output, Map<String, Object> options){
        Set<String> listinp = new Set<String>();
        Map<String,String> mapSuffix = new Map<String,String>();
        Map<String,String> mapInp = new Map<String,String>();
        Integer i=1;
        if((String)input.get('ServiceName') !=null){
           listinp.add((String)input.get('ServiceName'));
           mapInp.put((String)input.get('ServiceName'),'ServiceName');  
        }
        String ServiceN=(String)input.get('ServiceName'+i);
        while(ServiceN !=null){
            System.debug('ServiceN: '+ ServiceN);
           listinp.add(ServiceN);
           mapInp.put(ServiceN,'ServiceName'+i);
           i++;
           ServiceN=(String)input.get('ServiceName'+i);
           
        }
        System.debug('listinp: '+ listinp);
        if(listinp.size()>0){
          List<SM_WS_Suffix__mdt> SuffixURL = [SELECT developername,suffix__c,version__c FROM SM_WS_Suffix__mdt WHERE (DeveloperName in :listinp)];
            System.debug('SuffixURL: '+SuffixURL);
            for (SM_WS_Suffix__mdt Suff : SuffixURL){
                mapSuffix.put(Suff.developername, Suff.suffix__c);
                mapSuffix.put(mapInp.get(Suff.developername)+'_URL', Suff.suffix__c);
                mapSuffix.put(Suff.developername+'_version', Suff.version__c);
                mapSuffix.put(mapInp.get(Suff.developername)+'_version', Suff.version__c);
            }
            System.debug('mapSuffix: '+mapSuffix);
            output.putAll(mapSuffix);  
        }
        
    }
}