force-app/main/default/objects/VI_DonneesParcours__c/VI_DonneesParcours__c.object-meta.xml
<CustomObject>
    <description>Objet ayant pour objectif de stocker toutes les informations pouvant nécessiter une adaptation ou une mise à jour facile.</description>
    <label>Données Parcours</label>
    <nameField>
        <label>Nom de Données Parcours</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Données Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_EmailRelanceCPV1__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailRelanceCPV1__c</fullName>
    <description>Contenu du champ { VI_Email_Relance_CPV } de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  pour la première relance.</description>
    <label>Email Relance CPV 1</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_NomPartenaire__c.field-meta.xml
<CustomField>
    <fullName>VI_NomPartenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Champ qui permet de lier les données vente à un compte</description>
    <label>Nom du partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Données Parcours</relationshipLabel>
    <relationshipName>Donnees_Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Date_envoi_email__c.field-meta.xml
<CustomField>
    <fullName>VI_Date_envoi_email__c</fullName>
    <label>Date d&apos;envoi d&apos;email</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV1__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV1__c</fullName>
    <label>Date Relance CPV 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV5__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV5__c</fullName>
    <label>Date Relance CPV 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Email_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Email_CPV__c</fullName>
    <description>Champ email supplémentaire en cas de volonté du client de donner une adresse email différente pour l&apos;envoi des CPV</description>
    <label>Email CPV</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Email_Relance_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Email_Relance_CPV__c</fullName>
    <description>Ce chant remplis la parti variable de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  en étant égale aux champs VI_Email_Relance_CPV 1, 2, 3, 4 ou 5 de Donées Parcours</description>
    <label>Email Relance CPV</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/VI_BAT02_RelanceCPV_Test.cls
/*
*@Auhtor: Paul Ghoussoub
*@Description: Classe de test de VI_BAT02_RelanceCPV
*@CreatedDate: 30/03/2021
*/
@isTest
public class VI_BAT02_RelanceCPV_Test {
  
    @isTest
    static void testBatch(){
        
        Id profileId = [Select Id From Profile Where Name ='VI_PurePlayer'].Id;
        Account acc = VI_TestUtility.createAccount('Marketshot');
        acc.RecordTypeId = Account.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('PartenaireAccountRT').getRecordTypeId();
        insert acc;
        Contact con = VI_TestUtility.createContact('test','Contact','test@gmail.com',acc.Id);
        insert con;
        User u = VI_TestUtility.createCommunityUser(con.Id,profileId,'Test','Test');
        insert u;
        
        VI_DonneesParcours__c donneesParcours = new VI_DonneesParcours__c(VI_EmailRelanceCPV1__c='Relance des CPV n°1', VI_NomPartenaire__c=acc.Id);
        insert donneesParcours;
        

        
        System.runAs(u){
            Test.startTest();
        
            VI_Parcours__c parcours=VI_TestDataFactory.createParcours('CHF', null, 'PURE PLAYERS');
            parcours.VI_Date_envoi_email__c = system.today().adddays(-1);
            parcours.VI_DateRelanceCPV1__c = system.today();
            parcours.VI_Email_CPV__c = 'clement.bouquin@ei-technologies.com';
        	insert parcours;
        
            VI_BAT02_RelanceCPV.execute();
        
            Test.stopTest();        
            List<VI_Parcours__c> listParcours =[SELECT id, VI_Email_Relance_CPV__c
                                                FROM VI_Parcours__c
                                               	Where VI_Date_envoi_email__c=YESTERDAY AND VI_Email_CPV__c!=NULL];
            system.debug('¤ listParcours '+listParcours);
            if (listParcours.size() > 0) {
                for(VI_Parcours__c p:listParcours){
                    system.assertEquals(donneesParcours.VI_EmailRelanceCPV1__c, p.VI_Email_Relance_CPV__c);
                }
            }
            
            parcours.VI_DateRelanceCPV1__c = system.today()-2;
            parcours.VI_DateRelanceCPV5__c = system.today();
        	update parcours;
            VI_BAT02_RelanceCPV.execute();
        }
    }
}