force-app/main/default/objects/VI_DonneesParcours__c/VI_DonneesParcours__c.object-meta.xml
<CustomObject>
    <description>Objet ayant pour objectif de stocker toutes les informations pouvant nécessiter une adaptation ou une mise à jour facile.</description>
    <label>Données Parcours</label>
    <nameField>
        <label>Nom de Données Parcours</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Données Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_EmailRelanceCPV1__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailRelanceCPV1__c</fullName>
    <description>Contenu du champ { VI_Email_Relance_CPV } de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  pour la première relance.</description>
    <label>Email Relance CPV 1</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_EmailRelanceCPV2__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailRelanceCPV2__c</fullName>
    <description>Contenu du champ { VI_Email_Relance_CPV } de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  pour la deuxième relance.</description>
    <label>Email Relance CPV 2</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_EmailRelanceCPV3__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailRelanceCPV3__c</fullName>
    <description>Contenu du champ { VI_Email_Relance_CPV } de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  pour la troisième relance.</description>
    <label>Email Relance CPV 3</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_EmailRelanceCPV4__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailRelanceCPV4__c</fullName>
    <description>Contenu du champ { VI_Email_Relance_CPV } de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  pour la quatrième relance.</description>
    <label>Email Relance CPV 4</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_EmailRelanceCPV5__c.field-meta.xml
<CustomField>
    <fullName>VI_EmailRelanceCPV5__c</fullName>
    <description>Contenu du champ { VI_Email_Relance_CPV } de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  pour la cinquième relance.</description>
    <label>Email Relance CPV 5</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_NomPartenaire__c.field-meta.xml
<CustomField>
    <fullName>VI_NomPartenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Champ qui permet de lier les données vente à un compte</description>
    <label>Nom du partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Données Parcours</relationshipLabel>
    <relationshipName>Donnees_Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ChoixParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_ChoixParcours__c</fullName>
    <description>Le prospect au téléphone effectue soit un changement de fournisseur (même adresse cible) soit un emménagement (nouvelle adresse)</description>
    <label>Choix de la situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
                <label>Emménager dans un nouveau logement</label>
            </value>
            <value>
                <fullName>CHF</fullName>
                <label>Changer de fournisseur pour Engie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Contact__c.field-meta.xml
<CustomField>
    <fullName>VI_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contient le contact utilisé dans ce parcours</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parcours</relationshipLabel>
    <relationshipName>Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Date_envoi_email__c.field-meta.xml
<CustomField>
    <fullName>VI_Date_envoi_email__c</fullName>
    <label>Date d&apos;envoi d&apos;email</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV1__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV1__c</fullName>
    <label>Date Relance CPV 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV2__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV2__c</fullName>
    <label>Date Relance CPV 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV3__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV3__c</fullName>
    <label>Date Relance CPV 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV4__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV4__c</fullName>
    <label>Date Relance CPV 4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV5__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV5__c</fullName>
    <label>Date Relance CPV 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Email_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Email_CPV__c</fullName>
    <description>Champ email supplémentaire en cas de volonté du client de donner une adresse email différente pour l&apos;envoi des CPV</description>
    <label>Email CPV</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Email_Relance_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Email_Relance_CPV__c</fullName>
    <description>Ce chant remplis la parti variable de l&apos;email template &quot;Email n°5 - Relance CPV&quot;  en étant égale aux champs VI_Email_Relance_CPV 1, 2, 3, 4 ou 5 de Donées Parcours</description>
    <label>Email Relance CPV</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_PartenaireRelieAuParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_PartenaireRelieAuParcours__c</fullName>
    <formula>CreatedBy.Contact.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partenaire relié au parcours</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Tech_relance_CPV__c.field-meta.xml
<CustomField>
    <fullName>VI_Tech_relance_CPV__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tech Relance CPV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_TechRelanceCpvParametrablemetier__c.field-meta.xml
<CustomField>
    <fullName>VI_TechRelanceCpvParametrablemetier__c</fullName>
    <formula>IF(
OR(
ISPICKVAL(
VI_Case__r.VI_StatutEnveloppe__c ,&quot;Signed&quot;
),
ISPICKVAL(
VI_Case__r.VI_StatutEnveloppe__c,&quot;Declined&quot;
),
VI_Stop_Relance__c=true
),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech relance cpv paramétrable métier</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_URL_IBAN_en_selfcare__c.field-meta.xml
<CustomField>
    <fullName>VI_URL_IBAN_en_selfcare__c</fullName>
    <label>URL IBAN en selfcare</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/VI_BAT02_RelanceCPV.cls
/*
*@Auhtor: Paul Ghoussoub
*@Description: Batch qui relance les mandats chaque jour
*@CreatedDate: 30/03/2021
*@LastModified: 20/10/2021
*/

global class VI_BAT02_RelanceCPV implements Database.Batchable<sObject>{
    global final String Query = 'SELECT Id, VI_DateRelanceCPV1__c, VI_DateRelanceCPV2__c, VI_DateRelanceCPV3__c, VI_DateRelanceCPV4__c, VI_DateRelanceCPV5__c, VI_TechRelanceCpvParametrablemetier__c, VI_Email_Relance_CPV__c, VI_PartenaireRelieAuParcours__c, VI_Contact__c, VI_Email_CPV__c, VI_Date_envoi_email__c FROM VI_Parcours__c WHERE VI_Date_envoi_email__c!=NULL AND VI_Email_CPV__c!=NULL AND VI_TechRelanceCpvParametrablemetier__c=false AND VI_ChoixParcours__c=\'CHF\'';
    global final String emailTemplateQuery='Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName =\'Email5Relancecpv\''; 
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('VI_BAT02_RelanceCPV starting...');
        return Database.getQueryLocator(Query);
    }
    
    public static void execute(){
        VI_BAT02_RelanceCPV relanceBacth = new VI_BAT02_RelanceCPV();
        Database.executeBatch(relanceBacth,50); 
    }
    
    global void execute(Database.BatchableContext bc, List<VI_Parcours__c> scope){
        List<Messaging.Email> emailsToSend=new List<Messaging.Email>();
        EmailTemplate emailTemplate = Database.query(emailTemplateQuery);
        Date todaysDate = Date.today();
        system.debug('Dans le batch');
        for(VI_Parcours__c parcours:scope){
            List<VI_DonneesParcours__c> donneeParcours;
            donneeParcours=[Select Id, VI_EmailRelanceCPV1__c, VI_EmailRelanceCPV2__c, VI_EmailRelanceCPV3__c, VI_EmailRelanceCPV4__c, VI_EmailRelanceCPV5__c, VI_NomPartenaire__r.Name From VI_DonneesParcours__c Where VI_NomPartenaire__r.Name=:parcours.VI_PartenaireRelieAuParcours__c];
            
            if (donneeParcours.size() > 0) {
                if (parcours.VI_DateRelanceCPV1__c == todaysDate) {
                	parcours.VI_Email_Relance_CPV__c = donneeParcours[0].VI_EmailRelanceCPV1__c;
                }
                else if(parcours.VI_DateRelanceCPV2__c == todaysDate) {
                    parcours.VI_Email_Relance_CPV__c = donneeParcours[0].VI_EmailRelanceCPV2__c;
                }
                else if(parcours.VI_DateRelanceCPV3__c == todaysDate) {
                    parcours.VI_Email_Relance_CPV__c = donneeParcours[0].VI_EmailRelanceCPV3__c;
                } 
                else if(parcours.VI_DateRelanceCPV4__c == todaysDate) {
                    parcours.VI_Email_Relance_CPV__c = donneeParcours[0].VI_EmailRelanceCPV4__c;
                } 
                else if(parcours.VI_DateRelanceCPV5__c == todaysDate) {
                    parcours.VI_Email_Relance_CPV__c = donneeParcours[0].VI_EmailRelanceCPV5__c;
                } 
            }
            
            if (!String.isBlank(parcours.VI_Email_Relance_CPV__c)){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTemplateID(emailTemplate.Id); 
                mail.setWhatId(parcours.Id);
                mail.setTargetObjectId(parcours.VI_Contact__c);
                mail.setTreatTargetObjectAsRecipient(false);
                mail.setSaveAsActivity(false);
                mail.setTreatBodiesAsTemplate(true);
                
                
                // Strings to hold the email addresses to which you are sending the email.
                String[] toAddresses = new String[] {parcours.VI_Email_CPV__c}; 
                // Assign the addresses for the To and CC lists to the mail object.
                mail.setToAddresses(toAddresses);
                
                // Specify the address used when the recipients reply to the email. 
                //mail.setReplyTo(parcours.VI_Email_CPV__c);
                
                OrgWideEmailAddress emailSender=[select Id, Address, DisplayName from OrgWideEmailAddress where Address='noreply@clients-particuliers.engie.fr'];
                // Specify the name used as the display name.
               	// mail.setSenderDisplayName(emailSender.DisplayName);
               	// mail.setSenderDisplayName('Engie EITECH');
                mail.setOrgWideEmailAddressId(emailSender.id);

                
                // Specify the subject line for your email address.
                mail.setSubject(emailTemplate.subject);
                String emailBody=emailTemplate.HtmlValue;
                //system.debug('emailBody '+emailBody);
                if(parcours.VI_Email_Relance_CPV__c != null && emailBody.contains('{!VI_Parcours__c.VI_URL_IBAN_en_selfcare__c}')){
            		system.debug('contains VI_Email_Relance_CPV__c');
            		emailBody= emailBody.replace('{!VI_Parcours__c.VI_Email_Relance_CPV__c}', parcours.VI_Email_Relance_CPV__c);
        		}
                //system.debug('emailBody '+emailBody);
                mail.setHtmlBody(emailBody);
                // Set to True if you want to BCC yourself on the email.
                mail.setBccSender(false);
                system.debug('before send email');
                // Send the email you have created.
                emailsToSend.add(mail);
                //if(!test.isRunningTest()){
                //    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                //}
                parcours.VI_Tech_relance_CPV__c=true;
                system.debug('after send email');
            }
        }
        if(!test.isRunningTest()){
            Messaging.sendEmail(emailsToSend);
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug('VI_BAT02_RelanceCPV ending...');
    }
}