force-app/main/default/objects/VI_DonneesParcours__c/VI_DonneesParcours__c.object-meta.xml
<CustomObject>
    <description>Objet ayant pour objectif de stocker toutes les informations pouvant nécessiter une adaptation ou une mise à jour facile.</description>
    <label>Données Parcours</label>
    <nameField>
        <label>Nom de Données Parcours</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Données Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_NomPartenaire__c.field-meta.xml
<CustomField>
    <fullName>VI_NomPartenaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Champ qui permet de lier les données vente à un compte</description>
    <label>Nom du partenaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Données Parcours</relationshipLabel>
    <relationshipName>Donnees_Parcours</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_RelanceCPV1_J__c.field-meta.xml
<CustomField>
    <fullName>VI_RelanceCPV1_J__c</fullName>
    <description>Première relance des CPV à J +</description>
    <label>Relance CPV 1 : J+</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_RelanceCPV2_J__c.field-meta.xml
<CustomField>
    <fullName>VI_RelanceCPV2_J__c</fullName>
    <description>Deuxième relance des CPV à J+</description>
    <label>Relance CPV 2 : J+</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_RelanceCPV3_J__c.field-meta.xml
<CustomField>
    <fullName>VI_RelanceCPV3_J__c</fullName>
    <description>Troisième relance des CPV à J+</description>
    <label>Relance CPV 3 : J+</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_RelanceCPV4_J__c.field-meta.xml
<CustomField>
    <fullName>VI_RelanceCPV4_J__c</fullName>
    <description>Quatrième relance CPV à J+</description>
    <label>Relance CPV 4 : J+</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_DonneesParcours__c/fields/VI_RelanceCPV5_J__c.field-meta.xml
<CustomField>
    <fullName>VI_RelanceCPV5_J__c</fullName>
    <description>Cinquième relance CPV à J+</description>
    <label>Relance CPV 5 : J+</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/VI_Parcours__c.object-meta.xml
<CustomObject>
    <description>Utilisé pour le parcours Pure Player du portail Partner Community</description>
    <label>Parcours</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Numéro du parcours</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VI_Parcours__c/fields/VI_ChoixParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_ChoixParcours__c</fullName>
    <description>Le prospect au téléphone effectue soit un changement de fournisseur (même adresse cible) soit un emménagement (nouvelle adresse)</description>
    <label>Choix de la situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM</fullName>
                <label>Emménager dans un nouveau logement</label>
            </value>
            <value>
                <fullName>CHF</fullName>
                <label>Changer de fournisseur pour Engie</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_Date_envoi_email__c.field-meta.xml
<CustomField>
    <fullName>VI_Date_envoi_email__c</fullName>
    <label>Date d&apos;envoi d&apos;email</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV1__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV1__c</fullName>
    <label>Date Relance CPV 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV2__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV2__c</fullName>
    <label>Date Relance CPV 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV3__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV3__c</fullName>
    <label>Date Relance CPV 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV4__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV4__c</fullName>
    <label>Date Relance CPV 4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_DateRelanceCPV5__c.field-meta.xml
<CustomField>
    <fullName>VI_DateRelanceCPV5__c</fullName>
    <label>Date Relance CPV 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VI_Parcours__c/fields/VI_PartenaireRelieAuParcours__c.field-meta.xml
<CustomField>
    <fullName>VI_PartenaireRelieAuParcours__c</fullName>
    <formula>CreatedBy.Contact.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partenaire relié au parcours</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VI_SM046_ParcoursBeforeUpdateHandler.cls
/*
*@Author: Clément Bouquin
*@Description: Mise à jour des champs parcours grâce au trigger Before
*@CreatedDate: 07/10/2021
*@LastModified: 07/10/2021
*/

public inherited sharing class VI_SM046_ParcoursBeforeUpdateHandler {
 
/*    
* @author Clément Bouquin
* @date 07/10/2021
* @description Mise à jour des champs parcours grâce au trigger Before
* @param parcourList, oldParcourMap
* @return void ( called from a trigger)
*/
    public static void ParcoursBeforeUpdate(List<VI_Parcours__c> parcourList, Map<ID,VI_Parcours__c> oldParcourMap) {
        System.debug('updateParcours: START with ' + parcourList.size() + ' parcour records');
        for (VI_Parcours__c parIter : parcourList) {
            if(oldParcourMap.get(parIter.Id).VI_Date_envoi_email__c != parIter.VI_Date_envoi_email__c){
                if (parIter.VI_ChoixParcours__c == 'CHF') {
                    List<VI_DonneesParcours__c> donneeParcours;
                    donneeParcours=[Select Id, VI_RelanceCPV1_J__c, VI_RelanceCPV2_J__c, VI_RelanceCPV3_J__c, VI_RelanceCPV4_J__c, VI_RelanceCPV5_J__c, VI_NomPartenaire__r.Name 
                                    From VI_DonneesParcours__c 
                                    Where VI_NomPartenaire__r.Name=:parIter.VI_PartenaireRelieAuParcours__c];
                    if (donneeParcours.size() > 0) {
                        system.debug('parIter.id :'+ parIter.Id);
                        if (donneeParcours[0].VI_RelanceCPV1_J__c != null){
  							parIter.VI_DateRelanceCPV1__c = parIter.VI_Date_envoi_email__c.adddays(donneeParcours[0].VI_RelanceCPV1_J__c.intValue());
                            system.debug('coucou paul');
                        }
                        if (donneeParcours[0].VI_RelanceCPV2_J__c != null){
  							parIter.VI_DateRelanceCPV2__c = parIter.VI_Date_envoi_email__c.adddays(donneeParcours[0].VI_RelanceCPV2_J__c.intValue());
                        }
                        if (donneeParcours[0].VI_RelanceCPV3_J__c != null){
  							parIter.VI_DateRelanceCPV3__c = parIter.VI_Date_envoi_email__c.adddays(donneeParcours[0].VI_RelanceCPV3_J__c.intValue());
                        }
                        if (donneeParcours[0].VI_RelanceCPV4_J__c != null){
  							parIter.VI_DateRelanceCPV4__c = parIter.VI_Date_envoi_email__c.adddays(donneeParcours[0].VI_RelanceCPV4_J__c.intValue());
                        }
                        if (donneeParcours[0].VI_RelanceCPV5_J__c != null){
  							parIter.VI_DateRelanceCPV5__c = parIter.VI_Date_envoi_email__c.adddays(donneeParcours[0].VI_RelanceCPV5_J__c.intValue());
                        }
                    }
                }
            }
            System.debug('parIter.VI_DateRelanceCPV1__c :' + parIter.VI_DateRelanceCPV1__c);
            System.debug('parIter.VI_DateRelanceCPV2__c :' + parIter.VI_DateRelanceCPV2__c);
            System.debug('parIter.VI_DateRelanceCPV3__c :' + parIter.VI_DateRelanceCPV3__c);
            System.debug('parIter.VI_DateRelanceCPV4__c :' + parIter.VI_DateRelanceCPV4__c);
            System.debug('parIter.VI_DateRelanceCPV5__c :' + parIter.VI_DateRelanceCPV5__c);
        }
        System.debug('update Parcours data : END');  
    }
}