force-app/main/default/objects/HP_UserHistory__c/HP_UserHistory__c.object-meta.xml
<CustomObject>
    <label>HP_UserHistory</label>
    <nameField>
        <label>HP_UserHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP_UserHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_UserHistory__c/fields/HP_Date__c.field-meta.xml
<CustomField>
    <fullName>HP_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HP_UserHistory__c/fields/HP_DureeTraitement__c.field-meta.xml
<CustomField>
    <fullName>HP_DureeTraitement__c</fullName>
    <label>Durée de traitement</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_UserHistory__c/fields/HP_NombreTraitements__c.field-meta.xml
<CustomField>
    <fullName>HP_NombreTraitements__c</fullName>
    <label>Nombre de traitements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_UserHistory__c/fields/HP_TempsPresence__c.field-meta.xml
<CustomField>
    <fullName>HP_TempsPresence__c</fullName>
    <label>Temps de présence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_UserHistory__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HP_UserHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HP_EM040_UserHistory.cls
public with sharing  class HP_EM040_UserHistory {

    public static HP_UserHistory__c createUserHistory(String userId, Integer numberOfTreatments, Decimal somme, Decimal dureeTraitement, Date selectedDate) {
        HP_UserHistory__c userHistory = new HP_UserHistory__c();
               
        userHistory.User__c =userId;
        userHistory.HP_Date__c = selectedDate;
        userHistory.HP_NombreTraitements__c	 = numberOfTreatments;
        userHistory.HP_TempsPresence__c = somme;
        userHistory.HP_DureeTraitement__c = dureeTraitement;
        
        return userHistory; 
    }

    public static void saveUserHistoryList(List<HP_UserHistory__c> userHistoryList) {
        if(userHistoryList != null && userHistoryList.size() > 0) {
            insert userHistoryList;
        }
    }
}