force-app/main/default/objects/HP_Case_Action__mdt/HP_Case_Action__mdt.object-meta.xml
<CustomObject>
    <description>Metadata pour gérer les HP Case Actions</description>
    <label>HP Case Action</label>
    <pluralLabel>HP Case Actions</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_Button_Label__c.field-meta.xml
<CustomField>
    <fullName>HP_Button_Label__c</fullName>
    <description>HP_Button_Label</description>
    <inlineHelpText>HP_Button_Label</inlineHelpText>
    <label>Button Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_Has_Paramater__c.field-meta.xml
<CustomField>
    <fullName>HP_Has_Paramater__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Paramater</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>HP_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>HP_Is_Active</description>
    <inlineHelpText>HP_Is_Active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_LWC_Name__c.field-meta.xml
<CustomField>
    <fullName>HP_LWC_Name__c</fullName>
    <description>HP_LWC_Name</description>
    <inlineHelpText>HP_LWC_Name</inlineHelpText>
    <label>LWC Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_Order__c.field-meta.xml
<CustomField>
    <fullName>HP_Order__c</fullName>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_Paramater__c.field-meta.xml
<CustomField>
    <fullName>HP_Paramater__c</fullName>
    <label>Paramater</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>HP_Record_Type__c</fullName>
    <description>HP_Record_Type</description>
    <inlineHelpText>HP_Record_Type</inlineHelpText>
    <label>Record Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HP_Case_Action__mdt/fields/HP_Type__c.field-meta.xml
<CustomField>
    <fullName>HP_Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LWC</fullName>
                <default>true</default>
                <label>LWC</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_SM065_CaseActionsController.cls
/**
 * @description       : 
 * @author            : Hemdene Ben Hammouda
 * @group             : 
 * @last modified on  : 07-27-2021
 * @last modified by  : Hemdene Ben Hammouda
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   07-22-2021   Hemdene Ben Hammouda   Initial Version
**/
public with sharing class HP_SM065_CaseActionsController {

    @AuraEnabled(cacheable=true)
    public static List<HP_Case_Action__mdt> loadButtons(String caseId){
        System.debug('HP_SM065_CaseActionsController.loadButtons() | Method Start');
        List<HP_Case_Action__mdt> caseActions = new List<HP_Case_Action__mdt>(); 
        try{
            String rtDevNameCondition = '%'+[SELECT RecordType.DeveloperName,Id from Case where Id = :caseId limit 1 ].RecordType.DeveloperName+'%' ;
            caseActions = [SELECT DeveloperName, HP_Button_Label__c, HP_Has_Paramater__c, HP_Paramater__c, HP_Is_Active__c, HP_LWC_Name__c, HP_Order__c, HP_Record_Type__c,HP_Type__c from HP_Case_Action__mdt where HP_Record_Type__c like :rtDevNameCondition Order By HP_Order__c ASC];
            System.debug('HP_SM065_CaseActionsController.loadButtons() | Method Start');
            return caseActions;
            
        }catch (Exception ex) {
            System.debug('HP_SM065_CaseActionsController.loadButtons() | Error : ' + ex.getMessage());
            throw new AuraHandledException(ex.getMessage());
        }
        
    }

}