force-app/main/default/objects/ByPassSettings__c/ByPassSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Gérer les ByPass au niveau des triggers</description>
    <label>ByPassSettings</label>
</CustomObject>

force-app/main/default/objects/ByPassSettings__c/fields/ValidationRule__c.field-meta.xml
<CustomField>
    <fullName>ValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>@Project: MyPower
@Description: ByPass des validation rules</description>
    <label>ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/HP_PortailCanal__c.object-meta.xml
<CustomObject>
    <label>Canal</label>
    <nameField>
        <label>Canal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canaux</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_PaiementCB__c.field-meta.xml
<CustomField>
    <fullName>Droit_PaiementCB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mode de paiement CB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_ParcoursEmDm__c.field-meta.xml
<CustomField>
    <fullName>Droit_ParcoursEmDm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parcours EM/DM (avec résiliation)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteChf1Ex__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteChf1Ex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente CHF / 1ex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteChf2Ex__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteChf2Ex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente CHF / 2ex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteEm1Ex__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteEm1Ex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente EM / 1ex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteEm__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteEm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente EM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Liens_SF__c.field-meta.xml
<CustomField>
    <fullName>HP_Liens_SF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Liens SF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Modif_ventes__c.field-meta.xml
<CustomField>
    <fullName>HP_Modif_ventes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_Modif_ventes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Paiement_prlvt__c.field-meta.xml
<CustomField>
    <fullName>HP_Paiement_prlvt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_Paiement_prlvt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Unshort_Lien__c.field-meta.xml
<CustomField>
    <fullName>HP_Unshort_Lien__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unshort Lien</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Vente_Stay__c.field-meta.xml
<CustomField>
    <fullName>HP_Vente_Stay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente Stay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Visu_docs__c.field-meta.xml
<CustomField>
    <fullName>HP_Visu_docs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_Visu_docs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailPrestataire__c/HP_PortailPrestataire__c.object-meta.xml
<CustomObject>
    <label>Prestataire</label>
    <nameField>
        <label>Prestataire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestataires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailPrestataire__c/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Canal associé</label>
    <referenceTo>HP_PortailCanal__c</referenceTo>
    <relationshipLabel>Prestataires</relationshipLabel>
    <relationshipName>Prestataires</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_PortailPrestataire__c/fields/IdPrestataire__c.field-meta.xml
<CustomField>
    <fullName>IdPrestataire__c</fullName>
    <externalId>true</externalId>
    <label>ID prestataire</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/HP_PortailUtilisateur__c.object-meta.xml
<CustomObject>
    <label>Utilisateur Portail</label>
    <nameField>
        <displayFormat>UP-{00000}</displayFormat>
        <label>Utilisateur Portail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilisateurs Portail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <formula>Prestataire__r.Canal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Civilite__c.field-meta.xml
<CustomField>
    <fullName>Civilite__c</fullName>
    <label>Civilité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Format email</inlineHelpText>
    <label>Login</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <inlineHelpText>Min 8 caractères dont : 1 min, 1 maj, 1 spécial, 1 chiffre</inlineHelpText>
    <label>Mot de passe</label>
    <length>30</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>Prénom</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Prestataire__c.field-meta.xml
<CustomField>
    <fullName>Prestataire__c</fullName>
    <label>Prestataire associé</label>
    <referenceTo>HP_PortailPrestataire__c</referenceTo>
    <relationshipLabel>Utilisateurs Portail</relationshipLabel>
    <relationshipName>Utilisateurs_Portail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conseiller</fullName>
                <default>true</default>
                <label>Conseiller</label>
            </value>
            <value>
                <fullName>Superviseur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_WS001_PortailAuth_TEST.cls
/**
 * @File Name          : HP_WS001_PortailAuth_TEST.cls
 * @Description        : Classe de test de HP_WS001_PortailAuth
 * @Author             : Vincent Albiser
 * @Group              : 
 * @Last Modified By   : Badr Eddine Belkarchi
 * @Last Modified On   : 01-24-2022
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    10/12/2019   Vincent Albiser     Initial Version
**/
@isTest
public class HP_WS001_PortailAuth_TEST {

    /**
    * @description testSetup
    * @author Vincent Albiser | 10/12/2019 
    * @return void 
    **/
    @testSetup static void dataSetup(){
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){
            HP_PortailCanal__c canal = (HP_PortailCanal__c)HP_UTIL_SmartFactory.createSObject('HP_PortailCanal__c', null, new Map<String, Object>{
                'Name' => 'CRC-ENGIE',
                'Droit_VenteEm__c' => true,
                'Droit_PaiementCB__c' => true,
                'Droit_ParcoursEmDm__c' => true,
                'Droit_VenteChf1Ex__c' => true,
                'Droit_VenteChf2Ex__c' => true,
                'Droit_VenteEm1Ex__c' => true,
                'HP_Paiement_prlvt__c' => true,
                'HP_Visu_docs__c' => true,
                'HP_Modif_ventes__c' => true,
                'HP_Liens_SF__c' => true,
                'HP_Vente_Stay__c' => true,
                'HP_Unshort_Lien__c' => true
            }, null, null, null);
            insert canal;
    
            HP_PortailPrestataire__c presta = (HP_PortailPrestataire__c)HP_UTIL_SmartFactory.createSObject('HP_PortailPrestataire__c', null, new Map<String, Object>{
                'IdPrestataire__c' => 'Happe',
                'Name' => 'Happe',
                'Canal__c' => canal.Id
            }, null, null, null);
    
            insert presta;
    
            Profile systemAdminProfile = [SELECT Id FROM Profile WHERE Name = 'HP_SystemAdmin'];
            insert new ByPassSettings__c(SetupOwnerId = systemAdminProfile.Id, ValidationRule__c = true);
            
            HP_PortailUtilisateur__c utilisateur = (HP_PortailUtilisateur__c)HP_UTIL_SmartFactory.createSObject('HP_PortailUtilisateur__c', null, new Map<String, Object>{
                'Login__c'        => 'Hap001',
                'Password__c'     => '123456',
                'Role__c'         => 'Conseiller',
                'Prestataire__c'  => presta.Id,
                'Nom__c'			=> 'Test Nom',
                'Prenom__c'		=> 'Test Prénom',
                'Civilite__c'		=> 'Mr'
            }, null, null, null);
            insert utilisateur; 
        }        
              
    }

    /**
    * @description checkAuth_200
    * @author Vincent Albiser | 10/12/2019 
    * @return void 
    **/
    @isTest static void checkAuth_200() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Test.startTest();

            String json = '{"login": "Hap001"}';

            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/services/apexrest/portailAdmin/auth'; 
            req.httpMethod = 'POST';
            req.addHeader('Content-Type', 'application/json');            
            req.requestBody = Blob.valueOf(json);   

            RestContext.request = req;       
            RestContext.response = res;    

            HP_WS001_PortailAuth.checkAuth();

            System.assert(HP_HttpStatus.OK == res.statusCode, 'Echec checkAuth_200 statusCode');
            
        Test.stopTest(); 
        }
        
    }

    /**
    * @description checkAuth_401
    * @author Vincent Albiser | 10/12/2019 
    * @return void 
    **/
    @isTest static void checkAuth_401() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Test.startTest();

            String json = '{"login": "HaP001"}';

            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/services/apexrest/portailAdmin/auth'; 
            req.httpMethod = 'POST';
            req.addHeader('Content-Type', 'application/json');            
            req.requestBody = Blob.valueOf(json);   

            RestContext.request = req;       
            RestContext.response = res;    

            HP_WS001_PortailAuth.checkAuth();

            System.assert(HP_HttpStatus.UNAUTHTORIZED == res.statusCode, 'Echec checkAuth_401 statusCode');
            
        Test.stopTest();
        }
         
    }

    /**
    * @description checkAuth_400
    * @author Vincent Albiser | 10/12/2019 
    * @return void 
    **/
    @isTest static void checkAuth_400() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Test.startTest();

            String json = '{"login": "Hap}';

            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/services/apexrest/portailAdmin/auth'; 
            req.httpMethod = 'POST';
            req.addHeader('Content-Type', 'application/json');            
            req.requestBody = Blob.valueOf(json);   

            RestContext.request = req;       
            RestContext.response = res;    

            HP_WS001_PortailAuth.checkAuth();

            System.assert(HP_HttpStatus.BAD_REQUEST == res.statusCode, 'Echec checkAuth_400 statusCode');
            
        Test.stopTest(); 
    }
        }
        
}