force-app/main/default/objects/ByPassSettings__c/ByPassSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Gérer les ByPass au niveau des triggers</description>
    <label>ByPassSettings</label>
</CustomObject>

force-app/main/default/objects/ByPassSettings__c/fields/AccountTrigger__c.field-meta.xml
<CustomField>
    <fullName>AccountTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Gérer les bypass au niveau su trigger Account</description>
    <label>AccountTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ByPassSettings__c/fields/CaseTrigger__c.field-meta.xml
<CustomField>
    <fullName>CaseTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Gérer les bypass au niveau su trigger Case</description>
    <label>CaseTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ByPassSettings__c/fields/ContactTrigger__c.field-meta.xml
<CustomField>
    <fullName>ContactTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ContactTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ByPassSettings__c/fields/ProcessBuilder__c.field-meta.xml
<CustomField>
    <fullName>ProcessBuilder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>@Project: MyPower
@Description: ByPass des process builders</description>
    <label>ProcessBuilder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ByPassSettings__c/fields/ValidationRule__c.field-meta.xml
<CustomField>
    <fullName>ValidationRule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>@Project: MyPower
@Description: ByPass des validation rules</description>
    <label>ValidationRule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HP_BAT026_CheckKeywordOnCases_TEST.cls
/**
 * @description       : 
 * @author            : Badr Eddine Belkarchi
 * @group             : 
 * @last modified on  : 02-01-2022
 * @last modified by  : Badr Eddine Belkarchi
**/
@isTest
public with sharing class HP_BAT026_CheckKeywordOnCases_TEST {
    
    @testSetup
    static void setup() {

        insert new ByPassSettings__c(
            SetupOwnerId = UserInfo.getUserId(),
            ValidationRule__c 	= true,
            ProcessBuilder__c 	= true,
            AccountTrigger__c 	= true,
            ContactTrigger__c 	= true,
            CaseTrigger__c      = true
        );
    
        List < sObject > ls = Test.loadData(Case.sObjectType, 'HP_TestData_Cases'); 
    }

    @isTest static void execute() {
        Test.startTest();
        HP_BAT026_CheckBlacklistKeywordOnCases.execute();
        Test.stopTest();
    }

    @isTest static void HP_BAT026_CheckKeywordOnCases_TEST_Schedule() {
        Test.startTest();
        final String jobName = 'HP_BAT026_CheckBlacklistKeywordOnCases'+System.Math.random()*1000;
        final String cronExp = '0 0 22 ? * * *';
        HP_BAT026_CheckBlacklistKeywordOnCases.launchNewScheduler(cronExp,jobName);
        Test.stopTest();
    }
}