force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Base de connaissance</label>
    <pluralLabel>Base de connaissance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Categorie_Consigne__c.field-meta.xml
<CustomField>
    <fullName>Categorie_Consigne__c</fullName>
    <description>@description: champ pour la catégorie de consigne Knowledge
@projet: smile</description>
    <label>Categorie Consigne</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Modification des données personnelles</fullName>
            </value>
            <value>
                <fullName>Modification/annulation des OPS</fullName>
            </value>
            <value>
                <fullName>Communication Relevé Index</fullName>
            </value>
            <value>
                <fullName>Demande de duplicata</fullName>
            </value>
            <value>
                <fullName>Suivi activation</fullName>
            </value>
            <value>
                <fullName>Délai de paiement</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
            <value>
                <fullName>Historique factures</fullName>
            </value>
            <value>
                <fullName>Historique conso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Etape_de_l_omniscript__c.field-meta.xml
<CustomField>
    <fullName>Etape_de_l_omniscript__c</fullName>
    <label>Etape de l&apos;omniscript</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONTEXTE</fullName>
            </value>
            <value>
                <fullName>LOGEMENT</fullName>
            </value>
            <value>
                <fullName>CHOIX DE L&apos;OFFRE</fullName>
            </value>
            <value>
                <fullName>SERVICES DE GESTION</fullName>
            </value>
            <value>
                <fullName>CREATION OPS</fullName>
            </value>
            <value>
                <fullName>CRITÈRES DE NON RECEVABILITÉ DE L&apos;INDEX</fullName>
            </value>
            <value>
                <fullName>PROMOTION DU SELFCARE</fullName>
            </value>
            <value>
                <fullName>CONSIGNES MÉTIERS</fullName>
            </value>
            <value>
                <fullName>TRAITEMENT DEMANDE</fullName>
            </value>
            <value>
                <fullName>SYNTHÈSE OPS</fullName>
            </value>
            <value>
                <fullName>VISUALISATION DE LA PC / DES CPV</fullName>
            </value>
            <value>
                <fullName>CRÉATION OPS</fullName>
            </value>
            <value>
                <fullName>VÉRIFICATION DE L&apos;ACTIVATION DU CONTRAT</fullName>
            </value>
            <value>
                <fullName>SERVICES AFFINITAIRES</fullName>
            </value>
            <value>
                <fullName>RÉCAPITULATIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SM_BAT04_KnowledgeSyncDataCategoryTEST.cls
@IsTest
public with sharing class SM_BAT04_KnowledgeSyncDataCategoryTEST {
    
    @isTest
    static void testKnowldgeSyncDataCategory() {
        //create article 
        Id articleRId = [SELECT Id,Name FROM RecordType WHERE sObjectType='Knowledge__kav' and Name Like '%Article%'].Id;
        Knowledge__kav art = new Knowledge__kav(Title= 'article de test',UrlName='article-de-test',RecordTypeId = articleRId );
        insert art;

        //create data category for article 
        List<Knowledge__DataCategorySelection> dtselectionList = new List<Knowledge__DataCategorySelection>();
        Knowledge__DataCategorySelection kavDC1 = new Knowledge__DataCategorySelection();
        kavDC1.DataCategoryGroupName = 'Smile';
        kavDC1.DataCategoryName = 'Offre_ChF';
        kavDC1.ParentId = art.id;
        dtselectionList.add(kavDC1);

        Knowledge__DataCategorySelection kavDC2 = new Knowledge__DataCategorySelection();
        kavDC2.DataCategoryGroupName = 'Smile';
        kavDC2.DataCategoryName = 'Historique_factures';
        kavDC2.ParentId = art.id;
        dtselectionList.add(kavDC2);

        insert dtselectionList;
        String   knowledgeId = [SELECT KnowledgeArticleId FROM Knowledge__kav WHERE Id =: art.Id].KnowledgeArticleId;
                    System.debug('article id ' + knowledgeId);
        KbManagement.PublishingService.publishArticle(knowledgeId, true);

        Test.startTest();

        SM_BAT04_KnowledgeSyncDataCategory obj = new SM_BAT04_KnowledgeSyncDataCategory();
        DataBase.executeBatch(obj); 
    
        Test.stopTest();

        Knowledge__kav articleAfterBatch  = [SELECT id,Categorie_Consigne__c,Etape_de_l_omniscript__c FROM Knowledge__kav WHERE Title='article de test' limit  1];
        
        System.assertEquals(articleAfterBatch.Categorie_Consigne__c.contains('Historique factures'),true);
        System.assertEquals(articleAfterBatch.Categorie_Consigne__c.contains('Changement d\'offre'),true);
        System.assertEquals(articleAfterBatch.Etape_de_l_omniscript__c,'CHOIX DE L\'OFFRE');

        // Pour couverture de la classe test
        SM_BAT04_KnowledgeSyncDataCategorySch batchSch = new SM_BAT04_KnowledgeSyncDataCategorySch();
        batchSch.execute(null);
    }
}