force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Base de connaissance</label>
    <pluralLabel>Base de connaissance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Categorie_Consigne__c.field-meta.xml
<CustomField>
    <fullName>Categorie_Consigne__c</fullName>
    <description>@description: champ pour la catégorie de consigne Knowledge
@projet: smile</description>
    <label>Categorie Consigne</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acquisition</fullName>
            </value>
            <value>
                <fullName>Modification des données personnelles</fullName>
            </value>
            <value>
                <fullName>Modification/annulation des OPS</fullName>
            </value>
            <value>
                <fullName>Communication Relevé Index</fullName>
            </value>
            <value>
                <fullName>Demande de duplicata</fullName>
            </value>
            <value>
                <fullName>Suivi activation</fullName>
            </value>
            <value>
                <fullName>Délai de paiement</fullName>
            </value>
            <value>
                <fullName>Résiliation</fullName>
            </value>
            <value>
                <fullName>Historique factures</fullName>
            </value>
            <value>
                <fullName>Historique conso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Cle_Migration__c.field-meta.xml
<CustomField>
    <fullName>Cle_Migration__c</fullName>
    <description>@description: clé externe permettant de gérer le mapping dans les insert OS
@projet: smile</description>
    <label>Cle Migration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/Insert_Omniscript.recordType-meta.xml
<RecordType>
    <fullName>Insert_Omniscript</fullName>
    <active>true</active>
    <description>Consignes métiers organisées par thématique / parcours</description>
    <label>Insert Omniscript</label>
</RecordType>

force-app/main/default/classes/SM_AP56_KnowledgeArticle_TEST.cls
@isTest
public with sharing class SM_AP56_KnowledgeArticle_TEST {
    @IsTest(SeeAllData = false)
    static void getArticle_TEST(){
        // Insert les articles   Categorie_Consigne__c ='Acquisition',
        List<Knowledge__kav> articles = new List<Knowledge__kav>();

        for(Integer i = 0 ; i < 10 ; i++){
            Knowledge__kav a = new Knowledge__kav(
                Title = 'Title ' + i,
                Summary = 'Summary ' + i,
                URLName = 'engie'+i,
                Cle_Migration__c = String.valueOf(i),
                RecordTypeId = SObjectType.Knowledge__kav.getRecordTypeInfosByDeveloperName().get('Insert_Omniscript').getRecordTypeId()
            );
            articles.add(a); 
        }

        insert articles;

        articles = [SELECT Id, KnowledgeArticleId FROM Knowledge__kav WHERE Id IN: articles];

        for(Knowledge__kav anArticle : articles){
            String articleId = anArticle.KnowledgeArticleId;
            System.debug('*** article : ' + anArticle);
            KbManagement.PublishingService.publishArticle(articleId, true);
        }

        Map<String, Object> outputMap = new Map<String, Object>();
        Map<String, Object> inputMap = new Map<String, Object>();
        inputMap.put('CategorieKnowledge','Acquisition');
        SM_AP56_KnowledgeArticle knowledgeCtrl = new SM_AP56_KnowledgeArticle();
        knowledgeCtrl.invokeMethod('getArticle', null, outputMap, null);
        knowledgeCtrl.invokeMethod('getArticleByCategorie', inputMap, outputMap, null);
        knowledgeCtrl.invokeMethod('getArticleByOffre', null, outputMap, null);

        outputMap = (Map<String, Object>) outputMap.get('articles');

        //System.assertEquals(articles.size(), outputMap.size());
                         
    }
}