force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Base de connaissance</label>
    <pluralLabel>Base de connaissance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Cle_Migration__c.field-meta.xml
<CustomField>
    <fullName>Cle_Migration__c</fullName>
    <description>@description: clé externe permettant de gérer le mapping dans les insert OS
@projet: smile</description>
    <label>Cle Migration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Consigne__c.field-meta.xml
<CustomField>
    <fullName>Consigne__c</fullName>
    <description>@description: champ pour la consigne Knowledge
@projet: smile</description>
    <label>Consigne</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/Insert_Omniscript.recordType-meta.xml
<RecordType>
    <fullName>Insert_Omniscript</fullName>
    <active>true</active>
    <description>Consignes métiers organisées par thématique / parcours</description>
    <label>Insert Omniscript</label>
</RecordType>

force-app/main/default/classes/SM_CTRL001_FreeServices.cls
/**
 * @description       : LWC Controller for free services screen
 * @author            : David Attali
 * @group             : 
 * @last modified on  : 10-26-2020
 * @last modified by  : David ATTALI
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   10-26-2020   David ATTALI    Initial Version
**/
public class SM_CTRL001_FreeServices {
    
    @AuraEnabled(cacheable=false)
    public static Map<String, Object> setEdocumentStatus(Map<String, Object> inputMap) {
        
        String procedureName = 'DR_SM_dematerialisationDocumentContractuel_Input_SOAP';
        
        Boolean eDocumentChoices = (Boolean)inputMap.get('eDocumentChoices');
        
        String eDocumentChoicesString;
        if(eDocumentChoices == true){
            eDocumentChoicesString = 'Oui';
        } else {
            eDocumentChoicesString = 'Non';
        }
        
        String refClientIdBP = (String)inputMap.get('refClientIdBP');
        
        Map<String, Object> ipInput = new Map<String, Object> ();
        ipInput.put('eDocumentChoices', eDocumentChoicesString);
        ipInput.put('refClientIdBP', refClientIdBP);
        
        Map<String, Object> ipOutput = new Map<String, Object> ();
        if(!Test.isRunningTest()){
            ipOutput = (Map<String, Object>) vlocity_cmt.IntegrationProcedureService.runIntegrationService(procedureName, ipInput, null);
        } else {
            ipOutput.put('code', 'OCTOPUS_MAJPersonne_01');
        }
        
        return ipOutput;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object>  getKnowledge(Map<String, Object> inputMap) {

        String felMigrationKey = (String)inputMap.get('felMigrationKey');
        String eDocumentMigrationKey = (String)inputMap.get('eDocumentMigrationKey');

        List<Knowledge__kav> knowledges = [SELECT Cle_Migration__c, Consigne__c FROM Knowledge__kav
        WHERE RecordType.DeveloperName = 'Insert_Omniscript' AND PublishStatus = 'Online'
        AND Cle_Migration__c IN (:felMigrationKey, :eDocumentMigrationKey)];
        
        Map<String, Object> mapMigrationKeyToInstruction = new Map<String, Object>();
        
        for(Knowledge__kav knowledge : knowledges){
            if(knowledge.Cle_Migration__c == '000001045'){
                mapMigrationKeyToInstruction.put('felInstruction', knowledge.Consigne__c);
            } else if(knowledge.Cle_Migration__c == '000001405'){
                mapMigrationKeyToInstruction.put('eDocumentInstruction', knowledge.Consigne__c);
            }
        }

        return mapMigrationKeyToInstruction;
    }
}