force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Base de connaissance</label>
    <pluralLabel>Base de connaissance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Cle_Migration__c.field-meta.xml
<CustomField>
    <fullName>Cle_Migration__c</fullName>
    <description>@description: clé externe permettant de gérer le mapping dans les insert OS
@projet: smile</description>
    <label>Cle Migration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Consigne__c.field-meta.xml
<CustomField>
    <fullName>Consigne__c</fullName>
    <description>@description: champ pour la consigne Knowledge
@projet: smile</description>
    <label>Consigne</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/Insert_Omniscript.recordType-meta.xml
<RecordType>
    <fullName>Insert_Omniscript</fullName>
    <active>true</active>
    <description>Consignes métiers organisées par thématique / parcours</description>
    <label>Insert Omniscript</label>
</RecordType>

force-app/main/default/classes/SM_CTRL004_KnowledgeForLWC.cls
/**
 * @description       : Classe à utiliser pour la récupèration des articles Knowlegde dans les parcours LWC
 * @author            : Raouaa JMOUR
 * @group             : 
 * @last modified on  : 18-01-2021
 * @last modified by  : Raouaa JMOUR 
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   18-01-2021   Raouaa JMOUR    Initial Version
**/

public class SM_CTRL004_KnowledgeForLWC {
 

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getArticleByCleMigration(Map < String, Object > inputMap) {
         String cleMigrationArticle = (String) inputMap.get('cleMigration');
        Knowledge__kav article =[SELECT Cle_Migration__c,Id, Consigne__c FROM Knowledge__kav WHERE RecordType.DeveloperName = 'Insert_Omniscript' AND Cle_Migration__c IN (:cleMigrationArticle) LIMIT 1];
        
        Map < String, Object > outMap = new Map < String, Object >();

        outMap.put('article',article.Consigne__c);

        return outMap;
    }

    
}