force-app/main/default/objects/SM_Digsvc__c/SM_Digsvc__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration for the community self service login component</description>
    <label>SM_Digsvc</label>
</CustomObject>

force-app/main/default/objects/SM_Digsvc__c/fields/Communityname__c.field-meta.xml
<CustomField>
    <fullName>Communityname__c</fullName>
    <label>Community name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Digsvc__c/fields/communityurl__c.field-meta.xml
<CustomField>
    <fullName>communityurl__c</fullName>
    <description>@project : Smile / @description : contiendra l&apos;URL de la communauté sur laquelle se connecter</description>
    <label>communityurl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Digsvc__c/fields/instancetype__c.field-meta.xml
<CustomField>
    <fullName>instancetype__c</fullName>
    <description>@project : SMILE / @description permet de savoir si on est sur une org de prod / sandbox</description>
    <label>instancetype</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Digsvc__c/fields/orgurl__c.field-meta.xml
<CustomField>
    <fullName>orgurl__c</fullName>
    <description>url de l&apos;org dans laquelle se logguer et qui contient community</description>
    <label>orgurl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Digsvc__c/fields/striss__c.field-meta.xml
<CustomField>
    <fullName>striss__c</fullName>
    <description>champ de la connected app pour le sso</description>
    <label>striss</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Digsvc__c/fields/usrnamepostfix__c.field-meta.xml
<CustomField>
    <fullName>usrnamepostfix__c</fullName>
    <description>postfix pour le nom des users cree a partir des contacts pour le self service community</description>
    <label>usrnamepostfix</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_Digsvc__c/fields/xdusr__c.field-meta.xml
<CustomField>
    <fullName>xdusr__c</fullName>
    <description>nom du compte technique qui sert pour creer des utilisateurs dynamiquement, compte de synchronisation entre systeme aussi utilise pour les webservices xdata</description>
    <label>xdusr</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_AP57_ParticulierSSOController_TEST.cls
@isTest
private class SM_AP57_ParticulierSSOController_TEST
{
	@isTest
	static void auth_TEST(){

		SM_Digsvc__c ds = new SM_Digsvc__c();
        ds.orgurl__c = 'https://test.my.salesforce.com';
        ds.striss__c = 'ClientSecret';
        ds.usrnamepostfix__c = 'digital.engie.com';
        ds.xdusr__c = UserInfo.getUserName();  
        ds.communityUrl__c = 'https://randomurl.my.salesforce.com';  
        ds.instanceType__c = 'test';   
        ds.communityName__c = 'digital';

        insert ds;


		String token = 'sJZxdmRMoxM/jzMmNx1MmxoWO8XvS07n1Ppj/MgFM/rJ2ldkNJvkpkLZaBMEUZlRW71ubLMSC2/Yk/sdG62DiFjUQ3WzqJG0hkn0eBZL2Jf4YPYIR8XU4ChAcneyS3iL1w+EkEimHmzWGIjCSHR8Jw==';
		// Correspond à refbp=0306502365&nomBP=ISOIRD&parcoursId=smileModificationRdvDistributeur&dateEnvoiEmail=1549882525000
		ApexPages.CurrentPage().getParameters().put('token', token);
		SM_AP57_ParticulierSSOController authCtrl = new SM_AP57_ParticulierSSOController();
		authCtrl.particulierAuth();
	}
}