force-app/main/default/objects/HP_PortailCanal__c/HP_PortailCanal__c.object-meta.xml
<CustomObject>
    <label>Canal</label>
    <nameField>
        <label>Canal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canaux</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_PaiementCB__c.field-meta.xml
<CustomField>
    <fullName>Droit_PaiementCB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mode de paiement CB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_ParcoursEmDm__c.field-meta.xml
<CustomField>
    <fullName>Droit_ParcoursEmDm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Parcours EM/DM (avec résiliation)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteChf1Ex__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteChf1Ex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente CHF / 1ex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteChf2Ex__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteChf2Ex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente CHF / 2ex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteEm1Ex__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteEm1Ex__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente EM / 1ex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Droit_VenteEm__c.field-meta.xml
<CustomField>
    <fullName>Droit_VenteEm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vente EM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Modif_ventes__c.field-meta.xml
<CustomField>
    <fullName>HP_Modif_ventes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_Modif_ventes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Paiement_prlvt__c.field-meta.xml
<CustomField>
    <fullName>HP_Paiement_prlvt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_Paiement_prlvt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/HP_Visu_docs__c.field-meta.xml
<CustomField>
    <fullName>HP_Visu_docs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HP_Visu_docs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailCanal__c/fields/Visu_docs_s2__c.field-meta.xml
<CustomField>
    <fullName>Visu_docs_s2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visu docs s2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HP_PortailPrestataire__c/HP_PortailPrestataire__c.object-meta.xml
<CustomObject>
    <label>Prestataire</label>
    <nameField>
        <label>Prestataire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prestataires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailPrestataire__c/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Canal associé</label>
    <referenceTo>HP_PortailCanal__c</referenceTo>
    <relationshipLabel>Prestataires</relationshipLabel>
    <relationshipName>Prestataires</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_PortailPrestataire__c/fields/IdPrestataire__c.field-meta.xml
<CustomField>
    <fullName>IdPrestataire__c</fullName>
    <externalId>true</externalId>
    <label>ID prestataire</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/HP_PortailUtilisateur__c.object-meta.xml
<CustomObject>
    <label>Utilisateur Portail</label>
    <nameField>
        <displayFormat>UP-{00000}</displayFormat>
        <label>Utilisateur Portail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Utilisateurs Portail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Canal__c.field-meta.xml
<CustomField>
    <fullName>Canal__c</fullName>
    <formula>Prestataire__r.Canal__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Civilite__c.field-meta.xml
<CustomField>
    <fullName>Civilite__c</fullName>
    <label>Civilité</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
            </value>
            <value>
                <fullName>Mme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Format email</inlineHelpText>
    <label>Login</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <inlineHelpText>Min 8 caractères dont : 1 min, 1 maj, 1 spécial, 1 chiffre</inlineHelpText>
    <label>Mot de passe</label>
    <length>30</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Prenom__c.field-meta.xml
<CustomField>
    <fullName>Prenom__c</fullName>
    <label>Prénom</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Prestataire__c.field-meta.xml
<CustomField>
    <fullName>Prestataire__c</fullName>
    <label>Prestataire associé</label>
    <referenceTo>HP_PortailPrestataire__c</referenceTo>
    <relationshipLabel>Utilisateurs Portail</relationshipLabel>
    <relationshipName>Utilisateurs_Portail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Rôle</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conseiller</fullName>
                <default>true</default>
                <label>Conseiller</label>
            </value>
            <value>
                <fullName>Superviseur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_PortailUtilisateur__c/fields/Sgut2Statut__c.field-meta.xml
<CustomField>
    <fullName>Sgut2Statut__c</fullName>
    <label>Sgut2 Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attente réponse SGUT2</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>KO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HP_SM004_SGUT_Test.cls
/**
 * @File Name          : HP_SM004_SGUT_Test.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : Slimene Belhaj Ali
 * @Last Modified On   : 05-18-2021
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    27/12/2019   Vincent Albiser     Initial Version
**/
@isTest
public class HP_SM004_SGUT_Test {

    private enum StaticResource {
        HP_APIHourAccessTokenResponse_MOCK,
        HP_SM004_SGUT_GETUtilisateur_MOCK,
        HP_SM004_SGUT_Response_MOCK
	}

    @testSetup static void dataSetup(){
        System.runAs(HP_UTIL_SmartFactory.insertUserHP()){
            HP_PortailCanal__c canal = (HP_PortailCanal__c)HP_UTIL_SmartFactory.createSObject('HP_PortailCanal__c', null, new Map<String, Object>{
                'Name' => 'CRC-ENGIE',
                'Droit_VenteEm__c' => true,
                'Droit_PaiementCB__c' => true,
                'Droit_ParcoursEmDm__c' => true,
                'Droit_VenteChf1Ex__c' => true,
                'Droit_VenteChf2Ex__c' => true,
                'Visu_docs_s2__c' => true,
                'HP_Paiement_prlvt__c' => true,
                'HP_Visu_docs__c' => true,
                'HP_Modif_ventes__c' => true,
                'Droit_VenteEm1Ex__c' => true
            }, null, null, null);
            insert canal;
    
            HP_PortailPrestataire__c presta = (HP_PortailPrestataire__c)HP_UTIL_SmartFactory.createSObject('HP_PortailPrestataire__c', null, new Map<String, Object>{
                'IdPrestataire__c' => 'Happe',
                'Name' => 'Happe',
                'Canal__c' => canal.Id
            }, null, null, null);
    
            insert presta;
            
            HP_PortailUtilisateur__c utilisateur = (HP_PortailUtilisateur__c)HP_UTIL_SmartFactory.createSObject('HP_PortailUtilisateur__c', null, new Map<String, Object>{
                'Login__c'        => 'Hap001@gmail.com',
                'Password__c'     => 'Happ1179!',
                'Role__c'         => 'Conseiller',
                'Prestataire__c'  => presta.Id,
                'Nom__c'			=> 'Test Nom',
                'Prenom__c'		=> 'Test Prénom',
                'Civilite__c'		=> 'Mr'
            }, null, null, null);
            insert utilisateur;
        }
    }

    @isTest static void creationUtilisateurs_Test() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
                'auth/oauth/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/espaces-prives' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200, 
                null,
                new Map<String, String> {'Content-Type' => 'application/json'})
            };
    
            Test.startTest();
    
                Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
                HP_PortailUtilisateur__c utilisateur = [SELECT Id FROM HP_PortailUtilisateur__c WHERE Login__c =:'Hap001@gmail.com' LIMIT 1];
                HP_PortailUtilisateur__c output = HP_SM004_SGUT.creationUtilisateur(utilisateur.Id);
                
            Test.stopTest(); 
    
            System.assert(HP_EM002_PortailUtilisateur.getUtilisateurById(utilisateur.Id).Sgut2Statut__c == 'OK', 'Succès appel SGUT');
        }       
    }

    @isTest static void creationUtilisateurs_TestKO() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
                'auth/oauth/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/espaces-prives' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(400, 
                null,
                new Map<String, String> {'Content-Type' => 'application/json'})
            };
    
            Test.startTest();
    
                Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap));
                HP_PortailUtilisateur__c utilisateur = [SELECT Id FROM HP_PortailUtilisateur__c WHERE Login__c =:'Hap001@gmail.com' LIMIT 1];
                HP_PortailUtilisateur__c output = HP_SM004_SGUT.creationUtilisateur(utilisateur.Id);
                
            Test.stopTest(); 
    
            System.assert(HP_EM002_PortailUtilisateur.getUtilisateurById(utilisateur.Id).Sgut2Statut__c == 'KO', 'Erreur appel SGUT');
        }       
    }


     @isTest static void modificationMDP_Test() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
                'auth/oauth/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                '/identite/v1/espaces-prives/mdp' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_SM004_SGUT_Response_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/entites-espaces-prives?' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_SM004_SGUT_GETUtilisateur_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'})
            };
            
            Test.startTest();
    
                Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap)); 
                
    
                HP_PortailUtilisateur__c utilisateur = [SELECT Id FROM HP_PortailUtilisateur__c WHERE Login__c =: 'Hap001@gmail.com' LIMIT 1];
                HP_PortailUtilisateur__c output = HP_SM004_SGUT.modificationMDP(utilisateur.Id,'Happ1178!');
                
                
            Test.stopTest(); 
    
            System.assert(HP_EM002_PortailUtilisateur.getUtilisateurById(utilisateur.Id).Password__c == 'Happ1178!', 'Succès modification MDP SGUT');
        }       
    }

    @isTest static void modificationMDP_TestKO() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
                'auth/oauth/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                '/identite/v1/espaces-prives/mdp' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(400,
                                                       StaticResource.HP_SM004_SGUT_Response_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/entites-espaces-prives?' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_SM004_SGUT_GETUtilisateur_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'})
            };
            
            Test.startTest();
    
                Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap)); 
                
    
                HP_PortailUtilisateur__c utilisateur = [SELECT Id FROM HP_PortailUtilisateur__c WHERE Login__c =: 'Hap001@gmail.com' LIMIT 1];
                HP_PortailUtilisateur__c output = HP_SM004_SGUT.modificationMDP(utilisateur.Id,'Happ1178!');
                
                
            Test.stopTest(); 
    
            System.assert(HP_EM002_PortailUtilisateur.getUtilisateurById(utilisateur.Id).Sgut2Statut__c == 'KO', 'Erreur appel SGUT');
        }     
    }
 
    @isTest static void suppressionUtilisateur_Test() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
                'auth/oauth/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/espaces-prives/' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_SM004_SGUT_Response_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/entites-espaces-prives?' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_SM004_SGUT_GETUtilisateur_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'})
            };
    
            Test.startTest();
    
                Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap)); 
                HP_PortailUtilisateur__c utilisateur = [SELECT Id FROM HP_PortailUtilisateur__c WHERE Login__c =: 'Hap001@gmail.com' LIMIT 1];
                HP_PortailUtilisateur__c output = HP_SM004_SGUT.suppressionUtilisateur(utilisateur.Id);
                
            Test.stopTest(); 
    
            System.assert(HP_EM002_PortailUtilisateur.getUtilisateurById(utilisateur.Id).Sgut2Statut__c == 'OK', 'Succès appel SGUT');
        }    
    }

    @isTest static void suppressionUtilisateur_TestKO() {
        System.runAs(HP_UTIL_SmartFactory.runAsUserHP()){
            Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> bodyResponseMap = new Map<String, HP_UTIL_ResponseRestMock.ParameterMockWrapper> {
                'auth/oauth/v2/token' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(200,
                                                       StaticResource.HP_APIHourAccessTokenResponse_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/espaces-prives/' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(400,
                                                       StaticResource.HP_SM004_SGUT_Response_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'}),
                'identite/v1/entites-espaces-prives?' => new HP_UTIL_ResponseRestMock.ParameterMockWrapper(400,
                                                       StaticResource.HP_SM004_SGUT_GETUtilisateur_MOCK.name(),
                                                       new Map<String, String> {'Content-Type' => 'application/json'})
            };
    
            Test.startTest();
    
                Test.setMock(HttpCalloutMock.class, new HP_UTIL_ResponseRestMock(bodyResponseMap)); 
                HP_PortailUtilisateur__c utilisateur = [SELECT Id FROM HP_PortailUtilisateur__c WHERE Login__c =: 'Hap001@gmail.com' LIMIT 1];
                HP_PortailUtilisateur__c output = HP_SM004_SGUT.suppressionUtilisateur(utilisateur.Id);
                
            Test.stopTest(); 
    
            System.assert(HP_EM002_PortailUtilisateur.getUtilisateurById(utilisateur.Id).Sgut2Statut__c == 'KO', 'Erreur appel SGUT');
        }	       
    }
    
}