force-app/main/default/objects/Intervention__c/Intervention__c.object-meta.xml
<CustomObject>
    <description>Cet objet permet aux conseiller de consigner leurs actions sur le Case lors d&apos;un traitement Back Office.</description>
    <label>Intervention</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Intervention Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Intervention__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>@Description: Liaison de l&apos;intervention avec le case
@Project: Smile</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Intervention__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Liaison de l&apos;intervention avec un contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interventions</relationshipLabel>
    <relationshipName>Interventions_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Intervention__c/fields/Sous_type__c.field-meta.xml
<CustomField>
    <fullName>Sous_type__c</fullName>
    <description>@Description: Ce champ complète le Type d&apos;intervention
@Project: Smile</description>
    <label>Sous-type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SM31</fullName>
                <label>Recherche de règlement</label>
            </value>
            <value>
                <fullName>SM18</fullName>
                <label>Activation manuelle du contrat</label>
            </value>
            <value>
                <fullName>SM19</fullName>
                <label>Anomalie PDL</label>
            </value>
            <value>
                <fullName>SM15</fullName>
                <label>Contrat Ok Symphonie mais pas à la bonne date / bonne puissance / FTA KO</label>
            </value>
            <value>
                <fullName>SM32</fullName>
                <label>Ecarts comptable</label>
            </value>
            <value>
                <fullName>SM09</fullName>
                <label>Ecart sur remboursement</label>
            </value>
            <value>
                <fullName>SM26</fullName>
                <label>Erreur de prix</label>
            </value>
            <value>
                <fullName>SM03</fullName>
                <label>Facture de régularisation absente ou en erreur (problèmes UR, rythme de facturation)</label>
            </value>
            <value>
                <fullName>SM11</fullName>
                <label>Facture incohérente vs GRD ou CPV (problème entre GRD et nos intégrations)</label>
            </value>
            <value>
                <fullName>SM30</fullName>
                <label>J&apos;ai appliqué un mode opératoire mais cela ne fonctionne pas</label>
            </value>
            <value>
                <fullName>SM01</fullName>
                <label>Le client a déjà reçu une facture</label>
            </value>
            <value>
                <fullName>SM23</fullName>
                <label>Le client a été coupé par erreur / il nous alerte d&apos;une inversion PDL/PCE</label>
            </value>
            <value>
                <fullName>SM06</fullName>
                <label>Le client conteste son index</label>
            </value>
            <value>
                <fullName>SM16</fullName>
                <label>Le client est résilié mais recoit toujours des factures</label>
            </value>
            <value>
                <fullName>SM17</fullName>
                <label>Le client n&apos;a jamais reçu de facture et l&apos;OPS de MES est soldée sur le portail distributeur</label>
            </value>
            <value>
                <fullName>SM02</fullName>
                <label>Le client n&apos;a jamais reçu de facture et l&apos;OPS de MES n&apos;est pas soldée sur le portail distributeur</label>
            </value>
            <value>
                <fullName>SM08</fullName>
                <label>Le client n&apos;a pas accès à son suivi de conso et les index ne sont pas intégrés dans l&apos;outil</label>
            </value>
            <value>
                <fullName>SM22</fullName>
                <label>Le client se rétracte et il est déjà facturé</label>
            </value>
            <value>
                <fullName>SM25</fullName>
                <label>Le contrat a été fait sur le mauvais PDL / PCE</label>
            </value>
            <value>
                <fullName>SM14</fullName>
                <label>Le contrat n&apos;est pas répliqué (contrat modif en cours)</label>
            </value>
            <value>
                <fullName>SM24</fullName>
                <label>Le distributeur nous signale une inversion PDL / PCE</label>
            </value>
            <value>
                <fullName>SM05</fullName>
                <label>Les relevés de compteur sont absents dans nos outils</label>
            </value>
            <value>
                <fullName>SM12</fullName>
                <label>Le statut du contrat est en « résiliation en cours » (statut différent des portails et ISU)</label>
            </value>
            <value>
                <fullName>SM29</fullName>
                <label>Mise à jour de commune (SR12)</label>
            </value>
            <value>
                <fullName>SM28</fullName>
                <label>Passage en FTCDS</label>
            </value>
            <value>
                <fullName>SM10</fullName>
                <label>Présence d&apos;un écart entre les factures et les paiements enregistrés</label>
            </value>
            <value>
                <fullName>SM07</fullName>
                <label>Problème sur la transformation de la PC</label>
            </value>
            <value>
                <fullName>SM04</fullName>
                <label>Promo non appliquée</label>
            </value>
            <value>
                <fullName>SM21</fullName>
                <label>Propale création / transformation</label>
            </value>
            <value>
                <fullName>SM20</fullName>
                <label>Regroupement PDL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Intervention__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <description>@Description: Statut de l&apos;intervention
@Project: Smile</description>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nouveau</fullName>
                <default>true</default>
                <label>Nouveau</label>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>En attente</fullName>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Intervention__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>@Description: Type d&apos;intervention
@Project: Smile</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Blocage sur MES/RES/CHO</fullName>
            </value>
            <value>
                <fullName>Contestation d’index distributeur/factures</fullName>
            </value>
            <value>
                <fullName>Inversion PDL</fullName>
            </value>
            <value>
                <fullName>IRIS</fullName>
            </value>
            <value>
                <fullName>Je ne reçois pas mes factures</fullName>
            </value>
            <value>
                <fullName>POC Omni-channel</fullName>
            </value>
            <value>
                <fullName>Rétractation complexe</fullName>
            </value>
            <value>
                <fullName>Situation compte/règlement/remboursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SM_PureCloudCTIExtension_Test.cls
/*
* @Auhtor: Riadh Dallel ~ riadh.dallel@external.engie.com
* @Date: 25/06/2021
* @Description: Test class for class SM_PureCloudCTIExtension
*/
@isTest
global class SM_PureCloudCTIExtension_Test {

 

    @testSetup 
    static void dataSetup() {
        Id serviceRT = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Service').getRecordTypeId();
        // create Account
        Account acc = SM_TestDataFactory.createAccount('Smile_Account');
        Insert acc;
        // create Contact
        Contact testContact = SM_TestDataFactory.createContact('testContact', acc.Id);
        Insert testContact;
        // Create Cases

        Case testCase1 = SM_TestDataFactory.createCase('TEST', acc.Id);
        Case testCase2 = SM_TestDataFactory.createCase('TESTmajAffectation', acc.Id); 
        testCase1.RecordTypeId = serviceRT;
        testCase2.RecordTypeId = serviceRT;
        List<Case> casesToInsert = new List<Case>{testCase1,testCase2}; 
        Insert casesToInsert;
        // Create Task
        Task task = new Task(WhatId=casesToInsert[0].id,Subject='test_Genesys',Status='A traiter');
        insert task;
    }
    
    static String setData(String caseId,Task task)  {

        // préparation de l'input de méthode onSaveLog
        Map<String, Object> attributes = new Map<String, Object> ();
        attributes.put('sf_urlpop',caseId);
        Map<String, Object> interaction = new Map<String, Object> ();
        interaction.put('isConnected',true);
        Map<String, Object> saveLogData = new Map<String, Object> ();
        interaction.put('attributes',attributes);
        saveLogData.put('interaction',interaction);
        saveLogData.put('callLog',(Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(task)));
        String data = JSON.serialize(saveLogData);


        return data;
    }
    static String setData(String caseId){

        return setData(caseId,[select id from Task limit 1]);
    }

    @isTest
    global static void onSaveLog_Test() {
        String caseId='';
        Task task= new task();
        for(Case caseObj: [select id from Case limit 1])
            caseId=caseObj.id;
        
        for(Task taskObj: [select id from Task limit 1])
            task=taskObj;    

        String data =  setData(caseId,task);


        Test.startTest();
        SM_PureCloudCTIExtension pureCloudExtension = new SM_PureCloudCTIExtension();
        pureCloudExtension.onSaveLog(data);
        Test.stopTest();
	
        // vérifier la MAJ du champ PureCloud_acceptedGenesys__c
        for(Case caseObj: [select id,PureCloud_acceptedGenesys__c,ownerId from Case limit 1])
            System.assertEquals(true, caseObj.PureCloud_acceptedGenesys__c);


    }


    @isTest
    public static void majAffectation_Test(){

        //setup status of case to escaladé
        Case caseObj = [select Id,status,Subject,ownerId,Motif_escalade__c,Sous_motif_escalade__c,Raison_detaillee_escalade__c from case where Subject = 'TESTmajAffectation' limit 1 ];
        
        String caseId = caseObj.Id;
        caseObj.Type = 'Paiement';
        caseObj.Sous_type__c = 'Information détail facture';
        caseObj.Motif_escalade__c = 'MO04' ;
        caseObj.Sous_motif_escalade__c = 'SM06' ;
        caseObj.Raison_detaillee_escalade__c = 'test'; 
        caseObj.status = 'Escaladé';
        update caseObj;
        
        //setup intervention (one created 1 day before the other )
        Contact cnt = [Select id from Contact limit 1];
        Intervention__c interv = new Intervention__c(case__c = caseObj.Id,Statut__c = 'Nouveau',Type__c ='MO11',Contact__c = cnt.Id  ); 
        insert interv;
        Datetime yesterday = Datetime.now().addDays(-1);
        Test.setCreatedDate(interv.Id, yesterday);
        String OldInterventionId = interv.Id;


        Intervention__c NewInterv = new Intervention__c(case__c = caseObj.Id,Statut__c = 'Nouveau',Type__c ='MO11',Contact__c = cnt.Id  ); 
        insert NewInterv;
        Datetime today = Datetime.now();
        Test.setCreatedDate(NewInterv.Id, today);

        String data =  setData(caseId);
        
        Test.startTest();
        SM_PureCloudCTIExtension pureCloudExtension = new SM_PureCloudCTIExtension();
        pureCloudExtension.onSaveLog(data);
        Test.stopTest();

        List<Intervention__c> listCaseInterventions = [Select Id,Statut__c,OwnerId ,CreatedDate
                                                       From Intervention__c 
                                                       Where Case__c=:caseId
                                                       Order By CreatedDate Desc];
        
       
        // test if the last 'new' intervention owner is the same as the case owner
        System.assertEquals(listCaseInterventions[0].OwnerId,caseObj.OwnerId); 
        System.assertEquals(listCaseInterventions[0].statut__c,'En cours');
        System.assertNotEquals(listCaseInterventions[0].id,OldInterventionId);                                                  
    }

}