force-app/main/default/objects/HP_Codification__mdt/HP_Codification__mdt.object-meta.xml
<CustomObject>
    <label>HP_Codification</label>
    <pluralLabel>HP_Codifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_Codification__mdt/fields/keyType__c.field-meta.xml
<CustomField>
    <fullName>keyType__c</fullName>
    <label>keyType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Codification__mdt/fields/valueType__c.field-meta.xml
<CustomField>
    <fullName>valueType__c</fullName>
    <label>valueType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_CodificationValeur__mdt/HP_CodificationValeur__mdt.object-meta.xml
<CustomObject>
    <label>HP_CodificationValeur</label>
    <pluralLabel>HP_CodificationValeurs</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_CodificationValeur__mdt/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <label>key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_CodificationValeur__mdt/fields/parent__c.field-meta.xml
<CustomField>
    <fullName>parent__c</fullName>
    <label>parent</label>
    <referenceTo>HP_Codification__mdt</referenceTo>
    <relationshipLabel>HP_CodificationValeurs</relationshipLabel>
    <relationshipName>HP_CodificationValeurs</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/HP_CountryCode__mdt/HP_CountryCode__mdt.object-meta.xml
<CustomObject>
    <label>HP_CountryCode</label>
    <pluralLabel>HP_CountryCodes</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_CountryCode__mdt/fields/IndiFRA__c.field-meta.xml
<CustomField>
    <fullName>IndiFRA__c</fullName>
    <defaultValue>(&quot;+33&quot;)</defaultValue>
    <label>IndiFRA</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_CountryCode__mdt/fields/IsoFra__c.field-meta.xml
<CustomField>
    <fullName>IsoFra__c</fullName>
    <defaultValue>(&quot;FRA&quot;)</defaultValue>
    <label>IsoFra</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/HP_OmniChannelRouting__mdt.object-meta.xml
<CustomObject>
    <label>HP_OmniChannelRouting</label>
    <pluralLabel>HP_OmniChannelRoutings</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_CritCaseOrigin__c.field-meta.xml
<CustomField>
    <fullName>HP_CritCaseOrigin__c</fullName>
    <description>Origine du case happ-e</description>
    <label>HP_CritCaseOrigin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_CritCaseSubType__c.field-meta.xml
<CustomField>
    <fullName>HP_CritCaseSubType__c</fullName>
    <label>HP_CritCaseSubType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_CritCaseType__c.field-meta.xml
<CustomField>
    <fullName>HP_CritCaseType__c</fullName>
    <label>HP_CritCaseType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_CritQueue__c.field-meta.xml
<CustomField>
    <fullName>HP_CritQueue__c</fullName>
    <label>HP_CritQueue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_CritRecordType__c.field-meta.xml
<CustomField>
    <fullName>HP_CritRecordType__c</fullName>
    <description>Type d’enregistrement de la requête</description>
    <label>HP_CritRecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_CritSkillType__c.field-meta.xml
<CustomField>
    <fullName>HP_CritSkillType__c</fullName>
    <description>Type de compétence FO/BO</description>
    <label>HP_CritSkillType</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_ValuePriority__c.field-meta.xml
<CustomField>
    <fullName>HP_ValuePriority__c</fullName>
    <label>HP_ValuePriority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_OmniChannelRouting__mdt/fields/HP_ValueSkill__c.field-meta.xml
<CustomField>
    <fullName>HP_ValueSkill__c</fullName>
    <label>HP_ValueSkill</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_Parameter__mdt/HP_Parameter__mdt.object-meta.xml
<CustomObject>
    <description>Dans cette custom metadata, il y a touts les configs de HP.

DeveloperName est le clé
Value est la valeur.</description>
    <label>HP Parameter</label>
    <pluralLabel>HP Parameters</pluralLabel>
</CustomObject>

force-app/main/default/objects/HP_Parameter__mdt/fields/Is_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Is_Encrypted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Encrypted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/HP_UTIL_MetadataManager.cls
/** 
* @author Slimen Belhaj Ali 
* @date 31/12/2019 
* @description Classe permet de gerer les custom metadata
*/
public with sharing class HP_UTIL_MetadataManager {

    private static Map<String, String> metadataMap = null;
    private static String INTEGER_TYPE = 'INTEGER';
    private static String STRING_TYPE = 'STRING';


    private static List<HP_OmniChannelRouting__mdt> routingParameters = null;



    /** 
    * @author Slimene Belhaj Ali
    * @date 31/12/2019 
    * @description Methode permet de recuperer la configuration en fonction de clé
    * @param key, le clé de la config
    */
    @AuraEnabled(cacheable=true)
    public static String getConfigByKey(String key) {
        try {
            HP_Parameter__mdt mdt = [SELECT DeveloperName, value__c, Is_Encrypted__c FROM HP_Parameter__mdt WHERE DeveloperName = :key LIMIT 1];
            if(mdt != null){
                return mdt.Is_Encrypted__c? decrypt(mdt.Value__c) : mdt.Value__c;
            }else {
                return null;
            }
        } catch (Exception ex) {
            System.debug('Exception : '+ex.getMessage());
            return null;
        } 
    }

    public static String decrypt(String value){
        return HP_UTIL_CryptoUtils.decryptData(String.valueOf(value));
        
    }
       
       public static String getContryCode(String indicatif) {
        if(metadataMap == null) {
            metadataMap = new Map<String, String>();
            List<HP_CountryCode__mdt> MDTList = [select IndiFRA__c, IsoFra__c from HP_CountryCode__mdt];
            for(HP_CountryCode__mdt mdt : MDTList) {
                metadataMap.put(mdt.IndiFRA__c, mdt.IsoFra__c);
            }
        }
         System.debug('indicatif '+ indicatif);
        System.debug('MAP '+ metadataMap);
        System.debug('MAP ISO'+ metadataMap.get(indicatif));
        return metadataMap.get(indicatif);
    }




    /**
    * @description 
    * @author Antoine Latour | 27-11-2020 
    * @return List<HP_OmniChannelRouting__mdt> 
    **/
    public static List<HP_OmniChannelRouting__mdt> getOmniChannelRoutingMtd() {
        if(routingParameters == null) {
            routingParameters = [select HP_CritCaseOrigin__c,HP_CritCaseSubType__c,HP_CritCaseType__c,HP_CritQueue__c,HP_CritRecordType__c,HP_CritSkillType__c,HP_ValuePriority__c,HP_ValueSkill__c from HP_OmniChannelRouting__mdt];
        }
        return routingParameters;
    }




    /**
    * @description : Recuperer la configuration en fonction des clées
    * @author Ali AJELLAL | 11-12-2020 
    * @param keys 
    * @return Map<String, Map<object, object>> 
    **/
    public static Map<String, Map<object,object>> getCodification(List<String> keys){

        //get all parents with the children
        List<HP_Codification__mdt> allCodificationWithChild = [select ID,DeveloperName,keyType__c,valueType__c,(select ID,parent__c,DeveloperName, key__c, value__c from HP_CodificationValeurs__r) from HP_Codification__mdt where developername IN:keys];
        Map<String, Map<object,object>> result = new Map<String, Map<object,object>>();

        for (HP_Codification__mdt item : allCodificationWithChild) {
            System.debug('********item ******* '+ item);
            Map<object,object> dataToInsert = new Map<object,object>();
            //loop throw children
            for (HP_CodificationValeur__mdt codificationVal : item.HP_CodificationValeurs__r) {
                dataToInsert.put(extractData(codificationVal.key__c,item.keyType__c),extractData(codificationVal.value__c,item.valueType__c));
            }
            result.put(item.DeveloperName, dataToInsert);
        }

        System.debug('********result******* '+ result);
        return result;
    }

	/**
	* @description 
	* @author Ali AJELLAL | 11-12-2020 
	* @param field 
	* @param type 
	* @return Object 
	**/
	public static Object  extractData(Object field , String type){
		Object currentValue;
		
		if(type.toUpperCase() == INTEGER_TYPE){
		currentValue = Integer.valueOf(field);
		}
		if(type.toUpperCase() == STRING_TYPE){
			currentValue = String.valueOf(field);
		}
		return currentValue;
	}




}