force-app/main/default/objects/SM_QuestionConsentement__mdt/SM_QuestionConsentement__mdt.object-meta.xml
<CustomObject>
    <label>SM_QuestionConsentement</label>
    <pluralLabel>SM_QuestionConsentement</pluralLabel>
</CustomObject>

force-app/main/default/objects/SM_QuestionConsentement__mdt/fields/codeQuestionnaireQuestion__c.field-meta.xml
<CustomField>
    <fullName>codeQuestionnaireQuestion__c</fullName>
    <label>code questionnaire question</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_QuestionConsentement__mdt/fields/LibelleQuestion__c.field-meta.xml
<CustomField>
    <fullName>LibelleQuestion__c</fullName>
    <label>Libelle question</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SM_WS_Suffix__mdt/SM_WS_Suffix__mdt.object-meta.xml
<CustomObject>
    <description>@Project: Smile &amp; MyPower
@Description: Suffix des appels Webservices</description>
    <label>SM_WS_Suffix</label>
    <pluralLabel>SM_WS_Suffixs</pluralLabel>
</CustomObject>

force-app/main/default/objects/SM_WS_Suffix__mdt/fields/suffix__c.field-meta.xml
<CustomField>
    <fullName>suffix__c</fullName>
    <description>@Projet: Smile &amp; MyPower
@Description: Le suffix qui correspond à l&apos;appel</description>
    <label>suffix</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConsentementsHandler.cls
public with sharing class ConsentementsHandler {

    @AuraEnabled(cacheable=true)
    public static List<Object> getConsentementsQuestions() {
        List<Object> listObject = null;
        HttpResponse httpResp = CalloutManager.sendRequest('Questions_Consentement', null, 'GET', CalloutManager.Scope.READ,null,null);
        if(httpResp != null){
			Map < String, Object > resultAsMap = (Map < String, Object > ) JSON.deserializeUntyped(httpResp.getBody());
			listObject = (List < Object > ) resultAsMap.get('_data');
        }
        System.debug('1 - listObject'+ listObject);
        return listObject;
    }
     
    @AuraEnabled( cacheable=true )  
    public static List < SM_QuestionConsentement__mdt > fetchSmileQuestions() {
        
        String codeQuestion = null;

        List <SM_WS_Suffix__mdt> questions_suffix = [SELECT suffix__c FROM SM_WS_Suffix__mdt WHERE DeveloperName = 'Questions_Consentement'];

        for(SM_WS_Suffix__mdt qst : questions_suffix) {
            if (qst.suffix__c.contains('idQuestionnaire=7')){
                codeQuestion = '%Q7%';
            }
            else{
                codeQuestion = '%Q1%';
            }
        }
        
        List <SM_QuestionConsentement__mdt> questionnaire = [ SELECT Id, codeQuestionnaireQuestion__c, LibelleQuestion__c FROM SM_QuestionConsentement__mdt WHERE codeQuestionnaireQuestion__c LIKE :codeQuestion];

        return questionnaire;
 
    }
}