force-app/main/default/objects/HP_CaseHistory__c/HP_CaseHistory__c.object-meta.xml
<CustomObject>
    <label>HP Case History</label>
    <nameField>
        <label>HP Case History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP_CaseHistories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_CaseHistory__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>HP_CaseHistories</relationshipLabel>
    <relationshipName>HP_CaseHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HP_CaseHistory__c/fields/HP_ChangementStatutAncien__c.field-meta.xml
<CustomField>
    <fullName>HP_ChangementStatutAncien__c</fullName>
    <label>Ancien statut</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_CaseHistory__c/fields/HP_ChangementStatutNouveau__c.field-meta.xml
<CustomField>
    <fullName>HP_ChangementStatutNouveau__c</fullName>
    <label>Nouveau statut</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_CaseHistory__c/fields/HP_DateAttribution__c.field-meta.xml
<CustomField>
    <fullName>HP_DateAttribution__c</fullName>
    <label>Date Attribution</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_CaseHistory__c/fields/HP_DateChangementStatut__c.field-meta.xml
<CustomField>
    <fullName>HP_DateChangementStatut__c</fullName>
    <label>Date de changement statut</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HP_CaseHistory__c/fields/HP_DureeTraitement__c.field-meta.xml
<CustomField>
    <fullName>HP_DureeTraitement__c</fullName>
    <label>Duree Traitement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HP_CaseHistory__c/fields/HP_Type__c.field-meta.xml
<CustomField>
    <fullName>HP_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DMT</fullName>
                <default>true</default>
                <label>DMT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HP_CaseHistory__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HP_CaseHistories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HP_EM036_CaseHistory.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-18-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   08-31-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing  class HP_EM036_CaseHistory {
    
 
    public static List<HP_CaseHistory__c> getCaseHistory(String caseOwner, String caseId) {
        return [select Id, Case__c, HP_dateAttribution__c, HP_type__c, user__c from HP_caseHistory__c where case__c =:caseId and User__c =:caseOwner];   
    }

    public static HP_CaseHistory__c creatCaseHistory(Case cas, AgentWork agentWork,Boolean isCase){
        HP_CaseHistory__c caseHistory = new HP_CaseHistory__c();
        caseHistory.Case__c = isCase ? cas.Id : agentWork.WorkItemId;
        caseHistory.HP_DateAttribution__c = DateTime.now();

        caseHistory.User__c = isCase ?  cas.OwnerId : agentWork.UserId;
        return caseHistory;
    }





    public static List<HP_CaseHistory__c> getCaseHistoryByListCase(String caseOwner, List<String> casesId) {
        return [select Id, Case__c, HP_dateAttribution__c, HP_DateChangementStatut__c, HP_type__c, user__c from HP_caseHistory__c where case__c  IN :casesId and User__c =:caseOwner];   
    }

    public static List<HP_CaseHistory__c> getCaseHistoryByListCaseAndUser(String caseOwner, Set<String> casesId) {
        return [select Id, Case__c, HP_dateAttribution__c, HP_DateChangementStatut__c, HP_type__c, user__c from HP_caseHistory__c where (case__c  IN :casesId and User__c =:caseOwner) order by HP_DateAttribution__c desc limit 1];   
    }


    public static List<HP_CaseHistory__c> getCaseHistoryByUsers(List<Id> users, Date batchDate){
        return [ select Id ,Case__c, HP_DateAttribution__c, HP_DateChangementStatut__c, HP_ChangementStatutAncien__c, HP_ChangementStatutNouveau__c,HP_DureeTraitement__c, User__c, User__r.name from HP_CaseHistory__c where( (  DAY_ONLY(HP_DateAttribution__c) =:batchDate  or DAY_ONLY(HP_DateChangementStatut__c) =: batchDate)  and  User__c IN :users) ];
    }


    public static List<CaseHistory> getCaseHistoryByCasesIds(Set<Id> casesIds) {
        return [SELECT Id, CaseId, CreatedDate, Field, NewValue, OldValue FROM CaseHistory WHERE CaseId in : casesIds ORDER BY CreatedDate ASC];
    }



}