force-app/main/default/objects/HP_CaseHistory__c/HP_CaseHistory__c.object-meta.xml
<CustomObject>
    <label>HP Case History</label>
    <nameField>
        <label>HP Case History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP_CaseHistories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_CaseHistory__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>HP_CaseHistories</relationshipLabel>
    <relationshipName>HP_CaseHistories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HP_CaseSkill__c/HP_CaseSkill__c.object-meta.xml
<CustomObject>
    <label>HP_CaseSkill</label>
    <nameField>
        <label>HP_CaseSkillName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HP_CaseSkills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HP_CaseSkill__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>HP_Case_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HP_CaseSkill__c/fields/Skill_label__c.field-meta.xml
<CustomField>
    <fullName>Skill_label__c</fullName>
    <label>Skill label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HP_CaseSkill__c/fields/User_assign__c.field-meta.xml
<CustomField>
    <fullName>User_assign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User assigné</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HP_Case_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HP_SM038_AgentWork.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 01-12-2021
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
* Modifications Log 
* Ver   Date         Author                               Modification
* 1.0   12-08-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public without sharing class HP_SM038_AgentWork {
    
    @InvocableMethod
    public static void addCaseHistory(List<AgentWork> agentWorkList){
        System.debug('111');
        
        List<HP_CaseHistory__c> caseHistoryList = new List<HP_CaseHistory__c>();
        String userId = UserInfo.getUserId();
        String userAssigne;
        
        for(AgentWork agentWork : agentWorkList){
            HP_CaseHistory__c caseHistory = new HP_CaseHistory__c();
            boolean isQqueue =  string.valueOf(agentWork.UserId).startsWith('00G');
            
            if(agentWork.Status =='Opened' && agentWork.UserId == userId && !isQqueue ){
                caseHistory = HP_EM036_CaseHistory.creatCaseHistory(null,agentWork, false );
                caseHistoryList.add(caseHistory);
                userAssigne = agentWork.UserId;
            }
        }
        System.debug('caseHistoryList:'+caseHistoryList);
        if(caseHistoryList.size() > 0)  Database.insert(caseHistoryList);
        
        Set<Id> ids = new Set<Id>();
        for (AgentWork agentWork : agentWorkList) {
            ids.add(agentWork.WorkItemId);
        }
        System.debug('******ids**********:'+ids);
		createCaseSkills(ids, userAssigne);        
    }
    
    //trick pour pouvoir appeler cette méthode dans une classe de test
    public static void createCaseSkills(Set<Id> ids, Id userId){
        
        List<HP_CaseSkill__c> caseSkills = new List<HP_CaseSkill__c>();
        List<PendingServiceRouting> existingPsrList = [SELECT Id, WorkItemId, (select id, Skill.DeveloperName from SkillRequirements) FROM PendingServiceRouting WHERE WorkItemId IN :ids];
        
        for (PendingServiceRouting exist : existingPsrList) {
            
            for(SkillRequirement skreq : exist.SkillRequirements){
                HP_CaseSkill__c caseSkill = new HP_CaseSkill__c();
                caseSkill.Case__c = exist.WorkItemId;
                caseSkill.User_assign__c = userId;
                caseSkill.Skill_label__c = skreq.Skill.DeveloperName;
                System.debug('******skreq.Skill.DeveloperName**********:'+skreq.Skill.DeveloperName);
                
                caseSkills.add(caseSkill);
            }            
        }
        
        System.debug('******does caseSkills**********:'+caseSkills);
        if(caseSkills.size()>0) Database.insert(caseSkills);
    }
}